import { AircraftEntry } from "./types";

export const businessJets: AircraftEntry[] = [
  // ============================================================
  // GULFSTREAM
  // ============================================================
  {
    id: "gulfstream-g280",
    name: "Gulfstream G280",
    manufacturer: "Gulfstream Aerospace",
    type: "Business Jet",
    variant: "G280",
    firstFlight: "2009",
    inService: "2012",
    role: "Super-Midsize Business Jet",
    country: "USA",
    specs: {
      wingspan: "63 ft 1 in (19.23 m)",
      length: "66 ft 10 in (20.37 m)",
      maxSpeed: "Mach 0.85 (559 mph / 900 km/h)",
      range: "3,600 nm (6,667 km)",
      ceiling: "45,000 ft (13,716 m)",
      engines: "2× Honeywell HTF7250G turbofan",
      crew: "2",
      capacity: "10 passengers",
    },
    description:
      "The Gulfstream G280 is a super-midsize business jet developed as the successor to the G200. It offers transcontinental range with a spacious cabin, advanced avionics, and enhanced aerodynamics compared to its predecessor. The G280 features winglets and a distinctive Gulfstream nose profile.",
    funFact:
      "The G280 was originally developed in partnership with Israel Aerospace Industries (IAI) as the Galaxy/G200 replacement, and it holds several city-pair speed records in its class.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "oval Gulfstream windows",
        "rear-mounted twin engines",
        "winglets",
        "conventional low-mounted swept wing",
        "pointed nose",
      ],
    },
    aliases: ["G280", "Gulfstream 280"],
  },
  {
    id: "gulfstream-g550",
    name: "Gulfstream G550",
    manufacturer: "Gulfstream Aerospace",
    type: "Business Jet",
    variant: "G550",
    firstFlight: "2002",
    inService: "2003",
    role: "Ultra-Long-Range Large Business Jet",
    country: "USA",
    specs: {
      wingspan: "93 ft 6 in (28.50 m)",
      length: "96 ft 5 in (29.39 m)",
      maxSpeed: "Mach 0.885 (590 mph / 950 km/h)",
      range: "6,750 nm (12,501 km)",
      ceiling: "51,000 ft (15,545 m)",
      engines: "2× Rolls-Royce BR710 turbofan",
      crew: "2",
      capacity: "19 passengers",
    },
    description:
      "The Gulfstream G550 is an ultra-long-range large business jet capable of flying non-stop from New York to Tokyo. It features a wide-body cabin with large oval windows, a PlaneView flight deck with four large LCD displays, and advanced winglet technology. The G550 has served as a VIP transport and special missions platform for governments worldwide.",
    funFact:
      "The G550 set more than 50 city-pair speed records and was selected by the US Air Force as the C-37B VIP transport aircraft.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "large oval Gulfstream windows",
        "rear-mounted twin engines",
        "winglets",
        "wide-body fuselage",
        "distinctive Gulfstream nose",
      ],
    },
    aliases: ["G550", "Gulfstream 550", "GV-SP", "C-37B"],
  },
  {
    id: "gulfstream-g650",
    name: "Gulfstream G650",
    manufacturer: "Gulfstream Aerospace",
    type: "Business Jet",
    variant: "G650",
    firstFlight: "2009",
    inService: "2012",
    role: "Ultra-Long-Range Large Business Jet",
    country: "USA",
    specs: {
      wingspan: "99 ft 10 in (30.42 m)",
      length: "99 ft 10 in (30.42 m)",
      maxSpeed: "Mach 0.925 (Mach 0.85 cruise)",
      range: "7,000 nm (12,964 km)",
      ceiling: "51,000 ft (15,545 m)",
      engines: "2× Rolls-Royce BR725 turbofan",
      crew: "2",
      capacity: "18 passengers",
    },
    description:
      "The Gulfstream G650 was the world's fastest and longest-range business jet at its introduction, capable of flying from New York to Beijing non-stop. It introduced a new elliptical fuselage cross-section with the largest windows in the Gulfstream fleet, a fully fly-by-wire flight control system, and an advanced winglet design.",
    funFact:
      "The G650 was so popular at launch that used aircraft sold for more than the new price, with buyers paying premiums to avoid years-long order backlogs.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "largest oval Gulfstream windows in fleet",
        "rear-mounted twin engines",
        "elliptical fuselage cross-section",
        "active winglets",
        "fly-by-wire controls",
      ],
    },
    aliases: ["G650", "Gulfstream 650"],
  },
  {
    id: "gulfstream-g650er",
    name: "Gulfstream G650ER",
    manufacturer: "Gulfstream Aerospace",
    type: "Business Jet",
    variant: "G650ER",
    firstFlight: "2014",
    inService: "2014",
    role: "Ultra-Long-Range Large Business Jet",
    country: "USA",
    specs: {
      wingspan: "99 ft 10 in (30.42 m)",
      length: "99 ft 10 in (30.42 m)",
      maxSpeed: "Mach 0.925",
      range: "7,500 nm (13,890 km)",
      ceiling: "51,000 ft (15,545 m)",
      engines: "2× Rolls-Royce BR725 turbofan",
      crew: "2",
      capacity: "18 passengers",
    },
    description:
      "The Gulfstream G650ER is the extended-range variant of the G650, adding 500 nm of additional range through increased fuel capacity. It can fly from Los Angeles to Singapore non-stop and holds the record for the longest-range business jet flight. Visually nearly identical to the G650, it is distinguished primarily by its increased fuel tanks.",
    funFact:
      "The G650ER set the record for the fastest circumnavigation of the globe by a business jet in 2015, completing the trip in 41 hours and 7 minutes.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "large oval Gulfstream windows",
        "rear-mounted twin engines",
        "elliptical fuselage cross-section",
        "active winglets",
        "virtually identical profile to G650",
      ],
    },
    aliases: ["G650ER", "Gulfstream 650ER"],
  },
  {
    id: "gulfstream-g700",
    name: "Gulfstream G700",
    manufacturer: "Gulfstream Aerospace",
    type: "Business Jet",
    variant: "G700",
    firstFlight: "2019",
    inService: "2022",
    role: "Ultra-Long-Range Ultra-Large Business Jet",
    country: "USA",
    specs: {
      wingspan: "103 ft (31.39 m)",
      length: "109 ft 9 in (33.46 m)",
      maxSpeed: "Mach 0.925",
      range: "7,500 nm (13,890 km)",
      ceiling: "51,000 ft (15,545 m)",
      engines: "2× Rolls-Royce Pearl 700 turbofan",
      crew: "2",
      capacity: "19 passengers",
    },
    description:
      "The Gulfstream G700 is the flagship of the Gulfstream fleet and the largest purpose-built business jet in production. It features the widest and tallest cabin in its class, five living zones, a full galley, and the Symmetry flight deck with touch-screen avionics. The G700 uses the new Rolls-Royce Pearl 700 engines with active noise and vibration suppression.",
    funFact:
      "The G700's cabin has the lowest cabin altitude of any business jet at 4,850 feet when cruising at 51,000 feet, reducing passenger fatigue on long flights.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "largest cabin in Gulfstream fleet",
        "oval Gulfstream windows",
        "rear-mounted twin engines",
        "longest fuselage in class",
        "Rolls-Royce Pearl engines with nacelle chevrons",
      ],
    },
    aliases: ["G700", "Gulfstream 700"],
  },
  {
    id: "gulfstream-giv-g400",
    name: "Gulfstream GIV / G400",
    manufacturer: "Gulfstream Aerospace",
    type: "Business Jet",
    variant: "GIV-SP / G400",
    firstFlight: "1985",
    inService: "1987",
    role: "Long-Range Large Business Jet",
    country: "USA",
    specs: {
      wingspan: "77 ft 10 in (23.72 m)",
      length: "88 ft 4 in (26.92 m)",
      maxSpeed: "Mach 0.88 (581 mph / 935 km/h)",
      range: "4,220 nm (7,815 km)",
      ceiling: "45,000 ft (13,716 m)",
      engines: "2× Rolls-Royce Tay 611-8 turbofan",
      crew: "2",
      capacity: "14–19 passengers",
    },
    description:
      "The Gulfstream IV is the fourth generation of Gulfstream business jets, introducing high-bypass turbofan engines for improved fuel efficiency and reduced noise. The GIV-SP (Special Performance) variant and its successor the G400 offered improved performance. The aircraft features the signature Gulfstream oval windows and a conventional tail configuration.",
    funFact:
      "The Gulfstream IV was the first business jet to circumnavigate the globe westbound, completing the trip in 45 hours, 25 minutes in 1988.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "modern",
      distinguishingFeatures: [
        "oval Gulfstream windows",
        "rear-mounted twin engines",
        "swept low wing",
        "conventional tail",
        "Rolls-Royce Tay nacelles",
      ],
    },
    aliases: ["GIV", "G400", "Gulfstream IV", "Gulfstream 400", "GIV-SP", "C-20"],
  },
  {
    id: "gulfstream-gv-g500",
    name: "Gulfstream GV / G500",
    manufacturer: "Gulfstream Aerospace",
    type: "Business Jet",
    variant: "GV / G500",
    firstFlight: "1995",
    inService: "1997",
    role: "Ultra-Long-Range Large Business Jet",
    country: "USA",
    specs: {
      wingspan: "93 ft 6 in (28.50 m)",
      length: "96 ft 5 in (29.39 m)",
      maxSpeed: "Mach 0.885",
      range: "6,500 nm (12,038 km)",
      ceiling: "51,000 ft (15,545 m)",
      engines: "2× Rolls-Royce BR710-48 turbofan",
      crew: "2",
      capacity: "14–19 passengers",
    },
    description:
      "The Gulfstream V was a landmark aircraft that defined the ultra-long-range business jet category, capable of non-stop transatlantic and transpacific flight. It introduced the BR710 high-bypass turbofan and established many of the design cues later refined in the G550. The G500 was the updated designation for later production aircraft.",
    funFact:
      "The US Air Force operates the GV as the C-37A for senior government and military official transport, and NASA uses modified GVs for atmospheric research.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "modern",
      distinguishingFeatures: [
        "oval Gulfstream windows",
        "rear-mounted twin engines",
        "winglets",
        "long-range wide-body fuselage",
        "swept low wing",
      ],
    },
    aliases: ["GV", "G500", "Gulfstream V", "Gulfstream 500", "C-37A"],
  },

  // ============================================================
  // BOMBARDIER GLOBAL SERIES
  // ============================================================
  {
    id: "bombardier-global-7500",
    name: "Bombardier Global 7500",
    manufacturer: "Bombardier",
    type: "Business Jet",
    variant: "Global 7500",
    firstFlight: "2016",
    inService: "2018",
    role: "Ultra-Long-Range Ultra-Large Business Jet",
    country: "Canada",
    specs: {
      wingspan: "104 ft (31.39 m)",
      length: "111 ft (33.84 m)",
      maxSpeed: "Mach 0.925",
      range: "7,700 nm (14,260 km)",
      ceiling: "51,000 ft (15,545 m)",
      engines: "2× GE Passport turbofan",
      crew: "2–3",
      capacity: "19 passengers",
    },
    description:
      "The Bombardier Global 7500 is the world's largest and longest-range purpose-built business jet, with the ability to fly non-stop from New York to Singapore. It features four living spaces, a full stand-up galley, a dedicated crew rest area, and a bespoke interior. The aircraft uses the new GE Passport engines and features a smooth ride with active turbulence reduction.",
    funFact:
      "The Global 7500 flew non-stop from Singapore to Tucson — a distance of 8,152 nm — to set the world record for the longest non-stop business jet flight.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "longest business jet fuselage",
        "swept wing with winglets",
        "rear-mounted twin GE Passport engines",
        "square-oval cabin windows",
        "four distinct cabin zones",
      ],
    },
    aliases: ["Global 7500", "BD-700-2A12"],
  },
  {
    id: "bombardier-global-6500",
    name: "Bombardier Global 6500",
    manufacturer: "Bombardier",
    type: "Business Jet",
    variant: "Global 6500",
    firstFlight: "2018",
    inService: "2019",
    role: "Ultra-Long-Range Large Business Jet",
    country: "Canada",
    specs: {
      wingspan: "94 ft (28.65 m)",
      length: "99 ft 5 in (30.30 m)",
      maxSpeed: "Mach 0.90",
      range: "6,600 nm (12,223 km)",
      ceiling: "51,000 ft (15,545 m)",
      engines: "2× Rolls-Royce Pearl 15 turbofan",
      crew: "2",
      capacity: "17 passengers",
    },
    description:
      "The Bombardier Global 6500 is a re-engined and updated version of the Global 6000, featuring new Rolls-Royce Pearl 15 engines for improved fuel efficiency and range. It offers a wide-body cabin with up to four living zones and is certified for steep approaches into airports like London City. The Global 6500 benefits from the same smooth-ride technology as the Global 7500.",
    funFact:
      "The Global 6500 is one of only a handful of large business jets certified for steep approaches (5.5° glidepath) into London City Airport, which most large jets cannot access.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "Rolls-Royce Pearl engine nacelles",
        "rear-mounted twin engines",
        "swept wing with winglets",
        "wide-body fuselage",
        "square-oval cabin windows",
      ],
    },
    aliases: ["Global 6500", "BD-700"],
  },
  {
    id: "bombardier-global-5500",
    name: "Bombardier Global 5500",
    manufacturer: "Bombardier",
    type: "Business Jet",
    variant: "Global 5500",
    firstFlight: "2018",
    inService: "2019",
    role: "Long-Range Large Business Jet",
    country: "Canada",
    specs: {
      wingspan: "94 ft (28.65 m)",
      length: "96 ft 5 in (29.39 m)",
      maxSpeed: "Mach 0.90",
      range: "5,900 nm (10,927 km)",
      ceiling: "51,000 ft (15,545 m)",
      engines: "2× Rolls-Royce Pearl 15 turbofan",
      crew: "2",
      capacity: "16 passengers",
    },
    description:
      "The Bombardier Global 5500 is a re-engined evolution of the Global 5000, updated with Rolls-Royce Pearl 15 engines and refined aerodynamics for improved range and efficiency. It offers a wide-body cabin with three living zones and full stand-up headroom throughout. The aircraft shares its wing and tail structure with the Global 6500.",
    funFact:
      "When launched in 2018, the Global 5500 offered 500 nm more range than the Global 5000 it replaced, while also reducing operating costs through the new Pearl engines.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "Rolls-Royce Pearl engine nacelles",
        "rear-mounted twin engines",
        "swept wing with winglets",
        "wide-body fuselage",
        "shorter than Global 6500",
      ],
    },
    aliases: ["Global 5500"],
  },
  {
    id: "bombardier-challenger-650",
    name: "Bombardier Challenger 650",
    manufacturer: "Bombardier",
    type: "Business Jet",
    variant: "Challenger 650",
    firstFlight: "2014",
    inService: "2015",
    role: "Super-Midsize Business Jet",
    country: "Canada",
    specs: {
      wingspan: "64 ft 4 in (19.61 m)",
      length: "87 ft 10 in (26.77 m)",
      maxSpeed: "Mach 0.882",
      range: "4,000 nm (7,408 km)",
      ceiling: "41,000 ft (12,497 m)",
      engines: "2× General Electric CF34-3B turbofan",
      crew: "2",
      capacity: "19 passengers",
    },
    description:
      "The Bombardier Challenger 650 is an updated version of the Challenger 600 series, featuring improved avionics, enhanced cabin technology, and better fuel efficiency. It is renowned for its exceptionally wide stand-up cabin — the widest in its class — and its reliability in corporate and charter operations. The aircraft uses a T-tail configuration with rear-mounted engines.",
    funFact:
      "The Challenger 600 series has accumulated over 13 million flight hours and is one of the most popular large-cabin business jets ever built, with over 1,000 delivered.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "T-tail configuration",
        "rear-mounted twin engines",
        "wide-body fuselage",
        "circular cabin windows",
        "supercritical wing",
      ],
    },
    aliases: ["Challenger 650", "CL-650", "CRJ-600 predecessor"],
  },
  {
    id: "bombardier-challenger-350",
    name: "Bombardier Challenger 350",
    manufacturer: "Bombardier",
    type: "Business Jet",
    variant: "Challenger 350",
    firstFlight: "2013",
    inService: "2014",
    role: "Super-Midsize Business Jet",
    country: "Canada",
    specs: {
      wingspan: "69 ft 2 in (21.08 m)",
      length: "68 ft 11 in (21.00 m)",
      maxSpeed: "Mach 0.883",
      range: "3,200 nm (5,926 km)",
      ceiling: "45,000 ft (13,716 m)",
      engines: "2× Honeywell HTF7350 turbofan",
      crew: "2",
      capacity: "10 passengers",
    },
    description:
      "The Bombardier Challenger 350 is a super-midsize business jet evolved from the Challenger 300, featuring new winglets, improved engines, and enhanced avionics. It offers a flat-floor stand-up cabin, large panoramic windows, and an advanced Rockwell Collins Pro Line Fusion avionics suite. The Challenger 350 has become one of the best-selling business jets in the super-midsize category.",
    funFact:
      "The Challenger 350's Honeywell Primus Elite avionics suite features synthetic vision that can display a 3D rendering of terrain even in zero-visibility conditions.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "distinctive winglets",
        "rear-mounted twin engines",
        "large panoramic oval windows",
        "conventional tail",
        "flat-floor cabin",
      ],
    },
    aliases: ["Challenger 350", "CL-350"],
  },
  {
    id: "bombardier-challenger-300",
    name: "Bombardier Challenger 300",
    manufacturer: "Bombardier",
    type: "Business Jet",
    variant: "Challenger 300",
    firstFlight: "2001",
    inService: "2003",
    role: "Super-Midsize Business Jet",
    country: "Canada",
    specs: {
      wingspan: "63 ft 10 in (19.46 m)",
      length: "68 ft 11 in (21.00 m)",
      maxSpeed: "Mach 0.82",
      range: "3,100 nm (5,741 km)",
      ceiling: "45,000 ft (13,716 m)",
      engines: "2× Honeywell HTF7000 turbofan",
      crew: "2",
      capacity: "10 passengers",
    },
    description:
      "The Bombardier Challenger 300 was a clean-sheet design that created the super-midsize category, offering near-large-cabin roominess in a mid-size airframe. It features a flat-floor stand-up cabin, an advanced supercritical wing, and a conventional tail. The Challenger 300 was a commercial success that led directly to the improved Challenger 350.",
    funFact:
      "The Challenger 300 was the first clean-sheet business jet design by Bombardier, as earlier Challenger aircraft were developed from existing de Havilland designs.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "rear-mounted twin engines",
        "supercritical swept wing",
        "large oval cabin windows",
        "conventional tail",
        "flat-floor cabin",
      ],
    },
    aliases: ["Challenger 300", "CL-300"],
  },
  {
    id: "bombardier-learjet-45",
    name: "Bombardier Learjet 45",
    manufacturer: "Bombardier / Learjet",
    type: "Business Jet",
    variant: "Learjet 45",
    firstFlight: "1995",
    inService: "1998",
    role: "Midsize Business Jet",
    country: "USA",
    specs: {
      wingspan: "47 ft 10 in (14.58 m)",
      length: "58 ft (17.68 m)",
      maxSpeed: "Mach 0.81 (534 mph / 859 km/h)",
      range: "2,200 nm (4,074 km)",
      ceiling: "51,000 ft (15,545 m)",
      engines: "2× Honeywell TFE731-20 turbofan",
      crew: "2",
      capacity: "9 passengers",
    },
    description:
      "The Learjet 45 was a new-generation midsize business jet designed to bridge the gap between the smaller Learjet 31 and larger competitors. It introduced a stand-up flat-floor cabin to the Learjet line and featured an all-new supercritical wing. The aircraft is known for its T-tail configuration inherited from Learjet tradition and its high-altitude cruise performance.",
    funFact:
      "The Learjet 45 was developed after Bombardier acquired Learjet in 1990 and represents the first entirely new Learjet design under Canadian ownership.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "T-tail configuration",
        "rear-mounted twin engines",
        "Learjet pointed nose",
        "low swept wing",
        "stand-up flat-floor cabin",
      ],
    },
    aliases: ["Learjet 45", "LJ45"],
  },
  {
    id: "bombardier-learjet-75",
    name: "Bombardier Learjet 75",
    manufacturer: "Bombardier / Learjet",
    type: "Business Jet",
    variant: "Learjet 75",
    firstFlight: "2013",
    inService: "2013",
    role: "Midsize Business Jet",
    country: "USA",
    specs: {
      wingspan: "47 ft 10 in (14.58 m)",
      length: "58 ft (17.68 m)",
      maxSpeed: "Mach 0.81",
      range: "2,040 nm (3,778 km)",
      ceiling: "51,000 ft (15,545 m)",
      engines: "2× Honeywell TFE731-40BR turbofan",
      crew: "2",
      capacity: "9 passengers",
    },
    description:
      "The Learjet 75 is the most advanced aircraft in the Learjet lineup, featuring a Rockwell Collins Pro Line Fusion touchscreen avionics suite and improved engines over the Learjet 45XR it replaced. It retains the classic Learjet T-tail and low wing design with distinctive winglets. Production of the Learjet 75 ended in 2021 when Bombardier discontinued the Learjet line.",
    funFact:
      "The Learjet 75 was the final Learjet ever built — Bombardier announced the end of Learjet production in February 2021, closing a chapter that started with the legendary Learjet 23 in 1963.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "T-tail configuration",
        "rear-mounted twin engines",
        "Learjet pointed nose",
        "winglets",
        "low swept wing",
      ],
    },
    aliases: ["Learjet 75", "LJ75", "Learjet 75 Liberty"],
  },

  // ============================================================
  // CESSNA CITATION
  // ============================================================
  {
    id: "cessna-citation-cj3plus",
    name: "Cessna Citation CJ3+",
    manufacturer: "Cessna / Textron Aviation",
    type: "Business Jet",
    variant: "CJ3+",
    firstFlight: "2014",
    inService: "2014",
    role: "Light Business Jet",
    country: "USA",
    specs: {
      wingspan: "53 ft 3 in (16.23 m)",
      length: "51 ft 2 in (15.60 m)",
      maxSpeed: "480 mph (772 km/h)",
      range: "2,040 nm (3,778 km)",
      ceiling: "45,000 ft (13,716 m)",
      engines: "2× Williams FJ44-3A turbofan",
      crew: "1–2",
      capacity: "7 passengers",
    },
    description:
      "The Cessna Citation CJ3+ is an updated version of the popular CJ3 light jet, featuring the Garmin G3000 touch avionics suite while retaining the proven Williams FJ44 engines and airframe. It is known for its fuel efficiency, ability to operate from short runways, and single-pilot certification. The CJ3+ features a distinctive T-tail and straight wing design.",
    funFact:
      "The CJ3+ is single-pilot certified, meaning one qualified pilot can legally operate it without a co-pilot — a key selling point for owner-operators.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "T-tail configuration",
        "straight low wing",
        "rear-mounted twin engines",
        "Citation family nose profile",
        "small oval windows",
      ],
    },
    aliases: ["CJ3+", "Citation CJ3+", "525B"],
  },
  {
    id: "cessna-citation-cj4",
    name: "Cessna Citation CJ4",
    manufacturer: "Cessna / Textron Aviation",
    type: "Business Jet",
    variant: "CJ4",
    firstFlight: "2008",
    inService: "2010",
    role: "Light Business Jet",
    country: "USA",
    specs: {
      wingspan: "50 ft 9 in (15.47 m)",
      length: "53 ft 3 in (16.23 m)",
      maxSpeed: "489 mph (787 km/h)",
      range: "2,165 nm (4,009 km)",
      ceiling: "45,000 ft (13,716 m)",
      engines: "2× Williams FJ44-4A turbofan",
      crew: "1–2",
      capacity: "9 passengers",
    },
    description:
      "The Cessna Citation CJ4 is the largest aircraft in the Citation CJ family, offering a stretch of the CJ3 fuselage with more powerful Williams FJ44-4A engines and enhanced range. It features the Rockwell Collins Pro Line 21 avionics and a redesigned swept wing for better high-speed performance. Like all CJ variants, it is single-pilot certified.",
    funFact:
      "The CJ4's cabin can accommodate a standard-size adult standing partially upright, with a maximum interior height of 4 ft 9 in — a significant achievement for a light jet.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "T-tail configuration",
        "swept low wing",
        "rear-mounted twin engines",
        "slightly larger than CJ3",
        "Citation nose profile",
      ],
    },
    aliases: ["CJ4", "Citation CJ4", "525C"],
  },
  {
    id: "cessna-citation-latitude",
    name: "Cessna Citation Latitude",
    manufacturer: "Cessna / Textron Aviation",
    type: "Business Jet",
    variant: "Citation Latitude",
    firstFlight: "2014",
    inService: "2015",
    role: "Midsize Business Jet",
    country: "USA",
    specs: {
      wingspan: "72 ft 3 in (22.02 m)",
      length: "62 ft 3 in (18.97 m)",
      maxSpeed: "Mach 0.81 (527 mph / 848 km/h)",
      range: "2,700 nm (5,001 km)",
      ceiling: "45,000 ft (13,716 m)",
      engines: "2× Pratt & Whitney Canada PW306D1 turbofan",
      crew: "2",
      capacity: "9 passengers",
    },
    description:
      "The Cessna Citation Latitude is a midsize business jet featuring a new wide-body flat-floor cabin with full stand-up headroom of 6 feet, a significant step up from earlier Citation models. It uses a new supercritical wing and Pratt & Whitney Canada PW306D1 engines. The Latitude continues the Citation tradition of a T-tail configuration.",
    funFact:
      "The Citation Latitude was the first midsize business jet in its price range to offer a flat-floor cabin with true full stand-up headroom of six feet.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "T-tail configuration",
        "swept supercritical wing",
        "rear-mounted twin engines",
        "full stand-up cabin",
        "wide oval windows",
      ],
    },
    aliases: ["Citation Latitude", "680A"],
  },
  {
    id: "cessna-citation-longitude",
    name: "Cessna Citation Longitude",
    manufacturer: "Cessna / Textron Aviation",
    type: "Business Jet",
    variant: "Citation Longitude",
    firstFlight: "2016",
    inService: "2019",
    role: "Super-Midsize Business Jet",
    country: "USA",
    specs: {
      wingspan: "69 ft 10 in (21.29 m)",
      length: "70 ft 4 in (21.43 m)",
      maxSpeed: "Mach 0.84",
      range: "3,500 nm (6,482 km)",
      ceiling: "45,000 ft (13,716 m)",
      engines: "2× Honeywell HTF7700L turbofan",
      crew: "2",
      capacity: "12 passengers",
    },
    description:
      "The Cessna Citation Longitude is Cessna's flagship super-midsize business jet, built on the Citation Latitude platform with a stretched fuselage, new engines, and extended range. It features a flat-floor stand-up cabin with 12 seats, Garmin G5000 avionics, and a distinctive swept wing. The Longitude targets the competitive super-midsize segment against the Challenger 350 and Praetor 600.",
    funFact:
      "The Citation Longitude's development was more challenging than anticipated, causing it to slip several years behind schedule, but the resulting aircraft received strong market reception upon certification in 2019.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "T-tail configuration",
        "swept wing",
        "rear-mounted twin engines",
        "stretched Citation fuselage",
        "large oval windows",
      ],
    },
    aliases: ["Citation Longitude", "700"],
  },
  {
    id: "cessna-citation-x",
    name: "Cessna Citation X",
    manufacturer: "Cessna / Textron Aviation",
    type: "Business Jet",
    variant: "Citation X / X+",
    firstFlight: "1993",
    inService: "1996",
    role: "Super-Midsize Business Jet",
    country: "USA",
    specs: {
      wingspan: "63 ft 11 in (19.48 m)",
      length: "72 ft 4 in (22.04 m)",
      maxSpeed: "Mach 0.935 (617 mph / 993 km/h)",
      range: "3,460 nm (6,408 km)",
      ceiling: "51,000 ft (15,545 m)",
      engines: "2× Rolls-Royce AE 3007C turbofan",
      crew: "2",
      capacity: "12 passengers",
    },
    description:
      "The Cessna Citation X is the fastest civilian aircraft in production, capable of Mach 0.935 — just shy of the speed of sound. It features a highly swept supercritical wing, Rolls-Royce AE3007C engines, and a T-tail configuration. The Citation X+ variant added enhanced avionics and improved engines. It is a favorite of time-sensitive travelers and celebrities for its ability to cross the continent faster than any competing jet.",
    funFact:
      "The Citation X holds the FAI record as the fastest civilian business jet in the world, and was famously used by Tiger Woods to commute to tournaments — he reportedly crossed the US in under four hours.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "highly swept supercritical wing",
        "T-tail configuration",
        "rear-mounted twin engines",
        "long slender fuselage",
        "Rolls-Royce nacelles",
      ],
    },
    aliases: ["Citation X", "Citation Ten", "750", "Citation X+"],
  },
  {
    id: "cessna-citation-sovereign",
    name: "Cessna Citation Sovereign",
    manufacturer: "Cessna / Textron Aviation",
    type: "Business Jet",
    variant: "Citation Sovereign / Sovereign+",
    firstFlight: "2002",
    inService: "2004",
    role: "Midsize Business Jet",
    country: "USA",
    specs: {
      wingspan: "72 ft 4 in (22.04 m)",
      length: "63 ft 6 in (19.35 m)",
      maxSpeed: "Mach 0.80 (528 mph / 850 km/h)",
      range: "3,200 nm (5,926 km)",
      ceiling: "47,000 ft (14,326 m)",
      engines: "2× Pratt & Whitney Canada PW306C turbofan",
      crew: "2",
      capacity: "12 passengers",
    },
    description:
      "The Cessna Citation Sovereign is a midsize business jet positioned between the Citation Excel and Citation X in the product line. It features a new wing design with greater span, Pratt & Whitney Canada PW306C engines, and a T-tail configuration. The Sovereign+ introduced enhanced avionics and a Collins Pro Line 21 suite, and it was later replaced by the Citation Latitude.",
    funFact:
      "The Citation Sovereign was certified for steep approaches and short-field operations, allowing it to access over 400 airports that jets of comparable size cannot use.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "T-tail configuration",
        "rear-mounted twin engines",
        "wide-span swept wing",
        "Citation nose profile",
        "oval windows",
      ],
    },
    aliases: ["Citation Sovereign", "Citation Sovereign+", "680"],
  },
  {
    id: "cessna-citation-excel-xls",
    name: "Cessna Citation Excel / XLS",
    manufacturer: "Cessna / Textron Aviation",
    type: "Business Jet",
    variant: "Citation Excel / XLS / XLS+",
    firstFlight: "1996",
    inService: "1998",
    role: "Midsize Business Jet",
    country: "USA",
    specs: {
      wingspan: "56 ft 4 in (17.17 m)",
      length: "58 ft 9 in (17.91 m)",
      maxSpeed: "Mach 0.82 (507 mph / 816 km/h)",
      range: "2,100 nm (3,890 km)",
      ceiling: "45,000 ft (13,716 m)",
      engines: "2× Pratt & Whitney Canada PW545C turbofan",
      crew: "2",
      capacity: "8 passengers",
    },
    description:
      "The Cessna Citation Excel was a breakthrough midsize business jet that combined the wide flat-floor stand-up cabin of the Sovereign with the Citation V/Ultra wing and Citation X engines. The XLS and XLS+ variants added more powerful PW545 engines and improved avionics. It became one of the best-selling midsize business jets ever produced.",
    funFact:
      "The Citation Excel and its XLS variants became the best-selling midsize business jet family in history, with over 1,000 aircraft delivered across all variants.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "T-tail configuration",
        "rear-mounted twin engines",
        "swept low wing",
        "flat-floor stand-up cabin",
        "round cabin windows",
      ],
    },
    aliases: ["Citation Excel", "Citation XLS", "Citation XLS+", "560XL", "560XLS"],
  },

  // ============================================================
  // DASSAULT FALCON
  // ============================================================
  {
    id: "dassault-falcon-900lx",
    name: "Dassault Falcon 900LX",
    manufacturer: "Dassault Aviation",
    type: "Business Jet",
    variant: "Falcon 900LX",
    firstFlight: "2009",
    inService: "2010",
    role: "Long-Range Large Business Jet",
    country: "France",
    specs: {
      wingspan: "63 ft 5 in (19.33 m)",
      length: "66 ft 4 in (20.21 m)",
      maxSpeed: "Mach 0.87",
      range: "4,750 nm (8,800 km)",
      ceiling: "51,000 ft (15,545 m)",
      engines: "3× Honeywell TFE731-60 turbofan",
      crew: "2",
      capacity: "12–19 passengers",
    },
    description:
      "The Dassault Falcon 900LX is an enhanced version of the Falcon 900EX with blended winglets for improved range and fuel efficiency. Like all Falcon 900 variants, it features the distinctive tri-engine configuration with two rear-fuselage-mounted engines and one engine in the tail. The wide-body cabin offers exceptional comfort for long-range missions.",
    funFact:
      "The three-engine layout of the Falcon 900 series was originally designed to allow it to fly ETOPS-equivalent routes over water, as older regulations required three engines for oceanic flights beyond twin-engine range limits.",
    visual: {
      engineCount: 3,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted and tail-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "three-engine configuration",
        "S-duct center engine in tail",
        "two side-mounted rear engines",
        "winglets",
        "wide-body fuselage",
        "oval windows",
      ],
    },
    aliases: ["Falcon 900LX", "Falcon 900EX", "Falcon 900"],
  },
  {
    id: "dassault-falcon-7x",
    name: "Dassault Falcon 7X",
    manufacturer: "Dassault Aviation",
    type: "Business Jet",
    variant: "Falcon 7X",
    firstFlight: "2005",
    inService: "2007",
    role: "Ultra-Long-Range Large Business Jet",
    country: "France",
    specs: {
      wingspan: "86 ft (26.21 m)",
      length: "76 ft 2 in (23.22 m)",
      maxSpeed: "Mach 0.90",
      range: "5,950 nm (11,019 km)",
      ceiling: "51,000 ft (15,545 m)",
      engines: "3× Pratt & Whitney Canada PW307A turbofan",
      crew: "2",
      capacity: "12–16 passengers",
    },
    description:
      "The Dassault Falcon 7X was the world's first business jet designed entirely using digital design and simulation tools, featuring a fly-by-wire flight control system. It retains the distinctive Falcon three-engine layout with two side engines and a centerline S-duct tail engine. The 7X offers exceptional fuel efficiency and is renowned for its smooth ride and handling.",
    funFact:
      "The Falcon 7X was the first business jet ever designed entirely on computer with no physical mock-up, using Dassault's CATIA digital design software — the same tool used to design the Rafale fighter jet.",
    visual: {
      engineCount: 3,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted and tail-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "modern",
      distinguishingFeatures: [
        "three-engine configuration",
        "S-duct center engine in tail",
        "two side-mounted rear engines",
        "wide-body fuselage",
        "fly-by-wire controls",
        "oval windows",
      ],
    },
    aliases: ["Falcon 7X"],
  },
  {
    id: "dassault-falcon-8x",
    name: "Dassault Falcon 8X",
    manufacturer: "Dassault Aviation",
    type: "Business Jet",
    variant: "Falcon 8X",
    firstFlight: "2015",
    inService: "2016",
    role: "Ultra-Long-Range Large Business Jet",
    country: "France",
    specs: {
      wingspan: "86 ft (26.21 m)",
      length: "80 ft 6 in (24.54 m)",
      maxSpeed: "Mach 0.90",
      range: "6,450 nm (11,945 km)",
      ceiling: "51,000 ft (15,545 m)",
      engines: "3× Pratt & Whitney Canada PW307D turbofan",
      crew: "2",
      capacity: "14–16 passengers",
    },
    description:
      "The Dassault Falcon 8X is a stretched and extended-range version of the Falcon 7X, featuring a longer fuselage accommodating up to three cabin zones, improved PW307D engines, and new winglets. It retains the three-engine configuration unique to the Falcon 900 and 7X families. The 8X is the longest-range aircraft in the Falcon line and competes directly with the Global 6500 and Gulfstream G650.",
    funFact:
      "The Falcon 8X can fly non-stop from Paris to Los Angeles westbound — a trip of over 5,900 nm — while offering passengers one of the quietest cabins of any business jet.",
    visual: {
      engineCount: 3,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted and tail-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "three-engine configuration",
        "S-duct center engine in tail",
        "two side-mounted rear engines",
        "stretched fuselage vs 7X",
        "winglets",
        "oval windows",
      ],
    },
    aliases: ["Falcon 8X"],
  },
  {
    id: "dassault-falcon-2000lxs",
    name: "Dassault Falcon 2000LXS",
    manufacturer: "Dassault Aviation",
    type: "Business Jet",
    variant: "Falcon 2000LXS",
    firstFlight: "2013",
    inService: "2013",
    role: "Long-Range Large Business Jet",
    country: "France",
    specs: {
      wingspan: "63 ft 5 in (19.33 m)",
      length: "63 ft 6 in (19.36 m)",
      maxSpeed: "Mach 0.862",
      range: "4,000 nm (7,408 km)",
      ceiling: "47,000 ft (14,326 m)",
      engines: "2× Pratt & Whitney Canada PW308C turbofan",
      crew: "2",
      capacity: "10–12 passengers",
    },
    description:
      "The Dassault Falcon 2000LXS combines the extended range of the Falcon 2000LX with steep-approach capability (5.5°) for access to London City Airport and similar challenging airports. It uses PW308C engines and blended winglets for efficiency. Unlike the Falcon 900 and 7X/8X families, the 2000 series uses only two engines, making it more economical to operate.",
    funFact:
      "The Falcon 2000LXS is one of only two long-range jets certified for steep approaches into London City Airport — the other being the Bombardier Global 6500 — thanks to its unique high-lift wing design.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "twin-engine configuration",
        "rear-mounted twin engines",
        "winglets",
        "conventional Dassault tail",
        "wide-body Falcon fuselage",
        "oval windows",
      ],
    },
    aliases: ["Falcon 2000LXS", "Falcon 2000LX", "Falcon 2000"],
  },
  {
    id: "dassault-falcon-6x",
    name: "Dassault Falcon 6X",
    manufacturer: "Dassault Aviation",
    type: "Business Jet",
    variant: "Falcon 6X",
    firstFlight: "2021",
    inService: "2023",
    role: "Ultra-Long-Range Large Business Jet",
    country: "France",
    specs: {
      wingspan: "88 ft 8 in (27.02 m)",
      length: "80 ft 8 in (24.58 m)",
      maxSpeed: "Mach 0.90",
      range: "5,500 nm (10,186 km)",
      ceiling: "51,000 ft (15,545 m)",
      engines: "2× Pratt & Whitney Canada PW812D turbofan",
      crew: "2",
      capacity: "12–16 passengers",
    },
    description:
      "The Dassault Falcon 6X is the newest member of the Falcon family, featuring the widest cabin of any purpose-built business jet at 8 feet 6 inches. It uses Pratt & Whitney Canada PW812D engines and a new fly-by-wire system. Unlike the Falcon 7X and 8X, the 6X uses a twin-engine layout, which was selected after the original 5X program was cancelled due to engine issues.",
    funFact:
      "The Falcon 6X was originally going to be the Falcon 5X with Safran Silvercrest engines, but after years of engine development problems, Dassault cancelled that program and restarted with PW812D engines as the Falcon 6X.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "twin-engine configuration",
        "widest cabin in class",
        "rear-mounted twin engines",
        "swept wing",
        "conventional Dassault tail",
        "large oval windows",
      ],
    },
    aliases: ["Falcon 6X"],
  },
  {
    id: "dassault-falcon-50",
    name: "Dassault Falcon 50",
    manufacturer: "Dassault Aviation",
    type: "Business Jet",
    variant: "Falcon 50 / 50EX",
    firstFlight: "1976",
    inService: "1979",
    role: "Long-Range Midsize Business Jet",
    country: "France",
    specs: {
      wingspan: "61 ft 10 in (18.86 m)",
      length: "60 ft 9 in (18.52 m)",
      maxSpeed: "Mach 0.858",
      range: "3,450 nm (6,390 km)",
      ceiling: "49,000 ft (14,935 m)",
      engines: "3× Honeywell TFE731-40 turbofan",
      crew: "2",
      capacity: "8–9 passengers",
    },
    description:
      "The Dassault Falcon 50 is a long-range trijet business jet that established the Falcon family's tri-engine tradition. It uses the same fuselage cross-section as the Falcon 20 but with a new supercritical wing and three TFE731 engines — two on the rear fuselage sides and one through an S-duct in the tail. The Falcon 50EX introduced improved engines and avionics.",
    funFact:
      "The Falcon 50 was the first intercontinental business jet capable of transatlantic flight in its class, and it set multiple speed and range records when it entered service in 1979.",
    visual: {
      engineCount: 3,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted and tail-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "three-engine configuration",
        "S-duct center engine in tail",
        "two side-mounted rear engines",
        "supercritical wing",
        "oval Falcon windows",
      ],
    },
    aliases: ["Falcon 50", "Falcon 50EX"],
  },

  // ============================================================
  // EMBRAER
  // ============================================================
  {
    id: "embraer-phenom-100ev",
    name: "Embraer Phenom 100EV",
    manufacturer: "Embraer",
    type: "Business Jet",
    variant: "Phenom 100EV",
    firstFlight: "2007",
    inService: "2008",
    role: "Very Light Jet",
    country: "Brazil",
    specs: {
      wingspan: "40 ft 5 in (12.32 m)",
      length: "42 ft 2 in (12.85 m)",
      maxSpeed: "Mach 0.70 (453 mph / 730 km/h)",
      range: "1,178 nm (2,182 km)",
      ceiling: "41,000 ft (12,497 m)",
      engines: "2× Pratt & Whitney Canada PW617F-E turbofan",
      crew: "1",
      capacity: "4 passengers",
    },
    description:
      "The Embraer Phenom 100EV is a very light jet that redefined the entry-level business jet segment with its full stand-up flat-floor cabin, oval cabin windows, and ergonomic interior. The EV variant features upgraded PW617F-E engines, Garmin G950 avionics, and improved cabin pressurization for a lower effective cabin altitude. It is single-pilot certified and popular with owner-operators.",
    funFact:
      "The Phenom 100 was designed using a unique 'inside-out' philosophy — Embraer started by designing the ideal passenger experience and then built the aircraft around it, rather than adapting existing airframe technology.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "rear-mounted twin engines",
        "distinctive oval windows",
        "low swept wing",
        "conventional tail",
        "compact fuselage",
      ],
    },
    aliases: ["Phenom 100EV", "Phenom 100", "EMB-500"],
  },
  {
    id: "embraer-phenom-300e",
    name: "Embraer Phenom 300E",
    manufacturer: "Embraer",
    type: "Business Jet",
    variant: "Phenom 300E",
    firstFlight: "2008",
    inService: "2009",
    role: "Light Business Jet",
    country: "Brazil",
    specs: {
      wingspan: "52 ft (15.85 m)",
      length: "51 ft 11 in (15.82 m)",
      maxSpeed: "Mach 0.82 (521 mph / 839 km/h)",
      range: "2,010 nm (3,723 km)",
      ceiling: "45,000 ft (13,716 m)",
      engines: "2× Pratt & Whitney Canada PW535E1 turbofan",
      crew: "1–2",
      capacity: "10 passengers",
    },
    description:
      "The Embraer Phenom 300E is the top-selling light business jet in the world, featuring improved PW535E1 engines, enhanced avionics with Garmin G3000, and improved cabin materials. The distinctive T-tail configuration, combined with rear-mounted engines, gives the Phenom 300 its sleek appearance. The 300E added a heads-up display option and improved cabin pressurization.",
    funFact:
      "The Phenom 300 series has been the world's best-selling light business jet for multiple consecutive years, a record previously held by the Cessna Citation series.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "T-tail configuration",
        "rear-mounted twin engines",
        "swept low wing",
        "oval cabin windows",
        "sleek pointed nose",
      ],
    },
    aliases: ["Phenom 300E", "Phenom 300", "EMB-505"],
  },
  {
    id: "embraer-praetor-500",
    name: "Embraer Praetor 500",
    manufacturer: "Embraer",
    type: "Business Jet",
    variant: "Praetor 500",
    firstFlight: "2018",
    inService: "2019",
    role: "Midsize Business Jet",
    country: "Brazil",
    specs: {
      wingspan: "66 ft 4 in (20.22 m)",
      length: "65 ft 4 in (19.91 m)",
      maxSpeed: "Mach 0.83",
      range: "3,340 nm (6,185 km)",
      ceiling: "45,000 ft (13,716 m)",
      engines: "2× Honeywell HTF7500E turbofan",
      crew: "2",
      capacity: "9 passengers",
    },
    description:
      "The Embraer Praetor 500 is a midsize business jet derived from the Legacy 450, featuring new Honeywell HTF7500E engines with thrust reversers, new winglets, and advanced fly-by-wire flight controls. It offers exceptional range in the midsize category and a flat-floor stand-up cabin with 6-foot headroom. The Praetor 500 competes against the Challenger 350 and Cessna Citation Longitude.",
    funFact:
      "The Praetor 500 is the only midsize business jet with fly-by-wire flight controls, a technology previously found only in large and ultra-long-range business jets and military aircraft.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "distinctive winglets",
        "rear-mounted twin engines",
        "fly-by-wire flight controls",
        "conventional tail",
        "swept low wing",
        "oval cabin windows",
      ],
    },
    aliases: ["Praetor 500"],
  },
  {
    id: "embraer-praetor-600",
    name: "Embraer Praetor 600",
    manufacturer: "Embraer",
    type: "Business Jet",
    variant: "Praetor 600",
    firstFlight: "2018",
    inService: "2019",
    role: "Super-Midsize Business Jet",
    country: "Brazil",
    specs: {
      wingspan: "71 ft 4 in (21.74 m)",
      length: "72 ft 2 in (22.00 m)",
      maxSpeed: "Mach 0.83",
      range: "4,018 nm (7,441 km)",
      ceiling: "45,000 ft (13,716 m)",
      engines: "2× Honeywell HTF7500E turbofan",
      crew: "2",
      capacity: "12 passengers",
    },
    description:
      "The Embraer Praetor 600 is a super-midsize business jet derived from the Legacy 500, featuring a stretched fuselage, new winglets, and the same fly-by-wire system as the Praetor 500. It offers the longest range in the super-midsize category and can fly non-stop from London to New York. Like the Praetor 500, it features thrust reversers — unusual in this class.",
    funFact:
      "The Praetor 600 is the only super-midsize business jet that can fly non-stop from Europe to the US East Coast, completing the London-to-New York route without a fuel stop.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "distinctive winglets",
        "rear-mounted twin engines",
        "fly-by-wire flight controls",
        "conventional tail",
        "swept low wing",
        "large oval cabin windows",
      ],
    },
    aliases: ["Praetor 600"],
  },
  {
    id: "embraer-legacy-600-650",
    name: "Embraer Legacy 600 / 650",
    manufacturer: "Embraer",
    type: "Business Jet",
    variant: "Legacy 600 / 650",
    firstFlight: "2000",
    inService: "2001",
    role: "Large Business Jet",
    country: "Brazil",
    specs: {
      wingspan: "69 ft 9 in (21.26 m)",
      length: "98 ft 1 in (29.90 m)",
      maxSpeed: "Mach 0.80 (519 mph / 834 km/h)",
      range: "3,900 nm (7,223 km)",
      ceiling: "41,000 ft (12,497 m)",
      engines: "2× Rolls-Royce AE 3007A2 turbofan",
      crew: "2",
      capacity: "13–14 passengers",
    },
    description:
      "The Embraer Legacy 600 and 650 are large business jets derived from the Embraer ERJ-135 regional jet, featuring a stretched executive interior, winglets, and additional fuel tanks. The Legacy 650 extended range to 3,900 nm with additional fuel capacity. These aircraft offer a wide regional-airliner-derived cabin with excellent stand-up headroom at a competitive price point.",
    funFact:
      "The Embraer Legacy 600 was famously involved in the Gol Transportes Aéreos Flight 1907 mid-air collision in 2006 over the Brazilian Amazon — the Legacy landed safely despite damage to its winglet, while the Boeing 737 tragically crashed.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "large",
      era: "modern",
      distinguishingFeatures: [
        "T-tail configuration",
        "rear-mounted twin engines",
        "regional jet derived fuselage",
        "winglets",
        "swept low wing",
        "regional jet oval windows",
      ],
    },
    aliases: ["Legacy 600", "Legacy 650", "EMB-135BJ", "EMB-135ER"],
  },

  // ============================================================
  // OTHER
  // ============================================================
  {
    id: "pilatus-pc-24",
    name: "Pilatus PC-24",
    manufacturer: "Pilatus Aircraft",
    type: "Business Jet",
    variant: "PC-24",
    firstFlight: "2015",
    inService: "2018",
    role: "Super-Versatile Jet / Light Business Jet",
    country: "Switzerland",
    specs: {
      wingspan: "55 ft 2 in (16.82 m)",
      length: "55 ft 3 in (16.84 m)",
      maxSpeed: "Mach 0.82 (500 mph / 805 km/h)",
      range: "2,000 nm (3,704 km)",
      ceiling: "45,000 ft (13,716 m)",
      engines: "2× Williams FJ44-4A turbofan",
      crew: "1–2",
      capacity: "9 passengers",
    },
    description:
      "The Pilatus PC-24 is the world's only business jet capable of operating from grass, gravel, and dirt runways, earning it the 'Super Versatile Jet' designation. It features a large cargo door for baggage or medical stretcher loading, a flat-floor cabin, and a unique high-wing-like structure that provides exceptional low-speed handling. The PC-24 evolved from Pilatus's tradition of short takeoff and landing utility aircraft.",
    funFact:
      "The PC-24 can take off and land on unpaved runways as short as 2,790 feet, making it operable from more than 20,000 airports worldwide — compared to about 1,500 for conventional light jets.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "T-tail configuration",
        "rear-mounted twin engines",
        "large rear cargo door",
        "utility jet heritage appearance",
        "large rectangular windows",
        "robust landing gear for rough strips",
      ],
    },
    aliases: ["PC-24", "Super Versatile Jet", "SVJ"],
  },
  {
    id: "honda-ha-420-hondajet",
    name: "HondaJet HA-420",
    manufacturer: "Honda Aircraft Company",
    type: "Business Jet",
    variant: "HA-420 / Elite II",
    firstFlight: "2003",
    inService: "2015",
    role: "Very Light Jet",
    country: "USA / Japan",
    specs: {
      wingspan: "39 ft 9 in (12.12 m)",
      length: "42 ft 7 in (12.98 m)",
      maxSpeed: "Mach 0.72 (424 mph / 782 km/h)",
      range: "1,437 nm (2,661 km)",
      ceiling: "43,000 ft (13,106 m)",
      engines: "2× GE Honda HF120 turbofan",
      crew: "1",
      capacity: "5–6 passengers",
    },
    description:
      "The HondaJet HA-420 is the world's most delivered very light jet and features a radical over-wing engine mount (OEWM) design that is its most distinctive visual feature. This unconventional placement frees the rear fuselage for a larger baggage compartment and a quieter cabin, while reducing interference drag. The HondaJet uses a co-developed GE Honda HF120 engine and a natural laminar flow wing.",
    funFact:
      "The HondaJet's over-wing engine mount was originally considered aerodynamically infeasible, but Honda's founder Soichiro Honda insisted on pursuing the concept, and decades of research by engineer Michimasa Fujino proved it was not only possible but superior in efficiency.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "over-wing-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "over-wing engine mounts (OEWM) — unique to HondaJet",
        "engines mounted on pylons above and forward of wing",
        "no rear-fuselage engine pods",
        "natural laminar flow wing",
        "oval composite nose",
        "conventional tail",
      ],
    },
    aliases: ["HondaJet", "HA-420", "HondaJet Elite", "HondaJet Elite II"],
  },
  {
    id: "bombardier-learjet-60",
    name: "Bombardier Learjet 60",
    manufacturer: "Bombardier / Learjet",
    type: "Business Jet",
    variant: "Learjet 60 / 60XR",
    firstFlight: "1990",
    inService: "1993",
    role: "Midsize Business Jet",
    country: "USA",
    specs: {
      wingspan: "43 ft 9 in (13.34 m)",
      length: "58 ft 8 in (17.88 m)",
      maxSpeed: "Mach 0.81 (534 mph / 859 km/h)",
      range: "2,405 nm (4,454 km)",
      ceiling: "51,000 ft (15,545 m)",
      engines: "2× Pratt & Whitney Canada PW305A turbofan",
      crew: "2",
      capacity: "8 passengers",
    },
    description:
      "The Learjet 60 is a midsize business jet featuring a stretched version of the Learjet 55 fuselage with new Pratt & Whitney Canada PW305 engines. It represents a significant upgrade from earlier Learjets with a more spacious stand-up cabin while retaining the Learjet T-tail and distinctive pointed nose design. The 60XR variant added winglets and improved avionics.",
    funFact:
      "The Learjet 60 can cruise at 51,000 feet — above most airline traffic and commercial weather — making it a high-altitude performer that regularly outclimbs competing jets in its class.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "T-tail configuration",
        "rear-mounted twin engines",
        "iconic Learjet pointed nose",
        "low swept wing",
        "slender fuselage",
      ],
    },
    aliases: ["Learjet 60", "LJ60", "Learjet 60XR"],
  },
  {
    id: "hawker-800xp",
    name: "Hawker 800XP",
    manufacturer: "Raytheon / Hawker Beechcraft",
    type: "Business Jet",
    variant: "Hawker 800XP",
    firstFlight: "1983",
    inService: "1995",
    role: "Midsize Business Jet",
    country: "United Kingdom / USA",
    specs: {
      wingspan: "51 ft 4 in (15.65 m)",
      length: "51 ft 2 in (15.60 m)",
      maxSpeed: "Mach 0.82 (497 mph / 800 km/h)",
      range: "2,900 nm (5,371 km)",
      ceiling: "41,000 ft (12,497 m)",
      engines: "2× Honeywell TFE731-5BR turbofan",
      crew: "2",
      capacity: "8 passengers",
    },
    description:
      "The Hawker 800XP is a midsize business jet descended from the de Havilland DH.125 and developed through Hawker Siddeley, British Aerospace, and Raytheon ownership. It features a T-tail configuration with rear-mounted engines and is known for its wide flat-floor cabin. The 800XP variant introduced more powerful Honeywell TFE731-5BR engines and a Collins EFIS-84 avionics suite.",
    funFact:
      "The Hawker 800's lineage traces all the way back to the de Havilland DH.125 of 1962, making it one of the longest-running and most-evolved business jet designs in history — still recognizably similar after over 50 years of development.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "T-tail configuration",
        "rear-mounted twin engines",
        "squared fuselage cross-section",
        "oval windows",
        "wide flat-floor cabin",
      ],
    },
    aliases: ["Hawker 800XP", "Hawker 800", "HS 125-800", "BAe 125-800", "Raytheon Hawker 800"],
  },
  {
    id: "beechcraft-premier-i",
    name: "Beechcraft Premier I",
    manufacturer: "Raytheon / Beechcraft",
    type: "Business Jet",
    variant: "Premier I / IA",
    firstFlight: "1998",
    inService: "2001",
    role: "Light Business Jet",
    country: "USA",
    specs: {
      wingspan: "44 ft 6 in (13.56 m)",
      length: "46 ft (14.02 m)",
      maxSpeed: "Mach 0.80 (531 mph / 855 km/h)",
      range: "1,500 nm (2,778 km)",
      ceiling: "41,000 ft (12,497 m)",
      engines: "2× Williams FJ44-2A turbofan",
      crew: "1",
      capacity: "6 passengers",
    },
    description:
      "The Beechcraft Premier I is a light business jet notable for its composite fuselage — the first business jet to use this construction method — which provides the widest cabin cross-section in its class. The aircraft features a T-tail and distinctive rear-mounted Williams FJ44 engines, along with Rockwell Collins Pro Line 21 avionics. The Premier IA added improved avionics and customer options.",
    funFact:
      "The Premier I's composite fuselage allows a cabin width of 5 feet 5 inches — wider than the Learjet 45 and comparable to some midsize jets — making it the largest cabin in a light jet at its introduction.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "rear-fuselage-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "T-tail configuration",
        "rear-mounted twin engines",
        "composite fuselage",
        "wide cabin for size class",
        "round oval windows",
        "low swept wing",
      ],
    },
    aliases: ["Premier I", "Premier IA", "Beechjet Premier", "390 Premier I"],
  },
];
