import { AircraftEntry } from "./types";

export const commercialOther: AircraftEntry[] = [
  // ─── EMBRAER E-JETS ───────────────────────────────────────────────────────

  {
    id: "embraer-e170",
    name: "Embraer E170",
    manufacturer: "Embraer",
    type: "Narrow-body Regional Jet",
    firstFlight: "2002",
    inService: "2004",
    role: "Regional airliner",
    country: "Brazil",
    specs: {
      wingspan: "26.0 m (85 ft 3 in)",
      length: "29.9 m (98 ft 1 in)",
      maxSpeed: "Mach 0.82",
      range: "3,735 km (2,320 mi)",
      ceiling: "41,000 ft",
      engines: "2× GE CF34-8E",
      crew: "2",
      capacity: "70–80 passengers",
    },
    description:
      "The E170 is the smallest member of Embraer's original E-Jet family, offering a 2-2 seat configuration across all rows — eliminating the dreaded middle seat. It gave regional operators a quieter, more comfortable alternative to aging jets of the 1980s.",
    funFact:
      "The E170 was the first commercial aircraft to offer a true 2-2 seat layout in its class, meaning every passenger gets either a window or an aisle seat.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Underwing engines",
        "Low wing",
        "Conventional tail",
        "Curved wingtips",
        "2-2 cabin layout",
        "Slightly upturned winglets",
      ],
    },
    aliases: ["E170", "ERJ 170"],
  },

  {
    id: "embraer-e175",
    name: "Embraer E175",
    manufacturer: "Embraer",
    type: "Narrow-body Regional Jet",
    firstFlight: "2003",
    inService: "2005",
    role: "Regional airliner",
    country: "Brazil",
    specs: {
      wingspan: "28.7 m (94 ft 2 in)",
      length: "31.7 m (104 ft 0 in)",
      maxSpeed: "Mach 0.82",
      range: "3,735 km (2,320 mi)",
      ceiling: "41,000 ft",
      engines: "2× GE CF34-8E",
      crew: "2",
      capacity: "76–88 passengers",
    },
    description:
      "The E175 is a stretched variant of the E170, accommodating more passengers while retaining the 2-2 seat configuration. It is one of the most popular regional jets in North America, favored under scope clauses that limit regional jet size.",
    funFact:
      "The E175 is so perfectly sized for US scope clause restrictions that it dominates regional flying for United, American, and Delta regional partners.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Underwing engines",
        "Low wing",
        "Conventional tail",
        "Slightly longer fuselage than E170",
        "Curved winglets",
        "2-2 cabin layout",
      ],
    },
    aliases: ["E175", "ERJ 175"],
  },

  {
    id: "embraer-e190",
    name: "Embraer E190",
    manufacturer: "Embraer",
    type: "Narrow-body Regional Jet",
    firstFlight: "2004",
    inService: "2005",
    role: "Regional / short-haul airliner",
    country: "Brazil",
    specs: {
      wingspan: "28.7 m (94 ft 2 in)",
      length: "36.2 m (118 ft 11 in)",
      maxSpeed: "Mach 0.82",
      range: "4,537 km (2,819 mi)",
      ceiling: "41,000 ft",
      engines: "2× GE CF34-10E",
      crew: "2",
      capacity: "96–114 passengers",
    },
    description:
      "The E190 bridges the gap between regional and mainline operations. With a wider fuselage and longer range than the E170/175, it competes directly with the Boeing 737-600 and Airbus A318 while offering superior fuel efficiency at its seat count.",
    funFact:
      "JetBlue operated E190s with a unique 1-2 configuration in a premium section — giving every passenger aisle access in the front cabin.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Underwing engines",
        "Low wing",
        "Conventional tail",
        "Longer fuselage than E175",
        "Curved winglets",
        "Wider cabin cross-section",
      ],
    },
    aliases: ["E190", "ERJ 190"],
  },

  {
    id: "embraer-e195",
    name: "Embraer E195",
    manufacturer: "Embraer",
    type: "Narrow-body Regional Jet",
    firstFlight: "2004",
    inService: "2006",
    role: "Regional / short-haul airliner",
    country: "Brazil",
    specs: {
      wingspan: "28.7 m (94 ft 2 in)",
      length: "38.7 m (127 ft 0 in)",
      maxSpeed: "Mach 0.82",
      range: "4,260 km (2,647 mi)",
      ceiling: "41,000 ft",
      engines: "2× GE CF34-10E",
      crew: "2",
      capacity: "108–124 passengers",
    },
    description:
      "The E195 is the largest original E-Jet, stretching the E190 fuselage to carry up to 124 passengers. It sits at the boundary between regional and narrow-body mainline operations, often deployed on thinner routes where a 737 or A320 would be uneconomical.",
    funFact:
      "Azul Brazilian Airlines operates the world's largest E195 fleet and used it to open routes between small Brazilian cities that had never had jet service.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Underwing engines",
        "Low wing",
        "Conventional tail",
        "Longest of original E-Jet family",
        "Curved winglets",
        "2-2 cabin layout",
      ],
    },
    aliases: ["E195", "ERJ 195"],
  },

  {
    id: "embraer-e175-e2",
    name: "Embraer E175-E2",
    manufacturer: "Embraer",
    type: "Narrow-body Regional Jet (2nd generation)",
    firstFlight: "2019",
    inService: "2021",
    role: "Regional airliner",
    country: "Brazil",
    specs: {
      wingspan: "31.1 m (102 ft 0 in)",
      length: "33.7 m (110 ft 7 in)",
      maxSpeed: "Mach 0.82",
      range: "3,735 km (2,320 mi)",
      ceiling: "41,000 ft",
      engines: "2× Pratt & Whitney PW1700G",
      crew: "2",
      capacity: "80 passengers",
    },
    description:
      "The E175-E2 is the second-generation version of the E175, featuring new geared turbofan engines, redesigned wings, and an updated flight deck. However, US scope clause restrictions have severely limited its adoption by North American regional carriers.",
    funFact:
      "Despite being a significantly more efficient aircraft, the E175-E2 has struggled commercially in North America because its heavier weight puts it outside scope clause limits — a contractual quirk that keeps older, less efficient jets flying.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Underwing geared turbofan engines",
        "New winglet design",
        "Slightly longer wingspan than E175",
        "Sharper nose profile",
        "Low wing",
        "Conventional tail",
      ],
    },
    aliases: ["E175-E2", "E2 175"],
  },

  {
    id: "embraer-e190-e2",
    name: "Embraer E190-E2",
    manufacturer: "Embraer",
    type: "Narrow-body Regional Jet (2nd generation)",
    firstFlight: "2017",
    inService: "2018",
    role: "Regional / short-haul airliner",
    country: "Brazil",
    specs: {
      wingspan: "31.1 m (102 ft 0 in)",
      length: "36.2 m (118 ft 11 in)",
      maxSpeed: "Mach 0.82",
      range: "5,278 km (3,279 mi)",
      ceiling: "41,000 ft",
      engines: "2× Pratt & Whitney PW1900G",
      crew: "2",
      capacity: "96–106 passengers",
    },
    description:
      "The E190-E2 introduced Embraer's second-generation E-Jet platform with new GTF engines, a redesigned wing with sharktlet winglets, and fly-by-wire controls. It burns up to 17.3% less fuel per trip than the original E190 it replaces.",
    funFact:
      "The E190-E2 was dubbed the 'Profit Hunter' by Embraer — and the marketing stuck, with airlines using the nickname in their own promotional material.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Sharktlet winglets (distinctive curved tips)",
        "Underwing geared turbofan engines",
        "Low wing",
        "Conventional tail",
        "Longer nose than E1 family",
        "New engine nacelle shape",
      ],
    },
    aliases: ["E190-E2", "E2 190", "Profit Hunter"],
  },

  {
    id: "embraer-e195-e2",
    name: "Embraer E195-E2",
    manufacturer: "Embraer",
    type: "Narrow-body Regional Jet (2nd generation)",
    firstFlight: "2019",
    inService: "2019",
    role: "Regional / short-haul airliner",
    country: "Brazil",
    specs: {
      wingspan: "31.1 m (102 ft 0 in)",
      length: "41.5 m (136 ft 2 in)",
      maxSpeed: "Mach 0.82",
      range: "4,205 km (2,613 mi)",
      ceiling: "41,000 ft",
      engines: "2× Pratt & Whitney PW1900G",
      crew: "2",
      capacity: "120–146 passengers",
    },
    description:
      "The E195-E2 is the largest of the second-generation E-Jets and the most efficient single-aisle aircraft per seat in its class. With up to 146 seats, it competes head-to-head with the A220-300 and challenges the smallest 737/A320 variants.",
    funFact:
      "Azul Brazilian Airlines launched the E195-E2 into service and configured it in a 3-2 layout — making it one of the very few narrowbodies where the middle seat disappears entirely.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Sharktlet winglets",
        "Underwing geared turbofan engines",
        "Longest E-Jet fuselage",
        "Low wing",
        "Conventional tail",
        "Wide cabin for a regional jet",
      ],
    },
    aliases: ["E195-E2", "E2 195"],
  },

  {
    id: "embraer-erj145",
    name: "Embraer ERJ-145",
    manufacturer: "Embraer",
    type: "Regional Jet",
    firstFlight: "1995",
    inService: "1996",
    role: "Regional airliner",
    country: "Brazil",
    specs: {
      wingspan: "20.0 m (65 ft 9 in)",
      length: "29.9 m (98 ft 0 in)",
      maxSpeed: "Mach 0.78",
      range: "2,873 km (1,785 mi)",
      ceiling: "37,000 ft",
      engines: "2× Rolls-Royce AE 3007A",
      crew: "2",
      capacity: "50 passengers",
    },
    description:
      "The ERJ-145 emerged from a redesign of the turboprop EMB-120, ultimately becoming a fully new regional jet with rear-mounted engines and a narrow fuselage. It became a cornerstone of US regional aviation in the late 1990s and 2000s.",
    funFact:
      "The ERJ-145's fuselage is so narrow (1-2 seating) that tall passengers sometimes have to duck slightly when walking down the aisle — leading to its informal nickname 'the tube.'",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Rear fuselage mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "Rear-mounted engines",
        "Pointed nose",
        "Low wing",
        "Conventional tail",
        "Very narrow fuselage (1-2 seating)",
        "Small oval windows",
      ],
    },
    aliases: ["ERJ145", "ERJ 145", "EMB-145"],
  },

  {
    id: "embraer-erj135",
    name: "Embraer ERJ-135",
    manufacturer: "Embraer",
    type: "Regional Jet",
    firstFlight: "1998",
    inService: "1999",
    role: "Regional airliner",
    country: "Brazil",
    specs: {
      wingspan: "20.0 m (65 ft 9 in)",
      length: "26.3 m (86 ft 4 in)",
      maxSpeed: "Mach 0.78",
      range: "3,241 km (2,014 mi)",
      ceiling: "37,000 ft",
      engines: "2× Rolls-Royce AE 3007A",
      crew: "2",
      capacity: "37 passengers",
    },
    description:
      "The ERJ-135 is a shortened derivative of the ERJ-145 with a 37-seat capacity. Its compact size made it attractive for thin routes and as a business jet conversion (the Legacy 600). It shares the same type rating as the ERJ-145, simplifying airline operations.",
    funFact:
      "The ERJ-135 was converted into the Embraer Legacy 600 executive jet — essentially a 37-seat regional jet refitted with a VIP cabin and additional fuel tanks for transcontinental range.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Rear fuselage mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "Rear-mounted engines",
        "Shorter fuselage than ERJ-145",
        "Pointed nose",
        "Low wing",
        "Conventional tail",
        "Very narrow fuselage",
      ],
    },
    aliases: ["ERJ135", "ERJ 135", "EMB-135"],
  },

  // ─── BOMBARDIER CRJ FAMILY ────────────────────────────────────────────────

  {
    id: "bombardier-crj200",
    name: "Bombardier CRJ-200",
    manufacturer: "Bombardier Aerospace / Canadair",
    type: "Regional Jet",
    firstFlight: "1991",
    inService: "1992",
    role: "Regional airliner",
    country: "Canada",
    specs: {
      wingspan: "21.2 m (69 ft 7 in)",
      length: "26.8 m (87 ft 10 in)",
      maxSpeed: "Mach 0.81",
      range: "3,045 km (1,892 mi)",
      ceiling: "41,000 ft",
      engines: "2× GE CF34-3B1",
      crew: "2",
      capacity: "50 passengers",
    },
    description:
      "Derived from the Canadair Challenger 600 business jet, the CRJ-200 (originally CRJ-100) was one of the first successful regional jets. Its rear-mounted engines and T-tail give it a sleek profile, and it dominated North American regional flying through the 1990s and 2000s.",
    funFact:
      "The CRJ-200 is so closely related to the Challenger 600 business jet that pilots who fly one can relatively easily transition to the other — the fuselage cross-section is nearly identical.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Rear fuselage mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "Rear-mounted engines",
        "Distinctive T-tail",
        "Low wing",
        "Very narrow fuselage",
        "Business-jet heritage fuselage",
        "Tall vertical stabilizer",
      ],
    },
    aliases: ["CRJ200", "CRJ 200", "CRJ-100", "Canadair Regional Jet"],
  },

  {
    id: "bombardier-crj700",
    name: "Bombardier CRJ-700",
    manufacturer: "Bombardier Aerospace",
    type: "Regional Jet",
    firstFlight: "1999",
    inService: "2001",
    role: "Regional airliner",
    country: "Canada",
    specs: {
      wingspan: "23.2 m (76 ft 3 in)",
      length: "32.5 m (106 ft 8 in)",
      maxSpeed: "Mach 0.82",
      range: "3,004 km (1,867 mi)",
      ceiling: "41,000 ft",
      engines: "2× GE CF34-8C1",
      crew: "2",
      capacity: "70 passengers",
    },
    description:
      "The CRJ-700 is a substantially stretched and re-engined evolution of the CRJ-200, growing from 50 to 70 seats. It introduced a new wing, more powerful engines, and improved passenger comfort while retaining the familiar rear-engine T-tail configuration.",
    funFact:
      "Although it looks similar to the CRJ-200, the CRJ-700 shares almost no structural components — it was essentially designed from scratch around the same fuselage concept.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Rear fuselage mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "Rear-mounted engines",
        "T-tail",
        "Low wing",
        "Narrow fuselage",
        "Longer than CRJ-200",
        "Winglets",
      ],
    },
    aliases: ["CRJ700", "CRJ 700", "CL-600-2C10"],
  },

  {
    id: "bombardier-crj900",
    name: "Bombardier CRJ-900",
    manufacturer: "Bombardier Aerospace",
    type: "Regional Jet",
    firstFlight: "2001",
    inService: "2003",
    role: "Regional airliner",
    country: "Canada",
    specs: {
      wingspan: "24.9 m (81 ft 7 in)",
      length: "36.4 m (119 ft 5 in)",
      maxSpeed: "Mach 0.82",
      range: "2,876 km (1,787 mi)",
      ceiling: "41,000 ft",
      engines: "2× GE CF34-8C5",
      crew: "2",
      capacity: "86–90 passengers",
    },
    description:
      "The CRJ-900 stretches the CRJ-700 by 3.9 m to accommodate up to 90 passengers. It competes directly with the Embraer E175 and has been popular with US mainline carriers' regional subsidiaries. The extended fuselage makes it look notably elongated relative to its narrow width.",
    funFact:
      "The CRJ-900's fuselage is so long relative to its diameter that passengers boarding at the front can't see the rear of the cabin — it appears to disappear into a curve.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Rear fuselage mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Rear-mounted engines",
        "T-tail",
        "Low wing",
        "Elongated narrow fuselage",
        "Winglets",
        "Very long fuselage relative to width",
      ],
    },
    aliases: ["CRJ900", "CRJ 900", "CL-600-2D24"],
  },

  {
    id: "bombardier-crj1000",
    name: "Bombardier CRJ-1000",
    manufacturer: "Bombardier Aerospace",
    type: "Regional Jet",
    firstFlight: "2008",
    inService: "2010",
    role: "Regional airliner",
    country: "Canada",
    specs: {
      wingspan: "26.2 m (85 ft 11 in)",
      length: "39.1 m (128 ft 4 in)",
      maxSpeed: "Mach 0.82",
      range: "3,004 km (1,867 mi)",
      ceiling: "41,000 ft",
      engines: "2× GE CF34-8C5B1",
      crew: "2",
      capacity: "100 passengers",
    },
    description:
      "The CRJ-1000 is the ultimate stretch of the CRJ family, reaching 100 seats — the maximum for the regional jet category. Despite its impressive seat count, its narrow cabin and relatively modest range limited its commercial appeal compared to the Embraer E190.",
    funFact:
      "Air Nostrum of Spain was the launch customer for the CRJ-1000 and remains one of the few operators, using it on thin European routes where its small cabin width is less of a competitive disadvantage.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Rear fuselage mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Rear-mounted engines",
        "T-tail",
        "Low wing",
        "Longest CRJ fuselage",
        "Winglets",
        "Very slender fuselage for 100 seats",
      ],
    },
    aliases: ["CRJ1000", "CRJ 1000", "CRJ-1000 NextGen"],
  },

  // ─── ATR TURBOPROPS ───────────────────────────────────────────────────────

  {
    id: "atr-42-600",
    name: "ATR 42-600",
    manufacturer: "ATR (Aerei da Trasporto Regionale)",
    type: "Regional Turboprop",
    firstFlight: "2009",
    inService: "2013",
    role: "Regional airliner",
    country: "France / Italy",
    specs: {
      wingspan: "24.6 m (80 ft 7 in)",
      length: "22.7 m (74 ft 5 in)",
      maxSpeed: "556 km/h (346 mph)",
      range: "1,326 km (824 mi)",
      ceiling: "25,000 ft",
      engines: "2× Pratt & Whitney Canada PW127M",
      crew: "2",
      capacity: "48 passengers",
    },
    description:
      "The ATR 42-600 is the smaller of the two ATR regional turboprops, featuring an updated avionics suite (Thales AVTECH) over earlier -500 series variants. Its high wing and T-tail make it instantly recognizable, and its economics are hard to beat on short thin routes.",
    funFact:
      "ATR turboprops burn roughly 40% less fuel than equivalent regional jets, making them the preferred choice for island-hopping airlines across the Caribbean, Pacific, and Mediterranean.",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "Underwing, tractor propellers",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "High wing",
        "T-tail",
        "Turboprop engines with large propellers",
        "Circular fuselage cross-section",
        "Retractable undercarriage in fuselage fairings",
        "No winglets",
      ],
    },
    aliases: ["ATR 42", "ATR-42-600", "ATR42"],
  },

  {
    id: "atr-72-600",
    name: "ATR 72-600",
    manufacturer: "ATR (Aerei da Trasporto Regionale)",
    type: "Regional Turboprop",
    firstFlight: "2009",
    inService: "2009",
    role: "Regional airliner",
    country: "France / Italy",
    specs: {
      wingspan: "27.1 m (88 ft 9 in)",
      length: "27.2 m (89 ft 1 in)",
      maxSpeed: "556 km/h (346 mph)",
      range: "1,528 km (950 mi)",
      ceiling: "25,000 ft",
      engines: "2× Pratt & Whitney Canada PW127M",
      crew: "2",
      capacity: "70–78 passengers",
    },
    description:
      "The ATR 72-600 is the stretched, re-engined evolution of the ATR 72, the world's best-selling regional turboprop. The -600 series added a new cockpit, upgraded engines, and improved passenger comfort. It is the dominant turboprop for carriers across Asia, Europe, and the Pacific.",
    funFact:
      "IndiGo of India has operated one of the largest ATR 72 fleets in the world, using them to connect small Indian cities that lack the runway length or traffic for jet service.",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "Underwing, tractor propellers",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "High wing",
        "T-tail",
        "Turboprop engines with large 6-blade propellers",
        "Longer fuselage than ATR 42",
        "Fuselage-mounted main gear fairings",
        "Straight wing with slight anhedral",
      ],
    },
    aliases: ["ATR 72", "ATR-72-600", "ATR72"],
  },

  // ─── DE HAVILLAND CANADA DASH 8 ──────────────────────────────────────────

  {
    id: "dhc-dash8-q100",
    name: "De Havilland Canada Dash 8-100 / Q100",
    manufacturer: "De Havilland Canada / Bombardier",
    type: "Regional Turboprop",
    firstFlight: "1983",
    inService: "1984",
    role: "Regional airliner",
    country: "Canada",
    specs: {
      wingspan: "25.9 m (85 ft 0 in)",
      length: "22.3 m (73 ft 0 in)",
      maxSpeed: "500 km/h (311 mph)",
      range: "1,519 km (944 mi)",
      ceiling: "25,000 ft",
      engines: "2× Pratt & Whitney Canada PW120A",
      crew: "2",
      capacity: "37–39 passengers",
    },
    description:
      "The original Dash 8-100 introduced a high-wing twin-turboprop design that became the foundation for one of aviation's most successful regional aircraft families. The Q100 designation (Q for Quiet) was added after Bombardier's NVS noise-and-vibration suppression system was retrofitted.",
    funFact:
      "The 'Q' in Q100 stands for 'Quiet' — Bombardier's active noise-and-vibration suppression system dramatically reduced cabin noise, turning the notoriously loud Dash 8 into a much more palatable passenger experience.",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "Underwing, tractor propellers",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "High wing",
        "T-tail",
        "Turboprop engines",
        "Large rectangular fuselage cross-section",
        "Retractable tricycle gear",
        "Boxy fuselage shape",
      ],
    },
    aliases: ["Dash 8-100", "Q100", "DHC-8-100", "Dash 8 Series 100"],
  },

  {
    id: "dhc-dash8-q300",
    name: "De Havilland Canada Dash 8-300 / Q300",
    manufacturer: "De Havilland Canada / Bombardier",
    type: "Regional Turboprop",
    firstFlight: "1987",
    inService: "1989",
    role: "Regional airliner",
    country: "Canada",
    specs: {
      wingspan: "27.4 m (90 ft 0 in)",
      length: "25.7 m (84 ft 3 in)",
      maxSpeed: "530 km/h (329 mph)",
      range: "1,558 km (968 mi)",
      ceiling: "25,000 ft",
      engines: "2× Pratt & Whitney Canada PW123",
      crew: "2",
      capacity: "50–56 passengers",
    },
    description:
      "The Dash 8-300 is a stretched variant of the -100 with a longer fuselage and more powerful engines. It carries up to 56 passengers and offers improved range. Together with the Q100, it established the Dash 8 as a workhorse of Canadian and Australian regional aviation.",
    funFact:
      "Horizon Air (an Alaska Airlines subsidiary) was one of the largest Dash 8-300 operators and used them extensively across the Pacific Northwest, where short runways and mountain weather suited the turboprop's capabilities.",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "Underwing, tractor propellers",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "High wing",
        "T-tail",
        "Turboprop engines",
        "Stretched fuselage vs -100",
        "Larger windows than Q400",
        "Boxy rectangular fuselage",
      ],
    },
    aliases: ["Dash 8-300", "Q300", "DHC-8-300", "Dash 8 Series 300"],
  },

  {
    id: "dhc-dash8-q400",
    name: "Bombardier Dash 8-400 / Q400",
    manufacturer: "Bombardier Aerospace / De Havilland Canada",
    type: "Regional Turboprop",
    firstFlight: "1998",
    inService: "2000",
    role: "Regional airliner",
    country: "Canada",
    specs: {
      wingspan: "28.4 m (93 ft 3 in)",
      length: "32.8 m (107 ft 9 in)",
      maxSpeed: "667 km/h (414 mph)",
      range: "2,040 km (1,268 mi)",
      ceiling: "25,000 ft",
      engines: "2× Pratt & Whitney Canada PW150A",
      crew: "2",
      capacity: "70–90 passengers",
    },
    description:
      "The Q400 is a dramatically enlarged evolution of the original Dash 8, stretching the fuselage to carry up to 90 passengers while cruising at jet-like speeds. Its high speed for a turboprop made it capable of competing with regional jets on time while burning significantly less fuel.",
    funFact:
      "The Q400 is fast enough that Scandinavian Airlines briefly marketed it as a 'jet' to passengers — its 667 km/h cruise speed overlaps with the slowest regional jets, and the cabin is quieter than earlier Dash 8 variants.",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "Underwing, tractor propellers",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "High wing",
        "T-tail",
        "Large 6-blade propellers",
        "Long fuselage for a turboprop",
        "Distinctively large ventral fin below tail",
        "Boxy but elongated fuselage",
      ],
    },
    aliases: ["Q400", "Dash 8-400", "DHC-8-400", "Q Series 400", "Dash 8 Q400"],
  },

  // ─── SAAB ─────────────────────────────────────────────────────────────────

  {
    id: "saab-340",
    name: "Saab 340",
    manufacturer: "Saab Aircraft",
    type: "Regional Turboprop",
    firstFlight: "1983",
    inService: "1984",
    role: "Regional airliner",
    country: "Sweden",
    specs: {
      wingspan: "21.4 m (70 ft 4 in)",
      length: "19.7 m (64 ft 8 in)",
      maxSpeed: "529 km/h (329 mph)",
      range: "1,732 km (1,076 mi)",
      ceiling: "25,000 ft",
      engines: "2× GE CT7-9B",
      crew: "2",
      capacity: "33–37 passengers",
    },
    description:
      "The Saab 340 was originally developed jointly with Fairchild Aircraft before Saab took sole ownership of the program. Its low-wing, conventional-tail design was unusual among turboprops of its era and gave it a more airliner-like appearance than competitors.",
    funFact:
      "The Saab 340 is one of the few turboprops with a low wing — most turboprops use a high wing to keep the propellers away from the ground, but Saab's design prioritized cabin headroom and a conventional airliner appearance.",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "Underwing, tractor propellers",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "Low wing — unusual for a turboprop",
        "Conventional tail",
        "Turboprop engines",
        "Round fuselage",
        "Three-blade propellers",
        "No winglets",
      ],
    },
    aliases: ["Saab 340A", "Saab 340B", "SF340"],
  },

  {
    id: "saab-2000",
    name: "Saab 2000",
    manufacturer: "Saab Aircraft",
    type: "Regional Turboprop",
    firstFlight: "1992",
    inService: "1994",
    role: "Regional airliner",
    country: "Sweden",
    specs: {
      wingspan: "24.8 m (81 ft 3 in)",
      length: "27.3 m (89 ft 7 in)",
      maxSpeed: "682 km/h (424 mph)",
      range: "2,868 km (1,782 mi)",
      ceiling: "31,000 ft",
      engines: "2× Allison AE 2100A",
      crew: "2",
      capacity: "50–58 passengers",
    },
    description:
      "The Saab 2000 was designed to compete with regional jets by matching their speed using extremely powerful turboprop engines and advanced 6-blade propellers. It cruises at up to 682 km/h — faster than some regional jets — while burning less fuel. Despite its technical excellence, limited sales led to production ending in 1999.",
    funFact:
      "The Saab 2000 holds the distinction of being the fastest turboprop airliner ever to enter commercial service, capable of cruising at speeds that blurred the line between turboprop and jet travel.",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "Underwing, tractor propellers",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "Low wing turboprop",
        "6-blade Dowty propellers",
        "Longer fuselage than Saab 340",
        "Conventional tail",
        "Very large engine nacelles for turboprop",
        "High cruise speed",
      ],
    },
    aliases: ["Saab 2000", "SF2000"],
  },

  // ─── DORNIER 328 ──────────────────────────────────────────────────────────

  {
    id: "dornier-328",
    name: "Dornier 328",
    manufacturer: "Dornier Luftfahrt / AvCraft / RUAG",
    type: "Regional Turboprop",
    firstFlight: "1991",
    inService: "1993",
    role: "Regional airliner",
    country: "Germany",
    specs: {
      wingspan: "20.9 m (68 ft 7 in)",
      length: "21.3 m (69 ft 10 in)",
      maxSpeed: "620 km/h (385 mph)",
      range: "1,611 km (1,001 mi)",
      ceiling: "31,000 ft",
      engines: "2× Pratt & Whitney Canada PW119B",
      crew: "2",
      capacity: "30–33 passengers",
    },
    description:
      "The Dornier 328 is a high-wing pressurized turboprop notable for its wide cabin — wider per seat than some mainline jets. Derived from the earlier Dornier 228, it added pressurization and a T-tail. A jet variant, the 328JET, later appeared with Pratt & Whitney Canada PW306 engines.",
    funFact:
      "The Dornier 328's cabin is so wide relative to its passenger count that passengers in the front rows have nearly first-class shoulder room — the fuselage is unusually broad for a 30-seat aircraft.",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "Underwing, tractor propellers",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "High wing",
        "T-tail",
        "Notably wide fuselage for its size",
        "Turboprop engines",
        "Oval fuselage cross-section",
        "Small but wide regional design",
      ],
    },
    aliases: ["Do 328", "Do-328", "328 Turboprop"],
  },

  // ─── BAe JETSTREAM 41 ─────────────────────────────────────────────────────

  {
    id: "bae-jetstream41",
    name: "BAe Jetstream 41",
    manufacturer: "British Aerospace (BAe)",
    type: "Regional Turboprop",
    firstFlight: "1991",
    inService: "1992",
    role: "Regional airliner / commuter",
    country: "United Kingdom",
    specs: {
      wingspan: "18.3 m (60 ft 0 in)",
      length: "19.3 m (63 ft 2 in)",
      maxSpeed: "547 km/h (340 mph)",
      range: "1,433 km (891 mi)",
      ceiling: "26,000 ft",
      engines: "2× Garrett TPE331-14GR/HR",
      crew: "2",
      capacity: "29 passengers",
    },
    description:
      "The Jetstream 41 is an enlarged development of the earlier Jetstream 31, featuring a stretched fuselage, T-tail, and more powerful engines. It served commuter routes across the UK and US, known for its small but pressurized cabin that offered a step up from 19-seat turboprops.",
    funFact:
      "The Jetstream 41 has a stand-up cabin height that is technically sufficient for passengers under 5'7\" — making it one of the smallest pressurized airliners where you won't bang your head on the ceiling.",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "Underwing, tractor propellers",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "Low wing turboprop",
        "T-tail",
        "Very narrow fuselage",
        "Small circular windows",
        "Pointed nose",
        "Commuter-class size",
      ],
    },
    aliases: ["Jetstream 41", "J41", "BAe J41"],
  },

  // ─── SHORTS 360 ───────────────────────────────────────────────────────────

  {
    id: "shorts-360",
    name: "Shorts 360",
    manufacturer: "Short Brothers (Shorts)",
    type: "Regional Turboprop",
    firstFlight: "1981",
    inService: "1982",
    role: "Regional / commuter airliner",
    country: "United Kingdom",
    specs: {
      wingspan: "22.8 m (74 ft 10 in)",
      length: "21.6 m (70 ft 10 in)",
      maxSpeed: "393 km/h (244 mph)",
      range: "1,178 km (732 mi)",
      ceiling: "20,000 ft",
      engines: "2× Pratt & Whitney Canada PT6A-65R",
      crew: "2",
      capacity: "36 passengers",
    },
    description:
      "The Shorts 360 is a boxy, unpressurized twin-turboprop designed for rugged simplicity. Its slab-sided fuselage and fixed undercarriage made it instantly recognizable and maintenance-friendly. Affectionately called the 'Shed' by crews, it served commuter routes where economics trumped comfort.",
    funFact:
      "The Shorts 360 is one of the few commercial airliners with a completely unpressurized cabin — passengers are limited to low-altitude flights, which actually suited its intended short-hop routes perfectly.",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "Underwing, tractor propellers",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "twin-boom",
      landingGear: "fixed",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "High wing",
        "Extremely boxy rectangular fuselage",
        "Fixed undercarriage",
        "Twin tail fins",
        "Unpressurized cabin",
        "Slab-sided fuselage nicknamed the Shed",
      ],
    },
    aliases: ["Shorts 360", "SD3-60", "Short 360"],
  },

  // ─── LET L-410 ────────────────────────────────────────────────────────────

  {
    id: "let-l410",
    name: "Let L-410 Turbolet",
    manufacturer: "Let Kunovice (LET)",
    type: "Regional Turboprop",
    firstFlight: "1969",
    inService: "1971",
    role: "Regional / commuter airliner",
    country: "Czechoslovakia / Czech Republic",
    specs: {
      wingspan: "19.5 m (63 ft 10 in)",
      length: "14.4 m (47 ft 4 in)",
      maxSpeed: "390 km/h (242 mph)",
      range: "1,355 km (842 mi)",
      ceiling: "19,685 ft",
      engines: "2× GE H80-200",
      crew: "2",
      capacity: "19 passengers",
    },
    description:
      "The Let L-410 is a rugged short-takeoff-and-landing twin-turboprop developed for Soviet-bloc regional aviation. Designed for unprepared strips and harsh conditions, it became the workhorse of Soviet regional aviation and remains in production today for bush operators worldwide.",
    funFact:
      "The L-410 can operate from grass, gravel, and snow strips as short as 520 m — making it one of the most versatile commercial aircraft ever built and a staple of bush flying in Africa, South America, and Russia.",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "Underwing, tractor propellers",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "High wing",
        "Conventional tail",
        "Short stubby fuselage",
        "Large propellers relative to fuselage",
        "STOL-capable design",
        "Robust fixed or retractable gear",
      ],
    },
    aliases: ["L-410", "L-410UVP", "Turbolet"],
  },

  // ─── FOKKER 50 ────────────────────────────────────────────────────────────

  {
    id: "fokker-50",
    name: "Fokker 50",
    manufacturer: "Fokker",
    type: "Regional Turboprop",
    firstFlight: "1985",
    inService: "1987",
    role: "Regional airliner",
    country: "Netherlands",
    specs: {
      wingspan: "29.0 m (95 ft 1 in)",
      length: "25.2 m (82 ft 8 in)",
      maxSpeed: "522 km/h (324 mph)",
      range: "2,054 km (1,277 mi)",
      ceiling: "25,000 ft",
      engines: "2× Pratt & Whitney Canada PW125B",
      crew: "2",
      capacity: "46–58 passengers",
    },
    description:
      "The Fokker 50 is a thoroughly modernized redesign of the venerable Fokker F27 Friendship, featuring new Pratt & Whitney Canada turboprops, a glass cockpit, and a quieter cabin. It was the last turboprop developed by Fokker before the company's bankruptcy in 1996.",
    funFact:
      "Despite being introduced in 1987, the Fokker 50 shares the same basic fuselage shape as the F27 from the late 1950s — Fokker refined and updated the design so effectively that a revolutionary new aircraft wasn't needed.",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "Underwing, tractor propellers",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "High wing",
        "Conventional tail",
        "Circular fuselage",
        "6-blade propellers",
        "Oval passenger windows",
        "F27 heritage fuselage shape",
      ],
    },
    aliases: ["F50", "Fokker F50"],
  },

  // ─── BAe 146 / AVRO RJ ────────────────────────────────────────────────────

  {
    id: "bae-146",
    name: "BAe 146 / Avro RJ",
    manufacturer: "British Aerospace / Avro International Aerospace",
    type: "Regional Jet",
    firstFlight: "1981",
    inService: "1983",
    role: "Regional / short-haul airliner",
    country: "United Kingdom",
    specs: {
      wingspan: "26.3 m (86 ft 5 in)",
      length: "28.6 m (93 ft 10 in)",
      maxSpeed: "Mach 0.73",
      range: "2,965 km (1,842 mi)",
      ceiling: "35,000 ft",
      engines: "4× Honeywell ALF502 / LF507",
      crew: "2",
      capacity: "70–128 passengers",
    },
    description:
      "The BAe 146 is unique among regional jets for its four-engine configuration and high-wing layout. Designed for steep approach capability and short-field performance, it was the first airliner certified for London City Airport's steep 5.5° glideslope. The Avro RJ designation covers later variants with upgraded Honeywell LF507 engines.",
    funFact:
      "The BAe 146 was specifically designed for London City Airport's near-impossibly steep 5.5° glideslope — more than twice the standard 3° used at most airports. It remains one of very few airliners certified for this approach.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Underwing, four podded engines",
      wingPosition: "high",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "Four underwing engines — unique for a regional jet",
        "High wing",
        "T-tail",
        "Short stubby fuselage",
        "Steep approach certification",
        "Very low noise (quiet city operation)",
      ],
    },
    aliases: [
      "BAe 146-100",
      "BAe 146-200",
      "BAe 146-300",
      "Avro RJ70",
      "Avro RJ85",
      "Avro RJ100",
      "Whisperjet",
    ],
  },

  // ─── FOKKER 70 ────────────────────────────────────────────────────────────

  {
    id: "fokker-70",
    name: "Fokker 70",
    manufacturer: "Fokker",
    type: "Regional Jet",
    firstFlight: "1993",
    inService: "1994",
    role: "Regional airliner",
    country: "Netherlands",
    specs: {
      wingspan: "28.1 m (92 ft 1 in)",
      length: "30.9 m (101 ft 5 in)",
      maxSpeed: "Mach 0.77",
      range: "2,010 km (1,249 mi)",
      ceiling: "35,000 ft",
      engines: "2× Rolls-Royce Tay 620",
      crew: "2",
      capacity: "70–79 passengers",
    },
    description:
      "The Fokker 70 is a shortened variant of the Fokker 100, produced as a direct competitor to the BAe 146 and early CRJ. Powered by Rolls-Royce Tay engines mounted at the rear, it shares the Fokker 100's T-tail and low-wing configuration.",
    funFact:
      "The Fokker 70 was developed concurrently with the Fokker 100 on an accelerated timeline — the company needed a smaller companion model quickly and achieved certification within two years of program launch.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Rear fuselage mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "Rear-mounted engines",
        "T-tail",
        "Low wing",
        "Shorter than Fokker 100",
        "Circular fuselage",
        "Rolls-Royce Tay engine nacelles",
      ],
    },
    aliases: ["F70", "Fokker F70"],
  },

  // ─── FOKKER 100 ───────────────────────────────────────────────────────────

  {
    id: "fokker-100",
    name: "Fokker 100",
    manufacturer: "Fokker",
    type: "Short-haul Jet",
    firstFlight: "1986",
    inService: "1988",
    role: "Short-haul airliner",
    country: "Netherlands",
    specs: {
      wingspan: "28.1 m (92 ft 1 in)",
      length: "35.5 m (116 ft 5 in)",
      maxSpeed: "Mach 0.77",
      range: "3,170 km (1,970 mi)",
      ceiling: "35,000 ft",
      engines: "2× Rolls-Royce Tay 650",
      crew: "2",
      capacity: "107 passengers",
    },
    description:
      "The Fokker 100 was Fokker's most modern and successful jet, combining the proven Fokker F28 fuselage with new supercritical wings, Rolls-Royce Tay turbofans, and a glass cockpit. Its rear-mounted engines and T-tail were hallmarks of the Fokker jet line.",
    funFact:
      "The Fokker 100 achieved its 100-passenger capacity with one of the lowest seat-mile costs of any aircraft in its class during the 1990s — yet Fokker's financial troubles led to bankruptcy in 1996, ending production.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Rear fuselage mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "Rear-mounted engines",
        "T-tail",
        "Low wing",
        "Supercritical swept wing",
        "Circular fuselage",
        "Larger than Fokker 70",
      ],
    },
    aliases: ["F100", "Fokker F100"],
  },

  // ─── FOKKER F27 / F28 ─────────────────────────────────────────────────────

  {
    id: "fokker-f27",
    name: "Fokker F27 Friendship",
    manufacturer: "Fokker",
    type: "Regional Turboprop",
    firstFlight: "1955",
    inService: "1958",
    role: "Regional / short-haul airliner",
    country: "Netherlands",
    specs: {
      wingspan: "29.0 m (95 ft 2 in)",
      length: "23.6 m (77 ft 3 in)",
      maxSpeed: "480 km/h (298 mph)",
      range: "1,926 km (1,197 mi)",
      ceiling: "29,500 ft",
      engines: "2× Rolls-Royce Dart",
      crew: "2",
      capacity: "28–52 passengers",
    },
    description:
      "The F27 Friendship is one of the most successful turboprop airliners ever built, with over 786 produced. Its high wing and circular pressurized fuselage set the template for the regional turboprop category. It replaced piston airliners worldwide and remained in production until 1987.",
    funFact:
      "The Fokker F27 outsold its American competitor, the Fairchild FH-227, so decisively that Fairchild eventually licensed the design — making the F27 one of the most widely produced airliners in the non-jet category.",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "Underwing, tractor propellers",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "High wing",
        "Conventional tail",
        "Circular pressurized fuselage",
        "Rolls-Royce Dart engines",
        "Classic turboprop appearance",
        "Oval windows",
      ],
    },
    aliases: ["F27", "Fokker Friendship", "F27 Mk 500"],
  },

  {
    id: "fokker-f28",
    name: "Fokker F28 Fellowship",
    manufacturer: "Fokker",
    type: "Regional Jet",
    firstFlight: "1967",
    inService: "1969",
    role: "Short-haul airliner",
    country: "Netherlands",
    specs: {
      wingspan: "25.1 m (82 ft 3 in)",
      length: "29.6 m (97 ft 2 in)",
      maxSpeed: "Mach 0.75",
      range: "2,085 km (1,296 mi)",
      ceiling: "35,000 ft",
      engines: "2× Rolls-Royce Spey 555-15H",
      crew: "2",
      capacity: "65–85 passengers",
    },
    description:
      "The F28 Fellowship was Fokker's entry into the jet age, designed to complement the turboprop F27. Its rear-mounted Rolls-Royce Spey engines and T-tail gave it a clean, modern appearance and set the layout for future Fokker jets. It entered service with LTU in 1969.",
    funFact:
      "The F28 was the first jet aircraft to receive full Dutch certification, and its Rolls-Royce Spey engines were shared with the BAC One-Eleven — a rival aircraft that it would often compete with on the same routes.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Rear fuselage mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "early-jet",
      distinguishingFeatures: [
        "Rear-mounted Spey engines",
        "T-tail",
        "Low wing",
        "Short fuselage",
        "Pointed nose",
        "Classic 1960s regional jet profile",
      ],
    },
    aliases: ["F28", "Fokker Fellowship", "F28 Mk 1000", "F28 Mk 4000"],
  },

  // ─── SUKHOI SUPERJET 100 ──────────────────────────────────────────────────

  {
    id: "sukhoi-superjet100",
    name: "Sukhoi Superjet 100",
    manufacturer: "Sukhoi Civil Aircraft (SCAC) / United Aircraft Corporation",
    type: "Regional Jet",
    firstFlight: "2008",
    inService: "2011",
    role: "Regional airliner",
    country: "Russia",
    specs: {
      wingspan: "27.8 m (91 ft 2 in)",
      length: "29.9 m (98 ft 1 in)",
      maxSpeed: "Mach 0.81",
      range: "4,578 km (2,844 mi)",
      ceiling: "40,000 ft",
      engines: "2× PowerJet SaM146",
      crew: "2",
      capacity: "87–108 passengers",
    },
    description:
      "The Sukhoi Superjet 100 was Russia's first all-new commercial airliner since the Soviet era, developed with extensive Western involvement including Boeing as a consultant and Safran for the SaM146 engines. Despite technical merit, it suffered from poor support infrastructure and was largely grounded following sanctions after 2022.",
    funFact:
      "The SSJ-100 uses French-Russian SaM146 engines jointly developed by Snecma and NPO Saturn — one of the most successful East-West aviation partnerships ever completed, though sanctions have since severed that relationship.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Underwing engines",
        "Low wing",
        "Conventional tail",
        "Swept wings with winglets",
        "Wide oval windows",
        "Modern regional jet profile",
      ],
    },
    aliases: ["SSJ-100", "Superjet 100", "RRJ-95", "SSJ100"],
  },

  // ─── COMAC C919 ───────────────────────────────────────────────────────────

  {
    id: "comac-c919",
    name: "COMAC C919",
    manufacturer: "Commercial Aircraft Corporation of China (COMAC)",
    type: "Narrow-body Jet",
    firstFlight: "2017",
    inService: "2023",
    role: "Short / medium-haul airliner",
    country: "China",
    specs: {
      wingspan: "35.8 m (117 ft 5 in)",
      length: "38.9 m (127 ft 7 in)",
      maxSpeed: "Mach 0.82",
      range: "4,075 km (2,531 mi)",
      ceiling: "39,800 ft",
      engines: "2× CFM LEAP-1C",
      crew: "2",
      capacity: "158–168 passengers",
    },
    description:
      "The COMAC C919 is China's first domestically developed narrow-body airliner, designed to compete with the Boeing 737 MAX and Airbus A320neo. It entered commercial service with China Eastern in 2023, though it currently relies heavily on Western components including CFM engines and avionics from Honeywell and GE.",
    funFact:
      "Despite being positioned as China's 'homegrown' airliner, the C919 uses CFM LEAP engines from a Franco-American joint venture, Honeywell avionics, and numerous Western suppliers — making it a deeply international project marketed as Chinese.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Underwing CFM LEAP engines",
        "Low wing",
        "Conventional tail",
        "Winglets similar to A320neo style",
        "737-sized narrow-body profile",
        "Modern blended winglets",
      ],
    },
    aliases: ["C919", "COMAC C919"],
  },

  // ─── COMAC ARJ21 ──────────────────────────────────────────────────────────

  {
    id: "comac-arj21",
    name: "COMAC ARJ21",
    manufacturer: "Commercial Aircraft Corporation of China (COMAC)",
    type: "Regional Jet",
    firstFlight: "2008",
    inService: "2016",
    role: "Regional airliner",
    country: "China",
    specs: {
      wingspan: "27.3 m (89 ft 7 in)",
      length: "33.5 m (109 ft 11 in)",
      maxSpeed: "Mach 0.82",
      range: "3,700 km (2,299 mi)",
      ceiling: "39,800 ft",
      engines: "2× GE CF34-10A",
      crew: "2",
      capacity: "78–95 passengers",
    },
    description:
      "The ARJ21 (Advanced Regional Jet for the 21st Century) is China's first home-developed regional jet, powered by GE CF34 engines also used by the CRJ-700/900. Its design borrows heavily from the McDonnell Douglas MD-90 program that was produced in China, using a similar rear-engine T-tail configuration.",
    funFact:
      "The ARJ21 took 8 years from first flight to commercial certification — an unusually long development period that highlighted the difficulty of developing modern commercial aviation standards from scratch.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Rear fuselage mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Rear-mounted engines",
        "T-tail",
        "Low wing",
        "MD-90 heritage configuration",
        "Large oval windows",
        "Swept wing with winglets",
      ],
    },
    aliases: ["ARJ21", "ARJ21-700", "Xiangfeng"],
  },

  // ─── MITSUBISHI SPACEJET (MRJ) ────────────────────────────────────────────

  {
    id: "mitsubishi-spacejet",
    name: "Mitsubishi SpaceJet (MRJ)",
    manufacturer: "Mitsubishi Aircraft Corporation",
    type: "Regional Jet",
    firstFlight: "2015",
    inService: "Never entered service",
    role: "Regional airliner (cancelled)",
    country: "Japan",
    specs: {
      wingspan: "29.0 m (95 ft 2 in)",
      length: "35.8 m (117 ft 5 in)",
      maxSpeed: "Mach 0.82",
      range: "3,770 km (2,343 mi)",
      ceiling: "39,000 ft",
      engines: "2× Pratt & Whitney PW1200G",
      crew: "2",
      capacity: "88 passengers",
    },
    description:
      "The Mitsubishi SpaceJet (originally MRJ — Mitsubishi Regional Jet) was Japan's first attempt at a domestically developed commercial airliner in over 50 years. Featuring Pratt & Whitney geared turbofan engines and an advanced composite structure, it promised best-in-class efficiency. After six delays and enormous cost overruns, Mitsubishi formally suspended the program in 2023.",
    funFact:
      "The MRJ/SpaceJet program suffered six major certification delays totaling nearly a decade of postponement, largely due to Japan's lack of FAA certification expertise — a problem that ultimately proved insurmountable without a complete program restart.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Underwing geared turbofan engines",
        "Low wing",
        "Conventional tail",
        "Clean modern lines",
        "Large passenger windows",
        "Swept wing with winglets",
      ],
    },
    aliases: ["MRJ", "MRJ90", "SpaceJet M90", "Mitsubishi MRJ"],
  },

  // ─── HISTORIC JETS ────────────────────────────────────────────────────────

  {
    id: "douglas-dc8",
    name: "Douglas DC-8",
    manufacturer: "Douglas Aircraft Company",
    type: "Long-haul Jet",
    firstFlight: "1958",
    inService: "1959",
    role: "Long-haul airliner / freighter",
    country: "United States",
    specs: {
      wingspan: "43.4 m (142 ft 5 in)",
      length: "57.1 m (187 ft 4 in)",
      maxSpeed: "Mach 0.88",
      range: "9,985 km (6,205 mi)",
      ceiling: "43,000 ft",
      engines: "4× CFM56 (re-engined Super 70 series) or original JT3D",
      crew: "3",
      capacity: "189–259 passengers",
    },
    description:
      "The DC-8 was Douglas's answer to the Boeing 707 and a genuine competitor in the early jet age. Initially outsold by the 707, it earned a second life with the Super 60 stretched series and later Super 70 re-engining program, which fitted CFM56 turbofans and kept many aircraft flying as freighters into the 21st century.",
    funFact:
      "A DC-8 test aircraft broke the sound barrier in 1961 during a dive — reaching Mach 1.012 at 40,000 ft in a controlled test, making it the only subsonic commercial airliner to have exceeded the speed of sound (unofficially).",
    visual: {
      engineCount: 4,
      engineType: "turbojet",
      enginePlacement: "Underwing, podded on pylons",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "early-jet",
      distinguishingFeatures: [
        "Four underwing podded engines",
        "Low swept wing",
        "Conventional tail",
        "Long narrow fuselage",
        "Early jet airliner profile",
        "No winglets on original variants",
      ],
    },
    aliases: ["DC8", "Douglas DC-8", "DC-8-61", "DC-8-71", "Super DC-8"],
  },

  {
    id: "douglas-dc9",
    name: "Douglas DC-9",
    manufacturer: "Douglas Aircraft Company",
    type: "Short-haul Jet",
    firstFlight: "1965",
    inService: "1965",
    role: "Short / medium-haul airliner",
    country: "United States",
    specs: {
      wingspan: "28.5 m (93 ft 5 in)",
      length: "36.4 m (119 ft 4 in)",
      maxSpeed: "Mach 0.84",
      range: "2,780 km (1,727 mi)",
      ceiling: "35,000 ft",
      engines: "2× Pratt & Whitney JT8D-9A",
      crew: "2",
      capacity: "90–115 passengers",
    },
    description:
      "The DC-9 pioneered the rear-engine, T-tail configuration for short-haul jets, allowing a clean wing design and efficient operations from smaller airports. It was a massive commercial success and the direct ancestor of the MD-80 series, which itself evolved into the Boeing 717.",
    funFact:
      "The DC-9 family has had the longest production run of any commercial airliner design — with the Boeing 717 (MD-95) entering service in 1999, the basic design was in production for 35 years under three company names.",
    visual: {
      engineCount: 2,
      engineType: "turbojet",
      enginePlacement: "Rear fuselage mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "early-jet",
      distinguishingFeatures: [
        "Rear-mounted JT8D engines",
        "T-tail",
        "Low swept wing",
        "Clean wing (no underwing engines)",
        "Pointed nose",
        "Classic 1960s short-haul profile",
      ],
    },
    aliases: ["DC9", "DC-9-10", "DC-9-30", "DC-9-50"],
  },

  {
    id: "douglas-dc10",
    name: "Douglas DC-10",
    manufacturer: "McDonnell Douglas",
    type: "Wide-body Long-haul Jet",
    firstFlight: "1970",
    inService: "1971",
    role: "Long-haul wide-body airliner",
    country: "United States",
    specs: {
      wingspan: "50.4 m (165 ft 5 in)",
      length: "55.5 m (182 ft 1 in)",
      maxSpeed: "Mach 0.88",
      range: "9,600 km (5,965 mi)",
      ceiling: "42,000 ft",
      engines: "3× GE CF6-6D or P&W JT9D",
      crew: "3",
      capacity: "250–380 passengers",
    },
    description:
      "The DC-10 entered service as America's wide-body workhorse alongside the 747 and L-1011. Its distinctive three-engine layout — two under the wings and one mounted at the base of the vertical stabilizer with an S-duct intake — gave it both flexibility and a unique silhouette.",
    funFact:
      "The DC-10 suffered a turbulent early career including several high-profile crashes linked to a cargo door design flaw, but after fixes it compiled an excellent safety record and remains in service as the KC-10 military tanker decades later.",
    visual: {
      engineCount: 3,
      engineType: "turbofan",
      enginePlacement: "Two underwing + one at tail base with S-duct intake",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "modern",
      distinguishingFeatures: [
        "Three-engine configuration",
        "Center engine at base of vertical tail (not above fuselage)",
        "S-duct intake for center engine",
        "Two large underwing engines",
        "Wide-body fuselage",
        "Low swept wing",
      ],
    },
    aliases: ["DC10", "McDonnell Douglas DC-10", "KC-10 Extender"],
  },

  {
    id: "mcdonnell-douglas-md80",
    name: "McDonnell Douglas MD-80 Series",
    manufacturer: "McDonnell Douglas",
    type: "Short / Medium-haul Jet",
    variant: "MD-81 / MD-82 / MD-83 / MD-88",
    firstFlight: "1979",
    inService: "1980",
    role: "Short / medium-haul airliner",
    country: "United States",
    specs: {
      wingspan: "32.9 m (107 ft 10 in)",
      length: "45.1 m (147 ft 10 in)",
      maxSpeed: "Mach 0.76",
      range: "4,635 km (2,880 mi)",
      ceiling: "37,000 ft",
      engines: "2× Pratt & Whitney JT8D-217C",
      crew: "2",
      capacity: "130–172 passengers",
    },
    description:
      "The MD-80 family is a stretched, re-engined development of the DC-9, featuring more powerful and fuel-efficient JT8D-200 series engines and a lengthened fuselage. The various MD-8x sub-variants differed primarily in engine thrust and fuel capacity. It was the backbone of American, Delta, and Alitalia fleets for decades.",
    funFact:
      "American Airlines once operated over 350 MD-80s — the largest single-type fleet of any airline in history at the time — and relied on them so heavily they were nicknamed 'Mad Dogs' by crews who flew them daily.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Rear fuselage mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "Rear-mounted JT8D-200 engines",
        "T-tail",
        "Low swept wing",
        "Very long narrow fuselage",
        "Pointed nose",
        "Clean wing without underwing pods",
      ],
    },
    aliases: ["MD-81", "MD-82", "MD-83", "MD-88", "Mad Dog", "Super 80"],
  },

  {
    id: "mcdonnell-douglas-md90",
    name: "McDonnell Douglas MD-90",
    manufacturer: "McDonnell Douglas",
    type: "Short / Medium-haul Jet",
    firstFlight: "1993",
    inService: "1995",
    role: "Short / medium-haul airliner",
    country: "United States",
    specs: {
      wingspan: "32.9 m (107 ft 10 in)",
      length: "46.5 m (152 ft 6 in)",
      maxSpeed: "Mach 0.76",
      range: "3,861 km (2,399 mi)",
      ceiling: "37,000 ft",
      engines: "2× IAE V2525-D5",
      crew: "2",
      capacity: "153–172 passengers",
    },
    description:
      "The MD-90 updated the MD-80 with quieter, more fuel-efficient IAE V2500 turbofan engines, replacing the older JT8D series. The result was a significantly quieter aircraft that met Stage 4 noise regulations and offered improved operating economics. Boeing inherited the program after its McDonnell Douglas merger.",
    funFact:
      "The MD-90 was assembled in China by a joint venture — the Trunkliner program — representing one of the earliest major Chinese commercial aircraft manufacturing partnerships with a Western company.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Rear fuselage mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "Rear-mounted V2500 engines (larger nacelles than MD-80)",
        "T-tail",
        "Low swept wing",
        "Long narrow fuselage",
        "Pointed nose",
        "Slightly different nacelle shape than MD-80",
      ],
    },
    aliases: ["MD90", "MD-90-30"],
  },

  {
    id: "mcdonnell-douglas-md11",
    name: "McDonnell Douglas MD-11",
    manufacturer: "McDonnell Douglas",
    type: "Wide-body Long-haul Jet",
    firstFlight: "1990",
    inService: "1990",
    role: "Long-haul wide-body airliner / freighter",
    country: "United States",
    specs: {
      wingspan: "51.7 m (169 ft 8 in)",
      length: "61.2 m (200 ft 10 in)",
      maxSpeed: "Mach 0.87",
      range: "12,455 km (7,740 mi)",
      ceiling: "43,000 ft",
      engines: "3× GE CF6-80C2D1F or P&W PW4460",
      crew: "2",
      capacity: "285–410 passengers",
    },
    description:
      "The MD-11 is a modernized, stretched, and re-engined development of the DC-10, featuring winglets, an advanced two-crew glass cockpit, and improved aerodynamics. It fell short of its advertised range, and airlines quickly shifted to twin-engine widebodies, but it found a long second career as a cargo aircraft.",
    funFact:
      "The MD-11 was so popular as a freighter that FedEx, UPS, and Lufthansa Cargo still operate large fleets decades after passenger airlines retired theirs — its three-engine layout and large cargo door make it ideal for dense, heavy freight.",
    visual: {
      engineCount: 3,
      engineType: "turbofan",
      enginePlacement: "Two underwing + one at tail base with S-duct intake",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "modern",
      distinguishingFeatures: [
        "Three-engine configuration like DC-10",
        "Center engine at tail base with S-duct",
        "Winglets — key visual difference from DC-10",
        "Shorter upper fuselage length near tail",
        "Wide-body fuselage",
        "Longer than DC-10",
      ],
    },
    aliases: ["MD11", "MD-11F", "MD-11CF"],
  },

  {
    id: "lockheed-l1011",
    name: "Lockheed L-1011 TriStar",
    manufacturer: "Lockheed Corporation",
    type: "Wide-body Long-haul Jet",
    firstFlight: "1970",
    inService: "1972",
    role: "Long-haul wide-body airliner",
    country: "United States",
    specs: {
      wingspan: "47.3 m (155 ft 4 in)",
      length: "54.2 m (177 ft 8 in)",
      maxSpeed: "Mach 0.83",
      range: "9,653 km (5,998 mi)",
      ceiling: "42,000 ft",
      engines: "3× Rolls-Royce RB211-524B",
      crew: "3",
      capacity: "250–400 passengers",
    },
    description:
      "The L-1011 TriStar was technically the most advanced of the first-generation wide-bodies, featuring an advanced autopilot and auto-land system, an active control system, and the S-duct center engine that produced the iconic intake below the tail. The Rolls-Royce RB211 engine program's near-bankruptcy hurt its sales against the DC-10.",
    funFact:
      "The L-1011 was the first airliner certified for Category IIIc fully automatic landing in zero visibility — a technology so advanced that it took years for airports to build the ground infrastructure needed to use it.",
    visual: {
      engineCount: 3,
      engineType: "turbofan",
      enginePlacement: "Two underwing + one buried in tail with S-duct intake",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "modern",
      distinguishingFeatures: [
        "Center engine buried in tail — no nacelle visible from side",
        "Distinctive round S-duct intake below vertical stabilizer",
        "Two large underwing Rolls-Royce RB211 engines",
        "Very clean tail profile (no nacelle bump like DC-10/MD-11)",
        "Wide-body fuselage",
        "Low swept wing",
      ],
    },
    aliases: ["L-1011", "TriStar", "L1011"],
  },

  {
    id: "de-havilland-comet",
    name: "de Havilland Comet",
    manufacturer: "de Havilland",
    type: "Long-haul Jet",
    firstFlight: "1949",
    inService: "1952",
    role: "Long-haul airliner",
    country: "United Kingdom",
    specs: {
      wingspan: "35.0 m (114 ft 10 in)",
      length: "35.9 m (117 ft 9 in)",
      maxSpeed: "Mach 0.74",
      range: "6,035 km (3,750 mi)",
      ceiling: "42,000 ft",
      engines: "4× de Havilland Ghost 50 Mk1 (Comet 1) / 4× Rolls-Royce Avon (Comet 4)",
      crew: "3–4",
      capacity: "36–81 passengers",
    },
    description:
      "The Comet was the world's first commercial jet airliner, entering service with BOAC in 1952. Its pressurized cabin, smooth flight, and dramatic speed advantage over propeller aircraft made it a sensation. Tragically, structural failures due to metal fatigue around the square windows led to catastrophic explosive decompression accidents in 1953–1954.",
    funFact:
      "The Comet disasters directly led to the science of metal fatigue analysis being systematically applied to aircraft design — every modern pressurized aircraft benefits from the engineering lessons learned from the Comet's tragic failures.",
    visual: {
      engineCount: 4,
      engineType: "turbojet",
      enginePlacement: "Buried in wing roots",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "early-jet",
      distinguishingFeatures: [
        "Engines buried in wing roots — no visible nacelles",
        "Very clean wing profile",
        "Low swept wing",
        "Conventional tail",
        "Elegant narrow fuselage",
        "Pioneer jet airliner silhouette",
      ],
    },
    aliases: ["Comet 1", "Comet 4", "DH.106"],
  },

  {
    id: "sud-caravelle",
    name: "Sud Aviation Caravelle",
    manufacturer: "Sud Aviation (SNCASE)",
    type: "Short-haul Jet",
    firstFlight: "1955",
    inService: "1959",
    role: "Short / medium-haul airliner",
    country: "France",
    specs: {
      wingspan: "34.3 m (112 ft 6 in)",
      length: "36.2 m (118 ft 11 in)",
      maxSpeed: "Mach 0.78",
      range: "2,000 km (1,243 mi)",
      ceiling: "39,000 ft",
      engines: "2× Rolls-Royce Avon 533R",
      crew: "3",
      capacity: "64–99 passengers",
    },
    description:
      "The Caravelle was the world's first rear-engine jet airliner and the first to place the engines at the tail rather than in the wings. This pioneering configuration — which produced the clean wing that is now standard on short-haul jets — was adopted by Douglas for the DC-9 and BAC for the One-Eleven.",
    funFact:
      "The Caravelle's nose section was licensed directly from de Havilland and is essentially the same as the Comet's — France's first jet airliner literally had a British nose grafted onto a French fuselage.",
    visual: {
      engineCount: 2,
      engineType: "turbojet",
      enginePlacement: "Rear fuselage mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "early-jet",
      distinguishingFeatures: [
        "Rear-mounted engines — first aircraft to use this configuration",
        "Clean swept low wing (no underwing engines)",
        "Conventional tail",
        "de Havilland Comet nose",
        "Circular fuselage",
        "Elegant 1950s jet lines",
      ],
    },
    aliases: ["Caravelle", "SE-210", "Caravelle VI", "Caravelle 12"],
  },

  {
    id: "bac-one-eleven",
    name: "BAC One-Eleven",
    manufacturer: "British Aircraft Corporation (BAC)",
    type: "Short-haul Jet",
    firstFlight: "1963",
    inService: "1965",
    role: "Short-haul airliner",
    country: "United Kingdom",
    specs: {
      wingspan: "28.5 m (93 ft 5 in)",
      length: "32.6 m (107 ft 0 in)",
      maxSpeed: "Mach 0.82",
      range: "2,744 km (1,705 mi)",
      ceiling: "35,000 ft",
      engines: "2× Rolls-Royce Spey 512DW",
      crew: "2",
      capacity: "74–119 passengers",
    },
    description:
      "The BAC One-Eleven was Britain's answer to the Douglas DC-9, featuring Rolls-Royce Spey rear-mounted engines and a T-tail. It was popular with US carriers including Braniff, American, and Mohawk, as well as British United and British Caledonian. Romania produced a licensed copy, the ROMBAC 1-11, until 1989.",
    funFact:
      "The BAC One-Eleven suffered the 'deep stall' problem early in testing — the T-tail configuration allowed the horizontal stabilizer to be blanketed by a stalled wing, trapping the aircraft in an unrecoverable nose-high attitude. A prototype crashed, and stick pushers became mandatory.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Rear fuselage mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "early-jet",
      distinguishingFeatures: [
        "Rear-mounted Spey engines",
        "T-tail",
        "Low swept wing",
        "Clean wing without underwing pods",
        "Circular fuselage",
        "Classic British short-haul jet",
      ],
    },
    aliases: ["One-Eleven", "111", "BAC 111", "ROMBAC 1-11"],
  },

  {
    id: "convair-880",
    name: "Convair 880",
    manufacturer: "Convair (General Dynamics)",
    type: "Medium-haul Jet",
    firstFlight: "1959",
    inService: "1960",
    role: "Medium-haul airliner",
    country: "United States",
    specs: {
      wingspan: "36.6 m (120 ft 0 in)",
      length: "39.4 m (129 ft 4 in)",
      maxSpeed: "Mach 0.82",
      range: "5,230 km (3,250 mi)",
      ceiling: "41,000 ft",
      engines: "4× GE CJ805-3B",
      crew: "3",
      capacity: "88–110 passengers",
    },
    description:
      "The Convair 880 was marketed as the world's fastest commercial airliner of its era, hence the name (880 feet per second cruise speed). Built for prestige and speed, it was bought by Delta, TWA, and Cathay Pacific, but its economics were poor and Convair lost enormous sums on the program.",
    funFact:
      "Convair lost approximately $450 million on the 880 and 990 programs — the largest commercial loss in corporate history at the time — essentially bankrupting the commercial aviation division of General Dynamics.",
    visual: {
      engineCount: 4,
      engineType: "turbojet",
      enginePlacement: "Underwing, podded on pylons",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "early-jet",
      distinguishingFeatures: [
        "Four underwing podded turbojet engines",
        "Narrow fuselage (narrower than 707/DC-8)",
        "Low swept wing",
        "Conventional tail",
        "Slender elegant appearance",
        "Classic late-1950s jet airliner lines",
      ],
    },
    aliases: ["CV-880", "Convair 880", "Golden Arrow"],
  },

  {
    id: "convair-990",
    name: "Convair 990 Coronado",
    manufacturer: "Convair (General Dynamics)",
    type: "Medium-haul Jet",
    firstFlight: "1961",
    inService: "1962",
    role: "Medium-haul airliner",
    country: "United States",
    specs: {
      wingspan: "36.6 m (120 ft 0 in)",
      length: "42.4 m (139 ft 2 in)",
      maxSpeed: "Mach 0.91",
      range: "6,115 km (3,800 mi)",
      ceiling: "41,000 ft",
      engines: "4× GE CJ805-23B",
      crew: "3",
      capacity: "96–121 passengers",
    },
    description:
      "The Convair 990 Coronado was a stretched, re-engined development of the 880, designed to meet American Airlines' requirement for a faster, longer-range aircraft. Its distinctive anti-shock bodies — four speed pods on the trailing edge of the wings — are its most recognizable feature and were added to solve drag problems at high speed.",
    funFact:
      "The Convair 990's four distinctive wing-mounted speed pods (anti-shock bodies) were retrofitted after the aircraft couldn't meet its promised performance — they reduced transonic wave drag and allowed the aircraft to finally reach its advertised cruise speed.",
    visual: {
      engineCount: 4,
      engineType: "turbojet",
      enginePlacement: "Underwing, podded on pylons",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "early-jet",
      distinguishingFeatures: [
        "Four underwing engines",
        "Four distinctive anti-shock speed pods on wing trailing edge",
        "Longer fuselage than Convair 880",
        "Low swept wing",
        "Conventional tail",
        "Unique trailing-edge pods are unmistakable",
      ],
    },
    aliases: ["CV-990", "Convair Coronado", "Coronado"],
  },

  {
    id: "vickers-vc10",
    name: "Vickers VC10",
    manufacturer: "Vickers-Armstrongs (Aircraft)",
    type: "Long-haul Jet",
    firstFlight: "1962",
    inService: "1964",
    role: "Long-haul airliner",
    country: "United Kingdom",
    specs: {
      wingspan: "44.6 m (146 ft 2 in)",
      length: "52.3 m (171 ft 8 in)",
      maxSpeed: "Mach 0.86",
      range: "11,560 km (7,182 mi)",
      ceiling: "42,000 ft",
      engines: "4× Rolls-Royce Conway",
      crew: "4",
      capacity: "135–174 passengers",
    },
    description:
      "The VC10 was designed for BOAC's hot-and-high African and Asian routes, requiring excellent short-field performance from difficult airports. Its four rear-mounted Rolls-Royce Conway engines and T-tail gave it a clean wing and superb climb performance — and a reputation among passengers for the quietest cabin in the sky.",
    funFact:
      "The VC10 was so quiet in the cabin due to its rear-mounted engines that BOAC marketed it as 'the plane that whispers' — passengers in the front cabin heard almost nothing from the engines mounted far behind them.",
    visual: {
      engineCount: 4,
      engineType: "turbojet",
      enginePlacement: "Rear fuselage, four engines in two pairs",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "early-jet",
      distinguishingFeatures: [
        "Four rear-mounted engines in two paired nacelles",
        "T-tail",
        "Clean low swept wing (no underwing engines)",
        "Long elegant fuselage",
        "Distinctive large vertical stabilizer",
        "Quintessential British long-haul jet",
      ],
    },
    aliases: ["VC-10", "Super VC10", "VC10 C.Mk1"],
  },

  {
    id: "tupolev-tu154",
    name: "Tupolev Tu-154",
    manufacturer: "Tupolev",
    type: "Medium-haul Jet",
    firstFlight: "1968",
    inService: "1972",
    role: "Medium / long-haul airliner",
    country: "Soviet Union / Russia",
    specs: {
      wingspan: "37.6 m (123 ft 4 in)",
      length: "47.9 m (157 ft 2 in)",
      maxSpeed: "Mach 0.86",
      range: "3,900 km (2,424 mi)",
      ceiling: "39,370 ft",
      engines: "3× Kuznetsov NK-8-2U (Tu-154B) / Aviadvigatel PS-90A (Tu-154M)",
      crew: "3",
      capacity: "128–180 passengers",
    },
    description:
      "The Tu-154 was the Soviet Union's equivalent of the Boeing 727, featuring three rear-mounted engines and a T-tail. It became the workhorse of Aeroflot and Soviet-bloc carriers for decades, valued for its ability to operate from rough, unimproved runways. It remained in Russian military service well into the 2020s.",
    funFact:
      "The Tu-154 was designed to operate from unpaved and gravel runways at remote Soviet airstrips, resulting in its robust undercarriage with six-wheel bogies — significantly over-engineered by Western standards but essential for Soviet infrastructure.",
    visual: {
      engineCount: 3,
      engineType: "turbojet",
      enginePlacement: "Rear fuselage, center engine above fuselage with S-duct",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "Three rear-mounted engines",
        "Center engine above fuselage with S-duct intake",
        "T-tail",
        "Low swept wing",
        "Distinctive Soviet airliner profile",
        "Six-wheel main gear bogies",
      ],
    },
    aliases: ["Tu-154B", "Tu-154M", "Careless"],
  },

  {
    id: "tupolev-tu134",
    name: "Tupolev Tu-134",
    manufacturer: "Tupolev",
    type: "Short-haul Jet",
    firstFlight: "1963",
    inService: "1967",
    role: "Short / medium-haul airliner",
    country: "Soviet Union",
    specs: {
      wingspan: "29.0 m (95 ft 2 in)",
      length: "37.1 m (121 ft 8 in)",
      maxSpeed: "Mach 0.82",
      range: "3,020 km (1,877 mi)",
      ceiling: "39,370 ft",
      engines: "2× Soloviev D-30",
      crew: "3–4",
      capacity: "76–96 passengers",
    },
    description:
      "The Tu-134 was the Soviet Union's answer to the Caravelle and DC-9, featuring rear-mounted turbofan engines and a T-tail. It became one of the most widely used Soviet short-haul jets, serving Aeroflot and Warsaw Pact carriers. Distinctive features included a glazed nose used by the navigator.",
    funFact:
      "The Tu-134 retained a glazed nose for a navigator position well into the 1970s — a throwback to bomber-era thinking that Soviet designers included to allow celestial navigation over the vast, VOR-free Soviet interior.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Rear fuselage mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "Rear-mounted engines",
        "T-tail",
        "Distinctive glazed navigator's nose",
        "Low swept wing",
        "Soviet airliner design",
        "Narrow fuselage with porthole windows",
      ],
    },
    aliases: ["Tu-134A", "Tu-134B", "Crusty"],
  },

  {
    id: "ilyushin-il62",
    name: "Ilyushin Il-62",
    manufacturer: "Ilyushin",
    type: "Long-haul Jet",
    firstFlight: "1963",
    inService: "1967",
    role: "Long-haul airliner",
    country: "Soviet Union",
    specs: {
      wingspan: "43.2 m (141 ft 9 in)",
      length: "53.1 m (174 ft 3 in)",
      maxSpeed: "Mach 0.82",
      range: "10,000 km (6,214 mi)",
      ceiling: "42,650 ft",
      engines: "4× Kuznetsov NK-8-4 / Soloviev D-30KU",
      crew: "5",
      capacity: "168–195 passengers",
    },
    description:
      "The Il-62 was the Soviet Union's first intercontinental jet, designed to replace the turboprop Tu-114 on long routes. Its four rear-mounted engines in two paired nacelles closely resembled the Vickers VC10, though the Soviets denied any copying. It served Aeroflot's prestige routes to New York, Tokyo, and Havana.",
    funFact:
      "The Il-62 requires a tail support strut on the ground to prevent it from tipping backwards — its rear-heavy weight distribution meant it would literally fall on its tail if passengers weren't careful about boarding sequence.",
    visual: {
      engineCount: 4,
      engineType: "turbojet",
      enginePlacement: "Rear fuselage, four engines in two paired nacelles",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "cold-war",
      distinguishingFeatures: [
        "Four rear-mounted engines in paired nacelles",
        "T-tail",
        "Clean low swept wing",
        "Tail support strut visible on ground",
        "Long elegant Soviet fuselage",
        "Similar profile to Vickers VC10",
      ],
    },
    aliases: ["Il-62M", "Classic (NATO)", "Ilyushin 62"],
  },

  {
    id: "ilyushin-il86",
    name: "Ilyushin Il-86",
    manufacturer: "Ilyushin",
    type: "Wide-body Short / Medium-haul Jet",
    firstFlight: "1976",
    inService: "1980",
    role: "High-density short / medium-haul airliner",
    country: "Soviet Union",
    specs: {
      wingspan: "48.1 m (157 ft 10 in)",
      length: "59.5 m (195 ft 2 in)",
      maxSpeed: "Mach 0.82",
      range: "4,600 km (2,858 mi)",
      ceiling: "39,370 ft",
      engines: "4× Kuznetsov NK-86",
      crew: "3",
      capacity: "350 passengers",
    },
    description:
      "The Il-86 was the Soviet Union's first wide-body airliner and the largest Soviet passenger aircraft of its era. Designed for high-density domestic routes, it featured a unique lower-deck boarding system where passengers entered through doors in the belly and stowed their own luggage before climbing stairs into the main cabin.",
    funFact:
      "The Il-86's lower-deck boarding concept was revolutionary — passengers walked onto the aircraft at ground level through belly doors, stored their bags in the hold themselves, and then climbed internal stairs. No jet bridges or baggage handlers needed.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Underwing, podded on pylons",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "cold-war",
      distinguishingFeatures: [
        "Four underwing turbofan engines",
        "Wide-body fuselage",
        "Low swept wing",
        "Conventional tail",
        "Lower-deck boarding doors visible in belly",
        "Soviet wide-body design",
      ],
    },
    aliases: ["Il-86", "Camber (NATO)"],
  },

  {
    id: "ilyushin-il96",
    name: "Ilyushin Il-96",
    manufacturer: "Ilyushin / VASO",
    type: "Wide-body Long-haul Jet",
    firstFlight: "1988",
    inService: "1993",
    role: "Long-haul wide-body airliner",
    country: "Russia",
    specs: {
      wingspan: "57.7 m (189 ft 3 in)",
      length: "55.3 m (181 ft 5 in)",
      maxSpeed: "Mach 0.84",
      range: "11,500 km (7,146 mi)",
      ceiling: "40,026 ft",
      engines: "4× Aviadvigatel PS-90A",
      crew: "3",
      capacity: "262–435 passengers",
    },
    description:
      "The Il-96 is Russia's modern wide-body airliner, a significantly redesigned development of the Il-86 with a shorter fuselage, new PS-90A turbofan engines, winglets, and EFIS cockpit. Despite limited commercial success, it serves as the Russian Presidential aircraft and remains in limited production.",
    funFact:
      "Vladimir Putin's presidential aircraft is an Il-96-300PU, customized with advanced communications, a conference room, and defensive countermeasures — making it the Russian equivalent of Air Force One.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Underwing, podded on pylons",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "modern",
      distinguishingFeatures: [
        "Four underwing turbofan engines",
        "Winglets — differentiates from Il-86",
        "Wide-body fuselage",
        "Low swept wing",
        "Conventional tail",
        "Shorter fuselage than Il-86",
      ],
    },
    aliases: ["Il-96-300", "Il-96M", "Ilyushin 96"],
  },

  {
    id: "yakovlev-yak40",
    name: "Yakovlev Yak-40",
    manufacturer: "Yakovlev",
    type: "Regional Jet",
    firstFlight: "1966",
    inService: "1968",
    role: "Regional / feeder airliner",
    country: "Soviet Union",
    specs: {
      wingspan: "25.0 m (82 ft 0 in)",
      length: "20.4 m (66 ft 11 in)",
      maxSpeed: "Mach 0.64",
      range: "1,450 km (901 mi)",
      ceiling: "23,000 ft",
      engines: "3× Ivchenko AI-25",
      crew: "2–3",
      capacity: "27–32 passengers",
    },
    description:
      "The Yak-40 was the world's first regional jet designed specifically for feeder routes, created to replace piston-engine aircraft on Aeroflot's vast rural network. Its three rear-mounted engines and high-wing gave it excellent STOL performance from unprepared strips in remote Soviet territory.",
    funFact:
      "The Yak-40 was designed to operate from unpaved runways in Siberia at temperatures of -50°C — its three-engine configuration was a deliberate safety margin for operations far from any maintenance facility.",
    visual: {
      engineCount: 3,
      engineType: "turbofan",
      enginePlacement: "Rear fuselage, three engines clustered at tail",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "Three rear-mounted engines at tail",
        "T-tail",
        "Low straight wing",
        "Short compact fuselage",
        "Built-in airstair",
        "Soviet regional feeder design",
      ],
    },
    aliases: ["Yak-40", "Codling (NATO)"],
  },

  {
    id: "yakovlev-yak42",
    name: "Yakovlev Yak-42",
    manufacturer: "Yakovlev",
    type: "Short-haul Jet",
    firstFlight: "1975",
    inService: "1980",
    role: "Short / medium-haul airliner",
    country: "Soviet Union / Russia",
    specs: {
      wingspan: "34.9 m (114 ft 6 in)",
      length: "36.4 m (119 ft 5 in)",
      maxSpeed: "Mach 0.82",
      range: "1,900 km (1,181 mi)",
      ceiling: "30,000 ft",
      engines: "3× Lotarev D-36",
      crew: "3",
      capacity: "120 passengers",
    },
    description:
      "The Yak-42 scaled up the three-engine rear-mount concept of the Yak-40 to a mainline 120-seat capacity. Powered by the advanced Lotarev D-36 high-bypass turbofan — the first high-bypass engine developed in the Soviet Union — it offered significantly better fuel economy than older Soviet jets.",
    funFact:
      "The Yak-42 holds the unfortunate distinction of being involved in the 2011 Yaroslavl air disaster, which killed 44 people including most of the Kontinental Hockey League's Lokomotiv Yaroslavl team.",
    visual: {
      engineCount: 3,
      engineType: "turbofan",
      enginePlacement: "Rear fuselage, three engines clustered at tail",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "Three rear-mounted engines",
        "T-tail",
        "Low swept wing",
        "120-seat capacity",
        "Soviet Tu-154 competitor",
        "Large triple-engine tail cluster",
      ],
    },
    aliases: ["Yak-42D", "Clobber (NATO)"],
  },

  {
    id: "vickers-viscount",
    name: "Vickers Viscount",
    manufacturer: "Vickers-Armstrongs",
    type: "Short-haul Turboprop",
    firstFlight: "1948",
    inService: "1953",
    role: "Short / medium-haul airliner",
    country: "United Kingdom",
    specs: {
      wingspan: "28.6 m (93 ft 8 in)",
      length: "26.1 m (85 ft 8 in)",
      maxSpeed: "563 km/h (350 mph)",
      range: "2,775 km (1,724 mi)",
      ceiling: "25,000 ft",
      engines: "4× Rolls-Royce Dart",
      crew: "3",
      capacity: "40–71 passengers",
    },
    description:
      "The Viscount was the world's first turboprop airliner to enter commercial service, revolutionizing air travel with its smooth, vibration-free flight compared to piston aircraft. Its large oval windows — larger than any previous airliner — were a deliberate passenger-appeal feature. It was the best-selling British airliner ever.",
    funFact:
      "The Viscount's large oval passenger windows were the biggest on any airliner of its era — Vickers designed them specifically as a selling point, recognizing that passengers wanted to see the world below them, not stare at a wall.",
    visual: {
      engineCount: 4,
      engineType: "turboprop",
      enginePlacement: "Underwing, tractor propellers",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "Four underwing turboprop engines",
        "Distinctive large oval windows",
        "Low straight wing",
        "Conventional tail",
        "Circular pressurized fuselage",
        "Classic 1950s turboprop airliner",
      ],
    },
    aliases: ["Viscount 700", "Viscount 800", "Viscount 810"],
  },

  {
    id: "hawker-siddeley-trident",
    name: "Hawker Siddeley Trident",
    manufacturer: "de Havilland / Hawker Siddeley",
    type: "Short / Medium-haul Jet",
    firstFlight: "1962",
    inService: "1964",
    role: "Short / medium-haul airliner",
    country: "United Kingdom",
    specs: {
      wingspan: "29.9 m (98 ft 0 in)",
      length: "40.0 m (131 ft 2 in)",
      maxSpeed: "Mach 0.88",
      range: "4,345 km (2,700 mi)",
      ceiling: "35,000 ft",
      engines: "3× Rolls-Royce Spey 512-5W",
      crew: "3",
      capacity: "103–180 passengers",
    },
    description:
      "The Trident was designed specifically for British European Airways' (BEA) requirements — so specifically that its highly tailored specifications made it commercially unattractive to other airlines. Its three rear-mounted Spey engines and T-tail gave it a profile similar to the Boeing 727, but its smaller size and BEA-specific features limited sales to 117 aircraft.",
    funFact:
      "The Trident was the first aircraft in the world certified for fully automatic Category IIIa autoland in revenue service — it could land itself in near-zero visibility conditions at Heathrow, a capability that predated the L-1011 by years.",
    visual: {
      engineCount: 3,
      engineType: "turbofan",
      enginePlacement: "Rear fuselage, center engine with S-duct intake above fuselage",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "early-jet",
      distinguishingFeatures: [
        "Three rear-mounted Spey engines",
        "Center engine above fuselage with S-duct",
        "T-tail",
        "Low swept wing",
        "Clean wing without underwing engines",
        "Similar layout to Boeing 727",
      ],
    },
    aliases: ["Trident 1", "Trident 2", "Trident 3", "HS.121"],
  },
];
