import { AircraftEntry } from "./types";

export const commercialBoeing: AircraftEntry[] = [
  {
    id: "boeing-707",
    name: "Boeing 707",
    manufacturer: "Boeing",
    type: "Narrow-body jet airliner",
    firstFlight: "1957-12-20",
    inService: "1958-10-26",
    role: "Long-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "145 ft 9 in (44.4 m)",
      length: "152 ft 11 in (46.6 m)",
      maxSpeed: "627 mph (1,009 km/h)",
      range: "6,160 mi (9,913 km)",
      ceiling: "42,000 ft (12,802 m)",
      engines: "4× Pratt & Whitney JT3D turbofan",
      crew: "3–4",
      capacity: "140–219 passengers",
    },
    description:
      "The Boeing 707 is a narrow-body, four-engine jet airliner that launched the Jet Age of commercial aviation. It was Boeing's first commercially successful jetliner and defined intercontinental air travel for nearly two decades, fundamentally transforming how people crossed oceans and continents.",
    funFact:
      "The 707 prototype was informally called the 'Dash 80' and Boeing's test pilot Tex Johnston performed an unauthorized barrel roll over Lake Washington during a 1955 airshow to demonstrate its capabilities — a stunt that nearly got him fired.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Podded under swept wings, two per side",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "cold-war",
      distinguishingFeatures: [
        "Four underwing podded engines",
        "35-degree swept wings",
        "Narrow fuselage",
        "Low-mounted horizontal stabilizers",
        "Distinctive pointy nose",
        "Lower fuselage fuel vents on wingtips",
      ],
    },
    aliases: ["Seven-Oh-Seven", "Jet Stratoliner", "Dash 80 derivative"],
  },
  {
    id: "boeing-717",
    name: "Boeing 717",
    manufacturer: "Boeing",
    type: "Narrow-body jet airliner",
    variant: "717-200",
    firstFlight: "1998-09-02",
    inService: "1999-10-12",
    role: "Short- to medium-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "93 ft 3 in (28.4 m)",
      length: "124 ft 0 in (37.8 m)",
      maxSpeed: "504 mph (811 km/h)",
      range: "2,060 mi (3,815 km)",
      ceiling: "37,000 ft (11,278 m)",
      engines: "2× BMW/Rolls-Royce BR715 turbofan",
      crew: "2",
      capacity: "106–134 passengers",
    },
    description:
      "The Boeing 717, originally developed by McDonnell Douglas as the MD-95 before Boeing's merger, is a twin-engine narrow-body jet designed for high-frequency short-haul routes. Its rear-mounted engines and T-tail give it a distinctive silhouette inherited from the DC-9/MD-80 family.",
    funFact:
      "The 717 is technically the spiritual great-grandchild of the Douglas DC-9 from 1965. Despite being a 'Boeing' product, every design element traces back to McDonnell Douglas — Boeing never changed anything significant after the merger.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Rear-mounted, aft fuselage, one per side",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Rear fuselage-mounted engines",
        "T-tail configuration",
        "Clean underwing with no engines",
        "Narrow single-aisle fuselage",
        "Short overall length",
        "Two-class seating typical",
      ],
    },
    aliases: ["MD-95", "Seven-Seventeen"],
  },
  {
    id: "boeing-720",
    name: "Boeing 720",
    manufacturer: "Boeing",
    type: "Narrow-body jet airliner",
    firstFlight: "1959-11-23",
    inService: "1960-07-05",
    role: "Short- to medium-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "130 ft 10 in (39.9 m)",
      length: "136 ft 2 in (41.5 m)",
      maxSpeed: "627 mph (1,009 km/h)",
      range: "4,160 mi (6,695 km)",
      ceiling: "40,000 ft (12,192 m)",
      engines: "4× Pratt & Whitney JT3C or JT3D turbofan",
      crew: "3",
      capacity: "112–165 passengers",
    },
    description:
      "The Boeing 720 was a lighter, shorter-range derivative of the 707 designed for domestic and overland routes. Originally designated the 707-020, it featured a structural redesign for shorter fields and a modified wing with full-span leading-edge slats for improved low-speed performance.",
    funFact:
      "The FAA made Boeing rename the aircraft '720' to distinguish it from the 707, even though Boeing considered it a 707 variant. Several 720s were deliberately crash-tested in 1984 to evaluate a fire-suppression fuel additive called 'antimisting kerosene' — the test worked poorly but produced spectacular footage.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Podded under swept wings, two per side",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "cold-war",
      distinguishingFeatures: [
        "Four underwing podded engines",
        "Shorter fuselage than 707",
        "Full-span leading-edge slats",
        "35-degree swept wings",
        "Narrow single-aisle fuselage",
        "Nearly identical external appearance to 707-120",
      ],
    },
    aliases: ["707-020", "Seven-Twenty"],
  },
  {
    id: "boeing-727-100",
    name: "Boeing 727-100",
    manufacturer: "Boeing",
    type: "Narrow-body jet airliner",
    variant: "727-100",
    firstFlight: "1963-02-09",
    inService: "1964-02-01",
    role: "Short- to medium-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "108 ft 0 in (32.9 m)",
      length: "133 ft 2 in (40.6 m)",
      maxSpeed: "632 mph (1,017 km/h)",
      range: "2,250 mi (3,621 km)",
      ceiling: "42,000 ft (12,802 m)",
      engines: "3× Pratt & Whitney JT8D turbofan",
      crew: "3",
      capacity: "94–131 passengers",
    },
    description:
      "The Boeing 727-100 was the original variant of Boeing's first trijet, designed for medium-range routes from shorter runways. Its three rear-mounted engines — two on the sides of the aft fuselage and one in the tail with an S-duct — gave it a distinctive appearance and enabled operations from airports that could not handle four-engine jets.",
    funFact:
      "The 727's center engine has a straight-through air duct that runs through the vertical stabilizer — a unique S-shaped duct called the 'S-duct.' This was a revolutionary design that influenced many later aircraft and required exceptionally complex engineering.",
    visual: {
      engineCount: 3,
      engineType: "turbofan",
      enginePlacement: "Two aft fuselage sides, one tail-mounted with S-duct",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "Three rear-mounted engines",
        "Center engine in tail via S-duct",
        "T-tail configuration",
        "Clean underwing no engines",
        "Triple-slotted Fowler flaps",
        "Full-length leading-edge slats",
        "Distinctive aft airstairs under tail",
      ],
    },
    aliases: ["Seven-Twenty-Seven"],
  },
  {
    id: "boeing-727-200",
    name: "Boeing 727-200",
    manufacturer: "Boeing",
    type: "Narrow-body jet airliner",
    variant: "727-200",
    firstFlight: "1967-07-27",
    inService: "1968-12-14",
    role: "Short- to medium-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "108 ft 0 in (32.9 m)",
      length: "153 ft 2 in (46.7 m)",
      maxSpeed: "632 mph (1,017 km/h)",
      range: "2,550 mi (4,103 km)",
      ceiling: "42,000 ft (12,802 m)",
      engines: "3× Pratt & Whitney JT8D turbofan",
      crew: "3",
      capacity: "145–189 passengers",
    },
    description:
      "The 727-200 is the stretched, higher-capacity version of the 727-100 with a fuselage extended by 20 feet. It became the bestselling variant and eventually the best-selling commercial jetliner of its era, popular with airlines for its versatility and ability to operate from secondary airports.",
    funFact:
      "The 727-200 was so popular that it became the first commercial aircraft to sell over 1,000 units. It was also the preferred choice of D.B. Cooper, who famously hijacked a 727 in 1971 and parachuted from the rear airstairs — a unique door that only the 727 had. No other commercial jet of the era had aft airstairs that could open in flight.",
    visual: {
      engineCount: 3,
      engineType: "turbofan",
      enginePlacement: "Two aft fuselage sides, one tail-mounted with S-duct",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "large",
      era: "cold-war",
      distinguishingFeatures: [
        "Three rear-mounted engines",
        "Center engine in tail via S-duct",
        "T-tail configuration",
        "Longer fuselage than -100",
        "Clean underwing no engines",
        "Distinctive rear airstairs under tail",
        "Triple-slotted Fowler flaps",
      ],
    },
    aliases: ["Seven-Twenty-Seven-Two-Hundred"],
  },
  {
    id: "boeing-737-100",
    name: "Boeing 737-100",
    manufacturer: "Boeing",
    type: "Narrow-body jet airliner",
    variant: "737-100",
    firstFlight: "1967-04-09",
    inService: "1968-02-10",
    role: "Short-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "93 ft 0 in (28.3 m)",
      length: "94 ft 0 in (28.6 m)",
      maxSpeed: "586 mph (943 km/h)",
      range: "1,150 mi (1,851 km)",
      ceiling: "37,000 ft (11,278 m)",
      engines: "2× Pratt & Whitney JT8D-1 turbofan",
      crew: "2–3",
      capacity: "85–103 passengers",
    },
    description:
      "The Boeing 737-100 was the original variant of what would become the world's best-selling commercial jetliner family. Its short, stubby fuselage was designed for quick-turnaround short-haul routes and the aircraft sits notably low to the ground — a characteristic that would define all subsequent 737 variants.",
    funFact:
      "The 737-100 sits so low to the ground that its engines had to be mounted ahead of and above the wing rather than below it, giving all 737s their signature flat-bottomed engine nacelles. Only Lufthansa bought the -100 as its launch customer; most airlines preferred the longer -200. Only 30 were built.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, forward of wing leading edge, flattened nacelles",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "Flat-bottom engine nacelles (low ground clearance)",
        "Engines mounted ahead of wing",
        "Short stubby fuselage",
        "Low-slung profile",
        "No winglets",
        "Eyebrow windows above cockpit windshield",
      ],
    },
    aliases: ["Original 737", "Seven-Thirty-Seven"],
  },
  {
    id: "boeing-737-200",
    name: "Boeing 737-200",
    manufacturer: "Boeing",
    type: "Narrow-body jet airliner",
    variant: "737-200",
    firstFlight: "1967-08-08",
    inService: "1968-04-29",
    role: "Short-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "93 ft 0 in (28.3 m)",
      length: "100 ft 0 in (30.5 m)",
      maxSpeed: "586 mph (943 km/h)",
      range: "1,975 mi (3,178 km)",
      ceiling: "37,000 ft (11,278 m)",
      engines: "2× Pratt & Whitney JT8D turbofan",
      crew: "2–3",
      capacity: "97–130 passengers",
    },
    description:
      "The 737-200 is a stretched version of the original 737-100 and became the commercially successful workhorse of the original 737 series. It dominated short-haul operations through the 1970s and 1980s and was particularly popular with regional and charter airlines due to its rugged reliability.",
    funFact:
      "The 737-200 was so robust that operators in remote Alaska, Canada, and South America used a 'gravel kit' modification allowing it to operate from unpaved strips — complete with a vortex dissipator to prevent engine FOD ingestion. This made it one of the few jetliners ever certified for gravel runway operations.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, forward of wing leading edge, flattened nacelles",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "Flat-bottom engine nacelles",
        "Engines ahead of wing",
        "Slightly longer fuselage than -100",
        "Low-slung profile",
        "Eyebrow windows above cockpit windshield",
        "No winglets",
      ],
    },
    aliases: ["Original 737", "Seven-Thirty-Seven-Two-Hundred"],
  },
  {
    id: "boeing-737-300",
    name: "Boeing 737-300",
    manufacturer: "Boeing",
    type: "Narrow-body jet airliner",
    variant: "737-300",
    firstFlight: "1984-02-24",
    inService: "1984-11-28",
    role: "Short- to medium-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "94 ft 9 in (28.9 m)",
      length: "109 ft 7 in (33.4 m)",
      maxSpeed: "584 mph (939 km/h)",
      range: "2,255 mi (3,629 km)",
      ceiling: "37,000 ft (11,278 m)",
      engines: "2× CFM International CFM56-3 turbofan",
      crew: "2",
      capacity: "128–149 passengers",
    },
    description:
      "The 737-300 launched the second-generation 'Classic' 737 series, introducing CFM56 high-bypass turbofan engines and a stretched fuselage. To accommodate the larger engines under the famously low wing, Boeing moved and flattened the nacelles, creating the characteristic oval cross-section that defines all Classic and NG 737s.",
    funFact:
      "The CFM56 engines on the 737-300 are so large relative to the ground clearance that the accessory gearbox had to be moved from the bottom to the side of the engine, creating the distinctive D-shaped/oval nacelle cross-section unique to the 737 family. This creative solution became a defining visual signature of the airplane.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing forward, flattened/oval nacelles for ground clearance",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "Oval/D-shaped engine nacelles",
        "Engines ahead of and above wing line",
        "Eyebrow windows above cockpit (early production)",
        "EFIS glass cockpit",
        "No winglets (standard)",
        "Blended winglets optional",
      ],
    },
    aliases: ["737 Classic", "Seven-Thirty-Seven-Three-Hundred"],
  },
  {
    id: "boeing-737-400",
    name: "Boeing 737-400",
    manufacturer: "Boeing",
    type: "Narrow-body jet airliner",
    variant: "737-400",
    firstFlight: "1988-02-19",
    inService: "1988-09-15",
    role: "Short- to medium-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "94 ft 9 in (28.9 m)",
      length: "119 ft 7 in (36.4 m)",
      maxSpeed: "584 mph (939 km/h)",
      range: "2,090 mi (3,364 km)",
      ceiling: "37,000 ft (11,278 m)",
      engines: "2× CFM International CFM56-3C1 turbofan",
      crew: "2",
      capacity: "146–188 passengers",
    },
    description:
      "The 737-400 is the stretched, higher-capacity member of the Classic 737 family, extending the -300 by 10 feet to accommodate up to 188 passengers. It was the largest Classic 737 and filled the gap between the mid-size -300 and the larger 757.",
    funFact:
      "The 737-400 stretch required Boeing to add a tail bumper (a small skid under the tail) to prevent the tail from striking the runway during rotation — a problem that arises when fuselages are lengthened without changing the wing position. You can spot this small metal skid just below the aft fuselage.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing forward, flattened/oval nacelles",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "modern",
      distinguishingFeatures: [
        "Oval/D-shaped engine nacelles",
        "Longest Classic 737 fuselage",
        "Tail skid visible under rear fuselage",
        "No eyebrow windows (removed mid-production)",
        "Blended winglets optional",
      ],
    },
    aliases: ["737 Classic", "Seven-Thirty-Seven-Four-Hundred"],
  },
  {
    id: "boeing-737-500",
    name: "Boeing 737-500",
    manufacturer: "Boeing",
    type: "Narrow-body jet airliner",
    variant: "737-500",
    firstFlight: "1989-06-30",
    inService: "1990-02-28",
    role: "Short-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "94 ft 9 in (28.9 m)",
      length: "101 ft 9 in (31.0 m)",
      maxSpeed: "584 mph (939 km/h)",
      range: "2,235 mi (3,597 km)",
      ceiling: "37,000 ft (11,278 m)",
      engines: "2× CFM International CFM56-3C1 turbofan",
      crew: "2",
      capacity: "108–132 passengers",
    },
    description:
      "The 737-500 is the smallest member of the Classic 737 family, designed as a modern replacement for the original 737-200 with CFM56 engines and glass cockpit technology. It offered operators the efficiency benefits of the Classic series in a compact package suitable for thinner routes.",
    funFact:
      "The 737-500 was specifically designed to replace the -200 in fleets that needed the shorter fuselage, and it shares the same type rating as the -300 and -400, allowing airlines to use the same pilots across all three Classic variants — a significant cost advantage that Boeing marketed heavily.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing forward, flattened/oval nacelles",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "Oval/D-shaped engine nacelles",
        "Shortest Classic 737",
        "EFIS glass cockpit",
        "CFM56 engine shape distinguishes from 737-200",
        "No eyebrow windows",
      ],
    },
    aliases: ["737 Classic", "Seven-Thirty-Seven-Five-Hundred"],
  },
  {
    id: "boeing-737-600",
    name: "Boeing 737-600",
    manufacturer: "Boeing",
    type: "Narrow-body jet airliner",
    variant: "737-600",
    firstFlight: "1998-01-22",
    inService: "1998-09-18",
    role: "Short-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "112 ft 7 in (34.3 m)",
      length: "102 ft 6 in (31.2 m)",
      maxSpeed: "588 mph (946 km/h)",
      range: "3,235 mi (5,206 km)",
      ceiling: "41,000 ft (12,497 m)",
      engines: "2× CFM International CFM56-7B turbofan",
      crew: "2",
      capacity: "108–130 passengers",
    },
    description:
      "The 737-600 is the smallest member of the Next Generation (NG) 737 family, featuring a new larger wing, advanced avionics, and improved CFM56-7B engines. Despite its technical advances over the Classic series, it sold only 69 units — airlines preferred the larger NG variants.",
    funFact:
      "The 737-600 is the rarest commercial 737 ever sold, with only 69 delivered — making it harder to spot than a widebody on most routes. SAS (Scandinavian Airlines) was the primary operator, and the type is now largely retired, making a 737-600 sighting a genuine spotting prize.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing forward, oval nacelles, CFM56-7B",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Oval/D-shaped engine nacelles (slightly rounder than Classic)",
        "Larger wing than Classic 737s",
        "Blended winglets optional",
        "Advanced EFIS cockpit",
        "Shortest NG 737 fuselage",
      ],
    },
    aliases: ["737 NG", "737 Next Generation", "Seven-Thirty-Seven-Six-Hundred"],
  },
  {
    id: "boeing-737-700",
    name: "Boeing 737-700",
    manufacturer: "Boeing",
    type: "Narrow-body jet airliner",
    variant: "737-700",
    firstFlight: "1997-02-09",
    inService: "1998-01-13",
    role: "Short- to medium-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "112 ft 7 in (34.3 m)",
      length: "110 ft 4 in (33.6 m)",
      maxSpeed: "588 mph (946 km/h)",
      range: "3,365 mi (5,415 km)",
      ceiling: "41,000 ft (12,497 m)",
      engines: "2× CFM International CFM56-7B turbofan",
      crew: "2",
      capacity: "126–149 passengers",
    },
    description:
      "The 737-700 is the mid-size short-haul member of the Next Generation family, replacing the 737-300. It became famous as the primary aircraft of Southwest Airlines, the world's largest 737 operator, and is also the basis for the Boeing Business Jet (BBJ) corporate aircraft.",
    funFact:
      "Southwest Airlines has operated the 737-700 as its primary aircraft type and at one point operated the largest 737-700 fleet in the world. The aircraft's remarkable range for its size allowed Southwest to operate nonstop transcontinental flights — something originally considered impossible for a short-haul narrowbody.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing forward, oval nacelles",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Oval/D-shaped engine nacelles",
        "Blended winglets standard on most",
        "Larger wing visible vs Classic 737",
        "Advanced two-crew EFIS cockpit",
        "Shorter fuselage than -800",
      ],
    },
    aliases: ["737 NG", "737 Next Generation", "BBJ basis", "Seven-Thirty-Seven-Seven-Hundred"],
  },
  {
    id: "boeing-737-800",
    name: "Boeing 737-800",
    manufacturer: "Boeing",
    type: "Narrow-body jet airliner",
    variant: "737-800",
    firstFlight: "1998-07-31",
    inService: "1998-04-22",
    role: "Short- to medium-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "112 ft 7 in (34.3 m)",
      length: "129 ft 6 in (39.5 m)",
      maxSpeed: "588 mph (946 km/h)",
      range: "3,060 mi (4,925 km)",
      ceiling: "41,000 ft (12,497 m)",
      engines: "2× CFM International CFM56-7B27 turbofan",
      crew: "2",
      capacity: "162–189 passengers",
    },
    description:
      "The 737-800 is the most commercially successful variant of the Next Generation family and the best-selling 737 variant of all time, with over 4,900 delivered. A stretched version of the -700, it offers increased capacity on dense short- to medium-haul routes and is operated by virtually every major airline worldwide.",
    funFact:
      "The 737-800 is so ubiquitous that at any given moment there are estimated to be over 2,000 of them airborne simultaneously worldwide. It replaced the 757-200 on many routes and is considered the workhorse of modern commercial aviation — if you've flown in the past decade, you've almost certainly flown on one.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing forward, oval nacelles",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "Oval/D-shaped engine nacelles",
        "Blended winglets on most aircraft",
        "Longer fuselage than -700",
        "Two overwing emergency exits",
        "Advanced EFIS cockpit",
        "Tail skid under aft fuselage",
      ],
    },
    aliases: ["737 NG", "737 Next Generation", "Seven-Thirty-Seven-Eight-Hundred"],
  },
  {
    id: "boeing-737-900er",
    name: "Boeing 737-900ER",
    manufacturer: "Boeing",
    type: "Narrow-body jet airliner",
    variant: "737-900ER",
    firstFlight: "2006-08-01",
    inService: "2007-04-27",
    role: "Short- to medium-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "112 ft 7 in (34.3 m)",
      length: "138 ft 2 in (42.1 m)",
      maxSpeed: "588 mph (946 km/h)",
      range: "3,200 mi (5,150 km)",
      ceiling: "41,000 ft (12,497 m)",
      engines: "2× CFM International CFM56-7B27E turbofan",
      crew: "2",
      capacity: "177–215 passengers",
    },
    description:
      "The 737-900ER (Extended Range) is the longest and largest member of the Next Generation family, stretching the fuselage by 11 feet compared to the -800. The 'ER' designation refers to additional fuel tanks that extend range, along with structural improvements to handle the increased maximum takeoff weight.",
    funFact:
      "The 737-900ER added two extra emergency exit doors compared to the -900 (four overwing exits total) to meet evacuation requirements for the increased passenger load — making it one of the easiest variants to identify by counting exit door positions along the fuselage.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing forward, oval nacelles",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "Oval/D-shaped engine nacelles",
        "Longest NG 737 fuselage",
        "Four overwing emergency exit doors",
        "Blended winglets standard",
        "Tail skid visible under rear fuselage",
      ],
    },
    aliases: ["737-900ER", "737 NG", "Seven-Thirty-Seven-Nine-Hundred"],
  },
  {
    id: "boeing-737-max-8",
    name: "Boeing 737 MAX 8",
    manufacturer: "Boeing",
    type: "Narrow-body jet airliner",
    variant: "737 MAX 8",
    firstFlight: "2016-01-29",
    inService: "2017-05-22",
    role: "Short- to medium-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "117 ft 10 in (35.9 m)",
      length: "129 ft 8 in (39.5 m)",
      maxSpeed: "588 mph (946 km/h)",
      range: "3,550 mi (5,713 km)",
      ceiling: "41,000 ft (12,497 m)",
      engines: "2× CFM International LEAP-1B turbofan",
      crew: "2",
      capacity: "162–210 passengers",
    },
    description:
      "The 737 MAX 8 is the fourth generation of the 737 family, featuring CFM LEAP-1B engines, new split-tip 'scimitar' winglets, and updated avionics. It was grounded worldwide from March 2019 to November 2020 following two fatal crashes linked to the MCAS flight control system, representing the longest grounding of a commercial aircraft in history.",
    funFact:
      "To fit the larger LEAP-1B engines under the 737's famously low wing, Boeing moved the engines even further forward and higher — which changed the aircraft's flight characteristics enough to require the controversial MCAS (Maneuvering Characteristics Augmentation System) that played a role in the Lion Air and Ethiopian Airlines crashes.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing forward, larger round nacelles, LEAP engines",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "Split-tip scimitar winglets (distinctive dual-blade appearance)",
        "Larger rounder LEAP engine nacelles vs NG",
        "Engines mounted further forward than NG",
        "Redesigned sky interior",
        "Distinctive split winglet tips pointing up and down",
        "No oval nacelle cross-section — more circular",
      ],
    },
    aliases: ["737 MAX", "Seven-Thirty-Seven MAX Eight", "B38M"],
  },
  {
    id: "boeing-737-max-9",
    name: "Boeing 737 MAX 9",
    manufacturer: "Boeing",
    type: "Narrow-body jet airliner",
    variant: "737 MAX 9",
    firstFlight: "2017-04-13",
    inService: "2018-03-21",
    role: "Short- to medium-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "117 ft 10 in (35.9 m)",
      length: "138 ft 4 in (42.2 m)",
      maxSpeed: "588 mph (946 km/h)",
      range: "3,515 mi (5,657 km)",
      ceiling: "41,000 ft (12,497 m)",
      engines: "2× CFM International LEAP-1B turbofan",
      crew: "2",
      capacity: "178–220 passengers",
    },
    description:
      "The 737 MAX 9 is the stretched, higher-capacity member of the MAX family, corresponding to the 737-900ER in the NG series. It gained significant notoriety in January 2024 when an Alaska Airlines aircraft suffered an in-flight door plug blowout, triggering a temporary grounding and intense scrutiny of Boeing's manufacturing quality control.",
    funFact:
      "The January 2024 Alaska Airlines door plug blowout occurred when a plug covering an unused emergency exit door blew off at altitude — investigators found the bolts that should have secured it were missing. The aircraft's fuselage had a gaping hole at 16,000 feet, yet no passengers were seriously injured because the seats next to the opening happened to be unoccupied.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing forward, larger LEAP nacelles",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "Split-tip scimitar winglets",
        "Larger circular LEAP engine nacelles",
        "Longer fuselage than MAX 8",
        "Four overwing emergency exits",
        "Engines mounted high and forward",
      ],
    },
    aliases: ["737 MAX", "Seven-Thirty-Seven MAX Nine", "B39M"],
  },
  {
    id: "boeing-747-100",
    name: "Boeing 747-100",
    manufacturer: "Boeing",
    type: "Wide-body jet airliner",
    variant: "747-100",
    firstFlight: "1969-02-09",
    inService: "1970-01-22",
    role: "Long-range high-capacity commercial transport",
    country: "USA",
    specs: {
      wingspan: "195 ft 8 in (59.6 m)",
      length: "231 ft 10 in (70.7 m)",
      maxSpeed: "614 mph (988 km/h)",
      range: "5,300 mi (8,530 km)",
      ceiling: "45,100 ft (13,747 m)",
      engines: "4× Pratt & Whitney JT9D-7 turbofan",
      crew: "3",
      capacity: "366–452 passengers",
    },
    description:
      "The Boeing 747-100 was the world's first wide-body aircraft, revolutionary for its twin-aisle cabin that allowed mass air travel at scales previously unimaginable. Its iconic upper deck hump — housing the flight deck and originally a first-class lounge — became one of the most recognizable silhouettes in aviation history.",
    funFact:
      "The 747 was designed in just 28 months — an astonishing feat for an aircraft of its complexity. Boeing president Bill Allen bet the entire company on it, and the 747 factory in Everett, Washington remains the largest building by volume in the world. The original 747-100 hump was only a short bubble because Boeing expected airlines to use it for cargo nose-loading.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Four underwing podded engines, two per side",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "super-heavy",
      era: "cold-war",
      distinguishingFeatures: [
        "Short dorsal hump forward fuselage (upper deck forward only)",
        "Four underwing engines",
        "Twin-aisle wide body",
        "Distinctive raised cockpit above main deck",
        "10-abreast economy seating",
        "Massive fuselage cross-section",
      ],
    },
    aliases: ["Jumbo Jet", "Queen of the Skies", "Seven-Forty-Seven"],
  },
  {
    id: "boeing-747-200",
    name: "Boeing 747-200",
    manufacturer: "Boeing",
    type: "Wide-body jet airliner",
    variant: "747-200",
    firstFlight: "1971-10-11",
    inService: "1971-12-14",
    role: "Long-range high-capacity commercial transport",
    country: "USA",
    specs: {
      wingspan: "195 ft 8 in (59.6 m)",
      length: "231 ft 10 in (70.7 m)",
      maxSpeed: "614 mph (988 km/h)",
      range: "6,850 mi (11,023 km)",
      ceiling: "45,100 ft (13,747 m)",
      engines: "4× Pratt & Whitney JT9D-7R4G2 turbofan",
      crew: "3",
      capacity: "366–452 passengers",
    },
    description:
      "The 747-200 improved on the -100 with more powerful engines and increased range, making truly long nonstop intercontinental routes practical. It also spawned the 747-200F freighter and 747-200C combi variants, establishing the 747 as the backbone of global air cargo as well as passenger operations.",
    funFact:
      "One Air Force One aircraft, VC-25A (based on the 747-200), has been in continuous service since 1990. The famous blue-and-white livery was designed by industrial designer Raymond Loewy, who also designed Coca-Cola bottles and Lucky Strike cigarette packaging. He considered it one of his finest works.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Four underwing podded engines, two per side",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "super-heavy",
      era: "cold-war",
      distinguishingFeatures: [
        "Short dorsal hump (upper deck, forward section only)",
        "Four underwing engines",
        "Identical external silhouette to 747-100",
        "Raised cockpit above main deck",
        "10-abreast seating",
        "Large oval windows in upper deck",
      ],
    },
    aliases: ["Jumbo Jet", "Queen of the Skies", "747-200B"],
  },
  {
    id: "boeing-747-400",
    name: "Boeing 747-400",
    manufacturer: "Boeing",
    type: "Wide-body jet airliner",
    variant: "747-400",
    firstFlight: "1988-04-29",
    inService: "1989-02-09",
    role: "Long-range high-capacity commercial transport",
    country: "USA",
    specs: {
      wingspan: "211 ft 5 in (64.4 m)",
      length: "231 ft 10 in (70.7 m)",
      maxSpeed: "614 mph (988 km/h)",
      range: "8,430 mi (13,570 km)",
      ceiling: "45,100 ft (13,747 m)",
      engines: "4× CFM56-80C2 or Pratt & Whitney PW4000 or GE CF6 turbofan",
      crew: "2",
      capacity: "416–524 passengers",
    },
    description:
      "The 747-400 is the most successful and widely operated variant of the 747 family, featuring a stretched upper deck, new glass cockpit reducing crew from three to two, winglets, and composite materials. It dominated ultra-long-haul routes for two decades and was the first 747 to carry passengers nonstop from New York to Tokyo.",
    funFact:
      "The 747-400 has 171 miles (274 km) of wiring, 5 million parts from 1,500 suppliers in 33 states, and 6 million total parts. Its winglets are 6 feet tall and reduce fuel consumption by about 3%. Singapore Airlines operated the longest nonstop commercial route in history on a 747-400 before switching to the A340.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Four underwing podded engines, two per side",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "super-heavy",
      era: "modern",
      distinguishingFeatures: [
        "Stretched upper deck (longer hump than -100/-200)",
        "Upturned winglets at wingtips",
        "Four underwing engines",
        "Raised cockpit above main deck",
        "Two-crew glass cockpit",
        "Extended upper deck windows visible from outside",
      ],
    },
    aliases: ["Jumbo Jet", "Queen of the Skies", "747-400ER"],
  },
  {
    id: "boeing-747-8",
    name: "Boeing 747-8",
    manufacturer: "Boeing",
    type: "Wide-body jet airliner",
    variant: "747-8I",
    firstFlight: "2010-03-20",
    inService: "2012-06-01",
    role: "Long-range high-capacity commercial transport",
    country: "USA",
    specs: {
      wingspan: "224 ft 7 in (68.4 m)",
      length: "250 ft 2 in (76.3 m)",
      maxSpeed: "614 mph (988 km/h)",
      range: "8,000 mi (12,872 km)",
      ceiling: "43,100 ft (13,137 m)",
      engines: "4× General Electric GEnx-2B67 turbofan",
      crew: "2",
      capacity: "410–467 passengers",
    },
    description:
      "The 747-8 Intercontinental is the final and largest passenger variant of the 747 family, stretching the fuselage by 18.3 feet beyond the -400. It incorporates technology from the 787 Dreamliner including GEnx engines with serrated chevron nacelles, a new wing, and advanced avionics, making it the longest commercial aircraft ever built.",
    funFact:
      "The 747-8 is the longest commercial aircraft ever built, edging out the A340-600 by a few feet. Despite this distinction, it sold only 47 passenger units — one of Boeing's weakest commercial programs. Its freighter version (747-8F) sold much better, and Lufthansa was the only major airline to operate the passenger version in significant numbers.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Four underwing podded engines, two per side",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "super-heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "Stretched upper deck (longest hump of any 747)",
        "Serrated/chevron GEnx engine nacelles",
        "Raked wingtips (no upturned winglets, raked like 787)",
        "Longest fuselage of any commercial aircraft",
        "Four engines with GEnx distinctive nacelle shape",
        "New wing with different profile than -400",
      ],
    },
    aliases: ["747-8I", "747-8 Intercontinental", "Jumbo Jet"],
  },
  {
    id: "boeing-757-200",
    name: "Boeing 757-200",
    manufacturer: "Boeing",
    type: "Narrow-body jet airliner",
    variant: "757-200",
    firstFlight: "1982-02-19",
    inService: "1983-01-01",
    role: "Short- to medium-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "124 ft 10 in (38.1 m)",
      length: "155 ft 3 in (47.3 m)",
      maxSpeed: "614 mph (988 km/h)",
      range: "3,915 mi (6,300 km)",
      ceiling: "42,000 ft (12,802 m)",
      engines: "2× Rolls-Royce RB211 or Pratt & Whitney PW2000 turbofan",
      crew: "2",
      capacity: "200–239 passengers",
    },
    description:
      "The Boeing 757-200 is a narrow-body medium-range airliner known for its powerful engines, steep climb performance, and ability to operate from short, high-altitude, and hot-weather airports that challenge other aircraft. Its engines appear disproportionately large relative to its narrow fuselage, making it immediately recognizable.",
    funFact:
      "The 757 is famous for its powerful climb rate — pilots call it the 'rocket ship.' It was the aircraft of choice for ETOPS transatlantic operations from the US to Europe because its powerful engines allowed it to climb quickly above weather. It holds the record for the most passenger operations across the North Atlantic for a narrowbody aircraft.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, large engines proportionally large vs narrow fuselage",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "modern",
      distinguishingFeatures: [
        "Very large engines relative to narrow fuselage",
        "Long slender narrow-body fuselage",
        "Engines appear oversized for the aircraft",
        "Pointed nose similar to 737",
        "No winglets standard (though some retrofitted)",
        "Tall vertical stabilizer relative to fuselage",
      ],
    },
    aliases: ["Seven-Fifty-Seven", "Rocket Ship"],
  },
  {
    id: "boeing-757-300",
    name: "Boeing 757-300",
    manufacturer: "Boeing",
    type: "Narrow-body jet airliner",
    variant: "757-300",
    firstFlight: "1998-08-02",
    inService: "1999-03-19",
    role: "Short- to medium-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "124 ft 10 in (38.1 m)",
      length: "178 ft 7 in (54.4 m)",
      maxSpeed: "614 mph (988 km/h)",
      range: "3,395 mi (5,464 km)",
      ceiling: "42,000 ft (12,802 m)",
      engines: "2× Rolls-Royce RB211-535E4B or Pratt & Whitney PW2043 turbofan",
      crew: "2",
      capacity: "243–289 passengers",
    },
    description:
      "The 757-300 is the stretched version of the 757-200, extending the fuselage by 23 feet to become the longest single-aisle airliner ever built. Despite carrying nearly 300 passengers in a single-aisle cabin, it retained the same engines and wing, selling only 55 units due to difficult boarding logistics and passenger experience on a very long narrow fuselage.",
    funFact:
      "The 757-300 is so long that a tail strike is a real operational concern — pilots must use a very precise pitch attitude on rotation. It's the longest narrow-body aircraft ever put into production and remains the record holder for single-aisle fuselage length. Its length means it often cannot use standard jet bridges at many airports.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, proportionally large engines vs fuselage",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "Extremely long narrow-body fuselage",
        "Large engines look small on the longer airframe",
        "Tail skid under aft fuselage",
        "Longest single-aisle aircraft ever built",
        "Same wing/engines as -200 on much longer fuselage",
      ],
    },
    aliases: ["Seven-Fifty-Seven-Three-Hundred"],
  },
  {
    id: "boeing-767-200",
    name: "Boeing 767-200",
    manufacturer: "Boeing",
    type: "Wide-body jet airliner",
    variant: "767-200",
    firstFlight: "1981-09-26",
    inService: "1982-09-08",
    role: "Medium- to long-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "156 ft 1 in (47.6 m)",
      length: "159 ft 2 in (48.5 m)",
      maxSpeed: "593 mph (954 km/h)",
      range: "3,850 mi (6,195 km)",
      ceiling: "43,100 ft (13,137 m)",
      engines: "2× Pratt & Whitney JT9D or CF6 or PW4000 turbofan",
      crew: "2",
      capacity: "181–255 passengers",
    },
    description:
      "The Boeing 767-200 was Boeing's first twin-engine wide-body airliner, designed to replace the 707 on transatlantic and domestic trunk routes. It pioneered ETOPS (Extended-range Twin-engine Operational Performance Standards) operations, proving that twin-engine jets could safely cross oceans — transforming international aviation economics.",
    funFact:
      "The 767 was the first commercial aircraft to get ETOPS approval (in 1985), initially for 120 minutes from an alternate airport. This fundamentally changed aviation by allowing airlines to replace inefficient four-engine jets with cheaper twin-engine aircraft on long overwater routes — a change that eventually doomed the 747 on many routes.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, two engines",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "modern",
      distinguishingFeatures: [
        "Medium wide-body with two engines",
        "Twin-aisle cabin narrower than 747",
        "Shorter fuselage than later variants",
        "Distinctive narrow oval fuselage cross-section",
        "2-3-2 economy seating configuration",
        "No winglets (original)",
      ],
    },
    aliases: ["Seven-Sixty-Seven"],
  },
  {
    id: "boeing-767-300",
    name: "Boeing 767-300",
    manufacturer: "Boeing",
    type: "Wide-body jet airliner",
    variant: "767-300",
    firstFlight: "1986-01-30",
    inService: "1986-09-25",
    role: "Medium- to long-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "156 ft 1 in (47.6 m)",
      length: "180 ft 3 in (54.9 m)",
      maxSpeed: "593 mph (954 km/h)",
      range: "5,990 mi (9,640 km)",
      ceiling: "43,100 ft (13,137 m)",
      engines: "2× Pratt & Whitney PW4000 or GE CF6-80C2 turbofan",
      crew: "2",
      capacity: "218–269 passengers",
    },
    description:
      "The 767-300 is the stretched version of the 767-200, adding 21 feet of fuselage length and becoming the bestselling 767 passenger variant. It is extensively used for transatlantic routes and became the standard aircraft for medium-capacity intercontinental operations.",
    funFact:
      "The 767-300 is the aircraft that pioneered the twin-aisle transatlantic crossing on a large scale. Delta Air Lines and American Airlines used it to replace 747s on thinner transatlantic routes, proving that twin-engine aircraft could be as reliable as four-engine types. It also served as the basis for the KC-46 Pegasus military tanker.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, two engines",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "modern",
      distinguishingFeatures: [
        "Medium wide-body with two underwing engines",
        "Longer fuselage than -200",
        "Oval fuselage cross-section",
        "2-3-2 economy seating",
        "No winglets standard",
        "Twin-aisle cabin",
      ],
    },
    aliases: ["Seven-Sixty-Seven-Three-Hundred", "767-300ER"],
  },
  {
    id: "boeing-767-400er",
    name: "Boeing 767-400ER",
    manufacturer: "Boeing",
    type: "Wide-body jet airliner",
    variant: "767-400ER",
    firstFlight: "1999-10-09",
    inService: "2000-09-14",
    role: "Long-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "170 ft 4 in (51.9 m)",
      length: "201 ft 4 in (61.4 m)",
      maxSpeed: "593 mph (954 km/h)",
      range: "6,625 mi (10,662 km)",
      ceiling: "43,100 ft (13,137 m)",
      engines: "2× Pratt & Whitney PW4062 or GE CF6-80C2B8F turbofan",
      crew: "2",
      capacity: "245–375 passengers",
    },
    description:
      "The 767-400ER is the largest and longest-range variant of the 767 family, stretching the fuselage by 21 feet beyond the -300 and featuring a new wing with raked wingtips. It sold only 38 units — Delta and Continental were the exclusive operators — making it one of the rarest widebodies in commercial service.",
    funFact:
      "The 767-400ER introduced raked wingtips (a precursor technology to what would appear on the 787) rather than the traditional upturned winglets. Only Delta and Continental ordered it, and Continental's fleet was inherited by United after the merger — making United Airlines the world's sole operator of the type for many years.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, two engines",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "Raked wingtips (not upturned winglets)",
        "Longest 767 fuselage",
        "Medium wide-body",
        "Oval fuselage cross-section",
        "Two underwing engines",
        "2-3-2 seating configuration",
      ],
    },
    aliases: ["767-400", "Seven-Sixty-Seven-Four-Hundred"],
  },
  {
    id: "boeing-777-200",
    name: "Boeing 777-200",
    manufacturer: "Boeing",
    type: "Wide-body jet airliner",
    variant: "777-200",
    firstFlight: "1994-06-12",
    inService: "1995-06-07",
    role: "Long-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "199 ft 11 in (60.9 m)",
      length: "209 ft 1 in (63.7 m)",
      maxSpeed: "590 mph (950 km/h)",
      range: "5,235 mi (8,425 km)",
      ceiling: "43,100 ft (13,137 m)",
      engines: "2× GE90-77B, PW4077, or Trent 877 turbofan",
      crew: "2",
      capacity: "305–440 passengers",
    },
    description:
      "The Boeing 777-200 is the original variant of the 777 family and the world's largest twin-engine commercial aircraft when introduced. Famous for its massive GE90 engines, six-wheel bogie main landing gear, and fly-by-wire flight controls, the 777 set a new standard for long-haul twin-engine operations.",
    funFact:
      "The GE90 engine on the 777 holds the world record for highest thrust ever produced by a jet engine — 127,900 lbf. The engine's fan alone is nearly 10 feet in diameter. A single GE90 produces more thrust than all four engines on the early Boeing 707 combined.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, two very large engines",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "super-heavy",
      era: "modern",
      distinguishingFeatures: [
        "Enormous engines — largest turbofans on any twin",
        "Triple-axle main landing gear (6 wheels per bogie)",
        "Wide oval fuselage cross-section",
        "3-3-3 economy seating typical",
        "No winglets on base variants",
        "Very long fuselage relative to wing",
        "Distinctive round engine nacelles",
      ],
    },
    aliases: ["Triple Seven", "Seven-Seventy-Seven"],
  },
  {
    id: "boeing-777-200er",
    name: "Boeing 777-200ER",
    manufacturer: "Boeing",
    type: "Wide-body jet airliner",
    variant: "777-200ER",
    firstFlight: "1996-10-07",
    inService: "1997-02-06",
    role: "Ultra-long-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "199 ft 11 in (60.9 m)",
      length: "209 ft 1 in (63.7 m)",
      maxSpeed: "590 mph (950 km/h)",
      range: "7,725 mi (12,430 km)",
      ceiling: "43,100 ft (13,137 m)",
      engines: "2× GE90-90B, PW4090, or Trent 892 turbofan",
      crew: "2",
      capacity: "305–440 passengers",
    },
    description:
      "The 777-200ER (Extended Range) features additional fuel tanks and more powerful engines compared to the base -200, enabling nonstop ultra-long-haul routes that were previously impossible for a twin-engine jet. It became the bestselling initial 777 variant and the backbone of long-haul fleets worldwide.",
    funFact:
      "Malaysia Airlines Flight MH370 was a 777-200ER that disappeared on March 8, 2014, en route from Kuala Lumpur to Beijing. It remains the greatest aviation mystery of the modern era. Despite extensive searches, most of the aircraft has never been found, though debris washing up on Indian Ocean shores confirmed a general crash area years later.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, two very large engines",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "super-heavy",
      era: "modern",
      distinguishingFeatures: [
        "Enormous round engine nacelles",
        "Triple-axle main landing gear (6 wheels per bogie)",
        "Identical external appearance to base -200",
        "Wide-body oval fuselage",
        "3-3-3 economy seating",
        "No winglets",
      ],
    },
    aliases: ["Triple Seven ER", "777-200ER"],
  },
  {
    id: "boeing-777-300er",
    name: "Boeing 777-300ER",
    manufacturer: "Boeing",
    type: "Wide-body jet airliner",
    variant: "777-300ER",
    firstFlight: "2003-02-24",
    inService: "2004-05-29",
    role: "Ultra-long-range high-capacity commercial transport",
    country: "USA",
    specs: {
      wingspan: "212 ft 7 in (64.8 m)",
      length: "242 ft 4 in (73.9 m)",
      maxSpeed: "590 mph (950 km/h)",
      range: "7,370 mi (11,861 km)",
      ceiling: "43,100 ft (13,137 m)",
      engines: "2× General Electric GE90-115B turbofan",
      crew: "2",
      capacity: "365–396 passengers (typical 3-class)",
    },
    description:
      "The 777-300ER is the most commercially successful member of the 777 family and Boeing's most profitable aircraft program. Combining the stretched fuselage of the -300 with the range improvements of the -200ER, plus the world's most powerful commercial engines (GE90-115B), it dominates premium long-haul routes worldwide.",
    funFact:
      "The GE90-115B on the 777-300ER set the world thrust record at 127,900 lbf. Emirates operates the largest 777-300ER fleet in the world with over 130 aircraft, using it as the backbone of its global hub-and-spoke network out of Dubai. The aircraft's raked wingtips were a new feature distinguishing it from earlier 777s.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, two GE90-115B engines",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "super-heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "World's largest twin-engine airliner (until 777X)",
        "GE90-115B engines — largest turbofans ever built",
        "Triple-axle main landing gear (6 wheels per bogie)",
        "Raked wingtips (upturned rake, no vertical winglets)",
        "Longer fuselage than -200 variants",
        "3-3-3 economy seating standard",
        "Wide oval fuselage cross-section",
      ],
    },
    aliases: ["Triple Seven", "77W", "Seven-Seventy-Seven-Three-Hundred ER"],
  },
  {
    id: "boeing-777x",
    name: "Boeing 777X",
    manufacturer: "Boeing",
    type: "Wide-body jet airliner",
    variant: "777-9",
    firstFlight: "2020-01-25",
    inService: "Pending (2025 est.)",
    role: "Ultra-long-range high-capacity commercial transport",
    country: "USA",
    specs: {
      wingspan: "235 ft 5 in (71.8 m) extended / 212 ft 0 in (64.6 m) folded",
      length: "251 ft 9 in (76.7 m)",
      maxSpeed: "590 mph (950 km/h)",
      range: "7,285 mi (11,727 km)",
      ceiling: "43,100 ft (13,137 m)",
      engines: "2× General Electric GE9X-105B1A turbofan",
      crew: "2",
      capacity: "426 passengers (2-class)",
    },
    description:
      "The Boeing 777X is the next-generation evolution of the 777 family, featuring folding wingtips — a first for a commercial airliner — composite wings, new GE9X engines with the largest fan diameter of any commercial engine, and a redesigned cabin. Persistent certification delays have pushed entry into service years beyond original plans.",
    funFact:
      "The 777X has folding wingtips that fold upward by about 11 feet at each end, activated by electric motors, to fit within standard airport gate widths while providing the aerodynamic benefits of a much longer wingspan in flight. This feature was borrowed from naval carrier aircraft like the F/A-18 and marks the first use of folding wings on a commercial jetliner.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, two GE9X engines",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "super-heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "Folding wingtips (unique to any commercial airliner)",
        "GE9X engines with largest commercial fan diameter",
        "Composite wings",
        "Triple-axle main landing gear (6 wheels per bogie)",
        "Serrated/chevron GE9X engine nacelles",
        "Longer than 777-300ER",
        "Raked wingtip design when folded up",
      ],
    },
    aliases: ["777-9", "777X", "Triple Seven X"],
  },
  {
    id: "boeing-787-8",
    name: "Boeing 787-8 Dreamliner",
    manufacturer: "Boeing",
    type: "Wide-body jet airliner",
    variant: "787-8",
    firstFlight: "2009-12-15",
    inService: "2011-10-26",
    role: "Long-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "197 ft 0 in (60.1 m)",
      length: "186 ft 1 in (56.7 m)",
      maxSpeed: "593 mph (954 km/h)",
      range: "7,355 mi (11,838 km)",
      ceiling: "43,000 ft (13,106 m)",
      engines: "2× GE GEnx-1B or Rolls-Royce Trent 1000 turbofan",
      crew: "2",
      capacity: "242–335 passengers",
    },
    description:
      "The Boeing 787-8 Dreamliner is the original variant of Boeing's revolutionary composite-material airliner. With 50% of its structure made from carbon fiber reinforced polymer, it offers 20% better fuel efficiency than comparable aircraft. Its pressurized cabin at the equivalent of 6,000 feet altitude (vs 8,000 for older jets) reduces passenger fatigue.",
    funFact:
      "The 787's windows are 65% larger than those on comparable aircraft and use electrochromic dimmable technology — passengers can gradually darken them with a button rather than using a physical shade. The aircraft also uses electricity for systems that previously ran on bleed air from the engines, a major innovation that reduces fuel consumption.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, two engines with serrated nacelles",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "Serrated/chevron engine nacelle edges (noise reduction)",
        "Raked wingtips (smooth upward sweep, no vertical endplate)",
        "Swept cockpit windshield (distinctive angular shape)",
        "Smooth composite fuselage surface",
        "Engines appear highly integrated with nacelle chevrons",
        "No sharp fuselage joins — smooth blended composite skin",
        "2-3-2 seating typical",
      ],
    },
    aliases: ["Dreamliner", "787", "Seven-Eight-Seven"],
  },
  {
    id: "boeing-787-9",
    name: "Boeing 787-9 Dreamliner",
    manufacturer: "Boeing",
    type: "Wide-body jet airliner",
    variant: "787-9",
    firstFlight: "2013-09-17",
    inService: "2014-07-18",
    role: "Long-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "197 ft 0 in (60.1 m)",
      length: "206 ft 0 in (62.8 m)",
      maxSpeed: "593 mph (954 km/h)",
      range: "7,635 mi (12,288 km)",
      ceiling: "43,000 ft (13,106 m)",
      engines: "2× GE GEnx-1B76 or Rolls-Royce Trent 1000-G turbofan",
      crew: "2",
      capacity: "296 passengers (standard 3-class)",
    },
    description:
      "The 787-9 is the stretched, best-selling variant of the Dreamliner family, adding 20 feet of fuselage length and offering greater range than the -8. It became the preferred variant for airlines wanting to open new long-haul routes and was the first aircraft to fly nonstop from Perth to London (Qantas, 2018).",
    funFact:
      "Air New Zealand's 787-9 performed a high-speed low pass at the 2015 Paris Air Show in full Hobbit movie livery — one of the most dramatic airshow flybys in recent memory. The aircraft also holds the record for the longest nonstop commercial flights, with airlines like United and Qantas using it on ultra-long routes.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, two engines with serrated nacelles",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "Serrated/chevron engine nacelle edges",
        "Raked wingtips",
        "Swept cockpit windshield",
        "Longer fuselage than 787-8",
        "Smooth composite fuselage",
        "2-3-2 seating typical",
      ],
    },
    aliases: ["Dreamliner", "787", "Seven-Eight-Seven-Nine"],
  },
  {
    id: "boeing-787-10",
    name: "Boeing 787-10 Dreamliner",
    manufacturer: "Boeing",
    type: "Wide-body jet airliner",
    variant: "787-10",
    firstFlight: "2017-03-31",
    inService: "2018-03-25",
    role: "Long-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "197 ft 0 in (60.1 m)",
      length: "224 ft 0 in (68.3 m)",
      maxSpeed: "593 mph (954 km/h)",
      range: "6,430 mi (10,349 km)",
      ceiling: "43,000 ft (13,106 m)",
      engines: "2× GE GEnx-1B78 or Rolls-Royce Trent 1000-TEN turbofan",
      crew: "2",
      capacity: "330–440 passengers",
    },
    description:
      "The 787-10 is the largest and highest-capacity member of the Dreamliner family, stretching the fuselage by 18 feet beyond the -9. It offers exceptional seat-mile economics on medium- to long-haul routes and is intended to replace older widebodies on dense segments. Singapore Airlines was the launch customer.",
    funFact:
      "The 787-10 is so long that its full-length fuselage cannot be shipped in a single piece, requiring special structural assembly techniques. Despite being the least range-capable Dreamliner variant, it offers the best per-seat economics of the family — making it the choice for airlines serving dense routes where capacity matters more than ultra-long range.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, two engines with serrated nacelles",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "Serrated/chevron engine nacelle edges",
        "Raked wingtips",
        "Swept cockpit windshield",
        "Longest Dreamliner fuselage",
        "Smooth composite skin",
        "3-3-3 seating typical",
      ],
    },
    aliases: ["Dreamliner", "787-10", "Seven-Eight-Seven-Ten"],
  },
  {
    id: "boeing-747-400f",
    name: "Boeing 747-400F",
    manufacturer: "Boeing",
    type: "Wide-body cargo aircraft",
    variant: "747-400F",
    firstFlight: "1993-05-04",
    inService: "1993-11-17",
    role: "Long-range heavy cargo transport",
    country: "USA",
    specs: {
      wingspan: "211 ft 5 in (64.4 m)",
      length: "231 ft 10 in (70.7 m)",
      maxSpeed: "614 mph (988 km/h)",
      range: "4,450 mi (7,161 km) with full payload",
      ceiling: "45,100 ft (13,747 m)",
      engines: "4× GE CF6, PW4000, or RR RB211 turbofan",
      crew: "2",
      capacity: "112–116 tonnes payload",
    },
    description:
      "The 747-400F is the dedicated freighter variant of the 747-400, featuring a nose-loading cargo door that hinges upward to allow direct loading of oversized cargo onto the main deck. Without passenger windows or interior fittings, it is optimized purely for cargo, featuring the 747-400's improved engines and avionics in a pure-freight configuration.",
    funFact:
      "The 747F's nose door opens upward, allowing cargo to be driven directly onto the main deck — a design feature from the original 747 concept. UPS and FedEx operate some of the world's largest 747-400F fleets. The aircraft can carry virtually any cargo that fits through the nose, including other aircraft engines, helicopters, and oversized industrial equipment.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Four underwing podded engines, two per side",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "super-heavy",
      era: "modern",
      distinguishingFeatures: [
        "No passenger windows on fuselage",
        "Short upper deck hump (no extended passenger upper deck)",
        "Nose cargo door (hinges upward)",
        "Four underwing engines",
        "Upturned winglets",
        "Side cargo door visible on main deck",
      ],
    },
    aliases: ["747 Freighter", "747-400ERF", "Jumbo Freighter"],
  },
  {
    id: "boeing-767-300f",
    name: "Boeing 767-300F",
    manufacturer: "Boeing",
    type: "Wide-body cargo aircraft",
    variant: "767-300F",
    firstFlight: "1995-06-20",
    inService: "1995-10-19",
    role: "Medium- to long-range cargo transport",
    country: "USA",
    specs: {
      wingspan: "156 ft 1 in (47.6 m)",
      length: "180 ft 3 in (54.9 m)",
      maxSpeed: "593 mph (954 km/h)",
      range: "3,765 mi (6,058 km) with max payload",
      ceiling: "43,100 ft (13,137 m)",
      engines: "2× PW4000 or GE CF6-80C2 turbofan",
      crew: "2",
      capacity: "57.9 tonnes payload",
    },
    description:
      "The 767-300F is the freighter variant of the 767-300, featuring a large main deck cargo door and no passenger windows or interior. It has become a popular medium widebody freighter operated extensively by UPS, FedEx, and Amazon Air, and remains in production as one of Boeing's active programs.",
    funFact:
      "Amazon Air operates a large fleet of 767-300Fs — branded 'Amazon Air' — as the backbone of its own air cargo network, bypassing traditional express carriers. The aircraft helped Amazon achieve next-day delivery across much of the United States by controlling its own air freight capacity rather than relying entirely on FedEx or UPS.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, two engines",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "modern",
      distinguishingFeatures: [
        "No passenger windows on fuselage",
        "Large main deck cargo door on left forward fuselage",
        "Medium widebody profile",
        "Two underwing engines",
        "Blank fuselage sides",
        "Oval fuselage cross-section",
      ],
    },
    aliases: ["767 Freighter", "P-8 Poseidon base", "KC-46 Pegasus base"],
  },
  {
    id: "boeing-777f",
    name: "Boeing 777F",
    manufacturer: "Boeing",
    type: "Wide-body cargo aircraft",
    variant: "777F",
    firstFlight: "2008-07-14",
    inService: "2009-02-19",
    role: "Ultra-long-range heavy cargo transport",
    country: "USA",
    specs: {
      wingspan: "212 ft 7 in (64.8 m)",
      length: "209 ft 1 in (63.7 m)",
      maxSpeed: "590 mph (950 km/h)",
      range: "5,600 mi (9,012 km) with full payload",
      ceiling: "43,100 ft (13,137 m)",
      engines: "2× General Electric GE90-110B1L turbofan",
      crew: "2",
      capacity: "102.8 tonnes payload",
    },
    description:
      "The 777F is the freighter version of the 777-200LR, offering the range and capacity of a large twin-jet freighter. It features a nose-section main cargo door, no passenger cabin windows, and the same enormous GE90 engines as the passenger 777. Emirates SkyCargo and FedEx are major operators.",
    funFact:
      "The 777F can carry more cargo than any other twin-engine freighter in history, and its range allows nonstop transoceanic cargo flights that were previously only possible with four-engine aircraft. FedEx's 777F fleet handles its most critical intercontinental routes, effectively replacing 747 freighters on the highest-value cargo corridors.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Underwing, two GE90 engines",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "super-heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "No passenger windows",
        "Large main deck cargo door forward left fuselage",
        "Enormous GE90 engines",
        "Triple-axle main landing gear (6 wheels per bogie)",
        "Wide oval fuselage cross-section",
        "Raked wingtips",
      ],
    },
    aliases: ["Triple Seven Freighter", "777 Freighter"],
  },
  {
    id: "boeing-dreamlifter",
    name: "Boeing Dreamlifter",
    manufacturer: "Boeing",
    type: "Outsize cargo transport",
    variant: "747-400LCF",
    firstFlight: "2006-09-09",
    inService: "2007-01-31",
    role: "Oversize aircraft component transport",
    country: "USA",
    specs: {
      wingspan: "211 ft 5 in (64.4 m)",
      length: "235 ft 2 in (71.7 m)",
      maxSpeed: "608 mph (978 km/h)",
      range: "4,500 mi (7,240 km)",
      ceiling: "45,100 ft (13,747 m)",
      engines: "4× CF6-80C2B5F turbofan",
      crew: "2",
      capacity: "65,000 cu ft (1,840 m³) cargo volume — world's largest",
    },
    description:
      "The Boeing Dreamlifter (747-400LCF) is a heavily modified 747-400 with a massively enlarged upper fuselage bulge that makes it the largest cargo aircraft by volume in the world. Built exclusively to transport 787 Dreamliner components — wings, fuselage sections, tail sections — from suppliers around the world to Boeing's assembly plants.",
    funFact:
      "The Dreamlifter's cargo volume is so large that 787 wing sections — each over 100 feet long — are transported whole. The unique tail section swings open sideways on a hinge to load and unload cargo from the rear. In 2013, one Dreamlifter landed at the wrong airport in Wichita, Kansas, landing at a small regional airport instead of the larger McConnell Air Force Base — the aircraft barely fit and required special coordination to depart.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Four underwing podded engines, two per side",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "super-heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "Massively bulging upper fuselage blister/hump extending most of fuselage length",
        "Extremely wide upper fuselage — far wider than normal 747",
        "Tail swings to the right for rear loading",
        "Four underwing engines (747 base)",
        "No passenger windows",
        "Distinctive bloated profile unlike any other aircraft",
        "Original 747 dorsal hump replaced by enormous cargo bulge",
      ],
    },
    aliases: ["747-400LCF", "Large Cargo Freighter", "LCF"],
  },
  {
    id: "boeing-377-stratocruiser",
    name: "Boeing 377 Stratocruiser",
    manufacturer: "Boeing",
    type: "Long-range piston airliner",
    variant: "377",
    firstFlight: "1947-07-08",
    inService: "1949-04-01",
    role: "Long-range commercial transport",
    country: "USA",
    specs: {
      wingspan: "141 ft 3 in (43.1 m)",
      length: "110 ft 4 in (33.6 m)",
      maxSpeed: "375 mph (603 km/h)",
      range: "4,200 mi (6,759 km)",
      ceiling: "32,000 ft (9,754 m)",
      engines: "4× Pratt & Whitney R-4360 Wasp Major 28-cylinder radial",
      crew: "5",
      capacity: "55–117 passengers",
    },
    description:
      "The Boeing 377 Stratocruiser was a luxurious double-deck piston-engined airliner developed from the B-29 Superfortress and B-50 bomber. Featuring a lower-deck lounge bar that passengers could access via a circular staircase, it represented the pinnacle of luxury propeller air travel in the late 1940s and 1950s.",
    funFact:
      "The Stratocruiser's double-bubble fuselage cross-section — essentially two overlapping circles — made it one of the most distinctive looking aircraft of its era. Pan Am used them on transatlantic routes with a spiral staircase leading to the famous lower-deck cocktail lounge. The R-4360 Wasp Major engine had 28 cylinders arranged in four rows of seven and was the most powerful production piston aircraft engine ever built.",
    visual: {
      engineCount: 4,
      engineType: "piston",
      enginePlacement: "Underwing tractor, four piston radial engines",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "pre-wwii",
      distinguishingFeatures: [
        "Double-bubble fuselage cross-section",
        "Four large radial piston engines with prominent cowlings",
        "Upper and lower deck visible in fuselage shape",
        "Circular lower-deck lounge windows",
        "Propeller-driven — large paddle-blade propellers",
        "Rounded art-deco nose design",
        "Distinctive figure-eight fuselage cross-section",
      ],
    },
    aliases: ["Stratocruiser", "Three-Seventy-Seven", "Boeing 377"],
  },
];
