import { AircraftEntry } from "./types";

export const commercialAirbus: AircraftEntry[] = [
  {
    id: "airbus-a300",
    name: "A300",
    manufacturer: "Airbus",
    type: "Wide-body airliner",
    variant: "A300B4",
    firstFlight: "1972-10-28",
    inService: "1974",
    role: "Medium-to-long-range wide-body commercial transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "44.84 m (147 ft 1 in)",
      length: "54.08 m (177 ft 5 in)",
      maxSpeed: "Mach 0.82 (871 km/h; 541 mph)",
      range: "7,700 km (4,786 mi)",
      ceiling: "12,200 m (40,000 ft)",
      engines: "2 × GE CF6-80C2 or P&W JT9D turbofans",
      crew: "2–3",
      capacity: "266–361 passengers",
    },
    description:
      "The Airbus A300 was the world's first twin-engine wide-body airliner, launched as a joint European project to challenge American manufacturers. It introduced the concept that a wide-body aircraft didn't need four engines for transatlantic range, and pioneered many technologies that would define later Airbus designs. The A300 validated the twin-engine wide-body concept and gave Airbus its foothold in the commercial aviation market.",
    funFact:
      "The A300 was so revolutionary that when it first flew, most airlines were skeptical a twin-engine jet could carry that many passengers safely. Eastern Air Lines agreed to a six-month free trial in 1977 and liked it so much they ordered 23 aircraft.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "modern",
      distinguishingFeatures: [
        "First wide-body twin-engine airliner",
        "Distinctive large round engine nacelles under swept wings",
        "Classic Airbus nose profile",
        "Two-aisle wide-body cabin",
        "Six-abreast in business class",
      ],
    },
    aliases: ["A300B", "A300-600"],
  },
  {
    id: "airbus-a310",
    name: "A310",
    manufacturer: "Airbus",
    type: "Wide-body airliner",
    variant: "A310-300",
    firstFlight: "1982-04-03",
    inService: "1983",
    role: "Medium-range wide-body commercial transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "43.9 m (144 ft 0 in)",
      length: "46.66 m (153 ft 1 in)",
      maxSpeed: "Mach 0.84 (901 km/h; 560 mph)",
      range: "9,600 km (5,965 mi)",
      ceiling: "12,500 m (41,000 ft)",
      engines: "2 × GE CF6-80C2 or P&W JT9D-7R4 turbofans",
      crew: "2",
      capacity: "220–280 passengers",
    },
    description:
      "The A310 is a shortened, more efficient derivative of the A300, designed for thinner routes and optimized for medium-range operations. It introduced an advanced two-crew glass cockpit as standard and featured a refined wing for better aerodynamic efficiency. The A310 also pioneered the use of composite materials in primary aircraft structures at Airbus.",
    funFact:
      "The A310 was one of the first commercial jets certified for ETOPS (Extended-range Twin-engine Operational Performance Standards), allowing twin-engine airliners to fly transoceanic routes previously reserved for four-engine jets.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "modern",
      distinguishingFeatures: [
        "Shorter fuselage than A300",
        "Refined supercritical wing",
        "Advanced two-crew glass cockpit",
        "Wide-body twin-aisle cabin",
        "Slightly smaller than A300 but similar profile",
      ],
    },
    aliases: ["A310-200", "A310-300"],
  },
  {
    id: "airbus-a318",
    name: "A318",
    manufacturer: "Airbus",
    type: "Narrow-body airliner",
    variant: "A318-100",
    firstFlight: "2002-01-15",
    inService: "2003",
    role: "Short-to-medium-range narrow-body commercial transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "34.1 m (111 ft 10 in)",
      length: "31.44 m (103 ft 2 in)",
      maxSpeed: "Mach 0.82 (871 km/h; 541 mph)",
      range: "5,950 km (3,700 mi)",
      ceiling: "12,100 m (39,800 ft)",
      engines: "2 × CFM56-5B or P&W PW6000 turbofans",
      crew: "2",
      capacity: "107–132 passengers",
    },
    description:
      "The A318 is the smallest member of the A320 family, often called the 'Baby Bus.' It was designed for thin regional routes and smaller markets, sharing full commonality with other A320 family members. While commercially less successful than its siblings, the A318 proved useful for point-to-point routes where larger aircraft would be uneconomical.",
    funFact:
      "British Airways operated a special A318 'all-business class' service between London City Airport and New York JFK, carrying only 32 passengers in a fully flat-bed business class configuration. The aircraft had to stop in Shannon, Ireland to complete US customs before crossing the Atlantic.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Shortest A320 family member",
        "Round CFM56 engine nacelles",
        "Classic A320 family nose shape",
        "Stubby appearance compared to A320",
        "Single-aisle narrow-body cabin",
      ],
    },
    aliases: ["A318-100", "Baby Bus"],
  },
  {
    id: "airbus-a319",
    name: "A319",
    manufacturer: "Airbus",
    type: "Narrow-body airliner",
    variant: "A319-100",
    firstFlight: "1995-08-25",
    inService: "1996",
    role: "Short-to-medium-range narrow-body commercial transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "34.1 m (111 ft 10 in)",
      length: "33.84 m (111 ft 0 in)",
      maxSpeed: "Mach 0.82 (871 km/h; 541 mph)",
      range: "6,850 km (4,256 mi)",
      ceiling: "12,100 m (39,800 ft)",
      engines: "2 × CFM56-5B or IAE V2500 turbofans",
      crew: "2",
      capacity: "124–156 passengers",
    },
    description:
      "The A319 is a shortened version of the A320, offering the same operational characteristics with a smaller passenger capacity. It has proven popular with airlines operating on thinner routes and has also been adapted for VIP and corporate use as the ACJ319. Its range extension capability makes it suitable for thinner long-haul routes.",
    funFact:
      "The A319 holds the record for the longest non-stop flight by a single-aisle aircraft — an Air India A319 flew from Delhi to London, a distance of over 6,700 km, which was near the absolute limit of its range.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Slightly shorter than A320",
        "Round CFM56 or V2500 engine nacelles",
        "Classic A320 family nose and cockpit",
        "Single-aisle narrow-body cabin",
        "Wingtip fences (classic) or optional sharklets",
      ],
    },
    aliases: ["A319-100", "ACJ319"],
  },
  {
    id: "airbus-a320",
    name: "A320",
    manufacturer: "Airbus",
    type: "Narrow-body airliner",
    variant: "A320-200",
    firstFlight: "1987-02-22",
    inService: "1988",
    role: "Short-to-medium-range narrow-body commercial transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "35.8 m (117 ft 5 in)",
      length: "37.57 m (123 ft 3 in)",
      maxSpeed: "Mach 0.82 (871 km/h; 541 mph)",
      range: "6,150 km (3,821 mi)",
      ceiling: "12,100 m (39,800 ft)",
      engines: "2 × CFM56-5B or IAE V2500 turbofans",
      crew: "2",
      capacity: "150–186 passengers",
    },
    description:
      "The A320 revolutionized commercial aviation by introducing fly-by-wire flight controls and a glass cockpit to a narrow-body airliner. It was the first commercial jet to use digital fly-by-wire as a primary flight control system, replacing traditional cable-and-pulley controls. This technology allowed Airbus to create a family of aircraft with high commonality, reducing training and maintenance costs for airlines.",
    funFact:
      "The A320 was the first commercial airliner to use a sidestick controller instead of a conventional yoke, a concept borrowed from fighter aircraft. Pilots sit in a more ergonomic position and have a clear instrument panel view without a yoke in the way.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "First fly-by-wire narrow-body airliner",
        "Round CFM56 or V2500 nacelles",
        "Distinctive Airbus nose with drooped tip",
        "Wingtip fences on classic variant",
        "Single-aisle cabin with wider seats than 737",
      ],
    },
    aliases: ["A320-100", "A320-200", "A320ceo"],
  },
  {
    id: "airbus-a321",
    name: "A321",
    manufacturer: "Airbus",
    type: "Narrow-body airliner",
    variant: "A321-200",
    firstFlight: "1993-03-11",
    inService: "1994",
    role: "Short-to-medium-range narrow-body commercial transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "35.8 m (117 ft 5 in)",
      length: "44.51 m (146 ft 0 in)",
      maxSpeed: "Mach 0.82 (871 km/h; 541 mph)",
      range: "5,950 km (3,700 mi)",
      ceiling: "12,100 m (39,800 ft)",
      engines: "2 × CFM56-5B or IAE V2500 turbofans",
      crew: "2",
      capacity: "185–220 passengers",
    },
    description:
      "The A321 is the largest member of the original A320 family, stretched to carry more passengers on high-density routes. It maintains full pilot type-rating commonality with all other A320 family members. The A321 has become a workhorse of medium-haul operations and is the platform for the highly successful A321neo and A321XLR variants.",
    funFact:
      "The A321 shares exactly the same type rating as the A318, A319, and A320, meaning a pilot certified on one can fly all four with minimal additional training — an enormous advantage for airline scheduling and cost management.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "Longest original A320 family member",
        "Stretched fuselage with additional door pair",
        "Round CFM56 or V2500 nacelles",
        "Classic A320 family nose and cockpit",
        "Single-aisle cabin but stretched appearance",
      ],
    },
    aliases: ["A321-100", "A321-200", "A321ceo"],
  },
  {
    id: "airbus-a319neo",
    name: "A319neo",
    manufacturer: "Airbus",
    type: "Narrow-body airliner",
    variant: "A319neo",
    firstFlight: "2017-03-31",
    inService: "2018",
    role: "Short-to-medium-range narrow-body commercial transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "35.8 m (117 ft 5 in) with sharklets",
      length: "33.84 m (111 ft 0 in)",
      maxSpeed: "Mach 0.82 (871 km/h; 541 mph)",
      range: "6,850 km (4,256 mi)",
      ceiling: "12,100 m (39,800 ft)",
      engines: "2 × CFM LEAP-1A or P&W PW1100G turbofans",
      crew: "2",
      capacity: "120–160 passengers",
    },
    description:
      "The A319neo (New Engine Option) is the re-engined variant of the A319, featuring more fuel-efficient turbofan engines and distinctive large sharklet winglet tips. It delivers approximately 15–20% better fuel efficiency compared to the A319ceo. The neo family uses either the CFM LEAP-1A or Pratt & Whitney PW1100G geared turbofan engines.",
    funFact:
      "The PW1100G engine used on the A320neo family features a geared turbofan architecture where the fan rotates at a different speed than the low-pressure turbine, dramatically improving fuel efficiency — the gear ratio is about 3:1, allowing both to operate at their optimal speeds.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Large distinctive sharklet winglet tips",
        "Larger diameter engine nacelles than ceo",
        "CFM LEAP or PW1100G engines with chevron nozzles",
        "Classic A320 family nose shape",
        "Slightly shorter than A320neo",
      ],
    },
    aliases: ["A319 NEO", "A319 New Engine Option"],
  },
  {
    id: "airbus-a320neo",
    name: "A320neo",
    manufacturer: "Airbus",
    type: "Narrow-body airliner",
    variant: "A320neo",
    firstFlight: "2014-09-25",
    inService: "2016",
    role: "Short-to-medium-range narrow-body commercial transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "35.8 m (117 ft 5 in) with sharklets",
      length: "37.57 m (123 ft 3 in)",
      maxSpeed: "Mach 0.82 (871 km/h; 541 mph)",
      range: "6,300 km (3,915 mi)",
      ceiling: "12,100 m (39,800 ft)",
      engines: "2 × CFM LEAP-1A or P&W PW1100G turbofans",
      crew: "2",
      capacity: "150–194 passengers",
    },
    description:
      "The A320neo is the re-engined evolution of the world's best-selling single-aisle airliner, delivering a generational leap in fuel efficiency. With new-generation CFM LEAP or Pratt & Whitney geared turbofan engines and large sharklet winglets, it achieves 15–20% better fuel burn than its predecessor. The A320neo family became the fastest-selling commercial aircraft in history.",
    funFact:
      "The A320neo received more than 1,000 orders before it even flew — airlines were so confident in the technology and Airbus's track record that they committed billions of dollars to aircraft that didn't yet exist. It remains one of the most ordered aircraft in aviation history.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Large sharklet winglet tips (signature feature)",
        "Larger diameter nacelles than ceo variant",
        "CFM LEAP or PW GTF engines visible forward nacelle shape difference",
        "Classic A320 nose and cockpit profile",
        "Single-aisle narrow-body silhouette",
      ],
    },
    aliases: ["A320 NEO", "A320 New Engine Option"],
  },
  {
    id: "airbus-a321neo",
    name: "A321neo",
    manufacturer: "Airbus",
    type: "Narrow-body airliner",
    variant: "A321neo",
    firstFlight: "2016-11-09",
    inService: "2017",
    role: "Medium-to-long-range narrow-body commercial transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "35.8 m (117 ft 5 in) with sharklets",
      length: "44.51 m (146 ft 0 in)",
      maxSpeed: "Mach 0.82 (871 km/h; 541 mph)",
      range: "7,400 km (4,600 mi)",
      ceiling: "12,100 m (39,800 ft)",
      engines: "2 × CFM LEAP-1A or P&W PW1100G turbofans",
      crew: "2",
      capacity: "180–244 passengers",
    },
    description:
      "The A321neo is the stretched neo variant and has become one of the most transformative aircraft in commercial aviation. Its combination of size, efficiency, and range is enabling airlines to open new point-to-point routes that were previously only possible with wide-body jets. The A321neo is the platform for the revolutionary A321XLR and has effectively created a new category of long-range narrow-body operations.",
    funFact:
      "The A321neo can fly transatlantic routes — JetBlue launched daily service between New York and London using the A321neo, a route that would previously have required a wide-body aircraft. This opened up transatlantic travel to low-cost carriers for the first time.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "Large sharklet winglet tips",
        "Longest A320 neo family member",
        "Larger diameter LEAP or PW1100G nacelles",
        "Stretched fuselage with multiple door pairs",
        "Single-aisle but visually long and slender",
      ],
    },
    aliases: ["A321 NEO", "A321 New Engine Option"],
  },
  {
    id: "airbus-a321xlr",
    name: "A321XLR",
    manufacturer: "Airbus",
    type: "Narrow-body airliner",
    variant: "A321XLR",
    firstFlight: "2023-06-18",
    inService: "2024",
    role: "Long-range narrow-body commercial transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "35.8 m (117 ft 5 in) with sharklets",
      length: "44.51 m (146 ft 0 in)",
      maxSpeed: "Mach 0.82 (871 km/h; 541 mph)",
      range: "8,700 km (5,400 mi)",
      ceiling: "12,100 m (39,800 ft)",
      engines: "2 × CFM LEAP-1A or P&W PW1100G turbofans",
      crew: "2",
      capacity: "180–220 passengers",
    },
    description:
      "The A321XLR (Extra Long Range) is the most advanced variant of the A320 family, featuring a new rear center fuel tank that is integral to the fuselage structure rather than a supplemental add-on. This allows significantly more fuel capacity and thus range, enabling single-aisle operations on routes spanning up to 8,700 km. The XLR represents a fundamental change in how airlines can connect city pairs without wide-body economics.",
    funFact:
      "The A321XLR's new Rear Center Tank (RCT) required a novel structural certification approach from EASA — it's the first fuel tank of its type in a commercial narrow-body aircraft that is integral to the fuselage, rather than a removable auxiliary tank.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "Large sharklet winglet tips",
        "Externally very similar to A321neo",
        "New rear center tank (internal, not visible)",
        "Slightly updated landing gear fairings",
        "Longest-range single-aisle Airbus aircraft",
      ],
    },
    aliases: ["A321 XLR", "A321 Extra Long Range"],
  },
  {
    id: "airbus-a330-200",
    name: "A330-200",
    manufacturer: "Airbus",
    type: "Wide-body airliner",
    variant: "A330-200",
    firstFlight: "1997-08-13",
    inService: "1998",
    role: "Long-range wide-body commercial transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "60.3 m (197 ft 10 in)",
      length: "58.82 m (193 ft 0 in)",
      maxSpeed: "Mach 0.86 (913 km/h; 567 mph)",
      range: "13,450 km (8,355 mi)",
      ceiling: "12,500 m (41,000 ft)",
      engines: "2 × GE CF6-80E1, P&W PW4000, or RR Trent 700 turbofans",
      crew: "2",
      capacity: "210–406 passengers",
    },
    description:
      "The A330-200 is the shorter, longer-range variant of the A330 family. It trades some passenger capacity for significantly increased range, making it popular for thinner long-haul routes. It shares a common type rating with the A330-300 and many systems with the A340, offering airlines significant operational flexibility. The -200 has also been widely used as a freighter and for tanker conversions.",
    funFact:
      "Air Transat Flight 236 in 2001 ran out of fuel over the Atlantic due to a fuel leak and the crew managed to glide the A330-200 for 19 minutes, landing safely in the Azores. The incident led to improved fuel monitoring procedures and highlighted the A330's remarkable glide capabilities.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "Twin-engine wide-body (visually similar to A340 but only 2 engines)",
        "Shorter fuselage than A330-300",
        "Large Rolls-Royce Trent or GE/PW equivalent nacelles",
        "Wide-body twin-aisle silhouette",
        "Drooped wingtips (no winglets on classic)",
      ],
    },
    aliases: ["A330-200", "A332"],
  },
  {
    id: "airbus-a330-300",
    name: "A330-300",
    manufacturer: "Airbus",
    type: "Wide-body airliner",
    variant: "A330-300",
    firstFlight: "1992-11-02",
    inService: "1994",
    role: "Medium-to-long-range wide-body commercial transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "60.3 m (197 ft 10 in)",
      length: "63.69 m (208 ft 11 in)",
      maxSpeed: "Mach 0.86 (913 km/h; 567 mph)",
      range: "11,750 km (7,300 mi)",
      ceiling: "12,500 m (41,000 ft)",
      engines: "2 × GE CF6-80E1, P&W PW4000, or RR Trent 700 turbofans",
      crew: "2",
      capacity: "277–440 passengers",
    },
    description:
      "The A330-300 is the original and longer variant of the A330 family, offering high-capacity medium-to-long-range operations. Sharing its wing, cockpit, and systems architecture with the four-engine A340, the A330-300 proved that a twin-engine aircraft could efficiently serve the same role at lower operating costs. It became a major workhorse for airlines worldwide on medium-haul and long-haul routes.",
    funFact:
      "The A330 and A340 were developed simultaneously with a near-identical airframe — the only fundamental difference is the number of engines. This allowed Airbus to offer airlines a choice between twin and quad variants while minimizing development costs, a remarkably efficient design strategy.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "Twin-engine wide-body",
        "Longer fuselage than A330-200",
        "Large engine nacelles on swept wings",
        "Classic Airbus wide-body profile",
        "Twin-aisle cabin with 2-4-2 or 2-3-2 seating",
      ],
    },
    aliases: ["A330-300", "A333"],
  },
  {
    id: "airbus-a330-800neo",
    name: "A330-800neo",
    manufacturer: "Airbus",
    type: "Wide-body airliner",
    variant: "A330-800neo",
    firstFlight: "2018-11-06",
    inService: "2020",
    role: "Long-range wide-body commercial transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "64 m (209 ft 11 in) with new sharklets",
      length: "58.82 m (193 ft 0 in)",
      maxSpeed: "Mach 0.86 (913 km/h; 567 mph)",
      range: "15,090 km (9,375 mi)",
      ceiling: "12,500 m (41,000 ft)",
      engines: "2 × Rolls-Royce Trent 7000 turbofans",
      crew: "2",
      capacity: "220–406 passengers",
    },
    description:
      "The A330-800neo is the re-engined evolution of the A330-200, featuring Rolls-Royce Trent 7000 engines and a new aerodynamic package including sharklet winglets. It offers significantly improved fuel efficiency over the classic A330 and brings the airframe's economics closer to newer designs. The -800neo provides exceptional ultra-long-range capabilities for a mid-size wide-body.",
    funFact:
      "The A330-800neo set a world record for the longest flight by a twin-aisle commercial aircraft at the time of its certification test, flying non-stop from Toulouse to Mauritius and back — a journey of over 15,000 km each way — to demonstrate its extreme range capability.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "New large sharklet winglets (distinguishes from ceo)",
        "Trent 7000 engine nacelles",
        "Shorter fuselage than A330-900neo",
        "Updated A350-style cabin features",
        "Wide-body twin-aisle profile",
      ],
    },
    aliases: ["A330-800", "A338neo"],
  },
  {
    id: "airbus-a330-900neo",
    name: "A330-900neo",
    manufacturer: "Airbus",
    type: "Wide-body airliner",
    variant: "A330-900neo",
    firstFlight: "2017-10-19",
    inService: "2018",
    role: "Long-range wide-body commercial transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "64 m (209 ft 11 in) with new sharklets",
      length: "63.66 m (208 ft 10 in)",
      maxSpeed: "Mach 0.86 (913 km/h; 567 mph)",
      range: "13,334 km (8,287 mi)",
      ceiling: "12,500 m (41,000 ft)",
      engines: "2 × Rolls-Royce Trent 7000 turbofans",
      crew: "2",
      capacity: "260–440 passengers",
    },
    description:
      "The A330-900neo is the re-engined evolution of the A330-300 and the most popular of the two neo variants. It combines efficient Rolls-Royce Trent 7000 engines with aerodynamic improvements and a modern A350-inspired cabin, delivering a substantial improvement in fuel efficiency and passenger comfort over the classic A330-300. It has become popular as a cost-effective alternative to larger wide-bodies.",
    funFact:
      "The A330neo features the 'Airspace' cabin developed for the A350, featuring larger overhead bins, improved lighting, and better air quality — airlines can refresh their passenger experience without the cost of a completely new aircraft type.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "Distinctive large sharklet winglets",
        "Trent 7000 nacelles (larger than classic A330)",
        "Longer fuselage than A330-800neo",
        "Chevron exhaust nozzles on Trent 7000",
        "Updated nose and exterior similar to A350",
      ],
    },
    aliases: ["A330-900", "A339neo"],
  },
  {
    id: "airbus-a340-200",
    name: "A340-200",
    manufacturer: "Airbus",
    type: "Wide-body airliner",
    variant: "A340-200",
    firstFlight: "1992-04-01",
    inService: "1993",
    role: "Ultra-long-range wide-body commercial transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "60.3 m (197 ft 10 in)",
      length: "59.39 m (194 ft 10 in)",
      maxSpeed: "Mach 0.86 (913 km/h; 567 mph)",
      range: "15,000 km (9,321 mi)",
      ceiling: "12,500 m (41,000 ft)",
      engines: "4 × CFM56-5C or IAE V2500 turbofans",
      crew: "2",
      capacity: "239–303 passengers",
    },
    description:
      "The A340-200 is the shorter, ultra-long-range variant of the original A340, optimized for maximum range over capacity. It was designed to fly the world's thinnest ultra-long routes and was one of the first commercial jets capable of non-stop intercontinental operations in the early 1990s before ETOPS regulations matured. The -200 variant sacrificed passenger capacity for extraordinary range.",
    funFact:
      "South African Airways operated A340-200s on the world's longest commercial flights of the era, including Johannesburg to New York non-stop — a journey of over 15 hours that was only possible because of the A340's exceptional range.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded (4 engines)",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "Four engines under swept wing (key distinction from A330)",
        "Shorter fuselage than A340-300",
        "Long slender fuselage",
        "Small CFM56 or IAE nacelles (4 total)",
        "Additional centerline landing gear bogie",
      ],
    },
    aliases: ["A340-200", "A342"],
  },
  {
    id: "airbus-a340-300",
    name: "A340-300",
    manufacturer: "Airbus",
    type: "Wide-body airliner",
    variant: "A340-300",
    firstFlight: "1991-10-25",
    inService: "1993",
    role: "Long-range wide-body commercial transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "60.3 m (197 ft 10 in)",
      length: "63.69 m (208 ft 11 in)",
      maxSpeed: "Mach 0.86 (913 km/h; 567 mph)",
      range: "13,500 km (8,390 mi)",
      ceiling: "12,500 m (41,000 ft)",
      engines: "4 × CFM56-5C turbofans",
      crew: "2",
      capacity: "295–440 passengers",
    },
    description:
      "The A340-300 was the original and more commercially successful variant of the A340 family, sharing its airframe with the A330-300 but fitted with four engines to meet long-range ETOPS-exempt route requirements. Before ETOPS rules matured, airlines operating routes over oceans or remote areas required four-engine aircraft, and the A340 filled this role with better economics than the Boeing 747.",
    funFact:
      "The A340-300 was designed to counter the Boeing 747-400 on long-haul routes, but at a smaller capacity. Lufthansa was the launch customer and used A340-300s to open routes to remote destinations in Asia and Africa where the 747 would have been too large.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded (4 engines)",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "Four engines, identical airframe to A330-300",
        "Small CFM56 nacelles in pairs under each wing",
        "Long slender fuselage",
        "Classic Airbus wide-body nose profile",
        "Additional center landing gear",
      ],
    },
    aliases: ["A340-300", "A343"],
  },
  {
    id: "airbus-a340-500",
    name: "A340-500",
    manufacturer: "Airbus",
    type: "Wide-body airliner",
    variant: "A340-500",
    firstFlight: "2002-02-11",
    inService: "2003",
    role: "Ultra-long-range wide-body commercial transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "63.45 m (208 ft 2 in)",
      length: "67.93 m (222 ft 10 in)",
      maxSpeed: "Mach 0.86 (913 km/h; 567 mph)",
      range: "16,670 km (10,354 mi)",
      ceiling: "12,500 m (41,000 ft)",
      engines: "4 × Rolls-Royce Trent 553 turbofans",
      crew: "2",
      capacity: "293–372 passengers",
    },
    description:
      "The A340-500 was the ultra-long-range stretched variant of the A340, designed to fly non-stop between virtually any two points on the globe. It was the world's longest commercial aircraft when launched and held the record for the world's longest non-stop commercial flight when Singapore Airlines operated it on the Singapore–New York route. Its extreme range came at the cost of a relatively small passenger capacity for a four-engine wide-body.",
    funFact:
      "Singapore Airlines operated the world's longest commercial flight on the A340-500, flying non-stop from Singapore to Newark, New Jersey — a distance of 15,345 km taking nearly 19 hours. The route was ultimately cancelled because it was uneconomical, but it demonstrated the aircraft's extraordinary capability.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded (4 engines)",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "Four Trent 553 engines, noticeably larger nacelles than -300",
        "Very long stretched fuselage",
        "Extended wingspan with winglets",
        "Three landing gear bogies under fuselage",
        "One of the longest commercial airframes ever built",
      ],
    },
    aliases: ["A340-500", "A345"],
  },
  {
    id: "airbus-a340-600",
    name: "A340-600",
    manufacturer: "Airbus",
    type: "Wide-body airliner",
    variant: "A340-600",
    firstFlight: "2001-04-23",
    inService: "2002",
    role: "Long-range high-capacity wide-body commercial transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "63.45 m (208 ft 2 in)",
      length: "75.36 m (247 ft 3 in)",
      maxSpeed: "Mach 0.86 (913 km/h; 567 mph)",
      range: "14,630 km (9,090 mi)",
      ceiling: "12,500 m (41,000 ft)",
      engines: "4 × Rolls-Royce Trent 556 turbofans",
      crew: "2",
      capacity: "380–475 passengers",
    },
    description:
      "The A340-600 is the stretched, high-capacity version of the A340 and was the world's longest commercial aircraft for several years. Designed to compete directly with the Boeing 747-400 on high-density long-haul routes, it offered four-engine reliability with improved economics. The -600 features a distinctive stretched fuselage that extends well behind the trailing edge of the wing.",
    funFact:
      "At 75.36 m, the A340-600 held the title of world's longest commercial aircraft until the Boeing 747-8 and Airbus A350-1000 exceeded it. Its fuselage is so long that at higher angles of attack on takeoff, special runway markings are needed to ensure the tail doesn't strike the ground.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded (4 engines)",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "super-heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "Extremely long fuselage (world record holder)",
        "Four Trent 556 engines with large nacelles",
        "Extended wingspan with winglets",
        "Body length extends far behind wing trailing edge",
        "Multiple fuselage landing gear bogies",
      ],
    },
    aliases: ["A340-600", "A346"],
  },
  {
    id: "airbus-a350-900",
    name: "A350-900",
    manufacturer: "Airbus",
    type: "Wide-body airliner",
    variant: "A350-900",
    firstFlight: "2013-06-14",
    inService: "2015",
    role: "Long-range wide-body commercial transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "64.75 m (212 ft 5 in)",
      length: "66.89 m (219 ft 6 in)",
      maxSpeed: "Mach 0.89 (945 km/h; 587 mph)",
      range: "15,000 km (9,320 mi)",
      ceiling: "13,100 m (43,100 ft)",
      engines: "2 × Rolls-Royce Trent XWB-84 turbofans",
      crew: "2",
      capacity: "314–440 passengers",
    },
    description:
      "The A350-900 is Airbus's most advanced wide-body aircraft, featuring a fuselage constructed primarily of carbon fiber reinforced polymer (CFRP) composites. It introduced a visually distinctive curved cockpit window frame and larger cabin windows compared to previous Airbus jets. The A350 represents a clean-sheet design optimized for aerodynamic efficiency, advanced materials, and passenger comfort.",
    funFact:
      "Over 70% of the A350's airframe by weight is made from advanced materials — 53% CFRP composites, 14% titanium, and 6% steel. This extensive use of composites makes it one of the lightest aircraft in its class relative to its size, significantly reducing fuel consumption.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "Curved cockpit window frames (distinctive vs other jets)",
        "Dark grey composite fuselage sheen",
        "Larger cabin windows than other wide-bodies",
        "Raked wingtips (curved upward winglets)",
        "Trent XWB engine nacelles with chevron nozzles",
        "Composite-heavy construction visible in matte skin texture",
      ],
    },
    aliases: ["A350-900", "A359", "A350 XWB"],
  },
  {
    id: "airbus-a350-1000",
    name: "A350-1000",
    manufacturer: "Airbus",
    type: "Wide-body airliner",
    variant: "A350-1000",
    firstFlight: "2016-11-24",
    inService: "2018",
    role: "Ultra-long-range high-capacity wide-body commercial transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "64.75 m (212 ft 5 in)",
      length: "73.79 m (242 ft 0 in)",
      maxSpeed: "Mach 0.89 (945 km/h; 587 mph)",
      range: "16,100 km (10,000 mi)",
      ceiling: "13,100 m (43,100 ft)",
      engines: "2 × Rolls-Royce Trent XWB-97 turbofans",
      crew: "2",
      capacity: "369–480 passengers",
    },
    description:
      "The A350-1000 is the stretched, higher-capacity variant of the A350 family, targeting routes previously dominated by the Boeing 777. It features more powerful Trent XWB-97 engines and a strengthened airframe to handle the increased weight and stress. The A350-1000 is capable of operating the world's longest commercial routes while carrying a full payload, and has been selected by several airlines for ultra-long-haul non-stop service.",
    funFact:
      "Qantas selected the A350-1000 for its 'Project Sunrise' initiative to operate non-stop flights from Sydney and Melbourne to London and New York — approximately 19–20 hour flights covering over 17,000 km, which will be the world's longest commercial flights when launched.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "super-heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "Curved cockpit window frames (same as -900)",
        "Longer fuselage than A350-900",
        "Larger Trent XWB-97 nacelles",
        "Dark composite fuselage appearance",
        "Raked curved wingtips",
        "Six-wheel main landing gear bogies (vs four-wheel on -900)",
      ],
    },
    aliases: ["A350-1000", "A35K", "A350 XWB-1000"],
  },
  {
    id: "airbus-a380",
    name: "A380",
    manufacturer: "Airbus",
    type: "Wide-body airliner",
    variant: "A380-800",
    firstFlight: "2005-04-27",
    inService: "2007",
    role: "Ultra-high-capacity long-range wide-body commercial transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "79.75 m (261 ft 8 in)",
      length: "72.72 m (238 ft 7 in)",
      maxSpeed: "Mach 0.89 (945 km/h; 587 mph)",
      range: "15,200 km (9,445 mi)",
      ceiling: "13,100 m (43,000 ft)",
      engines: "4 × Engine Alliance GP7200 or Rolls-Royce Trent 970/972 turbofans",
      crew: "2",
      capacity: "555–853 passengers",
    },
    description:
      "The A380 is the world's largest commercial passenger aircraft and the only full-length double-deck airliner ever built for airline service. It was designed to challenge the Boeing 747's dominance on ultra-high-capacity hub-to-hub routes and introduced unprecedented levels of passenger space, noise reduction, and fuel efficiency per seat. The A380 features two complete passenger decks running the full length of the fuselage.",
    funFact:
      "The A380 has 320 km of wiring, 40,000 connectors, and weighs 277,000 kg empty. Its four engines produce a total of about 310,000 lbs of thrust. Emirates alone operates over 100 A380s and has used the aircraft to redefine long-haul luxury travel.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded (4 engines)",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "super-heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "Full-length double deck fuselage (unique feature)",
        "Extremely wide oval cross-section fuselage",
        "Four massive turbofan engines",
        "Characteristic hump profile from nose to tail",
        "Very large wing with winglets",
        "Upper deck windows visible along full fuselage length",
        "Largest commercial aircraft ever built",
      ],
    },
    aliases: ["A380-800", "A388", "Superjumbo"],
  },
  {
    id: "airbus-a330-200f",
    name: "A330-200F",
    manufacturer: "Airbus",
    type: "Wide-body freighter",
    variant: "A330-200F",
    firstFlight: "2009-11-05",
    inService: "2010",
    role: "Long-range wide-body cargo transport",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "60.3 m (197 ft 10 in)",
      length: "58.82 m (193 ft 0 in)",
      maxSpeed: "Mach 0.86 (913 km/h; 567 mph)",
      range: "7,400 km (4,600 mi) with max payload",
      ceiling: "12,500 m (41,000 ft)",
      engines: "2 × GE CF6-80E1 or P&W PW4000 turbofans",
      crew: "2",
      capacity: "Max payload: 70,000 kg (154,000 lb)",
    },
    description:
      "The A330-200F is a dedicated freighter variant of the A330-200, featuring a main-deck cargo door and reinforced floor. Unlike converted passenger aircraft, the -200F was designed from the outset as a freighter with a unique forward fuselage that allows greater volume on the main deck. It features a characteristic nose-high ground attitude thanks to a modified undercarriage design.",
    funFact:
      "The A330-200F has a distinctive nose-high ground stance when loaded — the forward fuselage is actually lower than a standard A330 to facilitate loading, giving it a unique raked appearance on the ground that is quite different from the passenger variant.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "Large main-deck cargo door on port side",
        "No passenger windows on fuselage",
        "Distinctive nose-high ground angle",
        "Blank fuselage sides without window cutouts",
        "Twin-engine wide-body freighter profile",
      ],
    },
    aliases: ["A330F", "A330-200 Freighter"],
  },
  {
    id: "airbus-beluga",
    name: "Airbus Beluga",
    manufacturer: "Airbus",
    type: "Outsize cargo transport",
    variant: "A300-600ST",
    firstFlight: "1994-09-13",
    inService: "1995",
    role: "Oversize component transport (Airbus aircraft sections)",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "44.84 m (147 ft 1 in)",
      length: "56.16 m (184 ft 3 in)",
      maxSpeed: "Mach 0.7 (750 km/h; 466 mph)",
      range: "1,666 km (1,035 mi) with max payload",
      ceiling: "10,700 m (35,000 ft)",
      engines: "2 × GE CF6-80C2A8 turbofans",
      crew: "2 + loadmaster",
      capacity: "Max payload: 47,000 kg (103,600 lb)",
    },
    description:
      "The Airbus Beluga (officially A300-600ST, Super Transporter) is one of the most visually striking aircraft ever built, featuring a massive bulbous upper fuselage cargo hold grafted onto the lower fuselage of an A300-600. It was developed to transport large aircraft sections (wings, fuselage sections) between Airbus manufacturing facilities across Europe, replacing the older Super Guppy aircraft. The Beluga's enormous 37.7 m³ cargo hold can accommodate complete aircraft wings.",
    funFact:
      "The Beluga looks like a cartoon whale or a flying white beluga whale, which is how it got its nickname. The cargo hold is so large that it could theoretically fit a complete A320 fuselage section inside it. The aircraft has inspired an almost cult-like following among aviation enthusiasts.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "Massive bulbous upper fuselage cargo hold (unmistakable)",
        "Whale-like profile from the side",
        "Normal A300 lower fuselage with balloon-like top",
        "Large upward-opening cargo door at front",
        "Cockpit lowered below the cargo floor level",
        "White livery with painted 'smile' on nose",
      ],
    },
    aliases: ["A300-600ST", "Super Transporter", "Beluga", "Super Guppy successor"],
  },
  {
    id: "airbus-belugaxl",
    name: "BelugaXL",
    manufacturer: "Airbus",
    type: "Outsize cargo transport",
    variant: "A330-743L",
    firstFlight: "2018-07-19",
    inService: "2020",
    role: "Oversize component transport (Airbus aircraft sections)",
    country: "France / Germany / UK / Spain",
    specs: {
      wingspan: "60.3 m (197 ft 10 in)",
      length: "63.1 m (207 ft 0 in)",
      maxSpeed: "Mach 0.69 (737 km/h; 458 mph)",
      range: "4,000 km (2,485 mi) with max payload",
      ceiling: "11,000 m (35,800 ft)",
      engines: "2 × Rolls-Royce Trent 700 turbofans",
      crew: "2 + loadmaster",
      capacity: "Max payload: 51,000 kg (112,400 lb)",
    },
    description:
      "The BelugaXL is the successor to the original Beluga, built on the A330-200 airframe to handle even larger aircraft sections as Airbus's production rates increased. It is even more dramatically whale-like in appearance than its predecessor, featuring an even larger and rounder upper fuselage cargo hold. The BelugaXL is decorated with a distinctive painted 'smile' face on its nose, making it one of the most whimsical-looking commercial aircraft ever operated.",
    funFact:
      "The BelugaXL's cargo hold volume is 30% larger than the original Beluga, allowing it to transport two A350 wings simultaneously instead of one. The fleet is operated by Airbus Transport International and flies between Airbus facilities in Germany, France, Spain, and the UK daily.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Under-wing podded",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "super-heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "Even larger and rounder bulbous upper fuselage than Beluga",
        "A330-based lower airframe (longer than original Beluga)",
        "Distinctive painted whale smile face on nose (iconic livery)",
        "Massive upward-opening cargo door at front",
        "Cockpit well below cargo floor level",
        "Whale-like silhouette more pronounced than A300-based Beluga",
        "Trent 700 engines (larger than original Beluga's CF6)",
      ],
    },
    aliases: ["Beluga XL", "A330-743L", "Super Transporter XL"],
  },
];
