import { AircraftEntry } from "./types";

export const generalAviation: AircraftEntry[] = [
  // ============================================================
  // CESSNA
  // ============================================================
  {
    id: "cessna-150",
    name: "Cessna 150",
    manufacturer: "Cessna",
    type: "Piston Single",
    firstFlight: "1957",
    inService: "1958",
    role: "Trainer / Personal",
    country: "USA",
    specs: {
      wingspan: "33 ft 4 in (10.2 m)",
      length: "23 ft 11 in (7.3 m)",
      maxSpeed: "122 kt (226 km/h)",
      range: "350 nm (648 km)",
      ceiling: "14,000 ft (4,267 m)",
      engines: "1× Continental O-200-A, 100 hp",
      crew: "1",
      capacity: "1 passenger",
    },
    description:
      "The Cessna 150 is one of the most produced light aircraft in history, with over 23,000 built. Designed as an affordable two-seat trainer, its high-wing configuration and docile handling characteristics made it the default choice for flight schools worldwide through the 1960s and 1970s.",
    funFact:
      "More pilots have learned to fly in a Cessna 150 than in any other aircraft type, earning it the nickname 'the universal trainer.'",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "high-wing strut-braced",
        "side-by-side seating",
        "small narrow fuselage",
        "fixed tricycle gear",
        "swept vertical tail",
        "overhead fuel selector",
      ],
    },
    aliases: ["C150", "150", "Cessna one-fifty"],
  },
  {
    id: "cessna-152",
    name: "Cessna 152",
    manufacturer: "Cessna",
    type: "Piston Single",
    firstFlight: "1977",
    inService: "1978",
    role: "Trainer / Personal",
    country: "USA",
    specs: {
      wingspan: "33 ft 2 in (10.1 m)",
      length: "24 ft 1 in (7.3 m)",
      maxSpeed: "123 kt (228 km/h)",
      range: "415 nm (768 km)",
      ceiling: "14,700 ft (4,480 m)",
      engines: "1× Lycoming O-235-L2C, 110 hp",
      crew: "1",
      capacity: "1 passenger",
    },
    description:
      "The Cessna 152 is the direct successor to the 150, featuring a more powerful and fuel-efficient Lycoming engine. It became the definitive two-seat trainer of the 1980s and remains popular in flight schools today due to its availability, simplicity, and low operating cost.",
    funFact:
      "The 152 was modified to run on 100LL avgas instead of the 80-octane fuel the 150 preferred — a change driven by the global phaseout of leaded 80-octane fuel.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "high-wing strut-braced",
        "side-by-side two seats",
        "fixed tricycle gear",
        "swept vertical tail",
        "larger fin compared to C150",
        "small oval windows",
      ],
    },
    aliases: ["C152", "152", "Cessna one-fifty-two"],
  },
  {
    id: "cessna-172-skyhawk",
    name: "Cessna 172 Skyhawk",
    manufacturer: "Cessna",
    type: "Piston Single",
    firstFlight: "1955",
    inService: "1956",
    role: "Trainer / Personal / Tour",
    country: "USA",
    specs: {
      wingspan: "36 ft 1 in (11.0 m)",
      length: "27 ft 2 in (8.3 m)",
      maxSpeed: "124 kt (230 km/h)",
      range: "640 nm (1,185 km)",
      ceiling: "14,000 ft (4,267 m)",
      engines: "1× Lycoming IO-360-L2A, 180 hp",
      crew: "1",
      capacity: "3 passengers",
    },
    description:
      "The Cessna 172 Skyhawk is the best-selling aircraft in history, with over 44,000 produced since 1956. A four-seat, high-wing single-engine aircraft, it is the de-facto standard for primary flight training globally and is renowned for its forgiving handling, utility, and longevity.",
    funFact:
      "A Cessna 172 holds the world flight endurance record — it stayed airborne for 64 days, 22 hours, 19 minutes, and 5 seconds in 1958–1959, refueling in flight from a moving vehicle.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "high-wing strut-braced",
        "four seats",
        "fixed tricycle gear",
        "large rear windows",
        "swept vertical tail",
        "distinctive nose cowl",
      ],
    },
    aliases: ["C172", "172", "Skyhawk", "Cessna one-seventy-two"],
  },
  {
    id: "cessna-177-cardinal",
    name: "Cessna 177 Cardinal",
    manufacturer: "Cessna",
    type: "Piston Single",
    firstFlight: "1966",
    inService: "1968",
    role: "Personal / Touring",
    country: "USA",
    specs: {
      wingspan: "35 ft 6 in (10.8 m)",
      length: "27 ft 3 in (8.3 m)",
      maxSpeed: "135 kt (250 km/h)",
      range: "700 nm (1,296 km)",
      ceiling: "14,600 ft (4,450 m)",
      engines: "1× Lycoming IO-360-A1B6D, 180 hp",
      crew: "1",
      capacity: "3 passengers",
    },
    description:
      "The Cessna 177 Cardinal was Cessna's attempt to modernize the 172 with a cantilever (unstruted) high wing, a roomier cabin, and a more stylish appearance. Although it did not surpass the 172 in sales, it earned a devoted following for its cleaner aerodynamics and improved visibility.",
    funFact:
      "The Cardinal was originally marketed as the '172 replacement,' but Cessna kept producing both — the Cardinal was discontinued in 1978 while the 172 continues to this day.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "cantilever high wing (no struts)",
        "large wraparound windows",
        "four seats",
        "fixed tricycle gear",
        "wider cabin than 172",
        "forward-hinged doors",
      ],
    },
    aliases: ["C177", "177", "Cardinal"],
  },
  {
    id: "cessna-182-skylane",
    name: "Cessna 182 Skylane",
    manufacturer: "Cessna",
    type: "Piston Single",
    firstFlight: "1956",
    inService: "1956",
    role: "Personal / Touring",
    country: "USA",
    specs: {
      wingspan: "36 ft 0 in (11.0 m)",
      length: "28 ft 11 in (8.8 m)",
      maxSpeed: "145 kt (268 km/h)",
      range: "915 nm (1,694 km)",
      ceiling: "18,100 ft (5,518 m)",
      engines: "1× Lycoming IO-540-AB1A5, 230 hp",
      crew: "1",
      capacity: "3 passengers",
    },
    description:
      "The Cessna 182 Skylane is a step up from the 172, offering more power, payload, and altitude capability. It features a fixed tricycle gear and a strut-braced high wing, making it a workhorse for personal travel, aerial photography, and light cargo operations.",
    funFact:
      "The turbocharged T182 variant can cruise comfortably at 20,000 feet, giving pilots the ability to fly over most weather systems in the continental United States.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "high-wing strut-braced",
        "four seats",
        "fixed tricycle gear",
        "larger engine cowl than 172",
        "swept vertical tail",
        "optional turbocharged variant",
      ],
    },
    aliases: ["C182", "182", "Skylane", "Cessna one-eighty-two"],
  },
  {
    id: "cessna-206-stationair",
    name: "Cessna 206 Stationair",
    manufacturer: "Cessna",
    type: "Piston Single",
    firstFlight: "1962",
    inService: "1964",
    role: "Utility / Cargo / Bush",
    country: "USA",
    specs: {
      wingspan: "36 ft 0 in (11.0 m)",
      length: "28 ft 3 in (8.6 m)",
      maxSpeed: "153 kt (283 km/h)",
      range: "740 nm (1,370 km)",
      ceiling: "15,700 ft (4,785 m)",
      engines: "1× Continental IO-550-F, 300 hp",
      crew: "1",
      capacity: "5 passengers",
    },
    description:
      "The Cessna 206 Stationair is the most capable single-engine piston aircraft in the Cessna lineup. Its wide fuselage, large cargo door, and 300 hp engine make it a favorite for bush operations, parachute jumping, aerial survey, and air taxi service in remote areas.",
    funFact:
      "The 206 is the only single-engine Cessna certified with a cargo door wide enough to load a stretcher, making it popular in medevac and remote medical transport roles.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "high-wing strut-braced",
        "wide utility cabin",
        "large rear cargo/passenger door",
        "fixed tricycle gear",
        "six seats",
        "optional floats or tundra tires",
      ],
    },
    aliases: ["C206", "206", "Stationair", "U206", "TU206"],
  },
  {
    id: "cessna-210-centurion",
    name: "Cessna 210 Centurion",
    manufacturer: "Cessna",
    type: "Piston Single",
    firstFlight: "1957",
    inService: "1960",
    role: "Personal / High-performance Touring",
    country: "USA",
    specs: {
      wingspan: "36 ft 9 in (11.2 m)",
      length: "28 ft 2 in (8.6 m)",
      maxSpeed: "185 kt (343 km/h)",
      range: "924 nm (1,712 km)",
      ceiling: "17,300 ft (5,273 m)",
      engines: "1× Continental TSIO-520-R, 310 hp",
      crew: "1",
      capacity: "5 passengers",
    },
    description:
      "The Cessna 210 Centurion is a high-performance retractable-gear single-engine aircraft offering speed and range comparable to twin-engine aircraft. Its cantilever high wing (no struts) and retractable gear give it a clean aerodynamic profile and impressive cruise performance.",
    funFact:
      "The turbocharged and pressurized P210 Silver Eagle variant can cruise at 23,000 feet — higher than most non-pressurized piston aircraft — making it unique in the general aviation world.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "cantilever high wing (no struts)",
        "retractable tricycle gear",
        "six seats",
        "large cowl for big engine",
        "optional pressurization",
        "turbocharged variants",
      ],
    },
    aliases: ["C210", "210", "Centurion", "P210"],
  },
  {
    id: "cessna-208-caravan",
    name: "Cessna 208 Caravan",
    manufacturer: "Cessna",
    type: "Turboprop Single",
    firstFlight: "1982",
    inService: "1984",
    role: "Utility / Cargo / Air Taxi",
    country: "USA",
    specs: {
      wingspan: "52 ft 1 in (15.9 m)",
      length: "37 ft 7 in (11.5 m)",
      maxSpeed: "186 kt (344 km/h)",
      range: "1,070 nm (1,982 km)",
      ceiling: "25,000 ft (7,620 m)",
      engines: "1× Pratt & Whitney Canada PT6A-114A, 675 shp",
      crew: "1",
      capacity: "9 passengers",
    },
    description:
      "The Cessna 208 Caravan is a rugged single-engine turboprop utility aircraft used worldwide for cargo, passenger transport, medevac, and skydiving. Its PT6A engine, large cargo pod option, and ability to operate from unprepared strips make it the backbone of bush and regional air transport.",
    funFact:
      "FedEx is the largest operator of Cessna Caravans, using a dedicated cargo variant (208B Super Cargomaster) to handle overnight package delivery to small communities across North America.",
    visual: {
      engineCount: 1,
      engineType: "turboprop",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "high-wing strut-braced",
        "large PT6A turboprop",
        "optional belly cargo pod",
        "fixed tricycle gear with large tires",
        "single turboprop with five-blade prop",
        "wide cabin door",
      ],
    },
    aliases: ["C208", "208", "Caravan", "Cargomaster"],
  },
  {
    id: "cessna-208b-grand-caravan",
    name: "Cessna 208B Grand Caravan",
    manufacturer: "Cessna",
    type: "Turboprop Single",
    firstFlight: "1986",
    inService: "1986",
    role: "Utility / Cargo / Regional Air Taxi",
    country: "USA",
    specs: {
      wingspan: "52 ft 1 in (15.9 m)",
      length: "41 ft 7 in (12.7 m)",
      maxSpeed: "175 kt (324 km/h)",
      range: "1,240 nm (2,296 km)",
      ceiling: "25,000 ft (7,620 m)",
      engines: "1× Pratt & Whitney Canada PT6A-114A, 675 shp",
      crew: "1",
      capacity: "13 passengers",
    },
    description:
      "The Cessna 208B Grand Caravan is a stretched version of the 208 Caravan with a lengthened fuselage accommodating up to 14 occupants. It is widely used as a regional airliner, cargo hauler, and float-equipped bush plane, and serves as a platform for turbine transition training.",
    funFact:
      "The Grand Caravan EX variant with the PT6A-140 engine produces 867 shp, making it one of the most powerful single-engine turboprops certified for single-pilot IFR operations.",
    visual: {
      engineCount: 1,
      engineType: "turboprop",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "high-wing strut-braced",
        "stretched fuselage vs 208",
        "large PT6A turboprop",
        "optional belly cargo pod",
        "fixed tricycle gear",
        "regional airliner interior option",
      ],
    },
    aliases: ["208B", "Grand Caravan", "Caravan EX", "Super Cargomaster"],
  },

  // ============================================================
  // PIPER
  // ============================================================
  {
    id: "piper-j3-cub",
    name: "Piper J-3 Cub",
    manufacturer: "Piper",
    type: "Piston Single",
    firstFlight: "1937",
    inService: "1938",
    role: "Trainer / Personal / Taildragger",
    country: "USA",
    specs: {
      wingspan: "35 ft 3 in (10.7 m)",
      length: "22 ft 4 in (6.8 m)",
      maxSpeed: "76 kt (141 km/h)",
      range: "191 nm (354 km)",
      ceiling: "11,500 ft (3,505 m)",
      engines: "1× Continental A-65, 65 hp",
      crew: "1",
      capacity: "1 passenger",
    },
    description:
      "The Piper J-3 Cub is one of the most iconic light aircraft ever built, famous for its simple construction, docile handling, and brilliant yellow paint scheme. Over 19,000 were produced, and it served as the primary trainer for U.S. military pilots during World War II under the designation L-4 Grasshopper.",
    funFact:
      "The J-3 Cub became so associated with 'Cub Yellow' paint that Piper trademarked the color — the specific shade of chrome yellow has become synonymous with the aircraft worldwide.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "taildragger",
      sizeClass: "light",
      era: "pre-wwii",
      distinguishingFeatures: [
        "high-wing strut-braced",
        "classic Cub Yellow color",
        "tandem seating",
        "taildragger gear",
        "fabric-covered tube-and-fabric construction",
        "large windows for visibility",
        "very small engine cowl",
      ],
    },
    aliases: ["J3", "Cub", "J-3", "L-4 Grasshopper"],
  },
  {
    id: "piper-pa18-super-cub",
    name: "Piper PA-18 Super Cub",
    manufacturer: "Piper",
    type: "Piston Single",
    firstFlight: "1949",
    inService: "1950",
    role: "Bush / STOL / Trainer",
    country: "USA",
    specs: {
      wingspan: "35 ft 3 in (10.7 m)",
      length: "22 ft 7 in (6.9 m)",
      maxSpeed: "115 kt (213 km/h)",
      range: "460 nm (852 km)",
      ceiling: "19,000 ft (5,791 m)",
      engines: "1× Lycoming O-360-C1G, 150 hp",
      crew: "1",
      capacity: "1 passenger",
    },
    description:
      "The Piper PA-18 Super Cub is the more powerful evolution of the J-3 Cub, designed for rough-field and mountain operations. With up to 150 hp and outstanding STOL performance, it remains a favorite of bush pilots, backcountry fliers, and agricultural operators worldwide.",
    funFact:
      "The Super Cub was produced for over 45 years (1949–1994) with remarkably few changes, a testament to how well the original design was refined. Clone manufacturers still build new examples today.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "taildragger",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "high-wing strut-braced",
        "tandem seating",
        "taildragger gear",
        "large tundra tire option",
        "fabric-covered construction",
        "excellent STOL performance",
        "optional floats",
      ],
    },
    aliases: ["PA-18", "Super Cub", "PA18"],
  },
  {
    id: "piper-pa28-cherokee",
    name: "Piper PA-28 Cherokee",
    manufacturer: "Piper",
    type: "Piston Single",
    firstFlight: "1960",
    inService: "1961",
    role: "Trainer / Personal",
    country: "USA",
    specs: {
      wingspan: "35 ft 5 in (10.8 m)",
      length: "23 ft 9 in (7.2 m)",
      maxSpeed: "127 kt (235 km/h)",
      range: "465 nm (861 km)",
      ceiling: "14,100 ft (4,298 m)",
      engines: "1× Lycoming O-320-E3D, 150 hp",
      crew: "1",
      capacity: "3 passengers",
    },
    description:
      "The Piper PA-28 Cherokee is a family of four-seat, low-wing, single-engine aircraft that became Piper's primary competitor to the Cessna 172. Known for its 'Hershey bar' rectangular wing and straightforward handling, it has trained generations of pilots and remains prevalent in flight schools.",
    funFact:
      "The PA-28 family has spawned over a dozen variants including the Arrow, Warrior, Archer, Pathfinder, and Dakota — making it one of the most prolifically varied aircraft families in general aviation history.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "low-wing",
        "rectangular 'Hershey bar' wing",
        "four seats",
        "fixed tricycle gear",
        "rounded nose cowl",
        "single door on right side",
      ],
    },
    aliases: ["PA-28", "Cherokee", "Warrior", "Archer"],
  },
  {
    id: "piper-pa28r-arrow",
    name: "Piper PA-28R Arrow",
    manufacturer: "Piper",
    type: "Piston Single",
    firstFlight: "1966",
    inService: "1967",
    role: "Personal / Complex Trainer",
    country: "USA",
    specs: {
      wingspan: "35 ft 5 in (10.8 m)",
      length: "24 ft 0 in (7.3 m)",
      maxSpeed: "156 kt (289 km/h)",
      range: "928 nm (1,719 km)",
      ceiling: "16,600 ft (5,060 m)",
      engines: "1× Lycoming IO-360-C1C, 200 hp",
      crew: "1",
      capacity: "3 passengers",
    },
    description:
      "The Piper PA-28R Arrow is a retractable-gear variant of the Cherokee family, widely used for complex aircraft training and personal touring. Its automatic gear extension system — which lowers the gear when airspeed decreases below a threshold — was designed to prevent gear-up landings.",
    funFact:
      "The Arrow's automatic gear extension system was so reliable it became a teaching crutch — pilots transitioning from the Arrow to other retractable aircraft sometimes forgot to lower the gear manually because they had always relied on the automatic system.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "low-wing",
        "retractable tricycle gear",
        "four seats",
        "tapered wing on later models",
        "automatic gear extension system",
        "constant-speed propeller",
      ],
    },
    aliases: ["PA-28R", "Arrow", "Cherokee Arrow", "Turbo Arrow"],
  },
  {
    id: "piper-pa32-cherokee-six",
    name: "Piper PA-32 Cherokee Six / Lance",
    manufacturer: "Piper",
    type: "Piston Single",
    firstFlight: "1963",
    inService: "1965",
    role: "Personal / Utility / Air Taxi",
    country: "USA",
    specs: {
      wingspan: "32 ft 9 in (9.98 m)",
      length: "27 ft 9 in (8.5 m)",
      maxSpeed: "163 kt (302 km/h)",
      range: "900 nm (1,667 km)",
      ceiling: "16,650 ft (5,075 m)",
      engines: "1× Lycoming IO-540-K1G5D, 300 hp",
      crew: "1",
      capacity: "5 passengers",
    },
    description:
      "The Piper PA-32 is a stretched, six-place version of the Cherokee family featuring a wide cabin and large cargo door. The Cherokee Six uses fixed gear while the Lance variant features retractable gear, giving pilots a choice between simplicity and performance.",
    funFact:
      "The PA-32 Saratoga variant added a tapered semi-tapered wing and became so popular that Piper kept it in production into the 2000s, long after most of the Cherokee family was discontinued.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "low-wing",
        "six seats",
        "wide cabin",
        "large aft baggage door",
        "fixed or retractable gear depending on variant",
        "long fuselage",
      ],
    },
    aliases: ["PA-32", "Cherokee Six", "Lance", "Saratoga"],
  },
  {
    id: "piper-pa34-seneca",
    name: "Piper PA-34 Seneca",
    manufacturer: "Piper",
    type: "Piston Twin",
    firstFlight: "1969",
    inService: "1972",
    role: "Multi-engine Trainer / Personal",
    country: "USA",
    specs: {
      wingspan: "38 ft 11 in (11.9 m)",
      length: "28 ft 7 in (8.7 m)",
      maxSpeed: "196 kt (363 km/h)",
      range: "820 nm (1,519 km)",
      ceiling: "25,000 ft (7,620 m)",
      engines: "2× Continental TSIO-360-KB, 220 hp each (turbocharged)",
      crew: "1",
      capacity: "5 passengers",
    },
    description:
      "The Piper PA-34 Seneca is a twin-engine light aircraft derived from the PA-32 Cherokee Six. It is the most popular multi-engine trainer in the world, used by flight schools on every continent for multi-engine rating training. Its counter-rotating engines eliminate the critical engine problem.",
    funFact:
      "The Seneca V's counter-rotating engines (left engine rotates clockwise, right counterclockwise) means there is no 'critical engine' — a feature borrowed from large airliners that greatly simplifies engine-out training.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "wing-mounted tractor (counter-rotating)",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "low-wing twin",
        "two wing-mounted engines",
        "retractable tricycle gear",
        "six seats",
        "counter-rotating propellers on later models",
        "turbocharged variants",
      ],
    },
    aliases: ["PA-34", "Seneca"],
  },
  {
    id: "piper-pa44-seminole",
    name: "Piper PA-44 Seminole",
    manufacturer: "Piper",
    type: "Piston Twin",
    firstFlight: "1976",
    inService: "1978",
    role: "Multi-engine Trainer",
    country: "USA",
    specs: {
      wingspan: "38 ft 7 in (11.8 m)",
      length: "27 ft 7 in (8.4 m)",
      maxSpeed: "168 kt (311 km/h)",
      range: "851 nm (1,576 km)",
      ceiling: "15,000 ft (4,572 m)",
      engines: "2× Lycoming O-360-E1A6D, 180 hp each (counter-rotating)",
      crew: "1",
      capacity: "3 passengers",
    },
    description:
      "The Piper PA-44 Seminole is a T-tail twin-engine aircraft purpose-built for multi-engine flight training. Its T-tail configuration and counter-rotating engines make it a realistic transition trainer, widely used by professional flight academies to prepare pilots for airline aircraft.",
    funFact:
      "The Seminole's T-tail mirrors the tail configuration of many regional and commercial jets, giving ab-initio students early familiarity with how a T-tail behaves differently from conventional empennage designs during approach.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "wing-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "low-wing twin",
        "T-tail empennage",
        "counter-rotating propellers",
        "retractable tricycle gear",
        "four seats",
        "mirrors jet trainer configuration",
      ],
    },
    aliases: ["PA-44", "Seminole"],
  },
  {
    id: "piper-pa46-malibu-meridian",
    name: "Piper PA-46 Malibu / Meridian",
    manufacturer: "Piper",
    type: "Piston Single / Turboprop Single",
    firstFlight: "1979",
    inService: "1983",
    role: "Personal / Business / High-performance Touring",
    country: "USA",
    specs: {
      wingspan: "43 ft 0 in (13.1 m)",
      length: "29 ft 0 in (8.8 m)",
      maxSpeed: "260 kt (481 km/h)",
      range: "1,000 nm (1,852 km)",
      ceiling: "30,000 ft (9,144 m)",
      engines: "1× Pratt & Whitney Canada PT6A-42A, 500 shp (Meridian)",
      crew: "1",
      capacity: "5 passengers",
    },
    description:
      "The Piper PA-46 family includes the piston-powered Malibu and the turboprop Meridian/M500. It was revolutionary as the first pressurized single-engine piston aircraft certified for single-pilot IFR flight, allowing owners to fly above weather at altitudes previously reserved for light twins and turboprops.",
    funFact:
      "The Malibu was designed with a pressurized cabin differential of 5.5 psi, maintaining a comfortable cabin altitude of 12,000 feet while the aircraft cruises at 25,000 feet — a feat previously requiring a twin-engine aircraft.",
    visual: {
      engineCount: 1,
      engineType: "turboprop",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "low-wing",
        "pressurized cabin",
        "retractable tricycle gear",
        "six seats",
        "large oval windows",
        "long pointed nose",
        "turboprop in Meridian/M500 variants",
      ],
    },
    aliases: ["PA-46", "Malibu", "Meridian", "M500", "M600"],
  },

  // ============================================================
  // BEECHCRAFT
  // ============================================================
  {
    id: "beechcraft-v35-bonanza",
    name: "Beechcraft V35 Bonanza",
    manufacturer: "Beechcraft",
    type: "Piston Single",
    firstFlight: "1945",
    inService: "1947",
    role: "Personal / Touring",
    country: "USA",
    specs: {
      wingspan: "33 ft 6 in (10.2 m)",
      length: "26 ft 5 in (8.1 m)",
      maxSpeed: "174 kt (322 km/h)",
      range: "810 nm (1,500 km)",
      ceiling: "17,500 ft (5,334 m)",
      engines: "1× Continental IO-520-BA, 285 hp",
      crew: "1",
      capacity: "4 passengers",
    },
    description:
      "The Beechcraft Bonanza V35 is famous for its distinctive V-tail — a 'butterfly' tail that combines the elevator and rudder functions into two ruddervator surfaces. Introduced in 1947, it is the longest-running production aircraft in aviation history and one of the most recognizable general aviation designs.",
    funFact:
      "The V-tail Bonanza earned the unfortunate nickname 'the doctor killer' due to a series of accidents in the 1950s–1970s, leading to an FAA investigation that ultimately determined the accidents were caused by pilot-induced structural overload, not a design flaw.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "v-tail",
      landingGear: "retractable",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "distinctive V-tail / butterfly tail",
        "low-wing",
        "retractable tricycle gear",
        "five seats",
        "ruddervator control surfaces",
        "clean aerodynamic fuselage",
      ],
    },
    aliases: ["V35", "V-tail Bonanza", "Bonanza", "Fork-tailed Doctor Killer"],
  },
  {
    id: "beechcraft-a36-bonanza",
    name: "Beechcraft A36 Bonanza",
    manufacturer: "Beechcraft",
    type: "Piston Single",
    firstFlight: "1967",
    inService: "1968",
    role: "Personal / Touring",
    country: "USA",
    specs: {
      wingspan: "33 ft 6 in (10.2 m)",
      length: "27 ft 6 in (8.4 m)",
      maxSpeed: "174 kt (322 km/h)",
      range: "812 nm (1,504 km)",
      ceiling: "18,500 ft (5,639 m)",
      engines: "1× Continental IO-550-B, 300 hp",
      crew: "1",
      capacity: "5 passengers",
    },
    description:
      "The Beechcraft A36 Bonanza replaced the V-tail with a conventional tail and stretched the fuselage to accommodate six seats and an aft double door for cargo loading. It remains in production today as the Model 36, one of the longest-running continuously produced aircraft in aviation history.",
    funFact:
      "The A36 Bonanza is certified in both the Normal and Utility categories, meaning it can legally perform limited aerobatic maneuvers (up to +4.4g) when flown solo with no fuel in certain tanks.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "low-wing",
        "conventional tail (not V-tail)",
        "retractable tricycle gear",
        "six seats",
        "aft double cargo door",
        "wide cabin",
      ],
    },
    aliases: ["A36", "Model 36", "Bonanza 36"],
  },
  {
    id: "beechcraft-baron-58",
    name: "Beechcraft Baron 58",
    manufacturer: "Beechcraft",
    type: "Piston Twin",
    firstFlight: "1969",
    inService: "1970",
    role: "Personal / Charter / Multi-engine Trainer",
    country: "USA",
    specs: {
      wingspan: "37 ft 10 in (11.5 m)",
      length: "29 ft 10 in (9.1 m)",
      maxSpeed: "200 kt (370 km/h)",
      range: "1,480 nm (2,741 km)",
      ceiling: "20,688 ft (6,306 m)",
      engines: "2× Continental IO-550-C, 300 hp each",
      crew: "1",
      capacity: "5 passengers",
    },
    description:
      "The Beechcraft Baron 58 is one of the most successful and longest-running twin-engine piston aircraft in general aviation. Known for its speed, climb performance, and range, the Baron serves in corporate transport, charter, multi-engine training, and air ambulance roles worldwide.",
    funFact:
      "The Baron 58 can climb to 10,000 feet on one engine at maximum gross weight — a capability that exceeds the single-engine climb performance of many turboprops, earning it a reputation as one of the safest light twins.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "wing-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "low-wing twin",
        "two wing-mounted engines",
        "retractable tricycle gear",
        "six seats",
        "stylish swept tail",
        "large oval windows",
      ],
    },
    aliases: ["Baron 58", "Baron", "B58"],
  },
  {
    id: "beechcraft-king-air-90",
    name: "Beechcraft King Air 90",
    manufacturer: "Beechcraft",
    type: "Turboprop Twin",
    firstFlight: "1963",
    inService: "1964",
    role: "Business / Charter / Utility",
    country: "USA",
    specs: {
      wingspan: "45 ft 11 in (14.0 m)",
      length: "35 ft 6 in (10.8 m)",
      maxSpeed: "270 kt (500 km/h)",
      range: "1,367 nm (2,531 km)",
      ceiling: "30,000 ft (9,144 m)",
      engines: "2× Pratt & Whitney Canada PT6A-135A, 550 shp each",
      crew: "1-2",
      capacity: "6 passengers",
    },
    description:
      "The Beechcraft King Air 90 is the entry-level model of the legendary King Air family, the world's best-selling turboprop series. It combines the flexibility of a pressurized cabin with PT6 turboprop reliability, serving in business aviation, special missions, aerial survey, and military utility roles.",
    funFact:
      "The King Air series has accumulated more flight hours than any other turboprop in history — the combined fleet has flown over 60 million flight hours, more than twice the next closest turboprop type.",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "wing-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "low-wing twin turboprop",
        "pressurized cabin",
        "retractable tricycle gear",
        "T-shaped windshield",
        "oval cabin windows",
        "PT6A engines",
      ],
    },
    aliases: ["King Air 90", "C90", "King Air C90"],
  },
  {
    id: "beechcraft-king-air-200",
    name: "Beechcraft King Air 200",
    manufacturer: "Beechcraft",
    type: "Turboprop Twin",
    firstFlight: "1972",
    inService: "1974",
    role: "Business / Charter / Special Missions",
    country: "USA",
    specs: {
      wingspan: "54 ft 6 in (16.6 m)",
      length: "43 ft 9 in (13.3 m)",
      maxSpeed: "290 kt (537 km/h)",
      range: "1,580 nm (2,926 km)",
      ceiling: "35,000 ft (10,668 m)",
      engines: "2× Pratt & Whitney Canada PT6A-42, 850 shp each",
      crew: "1-2",
      capacity: "9 passengers",
    },
    description:
      "The Beechcraft King Air 200 introduced the T-tail configuration to the King Air family, along with a longer fuselage, more powerful engines, and a higher cruise altitude. It is one of the most versatile and capable turboprops ever built, serving in over 90 countries in countless roles.",
    funFact:
      "The U.S. Army operates the King Air 200 as the C-12 Huron for personnel transport and the RC-12 Guardrail for SIGINT (signals intelligence) collection — giving the same airframe roles from VIP taxi to spy plane.",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "wing-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "low-wing twin turboprop",
        "T-tail empennage",
        "pressurized cabin",
        "retractable tricycle gear",
        "large oval windows",
        "distinctive nose shape",
      ],
    },
    aliases: ["King Air 200", "B200", "C-12 Huron", "Super King Air 200"],
  },
  {
    id: "beechcraft-king-air-350",
    name: "Beechcraft King Air 350",
    manufacturer: "Beechcraft",
    type: "Turboprop Twin",
    firstFlight: "1988",
    inService: "1990",
    role: "Business / Charter / Medical Evacuation",
    country: "USA",
    specs: {
      wingspan: "57 ft 11 in (17.7 m)",
      length: "46 ft 8 in (14.2 m)",
      maxSpeed: "312 kt (578 km/h)",
      range: "1,806 nm (3,346 km)",
      ceiling: "35,000 ft (10,668 m)",
      engines: "2× Pratt & Whitney Canada PT6A-60A, 1,050 shp each",
      crew: "1-2",
      capacity: "11 passengers",
    },
    description:
      "The Beechcraft King Air 350 is the top of the King Air lineup, featuring a stretched fuselage, winglets, and more powerful engines. It bridges the gap between turboprops and light jets in terms of capability, offering near-jet speed with turboprop fuel economy and exceptional range.",
    funFact:
      "The King Air 350ER (Extended Range) variant carries an optional 242-gallon fuel tank in the aft fuselage, extending range to over 2,400 nautical miles — allowing nonstop coast-to-coast U.S. travel without refueling.",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "wing-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "low-wing twin turboprop",
        "T-tail empennage",
        "winglets",
        "stretched fuselage vs King Air 200",
        "retractable tricycle gear",
        "11-seat cabin",
      ],
    },
    aliases: ["King Air 350", "B350", "Super King Air 350", "C-12J"],
  },
  {
    id: "beechcraft-1900",
    name: "Beechcraft 1900 Airliner",
    manufacturer: "Beechcraft",
    type: "Turboprop Twin",
    firstFlight: "1982",
    inService: "1984",
    role: "Regional Airliner / Cargo",
    country: "USA",
    specs: {
      wingspan: "57 ft 11 in (17.7 m)",
      length: "57 ft 10 in (17.6 m)",
      maxSpeed: "305 kt (565 km/h)",
      range: "1,586 nm (2,937 km)",
      ceiling: "25,000 ft (7,620 m)",
      engines: "2× Pratt & Whitney Canada PT6A-67D, 1,279 shp each",
      crew: "2",
      capacity: "19 passengers",
    },
    description:
      "The Beechcraft 1900 is a 19-passenger regional turboprop airliner developed from the King Air platform. It features a distinctive stabilizing surface arrangement — a ventral strake, T-tail, and large taillets — designed to provide good handling despite its small size. It has served thousands of short-haul routes globally.",
    funFact:
      "The 1900D variant introduced a stand-up cabin with a flat floor — a major improvement over earlier regional turboprops — allowing passengers to board and deplane without crouching, and earning it the nickname 'the tall turboprop.'",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "wing-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "low-wing regional airliner",
        "T-tail with ventral strakes and taillets",
        "19-seat cabin",
        "retractable tricycle gear",
        "long narrow fuselage",
        "two powerful PT6A engines",
      ],
    },
    aliases: ["Beech 1900", "1900D", "1900C", "Beechcraft 1900"],
  },

  // ============================================================
  // CIRRUS
  // ============================================================
  {
    id: "cirrus-sr20",
    name: "Cirrus SR20",
    manufacturer: "Cirrus Aircraft",
    type: "Piston Single",
    firstFlight: "1995",
    inService: "1999",
    role: "Personal / Trainer",
    country: "USA",
    specs: {
      wingspan: "35 ft 10 in (10.9 m)",
      length: "26 ft 0 in (7.9 m)",
      maxSpeed: "160 kt (296 km/h)",
      range: "900 nm (1,667 km)",
      ceiling: "17,500 ft (5,334 m)",
      engines: "1× Continental IO-360-ES, 200 hp",
      crew: "1",
      capacity: "3 passengers",
    },
    description:
      "The Cirrus SR20 is a composite-construction low-wing single that introduced the Cirrus Airframe Parachute System (CAPS) — a whole-aircraft ballistic parachute — as standard equipment. It brought modern avionics, side-stick control, and car-like ergonomics to personal aviation, fundamentally changing the market.",
    funFact:
      "As of 2024, the CAPS parachute system on Cirrus aircraft has saved over 200 lives in real emergencies, making it statistically one of the most effective safety innovations in general aviation history.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "composite construction",
        "low-wing",
        "fixed tricycle gear",
        "CAPS ballistic parachute canister on fuselage spine",
        "side-stick control",
        "large curved windshield",
        "modern glass cockpit",
      ],
    },
    aliases: ["SR20", "Cirrus SR-20"],
  },
  {
    id: "cirrus-sr22",
    name: "Cirrus SR22",
    manufacturer: "Cirrus Aircraft",
    type: "Piston Single",
    firstFlight: "2000",
    inService: "2001",
    role: "Personal / Touring / High-performance",
    country: "USA",
    specs: {
      wingspan: "38 ft 4 in (11.7 m)",
      length: "26 ft 0 in (7.9 m)",
      maxSpeed: "183 kt (339 km/h)",
      range: "1,049 nm (1,943 km)",
      ceiling: "17,500 ft (5,334 m)",
      engines: "1× Continental IO-550-N, 310 hp",
      crew: "1",
      capacity: "3 passengers",
    },
    description:
      "The Cirrus SR22 is the world's best-selling single-engine piston aircraft, topping the general aviation sales charts for over 15 consecutive years. Its combination of speed, range, comfort, advanced avionics, and the CAPS safety system has made it the benchmark personal aircraft of the 21st century.",
    funFact:
      "The SR22 Turbo (SRTG) variant, with a turbocharged engine, holds the piston single-engine distance record for circumnavigating the globe, completing the trip in under 10 days in some record attempts.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "composite construction",
        "low-wing",
        "fixed tricycle gear",
        "CAPS parachute canister visible on fuselage spine",
        "distinctive angular nose",
        "large windshield",
        "wider wingspan than SR20",
      ],
    },
    aliases: ["SR22", "SR22T", "SRTG", "Cirrus SR-22"],
  },
  {
    id: "cirrus-sf50-vision-jet",
    name: "Cirrus Vision Jet SF50",
    manufacturer: "Cirrus Aircraft",
    type: "Turbofan Single",
    firstFlight: "2008",
    inService: "2016",
    role: "Personal Jet / Light Business",
    country: "USA",
    specs: {
      wingspan: "38 ft 8 in (11.8 m)",
      length: "30 ft 8 in (9.4 m)",
      maxSpeed: "311 kt (576 km/h)",
      range: "1,200 nm (2,222 km)",
      ceiling: "31,000 ft (9,449 m)",
      engines: "1× Williams FJ33-5A, 1,800 lbf thrust",
      crew: "1",
      capacity: "4 passengers (+ 2 children in aft jumbo seats)",
    },
    description:
      "The Cirrus Vision Jet SF50 is the world's first single-engine personal jet, certified in 2016. It features a V-tail, CAPS parachute system, a spacious cabin with seven seats, and is designed to be flown by a single pilot. It brings jet travel within reach of individual owner-operators.",
    funFact:
      "The Vision Jet's engine is mounted atop the fuselage above the cabin (over-fuselage rear mounting), a configuration that keeps the intake away from foreign object debris on the ground and gives the aircraft its distinctive dolphin-like silhouette.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "over-fuselage rear-mounted",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "v-tail",
      landingGear: "retractable",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "single jet engine mounted above rear fuselage",
        "V-tail configuration",
        "low-wing",
        "CAPS whole-aircraft parachute",
        "large panoramic windows",
        "retractable tricycle gear",
        "distinctive dolphin fuselage profile",
      ],
    },
    aliases: ["SF50", "Vision Jet", "Cirrus Jet"],
  },

  // ============================================================
  // DIAMOND
  // ============================================================
  {
    id: "diamond-da20",
    name: "Diamond DA20",
    manufacturer: "Diamond Aircraft",
    type: "Piston Single",
    firstFlight: "1992",
    inService: "1994",
    role: "Trainer",
    country: "Austria / Canada",
    specs: {
      wingspan: "35 ft 9 in (10.9 m)",
      length: "23 ft 5 in (7.1 m)",
      maxSpeed: "135 kt (250 km/h)",
      range: "530 nm (981 km)",
      ceiling: "13,500 ft (4,115 m)",
      engines: "1× Continental IO-240-B, 125 hp",
      crew: "1",
      capacity: "1 passenger",
    },
    description:
      "The Diamond DA20 is a two-seat composite trainer known for its exceptional glide ratio, light controls, and fuel efficiency. Derived from glider technology, its T-tail and side-by-side seating make it a popular ab-initio trainer used by flight academies and the U.S. Air Force Academy.",
    funFact:
      "The Diamond DA20's glider heritage gives it a glide ratio of about 12:1 — significantly better than most GA trainers — meaning it can glide 12 feet forward for every foot of altitude lost, giving pilots more time to manage an engine failure.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "t-tail",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "composite construction",
        "low-wing",
        "T-tail",
        "fixed tricycle gear",
        "bubble canopy",
        "narrow fuselage",
        "graceful glider-like lines",
      ],
    },
    aliases: ["DA20", "Katana", "Eclipse", "DA-20"],
  },
  {
    id: "diamond-da40",
    name: "Diamond DA40",
    manufacturer: "Diamond Aircraft",
    type: "Piston Single",
    firstFlight: "1997",
    inService: "2000",
    role: "Personal / Trainer / Touring",
    country: "Austria",
    specs: {
      wingspan: "39 ft 4 in (12.0 m)",
      length: "26 ft 5 in (8.1 m)",
      maxSpeed: "147 kt (272 km/h)",
      range: "733 nm (1,358 km)",
      ceiling: "16,400 ft (4,999 m)",
      engines: "1× Lycoming IO-360-M1A, 180 hp",
      crew: "1",
      capacity: "3 passengers",
    },
    description:
      "The Diamond DA40 Diamond Star is a four-seat composite low-wing aircraft that extended Diamond's glider-derived efficiency principles to a four-seat touring aircraft. Its all-composite airframe, T-tail, and modern Garmin G1000 avionics suite made it a popular choice for both training and personal travel.",
    funFact:
      "The DA40 NG (Next Generation) variant is powered by a Austro Engine AE300 diesel engine running on Jet-A fuel — making it one of the first widely-sold diesel-powered general aviation aircraft, with significantly reduced fuel costs.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "t-tail",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "composite construction",
        "low-wing",
        "T-tail",
        "fixed tricycle gear",
        "four seats",
        "canopy-style forward-hinging doors",
        "graceful swept tail",
      ],
    },
    aliases: ["DA40", "Diamond Star", "DA-40"],
  },
  {
    id: "diamond-da42",
    name: "Diamond DA42 Twin Star",
    manufacturer: "Diamond Aircraft",
    type: "Piston Twin / Diesel Twin",
    firstFlight: "2002",
    inService: "2004",
    role: "Multi-engine Trainer / Personal",
    country: "Austria",
    specs: {
      wingspan: "44 ft 7 in (13.6 m)",
      length: "28 ft 3 in (8.6 m)",
      maxSpeed: "187 kt (346 km/h)",
      range: "1,300 nm (2,407 km)",
      ceiling: "18,000 ft (5,486 m)",
      engines: "2× Austro Engine AE300, 170 hp each (diesel)",
      crew: "1",
      capacity: "3 passengers",
    },
    description:
      "The Diamond DA42 Twin Star is a composite twin-engine aircraft powered by diesel engines burning Jet-A fuel. It is unique in the multi-engine trainer segment for its FADEC-controlled engines, which nearly eliminate fuel mismanagement accidents. It also serves as a surveillance and patrol aircraft platform.",
    funFact:
      "The DA42 was the first production general aviation twin to use full-authority digital engine control (FADEC) on both engines, eliminating the need for manual mixture and propeller controls — making engine management nearly automatic.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "wing-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "composite construction",
        "low-wing twin",
        "T-tail",
        "retractable tricycle gear",
        "diesel engines",
        "FADEC engine management",
        "graceful tapered wings",
      ],
    },
    aliases: ["DA42", "Twin Star", "DA-42"],
  },
  {
    id: "diamond-da62",
    name: "Diamond DA62",
    manufacturer: "Diamond Aircraft",
    type: "Diesel Twin",
    firstFlight: "2012",
    inService: "2015",
    role: "Personal / Charter / Surveillance",
    country: "Austria",
    specs: {
      wingspan: "47 ft 7 in (14.5 m)",
      length: "30 ft 10 in (9.4 m)",
      maxSpeed: "194 kt (359 km/h)",
      range: "1,078 nm (1,997 km)",
      ceiling: "20,000 ft (6,096 m)",
      engines: "2× Austro Engine AE330, 180 hp each (diesel)",
      crew: "1",
      capacity: "6 passengers",
    },
    description:
      "The Diamond DA62 is Diamond's flagship seven-seat composite twin, featuring diesel engines, a spacious cabin, and exceptional fuel economy. Designed for owner-operator travel, it burns Jet-A fuel at remarkably low rates, making long-range travel far more economical than comparable piston or turboprop twins.",
    funFact:
      "The DA62 burns approximately 8 gallons of Jet-A per hour per engine at cruise — about half the fuel consumption of comparable piston twins using avgas — making it one of the most fuel-efficient multi-engine aircraft available.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "wing-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "composite construction",
        "low-wing twin",
        "T-tail",
        "retractable tricycle gear",
        "diesel Jet-A engines",
        "seven-seat wide cabin",
        "large panoramic windows",
      ],
    },
    aliases: ["DA62", "DA-62"],
  },

  // ============================================================
  // MOONEY
  // ============================================================
  {
    id: "mooney-m20j",
    name: "Mooney M20J Model 201",
    manufacturer: "Mooney",
    type: "Piston Single",
    firstFlight: "1976",
    inService: "1977",
    role: "Personal / High-performance Touring",
    country: "USA",
    specs: {
      wingspan: "36 ft 1 in (11.0 m)",
      length: "26 ft 5 in (8.1 m)",
      maxSpeed: "175 kt (324 km/h)",
      range: "1,033 nm (1,913 km)",
      ceiling: "18,800 ft (5,730 m)",
      engines: "1× Lycoming IO-360-A3B6D, 200 hp",
      crew: "1",
      capacity: "3 passengers",
    },
    description:
      "The Mooney M20J, marketed as the Model 201, was the first production piston single capable of 200 mph (175 knots) on just 200 hp. Its distinctive forward-swept vertical tail, retractable gear, and aerodynamically efficient design made it the fastest production single-engine piston of its era.",
    funFact:
      "Mooney aircraft have a unique aerodynamic quirk: the vertical tail leans forward rather than aft, a distinctive Mooney design signature since the 1950s that pilots use to identify a Mooney from miles away.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "forward-swept vertical tail (unique Mooney signature)",
        "low-wing",
        "retractable tricycle gear",
        "four seats",
        "narrow fuselage for low drag",
        "constant-speed propeller",
      ],
    },
    aliases: ["M20J", "Model 201", "Mooney 201"],
  },
  {
    id: "mooney-m20r-ovation",
    name: "Mooney M20R Ovation",
    manufacturer: "Mooney",
    type: "Piston Single",
    firstFlight: "1993",
    inService: "1994",
    role: "Personal / High-performance Touring",
    country: "USA",
    specs: {
      wingspan: "36 ft 1 in (11.0 m)",
      length: "26 ft 9 in (8.2 m)",
      maxSpeed: "195 kt (361 km/h)",
      range: "1,480 nm (2,741 km)",
      ceiling: "20,000 ft (6,096 m)",
      engines: "1× Continental IO-550-G, 280 hp",
      crew: "1",
      capacity: "3 passengers",
    },
    description:
      "The Mooney M20R Ovation is a high-performance evolution of the M20 line, featuring a larger 280 hp engine and extended range. It is capable of crossing the continental U.S. in a single long-range leg, making it one of the most capable non-turbocharged single-engine piston aircraft available.",
    funFact:
      "The Mooney Ovation Ultra variant can achieve a true airspeed of over 200 knots at altitude on naturally aspirated power — a benchmark rarely reached by piston singles — giving it a range/speed combination that embarrasses many turboprops.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "forward-swept vertical tail (Mooney signature)",
        "low-wing",
        "retractable tricycle gear",
        "four seats",
        "larger cowl than M20J",
        "constant-speed propeller",
      ],
    },
    aliases: ["M20R", "Ovation", "Ovation Ultra"],
  },

  // ============================================================
  // OTHER NOTABLE GENERAL AVIATION AIRCRAFT
  // ============================================================
  {
    id: "pilatus-pc12",
    name: "Pilatus PC-12",
    manufacturer: "Pilatus Aircraft",
    type: "Turboprop Single",
    firstFlight: "1991",
    inService: "1994",
    role: "Business / Utility / Medical Evacuation",
    country: "Switzerland",
    specs: {
      wingspan: "53 ft 4 in (16.3 m)",
      length: "47 ft 3 in (14.4 m)",
      maxSpeed: "290 kt (537 km/h)",
      range: "1,845 nm (3,417 km)",
      ceiling: "30,000 ft (9,144 m)",
      engines: "1× Pratt & Whitney Canada PT6A-67P, 1,200 shp",
      crew: "1",
      capacity: "9 passengers",
    },
    description:
      "The Pilatus PC-12 is the world's best-selling pressurized single-turboprop business aircraft. Its combination of a large cargo door, pressurized cabin, PT6 reliability, and exceptional short-field performance makes it unmatched in versatility — serving in corporate aviation, air ambulance, charter, and government roles on every continent.",
    funFact:
      "The PC-12 can operate from grass strips as short as 1,312 feet (400 m) while carrying a full load — giving it access to remote airstrips that most pressurized business aircraft cannot reach, making it the aircraft of choice for humanitarian and medical missions in developing regions.",
    visual: {
      engineCount: 1,
      engineType: "turboprop",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "single turboprop with five-blade prop",
        "low-wing",
        "pressurized cabin",
        "retractable tricycle gear",
        "large forward cargo/passenger door",
        "large aft cargo door on cargo variant",
        "wide oval windows",
      ],
    },
    aliases: ["PC-12", "PC12", "Pilatus PC12 NG", "PC-12 NGX"],
  },
  {
    id: "pilatus-pc6-porter",
    name: "Pilatus PC-6 Porter",
    manufacturer: "Pilatus Aircraft",
    type: "Turboprop Single / STOL Utility",
    firstFlight: "1959",
    inService: "1960",
    role: "STOL Utility / Paradrop / Bush",
    country: "Switzerland",
    specs: {
      wingspan: "52 ft 0 in (15.9 m)",
      length: "36 ft 1 in (11.0 m)",
      maxSpeed: "150 kt (278 km/h)",
      range: "667 nm (1,235 km)",
      ceiling: "25,000 ft (7,620 m)",
      engines: "1× Pratt & Whitney Canada PT6A-27, 550 shp",
      crew: "1",
      capacity: "9 passengers",
    },
    description:
      "The Pilatus PC-6 Porter is one of the world's most capable STOL utility aircraft, able to operate from extremely short and unprepared surfaces. Its slab-sided fuselage, high wing, and large doors make it ideal for paradrop operations, mountain supply missions, and remote area transport where no other aircraft can operate.",
    funFact:
      "The PC-6 holds the world altitude record for a skydive — in 2014, a specially modified PC-6 served as the jump aircraft for Alan Eustace's stratospheric freefall from 135,890 feet (41.4 km), breaking Felix Baumgartner's previous record.",
    visual: {
      engineCount: 1,
      engineType: "turboprop",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "taildragger",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "high-wing STOL design",
        "slab-sided boxy fuselage",
        "large sliding side door",
        "taildragger gear",
        "optional floats or skis",
        "very large flaps for STOL performance",
        "distinctive upswept nose profile",
      ],
    },
    aliases: ["PC-6", "Porter", "Pilatus Porter", "Turbo Porter"],
  },
  {
    id: "daher-tbm-960",
    name: "Daher TBM 960",
    manufacturer: "Daher",
    type: "Turboprop Single",
    firstFlight: "2021",
    inService: "2022",
    role: "High-performance Business / Personal",
    country: "France",
    specs: {
      wingspan: "41 ft 0 in (12.5 m)",
      length: "34 ft 9 in (10.6 m)",
      maxSpeed: "330 kt (611 km/h)",
      range: "1,730 nm (3,204 km)",
      ceiling: "31,000 ft (9,449 m)",
      engines: "1× Pratt & Whitney Canada PT6E-66XT, 1,825 shp",
      crew: "1",
      capacity: "5 passengers",
    },
    description:
      "The Daher TBM 960 is the pinnacle of the TBM family — the world's fastest single-engine turboprop. With a FADEC-equipped PT6 engine, all-electric pressurization, and Garmin G3000 avionics, it offers near-jet performance at turboprop operating costs, making it a favorite of high-net-worth owner-pilots.",
    funFact:
      "The TBM 960 can reach its service ceiling of 31,000 feet in approximately 18 minutes from brake release — a climb rate that rivals many light jets and allows pilots to rapidly ascend above weather on short notice.",
    visual: {
      engineCount: 1,
      engineType: "turboprop",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "single turboprop low-wing",
        "pressurized cabin",
        "retractable tricycle gear",
        "long pointed nose",
        "distinctive TBM nose profile",
        "high-speed cruise configuration",
        "five-blade propeller",
      ],
    },
    aliases: ["TBM 960", "TBM960", "TBM 940", "TBM 930", "TBM family"],
  },
  {
    id: "grumman-aa5",
    name: "Grumman AA-5",
    manufacturer: "Grumman American / American General",
    type: "Piston Single",
    firstFlight: "1970",
    inService: "1972",
    role: "Personal / Touring",
    country: "USA",
    specs: {
      wingspan: "31 ft 6 in (9.6 m)",
      length: "22 ft 0 in (6.7 m)",
      maxSpeed: "140 kt (259 km/h)",
      range: "620 nm (1,148 km)",
      ceiling: "12,650 ft (3,856 m)",
      engines: "1× Lycoming O-320-E2G, 150 hp",
      crew: "1",
      capacity: "3 passengers",
    },
    description:
      "The Grumman AA-5 Traveler and its variants (Tiger, Cheetah, Lynx) are distinctive low-wing four-seat aircraft featuring bonded aluminum construction and a sliding canopy rather than conventional doors. This unique entry system gives excellent visibility and a sporty, aircraft-carrier feel.",
    funFact:
      "Grumman designed the AA-5 fuselage using bonded (glued) aluminum rather than riveted construction — a technique borrowed from their naval aircraft experience — producing a smoother surface and lighter structure, but requiring specialized repair techniques.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "sliding canopy (no conventional doors)",
        "low-wing",
        "fixed tricycle gear",
        "four seats",
        "bonded aluminum construction",
        "distinctive windshield rake angle",
      ],
    },
    aliases: ["AA-5", "Traveler", "Tiger", "Cheetah", "Grumman Tiger"],
  },
  {
    id: "maule-m7",
    name: "Maule M-7",
    manufacturer: "Maule Air",
    type: "Piston Single / STOL",
    firstFlight: "1984",
    inService: "1985",
    role: "STOL / Bush / Personal",
    country: "USA",
    specs: {
      wingspan: "30 ft 10 in (9.4 m)",
      length: "23 ft 9 in (7.2 m)",
      maxSpeed: "145 kt (269 km/h)",
      range: "500 nm (926 km)",
      ceiling: "17,000 ft (5,182 m)",
      engines: "1× Lycoming IO-540-W1A5D, 235 hp",
      crew: "1",
      capacity: "4 passengers",
    },
    description:
      "The Maule M-7 is a high-wing STOL utility aircraft hand-built in Moultrie, Georgia, known for exceptional short-field performance, a taildragger configuration, and the ability to be equipped with wheels, floats, skis, or amphibious floats interchangeably. It is a staple of Alaskan bush aviation.",
    funFact:
      "Maule Aircraft is one of the last remaining U.S. general aviation manufacturers still producing aircraft in very small numbers by hand — their factory in Moultrie, Georgia, operates more like a custom shop than a production line, with each aircraft built to the customer's specification.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "taildragger",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "high-wing strut-braced",
        "taildragger gear",
        "STOL flap system",
        "fabric and aluminum construction",
        "optional floats or skis",
        "distinctive boxy fuselage",
        "four side-by-side seats",
      ],
    },
    aliases: ["M-7", "Maule", "Maule Star Rocket", "M7"],
  },
  {
    id: "dehavilland-dhc2-beaver",
    name: "de Havilland DHC-2 Beaver",
    manufacturer: "de Havilland Canada",
    type: "Piston Single / STOL",
    firstFlight: "1947",
    inService: "1948",
    role: "Bush / Float Plane / STOL Utility",
    country: "Canada",
    specs: {
      wingspan: "48 ft 0 in (14.6 m)",
      length: "30 ft 4 in (9.2 m)",
      maxSpeed: "137 kt (254 km/h)",
      range: "450 nm (833 km)",
      ceiling: "18,000 ft (5,486 m)",
      engines: "1× Pratt & Whitney R-985 Wasp Junior, 450 hp",
      crew: "1",
      capacity: "6 passengers or 1,200 lb cargo",
    },
    description:
      "The de Havilland DHC-2 Beaver is one of the most celebrated bush planes in aviation history, legendary for its rugged construction, STOL capability, and ability to operate on wheels, floats, skis, or amphibious floats. It was designated a Canadian aeronautical milestone and remains in active service over 75 years after its first flight.",
    funFact:
      "Over 1,600 Beavers were built between 1947 and 1967, and most are still flying today — an extraordinary testament to the design's durability. The type has been used by the U.S. Army, bush operators in Alaska and the Canadian north, and countless humanitarian organizations.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted radial",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "taildragger",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "high-wing STOL design",
        "radial engine cowling",
        "taildragger gear",
        "optional floats standard in bush operations",
        "boxy square fuselage cross-section",
        "large forward cargo door",
        "iconic Canadian bush plane profile",
      ],
    },
    aliases: ["DHC-2", "Beaver", "L-20 Beaver", "U-6 Beaver"],
  },
  {
    id: "dehavilland-dhc3-otter",
    name: "de Havilland DHC-3 Otter",
    manufacturer: "de Havilland Canada",
    type: "Piston Single (or Turboprop Single)",
    firstFlight: "1951",
    inService: "1953",
    role: "Bush / Float Plane / STOL Utility",
    country: "Canada",
    specs: {
      wingspan: "58 ft 0 in (17.7 m)",
      length: "41 ft 10 in (12.8 m)",
      maxSpeed: "148 kt (274 km/h)",
      range: "833 nm (1,543 km)",
      ceiling: "17,400 ft (5,304 m)",
      engines: "1× Pratt & Whitney Canada PT6A-135A, 750 shp (Turbo Otter conversion)",
      crew: "1",
      capacity: "10 passengers or 3,000 lb cargo",
    },
    description:
      "The de Havilland DHC-3 Otter, known as the 'Single Otter,' is a larger version of the Beaver designed for heavier loads and longer range. Many have been converted to turboprop power (Turbo Otter), dramatically improving performance. It remains an irreplaceable workhorse of Canadian and Alaskan bush operations.",
    funFact:
      "The Otter's nickname 'King Beaver' reflects its role as the direct big brother to the DHC-2 — sharing the same high-wing, taildragger DNA but offering twice the payload. STOL performance so impressed the U.S. Army that they purchased 184 examples for operations in Korea and later Vietnam.",
    visual: {
      engineCount: 1,
      engineType: "turboprop",
      enginePlacement: "nose-mounted tractor",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "taildragger",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "high-wing STOL design",
        "large boxy fuselage",
        "taildragger gear",
        "optional floats or skis",
        "large cargo door",
        "10-seat capacity",
        "Canadian bush plane heritage",
      ],
    },
    aliases: ["DHC-3", "Otter", "Single Otter", "Turbo Otter", "U-1 Otter"],
  },
  {
    id: "dehavilland-dhc6-twin-otter",
    name: "de Havilland DHC-6 Twin Otter",
    manufacturer: "de Havilland Canada / Viking Air",
    type: "Turboprop Twin / STOL",
    firstFlight: "1965",
    inService: "1966",
    role: "Regional / STOL / Float Plane / Bush",
    country: "Canada",
    specs: {
      wingspan: "65 ft 0 in (19.8 m)",
      length: "51 ft 9 in (15.8 m)",
      maxSpeed: "182 kt (337 km/h)",
      range: "1,048 nm (1,941 km)",
      ceiling: "26,700 ft (8,138 m)",
      engines: "2× Pratt & Whitney Canada PT6A-27, 620 shp each",
      crew: "2",
      capacity: "19 passengers",
    },
    description:
      "The de Havilland DHC-6 Twin Otter is one of the world's most capable STOL utility aircraft, combining twin-turboprop reliability with the ability to operate from grass strips, gravel bars, water (as a floatplane), and snow (on skis). It serves as a regional airliner, paradrop aircraft, and humanitarian transport on every continent.",
    funFact:
      "The Twin Otter has one of the slowest stall speeds of any twin-turboprop — approximately 64 knots — giving it the ability to land in less than 1,000 feet. This makes it the go-to aircraft for resupplying remote polar research stations in Antarctica.",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "wing-mounted tractor",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "high-wing twin turboprop",
        "distinctive tall slab-sided fuselage",
        "large fixed tricycle gear with tundra tire option",
        "optional floats or skis",
        "squared-off fuselage cross-section",
        "two PT6A engines",
        "excellent STOL performance",
      ],
    },
    aliases: ["DHC-6", "Twin Otter", "Series 300", "Viking Twin Otter"],
  },
];
