import { AircraftEntry } from "./types";

export const helicopters: AircraftEntry[] = [
  // ============================================================
  // MILITARY US HELICOPTERS
  // ============================================================
  {
    id: "uh-60-black-hawk",
    name: "UH-60 Black Hawk",
    manufacturer: "Sikorsky",
    type: "Helicopter",
    variant: "UH-60L/M",
    firstFlight: "1974",
    inService: "1979",
    role: "Utility / Troop Transport",
    country: "USA",
    specs: {
      length: "64 ft 10 in (19.76 m)",
      maxSpeed: "183 mph (294 km/h)",
      range: "362 mi (584 km)",
      ceiling: "19,000 ft (5,790 m)",
      engines: "2× General Electric T700-GE-701C turboshaft",
      crew: "2–4",
      capacity: "11 troops",
    },
    description:
      "The UH-60 Black Hawk is the US Army's primary utility tactical transport helicopter, replacing the aging UH-1 Huey. It has served in every major US conflict since the 1980s and is operated by all branches of the US military as well as dozens of allied nations.",
    funFact:
      "The Black Hawk's name comes from the Sauk Nation war leader Black Hawk, and the helicopter famously appeared in the 1993 Battle of Mogadishu depicted in the book and film 'Black Hawk Down.'",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "four-blade main rotor",
        "four-blade tail rotor",
        "wide cargo door on sides",
        "stub wings for external stores",
      ],
    },
    aliases: ["Black Hawk", "Blackhawk", "UH-60", "Hawk"],
  },
  {
    id: "ah-64-apache",
    name: "AH-64 Apache",
    manufacturer: "Boeing",
    type: "Helicopter",
    variant: "AH-64D",
    firstFlight: "1975",
    inService: "1986",
    role: "Attack Helicopter",
    country: "USA",
    specs: {
      length: "58 ft 1 in (17.73 m)",
      maxSpeed: "182 mph (293 km/h)",
      range: "295 mi (476 km)",
      ceiling: "21,000 ft (6,400 m)",
      engines: "2× General Electric T700-GE-701D turboshaft",
      crew: "2",
    },
    description:
      "The AH-64 Apache is the US Army's primary attack helicopter, armed with a 30mm chain gun, Hellfire missiles, and Hydra rockets. It features tandem seating with the co-pilot/gunner in front and the pilot behind, along with a mast-mounted radar on the D model.",
    funFact:
      "The Apache's 30mm M230 chain gun can fire up to 625 rounds per minute and automatically slews to aim wherever the gunner's helmet-mounted sight is looking.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "tandem cockpit",
        "stub wings with weapons pylons",
        "nose-mounted sensor turret",
        "four-blade main rotor",
        "mast-mounted radar dome (D/E model)",
      ],
    },
    aliases: ["Apache", "AH-64", "Longbow Apache"],
  },
  {
    id: "ah-64e-guardian",
    name: "AH-64E Guardian",
    manufacturer: "Boeing",
    type: "Helicopter",
    variant: "AH-64E",
    firstFlight: "2008",
    inService: "2011",
    role: "Attack Helicopter",
    country: "USA",
    specs: {
      length: "58 ft 1 in (17.73 m)",
      maxSpeed: "186 mph (299 km/h)",
      range: "295 mi (476 km)",
      ceiling: "20,000 ft (6,096 m)",
      engines: "2× General Electric T700-GE-701D turboshaft",
      crew: "2",
    },
    description:
      "The AH-64E Guardian is the most advanced variant of the Apache, featuring improved drive system, higher-power engines, upgraded composite rotor blades, and the ability to control unmanned aerial vehicles. It incorporates a Level 4 manned-unmanned teaming capability.",
    funFact:
      "The AH-64E Guardian can act as an airborne controller for unmanned aerial vehicles, allowing its crew to relay video feeds and direct drone operations during combat.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "tandem cockpit",
        "stub wings with weapons pylons",
        "nose-mounted TADS/PNVS sensor",
        "mast-mounted fire control radar",
        "composite rotor blades",
      ],
    },
    aliases: ["Apache Guardian", "AH-64E", "Guardian"],
  },
  {
    id: "ch-47-chinook",
    name: "CH-47 Chinook",
    manufacturer: "Boeing",
    type: "Helicopter",
    variant: "CH-47F",
    firstFlight: "1961",
    inService: "1962",
    role: "Heavy Lift / Cargo Transport",
    country: "USA",
    specs: {
      length: "98 ft 11 in (30.14 m)",
      maxSpeed: "196 mph (315 km/h)",
      range: "400 mi (741 km)",
      ceiling: "20,000 ft (6,096 m)",
      engines: "2× Honeywell T55-GA-714A turboshaft",
      crew: "2–4",
      capacity: "33–55 troops or 28,000 lb cargo",
    },
    description:
      "The CH-47 Chinook is a tandem-rotor heavy-lift helicopter used by the US Army since the Vietnam War. Its distinctive tandem rotor configuration eliminates the need for a tail rotor and allows for high payload capacity in hot and high altitude conditions.",
    funFact:
      "The Chinook once lifted an entire disabled CH-47 helicopter and flew it to safety, and it remains one of the few aircraft that can self-deploy across the Atlantic Ocean without refueling stops.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "no-tail",
      landingGear: "fixed",
      sizeClass: "heavy",
      era: "cold-war",
      distinguishingFeatures: [
        "tandem rotors fore and aft",
        "no tail rotor",
        "wide rear loading ramp",
        "three-point fixed landing gear",
        "sponson fuel tanks on sides",
      ],
    },
    aliases: ["Chinook", "CH-47", "Shithook", "Hook"],
  },
  {
    id: "uh-1-huey",
    name: "UH-1 Iroquois",
    manufacturer: "Bell",
    type: "Helicopter",
    variant: "UH-1H",
    firstFlight: "1956",
    inService: "1959",
    role: "Utility Helicopter",
    country: "USA",
    specs: {
      length: "57 ft 1 in (17.4 m)",
      maxSpeed: "135 mph (217 km/h)",
      range: "318 mi (511 km)",
      ceiling: "19,390 ft (5,910 m)",
      engines: "1× Lycoming T53-L-13 turboshaft",
      crew: "2–4",
      capacity: "6–8 troops",
    },
    description:
      "The UH-1 Iroquois, universally known as the Huey, became the iconic helicopter of the Vietnam War era. Its distinctive two-blade rotor created the 'whop-whop' sound synonymous with Vietnam. It served as troop transport, medevac, and gunship in countless configurations.",
    funFact:
      "More than 16,000 Hueys were built, making it one of the most produced helicopters in history, and the sound of its two-blade rotor is so distinctive that veterans can identify it instantly decades later.",
    visual: {
      engineCount: 1,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "skids",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "two-blade semi-rigid main rotor",
        "skid landing gear",
        "open side doors",
        "single turboshaft engine",
        "slim fuselage",
      ],
    },
    aliases: ["Huey", "Iroquois", "UH-1", "Slick"],
  },
  {
    id: "ah-1-cobra",
    name: "AH-1 Cobra",
    manufacturer: "Bell",
    type: "Helicopter",
    variant: "AH-1G",
    firstFlight: "1965",
    inService: "1967",
    role: "Attack Helicopter",
    country: "USA",
    specs: {
      length: "53 ft 4 in (16.26 m)",
      maxSpeed: "172 mph (277 km/h)",
      range: "357 mi (574 km)",
      ceiling: "11,400 ft (3,475 m)",
      engines: "1× Lycoming T53-L-13 turboshaft",
      crew: "2",
    },
    description:
      "The AH-1 Cobra was the world's first purpose-built attack helicopter, developed urgently during the Vietnam War. Built on UH-1 components, it featured a slim fuselage with tandem seating to reduce frontal profile and carried a nose turret with various weapons combinations.",
    funFact:
      "The Cobra was developed and flew its first flight within only 6 months of the Army contract award in 1965 — an extraordinary development timeline driven by urgent combat needs in Vietnam.",
    visual: {
      engineCount: 1,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "skids",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "very slim fuselage",
        "tandem seating",
        "stub wings with weapons pylons",
        "nose gun turret",
        "two-blade rotor",
      ],
    },
    aliases: ["Cobra", "HueyCobra", "AH-1G", "Snake"],
  },
  {
    id: "ah-1z-viper",
    name: "AH-1Z Viper",
    manufacturer: "Bell",
    type: "Helicopter",
    variant: "AH-1Z",
    firstFlight: "2000",
    inService: "2010",
    role: "Attack Helicopter",
    country: "USA",
    specs: {
      length: "58 ft 4 in (17.78 m)",
      maxSpeed: "211 mph (340 km/h)",
      range: "430 mi (692 km)",
      ceiling: "20,000 ft (6,096 m)",
      engines: "2× General Electric T700-GE-401C turboshaft",
      crew: "2",
    },
    description:
      "The AH-1Z Viper is the US Marine Corps' primary attack helicopter, a twin-engine evolution of the Cobra. It shares 84% parts commonality with the UH-1Y Venom and features a four-blade composite rotor, advanced sensors, and the ability to carry a wide range of weapons including Hellfire and AIM-9 missiles.",
    funFact:
      "The AH-1Z Viper and UH-1Y Venom were designed as a 'Y/Z' upgrade pair with maximized parts commonality to simplify Marine Corps logistics — they share engines, rotor systems, transmissions, and cockpit avionics.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "skids",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "four-blade composite rotor",
        "slim tandem fuselage",
        "stub wings with weapons",
        "target sight system nose turret",
        "twin engines side by side",
      ],
    },
    aliases: ["Viper", "AH-1Z", "Zulu Cobra", "SuperCobra successor"],
  },
  {
    id: "oh-58-kiowa",
    name: "OH-58 Kiowa",
    manufacturer: "Bell",
    type: "Helicopter",
    variant: "OH-58D",
    firstFlight: "1966",
    inService: "1969",
    role: "Scout / Observation",
    country: "USA",
    specs: {
      length: "42 ft 2 in (12.85 m)",
      maxSpeed: "149 mph (240 km/h)",
      range: "345 mi (556 km)",
      ceiling: "15,000 ft (4,572 m)",
      engines: "1× Allison 250-C30R turboshaft",
      crew: "2",
    },
    description:
      "The OH-58 Kiowa is a military scout helicopter based on the Bell 206 JetRanger. The OH-58D Kiowa Warrior variant added a mast-mounted sight above the rotor head with thermal imaging and laser rangefinder, enabling it to designate targets for other weapons systems from behind cover.",
    funFact:
      "The Kiowa Warrior's mast-mounted sight allows the pilot to hover behind terrain with only the sight ball visible above the ridgeline, making it nearly invisible to ground observers while still tracking targets.",
    visual: {
      engineCount: 1,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "skids",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "mast-mounted sensor ball (D model)",
        "small bubble cockpit",
        "skid gear",
        "two-blade rotor",
      ],
    },
    aliases: ["Kiowa", "OH-58", "Kiowa Warrior"],
  },
  {
    id: "ch-53e-super-stallion",
    name: "CH-53E Super Stallion",
    manufacturer: "Sikorsky",
    type: "Helicopter",
    variant: "CH-53E",
    firstFlight: "1974",
    inService: "1981",
    role: "Heavy Lift Helicopter",
    country: "USA",
    specs: {
      length: "99 ft 1 in (30.19 m)",
      maxSpeed: "196 mph (315 km/h)",
      range: "621 mi (999 km)",
      ceiling: "18,500 ft (5,640 m)",
      engines: "3× General Electric T64-GE-416 turboshaft",
      crew: "3–5",
      capacity: "55 troops or 36,000 lb external load",
    },
    description:
      "The CH-53E Super Stallion is the largest and heaviest helicopter in the US military inventory. With three engines and a seven-blade main rotor, it can lift virtually any Marine Corps equipment and is used extensively for vertical assault, ship-to-shore movement, and combat recovery.",
    funFact:
      "The CH-53E can lift and carry another CH-53 helicopter as an external load, and it has recovered countless downed aircraft from hostile territory over its decades of service.",
    visual: {
      engineCount: 3,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "heavy",
      era: "modern",
      distinguishingFeatures: [
        "seven-blade main rotor",
        "three engines",
        "tilted tail rotor",
        "rear cargo ramp",
        "sponson fuel tanks",
      ],
    },
    aliases: ["Super Stallion", "CH-53E", "Hurricane Maker", "Shitter"],
  },
  {
    id: "ch-53k-king-stallion",
    name: "CH-53K King Stallion",
    manufacturer: "Sikorsky",
    type: "Helicopter",
    variant: "CH-53K",
    firstFlight: "2015",
    inService: "2022",
    role: "Heavy Lift Helicopter",
    country: "USA",
    specs: {
      length: "99 ft (30.2 m)",
      maxSpeed: "200 mph (321 km/h)",
      range: "460 mi (740 km)",
      ceiling: "14,380 ft (4,383 m)",
      engines: "3× General Electric T408-GE-400 turboshaft",
      crew: "3–5",
      capacity: "36 troops or 27,000 kg external load",
    },
    description:
      "The CH-53K King Stallion is the next-generation heavy lift helicopter for the US Marine Corps, replacing the CH-53E. It offers three times the lift capability of the Super Stallion with a composite rotor system, fly-by-wire flight controls, and a wider cabin with modern glass cockpit.",
    funFact:
      "The King Stallion's 7-blade composite main rotor is so large — 79 feet in diameter — that each blade is nearly as long as a standard school bus.",
    visual: {
      engineCount: 3,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "seven-blade composite main rotor",
        "three engines",
        "wider fuselage than CH-53E",
        "rear cargo ramp",
        "advanced glass cockpit",
      ],
    },
    aliases: ["King Stallion", "CH-53K"],
  },
  {
    id: "mh-6-little-bird",
    name: "MH-6 Little Bird",
    manufacturer: "Boeing (MD Helicopters)",
    type: "Helicopter",
    variant: "MH-6M",
    firstFlight: "1963",
    inService: "1980",
    role: "Special Operations Light Helicopter",
    country: "USA",
    specs: {
      length: "32 ft 3 in (9.84 m)",
      maxSpeed: "175 mph (282 km/h)",
      range: "230 mi (370 km)",
      ceiling: "16,000 ft (4,877 m)",
      engines: "1× Allison 250-C30R turboshaft",
      crew: "2",
      capacity: "6 troops on external benches",
    },
    description:
      "The MH-6 Little Bird is a light special operations helicopter flown by the 160th Special Operations Aviation Regiment (Night Stalkers). Its compact size allows it to operate in confined urban environments, and troops can ride on external bench seats or skid-mounted platforms for rapid insertion.",
    funFact:
      "The Little Bird is so small it can fit inside a C-130 transport — multiple Little Birds can be transported and rapidly reassembled for deployment, making them ideal for covert operations.",
    visual: {
      engineCount: 1,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "skids",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "very small compact size",
        "external bench seats for troops",
        "skid gear",
        "two-blade main rotor",
        "egg-shaped fuselage",
      ],
    },
    aliases: ["Little Bird", "MH-6", "AH-6", "Killer Egg"],
  },
  {
    id: "mh-60-seahawk",
    name: "MH-60 Seahawk",
    manufacturer: "Sikorsky",
    type: "Helicopter",
    variant: "MH-60S/R",
    firstFlight: "1979",
    inService: "1984",
    role: "Naval Helicopter / Anti-Submarine Warfare",
    country: "USA",
    specs: {
      length: "64 ft 10 in (19.76 m)",
      maxSpeed: "180 mph (290 km/h)",
      range: "600 mi (965 km)",
      ceiling: "10,000 ft (3,048 m)",
      engines: "2× General Electric T700-GE-401C turboshaft",
      crew: "3–4",
    },
    description:
      "The MH-60 Seahawk is the naval variant of the Black Hawk family, adapted for shipboard operations with folding rotor blades and tail, flotation gear, and maritime sensors. The SH-60/MH-60 family performs anti-submarine warfare, search and rescue, and vertical replenishment missions from Navy ships.",
    funFact:
      "The Seahawk's rotor blades fold automatically in under 90 seconds for shipboard storage, and its undercarriage includes a 'bear trap' recovery assistance system for landing on pitching flight decks in rough seas.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "folding rotor blades",
        "folding tail section",
        "sponson floatation gear",
        "dipping sonar",
        "torpedo and sonobuoy capacity",
      ],
    },
    aliases: ["Seahawk", "MH-60", "SH-60", "Romeo", "Sierra"],
  },
  {
    id: "v-22-osprey",
    name: "V-22 Osprey",
    manufacturer: "Bell Boeing",
    type: "Tiltrotor",
    variant: "MV-22B",
    firstFlight: "1989",
    inService: "2007",
    role: "Tiltrotor / Multi-Mission",
    country: "USA",
    specs: {
      length: "57 ft 4 in (17.47 m)",
      maxSpeed: "316 mph (509 km/h)",
      range: "1,011 mi (1,627 km)",
      ceiling: "25,000 ft (7,620 m)",
      engines: "2× Rolls-Royce AE1107C turboshaft",
      crew: "2–4",
      capacity: "24 troops",
    },
    description:
      "The V-22 Osprey is a tiltrotor aircraft that combines the vertical takeoff and landing capability of a helicopter with the speed, range, and fuel efficiency of a turboprop aircraft. The rotors tilt from vertical for helicopter-mode to horizontal for airplane-mode during flight.",
    funFact:
      "The V-22 can fly three times faster than a conventional helicopter and has a range four times greater, yet it can still land vertically on a ship deck or unimproved landing zone with no runway required.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "wingtip-mounted tilting",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "h-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "tiltrotor — rotors tilt from vertical to horizontal",
        "large prop-rotors at wingtips",
        "fixed wing with twin tails",
        "rear ramp",
        "unique transition flight mode",
      ],
    },
    aliases: ["Osprey", "V-22", "Widow Maker (informal)", "MV-22"],
  },
  {
    id: "ch-46-sea-knight",
    name: "CH-46 Sea Knight",
    manufacturer: "Boeing Vertol",
    type: "Helicopter",
    variant: "CH-46E",
    firstFlight: "1958",
    inService: "1964",
    role: "Medium Lift / Assault Transport",
    country: "USA",
    specs: {
      length: "84 ft 4 in (25.7 m)",
      maxSpeed: "165 mph (266 km/h)",
      range: "633 mi (1,019 km)",
      ceiling: "14,000 ft (4,267 m)",
      engines: "2× General Electric T58-GE-16 turboshaft",
      crew: "3",
      capacity: "25 troops",
    },
    description:
      "The CH-46 Sea Knight is a tandem-rotor medium-lift helicopter that served the US Marine Corps and Navy for over 50 years. Used primarily for assault transport, combat search and rescue, and ship replenishment, it was replaced in Marine Corps service by the MV-22 Osprey.",
    funFact:
      "The CH-46 Sea Knight served the US Marine Corps from the Vietnam War through the Iraq War — a remarkable 42-year front-line service life — before being replaced by the V-22 Osprey in 2015.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "no-tail",
      landingGear: "fixed",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "tandem rotors fore and aft",
        "no tail rotor",
        "rear loading ramp",
        "sponson floatation gear",
        "overlapping rotor discs",
      ],
    },
    aliases: ["Sea Knight", "CH-46", "Phrog", "Flying Banana"],
  },
  {
    id: "sh-3-sea-king",
    name: "SH-3 Sea King",
    manufacturer: "Sikorsky",
    type: "Helicopter",
    variant: "SH-3H",
    firstFlight: "1959",
    inService: "1961",
    role: "Anti-Submarine Warfare / SAR",
    country: "USA",
    specs: {
      length: "72 ft 8 in (22.15 m)",
      maxSpeed: "166 mph (267 km/h)",
      range: "625 mi (1,006 km)",
      ceiling: "14,700 ft (4,481 m)",
      engines: "2× General Electric T58-GE-10 turboshaft",
      crew: "4",
    },
    description:
      "The SH-3 Sea King is a twin-turboshaft anti-submarine warfare helicopter that served as the US Navy's primary ASW platform for three decades. It introduced amphibious capability with a boat hull for water landings and was used for presidential transport as Marine One.",
    funFact:
      "A Sea King helicopter retrieved the Apollo astronauts from the ocean after every Moon mission from Apollo 11 through Apollo 17, making it one of the most historically significant aircraft in space program history.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "amphibious boat hull",
        "sponson floats",
        "folding rotor blades",
        "dipping sonar",
        "five-blade main rotor",
      ],
    },
    aliases: ["Sea King", "SH-3", "Marine One (when VIP configured)"],
  },

  // ============================================================
  // MILITARY OTHER HELICOPTERS
  // ============================================================
  {
    id: "mi-24-hind",
    name: "Mi-24 Hind",
    manufacturer: "Mil",
    type: "Helicopter",
    natoReportingName: "Hind",
    variant: "Mi-24D/V",
    firstFlight: "1969",
    inService: "1972",
    role: "Attack / Assault Helicopter",
    country: "Russia",
    specs: {
      length: "70 ft 5 in (21.5 m)",
      maxSpeed: "208 mph (335 km/h)",
      range: "280 mi (450 km)",
      ceiling: "14,764 ft (4,500 m)",
      engines: "2× Isotov TV3-117 turboshaft",
      crew: "2–3",
      capacity: "8 troops",
    },
    description:
      "The Mi-24 Hind is a large Soviet/Russian gunship and assault helicopter unique in its ability to transport troops while delivering devastating firepower. Often called the 'flying tank,' it features heavy armor, stub wings with weapons pylons, and a crew of two in tandem cockpits.",
    funFact:
      "The Mi-24 Hind is one of the very few armed helicopters in the world capable of carrying a squad of fully equipped soldiers into battle — essentially combining the roles of attack helicopter and troop transport in one aircraft.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "cold-war",
      distinguishingFeatures: [
        "large stub wings with weapons",
        "retractable landing gear",
        "greenhouse canopy",
        "tandem cockpit",
        "chin gun turret",
        "troop cabin",
      ],
    },
    aliases: ["Hind", "Mi-24", "Flying Tank", "Krokodil"],
  },
  {
    id: "mi-8-hip",
    name: "Mi-8 Hip",
    manufacturer: "Mil",
    type: "Helicopter",
    natoReportingName: "Hip",
    variant: "Mi-8T",
    firstFlight: "1961",
    inService: "1967",
    role: "Utility / Transport Helicopter",
    country: "Russia",
    specs: {
      length: "82 ft 10 in (25.24 m)",
      maxSpeed: "161 mph (260 km/h)",
      range: "295 mi (475 km)",
      ceiling: "14,764 ft (4,500 m)",
      engines: "2× Klimov TV2-117A turboshaft",
      crew: "2–3",
      capacity: "24 troops or 8,800 lb cargo",
    },
    description:
      "The Mi-8 Hip is one of the world's most produced and widely operated helicopters, serving in over 50 countries. A rugged twin-turbine transport, it has been adapted for nearly every role including gunship, medevac, ECM, and VIP transport, and remains in production in modernized form.",
    funFact:
      "With over 17,000 built since 1965 and still in production today, the Mi-8 family is one of the best-selling helicopters in aviation history — more Mi-8s are operating today than any other twin-turbine helicopter.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "five-blade main rotor",
        "three-blade tail rotor",
        "rounded nose",
        "large troop/cargo cabin",
        "clamshell rear doors",
      ],
    },
    aliases: ["Hip", "Mi-8", "Mi-8T"],
  },
  {
    id: "mi-17",
    name: "Mi-17",
    manufacturer: "Mil / Kazan Helicopters",
    type: "Helicopter",
    natoReportingName: "Hip-H",
    variant: "Mi-17V-5",
    firstFlight: "1975",
    inService: "1981",
    role: "Utility / Transport Helicopter",
    country: "Russia",
    specs: {
      length: "83 ft (25.3 m)",
      maxSpeed: "155 mph (250 km/h)",
      range: "360 mi (580 km)",
      ceiling: "19,685 ft (6,000 m)",
      engines: "2× Klimov TV3-117MT turboshaft",
      crew: "3",
      capacity: "36 troops or 13,000 lb cargo",
    },
    description:
      "The Mi-17 is the export designation of the Mi-8MT, an upgraded version of the Mi-8 with more powerful engines and a relocated tail rotor to the left side. It is widely used by military and civilian operators worldwide and is distinguishable from the Mi-8 by its reversed tail rotor rotation direction.",
    funFact:
      "The Mi-17 was purchased by the United States for the Afghan National Army, making it one of the rare cases where the US military bought and operated Russian-designed military helicopters — a decision that caused significant political controversy.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "five-blade main rotor",
        "tail rotor on left side (vs right on Mi-8)",
        "more powerful engines than Mi-8",
        "rounded nose",
        "large troop/cargo cabin",
      ],
    },
    aliases: ["Mi-17", "Hip-H", "Mi-8MT"],
  },
  {
    id: "mi-26-halo",
    name: "Mi-26 Halo",
    manufacturer: "Mil",
    type: "Helicopter",
    natoReportingName: "Halo",
    variant: "Mi-26T",
    firstFlight: "1977",
    inService: "1983",
    role: "Heavy Lift Helicopter",
    country: "Russia",
    specs: {
      length: "110 ft 8 in (33.73 m)",
      maxSpeed: "183 mph (295 km/h)",
      range: "497 mi (800 km)",
      ceiling: "15,091 ft (4,600 m)",
      engines: "2× Lotarev D-136 turboshaft",
      crew: "4–5",
      capacity: "90 troops or 44,000 lb cargo",
    },
    description:
      "The Mi-26 Halo is the world's largest and most powerful production helicopter, capable of lifting payloads that no other helicopter can match. Its eight-blade main rotor spans 105 feet, and its cargo hold is large enough to carry another helicopter inside.",
    funFact:
      "In 2001, a Mi-26 recovered a 20,000-year-old frozen woolly mammoth from a Siberian glacier by airlifting the entire block of ice and permafrost in a cargo net — an operation as unusual as any military mission.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "super-heavy",
      era: "cold-war",
      distinguishingFeatures: [
        "eight-blade main rotor",
        "massive fuselage",
        "rear cargo ramp",
        "five-blade tail rotor",
        "largest helicopter in production",
      ],
    },
    aliases: ["Halo", "Mi-26", "Flying Cow"],
  },
  {
    id: "mi-28-havoc",
    name: "Mi-28 Havoc",
    manufacturer: "Mil",
    type: "Helicopter",
    natoReportingName: "Havoc",
    variant: "Mi-28N",
    firstFlight: "1982",
    inService: "1996",
    role: "Attack Helicopter",
    country: "Russia",
    specs: {
      length: "70 ft 6 in (21.5 m)",
      maxSpeed: "199 mph (320 km/h)",
      range: "280 mi (450 km)",
      ceiling: "18,700 ft (5,700 m)",
      engines: "2× Klimov TV3-117VMA turboshaft",
      crew: "2",
    },
    description:
      "The Mi-28 Havoc is Russia's dedicated all-weather day/night attack helicopter, designed as a rival to the AH-64 Apache. The Mi-28N Night Hunter variant features a mast-mounted radar system and is the current primary attack helicopter of the Russian Air Force.",
    funFact:
      "The Mi-28 has a small emergency cabin behind the main cockpit that can carry two passengers for rescue missions — an unusual feature for a dedicated attack helicopter — though they must endure cramped conditions.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "tandem cockpit with stepped seating",
        "stub wings with weapons pylons",
        "nose turret with 30mm cannon",
        "five-blade main rotor",
        "mast-mounted radar (Mi-28N)",
      ],
    },
    aliases: ["Havoc", "Mi-28", "Night Hunter (Mi-28N)"],
  },
  {
    id: "ka-50-hokum",
    name: "Ka-50 Hokum",
    manufacturer: "Kamov",
    type: "Helicopter",
    natoReportingName: "Hokum-A",
    variant: "Ka-50",
    firstFlight: "1982",
    inService: "1995",
    role: "Attack Helicopter",
    country: "Russia",
    specs: {
      length: "52 ft 6 in (16.0 m)",
      maxSpeed: "196 mph (315 km/h)",
      range: "285 mi (460 km)",
      ceiling: "18,700 ft (5,500 m)",
      engines: "2× Klimov TV3-117VK turboshaft",
      crew: "1",
    },
    description:
      "The Ka-50 Black Shark is a single-seat attack helicopter notable for its coaxial contra-rotating rotor system, eliminating the need for a tail rotor. It is the only single-seat attack helicopter in operational service and features a K-37-800 ejection seat — unique among helicopters.",
    funFact:
      "The Ka-50 is the world's only single-seat production attack helicopter, and it has an ejection seat — the rotor blades are explosively jettisoned before the seat fires, making it one of only two helicopters in history with crew ejection capability.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "coaxial contra-rotating rotors",
        "no tail rotor",
        "single-seat cockpit",
        "stub wings with weapons",
        "ejection seat",
      ],
    },
    aliases: ["Hokum", "Ka-50", "Black Shark", "Werewolf"],
  },
  {
    id: "ka-52-alligator",
    name: "Ka-52 Alligator",
    manufacturer: "Kamov",
    type: "Helicopter",
    natoReportingName: "Hokum-B",
    variant: "Ka-52",
    firstFlight: "1997",
    inService: "2011",
    role: "Attack Helicopter",
    country: "Russia",
    specs: {
      length: "52 ft 6 in (16.0 m)",
      maxSpeed: "196 mph (315 km/h)",
      range: "685 mi (1,100 km)",
      ceiling: "18,700 ft (5,500 m)",
      engines: "2× Klimov VK-2500 turboshaft",
      crew: "2",
    },
    description:
      "The Ka-52 Alligator is the two-seat derivative of the Ka-50 Black Shark, featuring a side-by-side cockpit configuration rather than tandem seating. It uses the same coaxial rotor system as the Ka-50 and serves as the Russian Army's primary attack helicopter alongside the Mi-28.",
    funFact:
      "Unlike most attack helicopters with tandem seating, the Ka-52 seats its two crew members side-by-side like a conventional aircraft — a unique arrangement that facilitates crew coordination but increases the fuselage's frontal cross-section.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "coaxial contra-rotating rotors",
        "no tail rotor",
        "side-by-side cockpit",
        "stub wings with weapons",
        "wide nose with sensors",
      ],
    },
    aliases: ["Alligator", "Ka-52", "Hokum-B"],
  },
  {
    id: "eurocopter-tiger",
    name: "Eurocopter Tiger",
    manufacturer: "Airbus Helicopters (formerly Eurocopter)",
    type: "Helicopter",
    variant: "HAP/ARH/UHT",
    firstFlight: "1991",
    inService: "2003",
    role: "Attack Helicopter",
    country: "France/Germany",
    specs: {
      length: "47 ft 2 in (14.38 m)",
      maxSpeed: "178 mph (287 km/h)",
      range: "466 mi (750 km)",
      ceiling: "13,100 ft (3,990 m)",
      engines: "2× Turbomeca/Rolls-Royce MTR390 turboshaft",
      crew: "2",
    },
    description:
      "The Eurocopter Tiger is a Franco-German attack helicopter developed jointly by France and Germany, also used by Australia and Spain. It features an advanced composite construction, mast-mounted sight, and helmet-mounted sighting systems. It operates in anti-tank, escort, and fire support roles.",
    funFact:
      "The Tiger was designed to be highly stealthy by helicopter standards — its all-composite airframe reduces its radar cross-section significantly, and its exhaust suppressors reduce infrared signature to make it harder to target with heat-seeking missiles.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "sleek composite fuselage",
        "tandem stepped cockpit",
        "mast-mounted sight",
        "stub wings with weapons",
        "fenestron enclosed tail rotor",
      ],
    },
    aliases: ["Tiger", "Eurocopter Tiger", "EC665"],
  },
  {
    id: "aw101-merlin",
    name: "AW101 Merlin",
    manufacturer: "AgustaWestland",
    type: "Helicopter",
    variant: "Merlin HM2",
    firstFlight: "1987",
    inService: "1998",
    role: "Anti-Submarine Warfare / Transport",
    country: "UK/Italy",
    specs: {
      length: "74 ft 10 in (22.81 m)",
      maxSpeed: "192 mph (309 km/h)",
      range: "600 mi (1,000 km)",
      ceiling: "15,000 ft (4,575 m)",
      engines: "3× Rolls-Royce/Turbomeca RTM322 turboshaft",
      crew: "3–4",
      capacity: "30 troops",
    },
    description:
      "The AW101 Merlin is a medium-lift military helicopter used by the UK, Italy, Canada, Denmark, Portugal, and others. It operates in anti-submarine warfare, search and rescue, amphibious assault, and VIP transport roles. The Canadian variant serves as the VH-71 Kestrel presidential helicopter candidate.",
    funFact:
      "The Merlin serves as the UK's 'Crowbar' VIP helicopter, transporting the British Prime Minister and senior government officials, making it arguably the most politically important helicopter in British service.",
    visual: {
      engineCount: 3,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "modern",
      distinguishingFeatures: [
        "five-blade main rotor",
        "three engines",
        "folding tail",
        "retractable landing gear",
        "dipping sonar (ASW variants)",
      ],
    },
    aliases: ["Merlin", "AW101", "EH101", "Crowbar"],
  },
  {
    id: "nh90",
    name: "NH90",
    manufacturer: "NHIndustries",
    type: "Helicopter",
    variant: "TTH/NFH",
    firstFlight: "1995",
    inService: "2007",
    role: "Multi-Role Military Helicopter",
    country: "Europe (multi-national)",
    specs: {
      length: "64 ft (19.56 m)",
      maxSpeed: "186 mph (300 km/h)",
      range: "621 mi (1,000 km)",
      ceiling: "20,000 ft (6,096 m)",
      engines: "2× Rolls-Royce/Turbomeca RTM322 or GE T700 turboshaft",
      crew: "2–4",
      capacity: "20 troops",
    },
    description:
      "The NH90 is a medium-size, twin-engine military helicopter developed by a NATO consortium including France, Germany, Italy, Netherlands, and Portugal. It operates in tactical troop transport (TTH) and naval frigates helicopter (NFH) variants, with fly-by-wire flight controls throughout.",
    funFact:
      "The NH90 was the first production helicopter in the world to be equipped with a full fly-by-wire flight control system, replacing traditional mechanical linkages with digital electronic controls for improved handling and reduced pilot workload.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "full fly-by-wire controls",
        "four-blade main rotor",
        "retractable landing gear",
        "rear loading ramp (TTH)",
        "all-composite construction",
      ],
    },
    aliases: ["NH90", "TTH", "NFH"],
  },
  {
    id: "westland-lynx",
    name: "Westland Lynx",
    manufacturer: "Westland Helicopters",
    type: "Helicopter",
    variant: "Lynx AH7/HMA8",
    firstFlight: "1971",
    inService: "1977",
    role: "Anti-Tank / Naval Helicopter",
    country: "UK",
    specs: {
      length: "49 ft 9 in (15.16 m)",
      maxSpeed: "201 mph (324 km/h)",
      range: "368 mi (592 km)",
      ceiling: "10,600 ft (3,230 m)",
      engines: "2× Rolls-Royce Gem turboshaft",
      crew: "2",
      capacity: "10 troops",
    },
    description:
      "The Westland Lynx is a versatile British military helicopter used by the Army for anti-tank and utility roles and by the Navy for anti-submarine warfare and anti-ship roles. In 1986, a modified Lynx set the world helicopter speed record of 249.1 mph (400.87 km/h).",
    funFact:
      "The Lynx held the world absolute speed record for helicopters from 1986 to 2013 — 27 years — when a specially prepared Lynx G-LYNX flew at 249.1 mph. No other helicopter surpassed this until 2013.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "four-blade semi-rigid rotor",
        "compact fuselage",
        "skid or wheeled undercarriage variants",
        "folding rotor blades (naval)",
      ],
    },
    aliases: ["Lynx", "Westland Lynx", "Super Lynx", "Wildcat (successor)"],
  },
  {
    id: "sa-341-gazelle",
    name: "SA 341 Gazelle",
    manufacturer: "Aérospatiale / Westland",
    type: "Helicopter",
    variant: "SA 341B/H",
    firstFlight: "1967",
    inService: "1973",
    role: "Light Utility / Scout",
    country: "France/UK",
    specs: {
      length: "39 ft 3 in (11.97 m)",
      maxSpeed: "193 mph (310 km/h)",
      range: "360 mi (670 km)",
      ceiling: "16,400 ft (5,000 m)",
      engines: "1× Turbomeca Astazou IIIN turboshaft",
      crew: "2",
      capacity: "3 passengers",
    },
    description:
      "The SA 341 Gazelle is a light French military helicopter notable for being the first production helicopter to feature a fenestron (enclosed fan-in-fin) tail rotor, which reduces noise and improves safety. It has been widely exported and served in numerous conflicts.",
    funFact:
      "The Gazelle's fenestron tail rotor — an enclosed shrouded fan inside the tail fin — was a revolutionary innovation when introduced in the 1960s and made the helicopter significantly quieter and safer on the ground than those with exposed tail rotors.",
    visual: {
      engineCount: 1,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "skids",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "fenestron enclosed tail rotor in fin",
        "slim fuselage",
        "large bubble canopy",
        "three-blade main rotor",
        "distinctive tail fin shape",
      ],
    },
    aliases: ["Gazelle", "SA 341", "SA 342"],
  },

  // ============================================================
  // CIVILIAN HELICOPTERS
  // ============================================================
  {
    id: "bell-206-jetranger",
    name: "Bell 206 JetRanger",
    manufacturer: "Bell",
    type: "Helicopter",
    variant: "206B-3",
    firstFlight: "1962",
    inService: "1966",
    role: "Light Utility / Tour / Training",
    country: "USA",
    specs: {
      length: "38 ft 9 in (11.82 m)",
      maxSpeed: "133 mph (214 km/h)",
      range: "397 mi (640 km)",
      ceiling: "13,500 ft (4,115 m)",
      engines: "1× Allison 250-C20B turboshaft",
      crew: "1",
      capacity: "4 passengers",
    },
    description:
      "The Bell 206 JetRanger is one of the most successful and recognizable light turbine helicopters ever built, with over 8,000 produced. It has served in military, police, news, tour, corporate, and agriculture roles worldwide and is the basis for the military OH-58 Kiowa.",
    funFact:
      "The Bell 206 JetRanger was the first helicopter to fly solo around the world non-stop — in 1982, H. Ross Perot Jr. and Jay Coburn completed the circumnavigation in 29 days, 3 hours, and 8 minutes.",
    visual: {
      engineCount: 1,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "skids",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "two-blade semi-rigid rotor",
        "skid gear",
        "elongated teardrop fuselage",
        "large bubble cockpit windows",
        "single turbine engine",
      ],
    },
    aliases: ["JetRanger", "Bell 206", "206B", "LongRanger (stretched)"],
  },
  {
    id: "bell-407",
    name: "Bell 407",
    manufacturer: "Bell",
    type: "Helicopter",
    variant: "407GXi",
    firstFlight: "1995",
    inService: "1996",
    role: "Light Utility / EMS / Law Enforcement",
    country: "USA",
    specs: {
      length: "41 ft 7 in (12.7 m)",
      maxSpeed: "140 mph (225 km/h)",
      range: "390 mi (628 km)",
      ceiling: "18,690 ft (5,697 m)",
      engines: "1× Rolls-Royce 250-C47B turboshaft",
      crew: "1",
      capacity: "6 passengers",
    },
    description:
      "The Bell 407 is a single-turbine light helicopter evolved from the Bell 206L LongRanger. It features a four-blade composite rotor system derived from the military OH-58D Kiowa Warrior, giving it improved performance over the JetRanger family. It is widely used for EMS, law enforcement, and corporate transport.",
    funFact:
      "The Bell 407 borrows its four-blade composite rotor directly from the US Army's OH-58D Kiowa Warrior military scout helicopter, making it one of the few civilian aircraft to directly share rotor technology with a front-line combat aircraft.",
    visual: {
      engineCount: 1,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "skids",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "four-blade composite main rotor",
        "skid gear",
        "wider cabin than Bell 206",
        "T-bar cyclic control",
      ],
    },
    aliases: ["Bell 407", "407GXP", "407GXi"],
  },
  {
    id: "bell-412",
    name: "Bell 412",
    manufacturer: "Bell",
    type: "Helicopter",
    variant: "412EP",
    firstFlight: "1979",
    inService: "1981",
    role: "Medium Utility / Offshore / EMS",
    country: "USA/Canada",
    specs: {
      length: "56 ft 2 in (17.12 m)",
      maxSpeed: "161 mph (259 km/h)",
      range: "402 mi (648 km)",
      ceiling: "20,000 ft (6,096 m)",
      engines: "2× Pratt & Whitney Canada PT6T-3D twin turboshaft",
      crew: "1–2",
      capacity: "13 passengers",
    },
    description:
      "The Bell 412 is a twin-engine utility helicopter derived from the Bell 212 with a four-blade composite rotor replacing the original two-blade teetering rotor. Widely used for offshore oil and gas support, military utility transport, EMS, and SAR. The military version is the UH-1N Twin Huey.",
    funFact:
      "The Bell 412's twin-engine configuration uses a 'Twin Pac' — two PT6 turboshaft engines linked together driving a single output shaft — a clever design that allows either engine alone to maintain flight if the other fails.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "skids",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "four-blade composite rotor",
        "twin turboshaft engines (Twin Pac)",
        "skid gear",
        "wide cabin with sliding doors",
      ],
    },
    aliases: ["Bell 412", "412EP", "412EPI", "UH-1N (military)"],
  },
  {
    id: "bell-429",
    name: "Bell 429",
    manufacturer: "Bell",
    type: "Helicopter",
    variant: "Bell 429",
    firstFlight: "2007",
    inService: "2009",
    role: "Light Twin / EMS / Corporate",
    country: "USA/Canada",
    specs: {
      length: "42 ft 5 in (12.93 m)",
      maxSpeed: "178 mph (287 km/h)",
      range: "466 mi (749 km)",
      ceiling: "17,600 ft (5,364 m)",
      engines: "2× Honeywell HTS900-2 turboshaft",
      crew: "1–2",
      capacity: "7 passengers",
    },
    description:
      "The Bell 429 is a modern light twin-engine helicopter with a wide flat-floor cabin, IFR capabilities, and a full-authority digital engine control (FADEC) system. It is Bell's most technologically advanced light twin and is popular for EMS, law enforcement, and corporate operations.",
    funFact:
      "The Bell 429 was the first helicopter certified under the new FAA rotorcraft performance requirements with a wide-body flat-floor cabin, giving it an almost van-like interior volume for its external size — a major advantage for EMS operations.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "skids",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "four-blade semi-rigid rotor",
        "wide flat-floor cabin",
        "twin engines side by side",
        "skid gear",
        "glass cockpit",
      ],
    },
    aliases: ["Bell 429", "429WLG (wheeled landing gear variant)"],
  },
  {
    id: "bell-505",
    name: "Bell 505 Jet Ranger X",
    manufacturer: "Bell",
    type: "Helicopter",
    variant: "Bell 505",
    firstFlight: "2014",
    inService: "2016",
    role: "Light Utility / Training / Tour",
    country: "USA",
    specs: {
      length: "36 ft 9 in (11.2 m)",
      maxSpeed: "125 mph (201 km/h)",
      range: "369 mi (594 km)",
      ceiling: "18,200 ft (5,547 m)",
      engines: "1× Safran Arriel 2R turboshaft",
      crew: "1",
      capacity: "4 passengers",
    },
    description:
      "The Bell 505 Jet Ranger X is the modern successor to the legendary Bell 206 JetRanger, featuring a Garmin G1000H glass cockpit, improved performance, and lower operating costs. It is designed for training, tour operations, and personal utility missions with a fully digital flight management system.",
    funFact:
      "Despite being named the Jet Ranger X as a successor to the original JetRanger, the Bell 505 is designed around a clean-sheet platform and shares no major components with the original 206 — it represents a complete generational leap in light helicopter design.",
    visual: {
      engineCount: 1,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "skids",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "Garmin G1000H glass cockpit",
        "four-blade composite rotor",
        "skid gear",
        "modern streamlined fuselage",
      ],
    },
    aliases: ["Bell 505", "Jet Ranger X", "JRX"],
  },
  {
    id: "robinson-r22",
    name: "Robinson R22",
    manufacturer: "Robinson Helicopter Company",
    type: "Helicopter",
    variant: "R22 Beta II",
    firstFlight: "1975",
    inService: "1979",
    role: "Training / Personal",
    country: "USA",
    specs: {
      length: "28 ft 8 in (8.76 m)",
      maxSpeed: "102 mph (164 km/h)",
      range: "218 mi (350 km)",
      ceiling: "14,000 ft (4,267 m)",
      engines: "1× Lycoming O-320 piston",
      crew: "1",
      capacity: "1 passenger",
    },
    description:
      "The Robinson R22 is a two-seat light piston helicopter that became the world's most popular helicopter trainer. Its low purchase and operating costs made helicopter training accessible to a much broader audience, though it has strict weight and temperature limitations due to its small engine.",
    funFact:
      "The Robinson R22 is the most common helicopter used for private pilot training worldwide, yet it has a unique 'low rotor RPM' warning system because its light rotor has less inertia — pilots must be especially careful not to allow RPM to decay during autorotations.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "skids",
      sizeClass: "ultralight",
      era: "modern",
      distinguishingFeatures: [
        "two-blade teetering main rotor",
        "very compact fuselage",
        "skid gear",
        "piston engine",
        "side-by-side seating",
        "T-bar cyclic",
      ],
    },
    aliases: ["R22", "Robinson R22"],
  },
  {
    id: "robinson-r44",
    name: "Robinson R44",
    manufacturer: "Robinson Helicopter Company",
    type: "Helicopter",
    variant: "R44 Cadet / Raven II",
    firstFlight: "1990",
    inService: "1993",
    role: "Light Utility / Tour / Training",
    country: "USA",
    specs: {
      length: "38 ft 2 in (11.63 m)",
      maxSpeed: "130 mph (209 km/h)",
      range: "300 mi (483 km)",
      ceiling: "14,000 ft (4,267 m)",
      engines: "1× Lycoming IO-540 piston",
      crew: "1",
      capacity: "3 passengers",
    },
    description:
      "The Robinson R44 is a four-seat piston helicopter and the world's best-selling general aviation helicopter. It offers significantly more capability than the R22 with a larger cabin and more powerful engine, while maintaining the Robinson philosophy of simplicity and low operating costs.",
    funFact:
      "The Robinson R44 is the world's best-selling helicopter year after year, with more R44s delivered annually than any other helicopter model — a remarkable achievement for a piston-powered aircraft competing against turbine-powered alternatives.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "skids",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "two-blade teetering main rotor",
        "four-seat cabin",
        "skid gear",
        "piston engine",
        "larger than R22",
      ],
    },
    aliases: ["R44", "Robinson R44", "Raven", "Astro"],
  },
  {
    id: "robinson-r66",
    name: "Robinson R66",
    manufacturer: "Robinson Helicopter Company",
    type: "Helicopter",
    variant: "R66",
    firstFlight: "2007",
    inService: "2010",
    role: "Light Utility / Tour",
    country: "USA",
    specs: {
      length: "39 ft 5 in (12.01 m)",
      maxSpeed: "140 mph (226 km/h)",
      range: "350 mi (563 km)",
      ceiling: "14,000 ft (4,267 m)",
      engines: "1× Rolls-Royce RR300 turboshaft",
      crew: "1",
      capacity: "4 passengers",
    },
    description:
      "The Robinson R66 is a five-seat turbine helicopter based on the R44 airframe but powered by a Rolls-Royce turboshaft engine. It bridges the gap between piston Robinson helicopters and more expensive turbine alternatives, offering turbine reliability with Robinson's renowned simplicity and low cost.",
    funFact:
      "Robinson's Frank Robinson designed the R66 with a turbine engine at age 77, showing that the founder's innovative drive never diminished — the R66 became the most affordable certified turbine helicopter on the market upon its introduction.",
    visual: {
      engineCount: 1,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "skids",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "two-blade teetering main rotor",
        "turbine engine (vs piston R44)",
        "five-seat cabin",
        "skid gear",
        "similar profile to R44",
      ],
    },
    aliases: ["R66", "Robinson R66"],
  },
  {
    id: "sikorsky-s76",
    name: "Sikorsky S-76",
    manufacturer: "Sikorsky",
    type: "Helicopter",
    variant: "S-76D",
    firstFlight: "1977",
    inService: "1979",
    role: "Corporate / Offshore / EMS",
    country: "USA",
    specs: {
      length: "52 ft 6 in (16.0 m)",
      maxSpeed: "178 mph (287 km/h)",
      range: "441 mi (710 km)",
      ceiling: "15,000 ft (4,572 m)",
      engines: "2× Pratt & Whitney Canada PW210S turboshaft",
      crew: "1–2",
      capacity: "12 passengers",
    },
    description:
      "The Sikorsky S-76 is a twin-turbine commercial helicopter designed specifically for corporate transport and offshore oil and gas support. It features retractable landing gear — unusual for a commercial helicopter — and has served as presidential transport in numerous countries.",
    funFact:
      "Sikorsky S-76s have served as helicopters for multiple heads of state, and it was the helicopter of choice for Queen Elizabeth II of the United Kingdom for several decades — one of the aircraft she preferred for travel to Balmoral Castle.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "retractable tricycle landing gear",
        "four-blade composite rotor",
        "streamlined fuselage",
        "twin engines",
        "wide corporate cabin",
      ],
    },
    aliases: ["S-76", "Sikorsky S-76", "Spirit", "Eagle"],
  },
  {
    id: "sikorsky-s92",
    name: "Sikorsky S-92",
    manufacturer: "Sikorsky",
    type: "Helicopter",
    variant: "S-92A",
    firstFlight: "1998",
    inService: "2004",
    role: "Heavy Commercial / Offshore / VIP",
    country: "USA",
    specs: {
      length: "66 ft 9 in (20.35 m)",
      maxSpeed: "189 mph (304 km/h)",
      range: "598 mi (963 km)",
      ceiling: "15,000 ft (4,572 m)",
      engines: "2× General Electric CT7-8A turboshaft",
      crew: "2",
      capacity: "19 passengers",
    },
    description:
      "The Sikorsky S-92 is a large commercial helicopter used extensively for offshore oil and gas transport, VIP/executive transport, and SAR. It is the primary helicopter used for US presidential support (Marine One operations) and is operated by the Irish Air Corps as their VIP helicopter.",
    funFact:
      "The S-92 serves as the primary helicopter for the US Presidential support mission — while the VH-3D Sea King is the famous 'Marine One,' the S-92 variants (VH-92A) are replacing them and will become the official Marine One in the 2020s.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "four-blade composite main rotor",
        "retractable landing gear",
        "wide fuselage",
        "twin GE turboshaft engines",
        "rear clamshell doors optional",
      ],
    },
    aliases: ["S-92", "Sikorsky S-92", "VH-92A (presidential)"],
  },
  {
    id: "airbus-h125",
    name: "Airbus H125",
    manufacturer: "Airbus Helicopters",
    type: "Helicopter",
    variant: "H125 (formerly AS350 B3)",
    firstFlight: "1974",
    inService: "1977",
    role: "Light Utility / Tour / Agricultural",
    country: "France",
    specs: {
      length: "42 ft 6 in (12.94 m)",
      maxSpeed: "178 mph (287 km/h)",
      range: "370 mi (596 km)",
      ceiling: "23,000 ft (7,010 m)",
      engines: "1× Safran Arriel 2D turboshaft",
      crew: "1",
      capacity: "5 passengers",
    },
    description:
      "The Airbus H125 (formerly AS350 Écureuil/Squirrel) is one of the world's most popular single-engine commercial helicopters. Known for exceptional high-altitude performance, it holds the record for the highest helicopter landing ever — on the summit of Mount Everest in 2005.",
    funFact:
      "On May 14, 2005, test pilot Didier Delsalle landed an AS350 B3 (H125 predecessor) on the summit of Mount Everest at 29,032 feet — the highest helicopter landing ever recorded, a feat that remained unchallenged for decades.",
    visual: {
      engineCount: 1,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "skids",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "three-blade Starflex rotor system",
        "fenestron tail option or conventional tail rotor",
        "skid gear",
        "wide bubble canopy",
        "single turbine engine",
      ],
    },
    aliases: ["H125", "AS350", "Ecureuil", "Squirrel", "AStar", "B3"],
  },
  {
    id: "airbus-h130",
    name: "Airbus H130",
    manufacturer: "Airbus Helicopters",
    type: "Helicopter",
    variant: "H130 T2 (formerly EC130)",
    firstFlight: "1999",
    inService: "2001",
    role: "Light Tour / VIP / EMS",
    country: "France",
    specs: {
      length: "38 ft 9 in (11.82 m)",
      maxSpeed: "155 mph (250 km/h)",
      range: "368 mi (592 km)",
      ceiling: "23,000 ft (7,010 m)",
      engines: "1× Safran Arriel 2D turboshaft",
      crew: "1",
      capacity: "7 passengers",
    },
    description:
      "The Airbus H130 is a single-engine light helicopter designed for tourist operations, featuring a panoramic cabin with excellent visibility for all passengers. It uses a Fenestron enclosed tail rotor for reduced noise, making it popular at noise-sensitive tourist locations like national parks.",
    funFact:
      "The H130 is the most-used helicopter for Grand Canyon aerial tours, chosen for its wide panoramic windows and especially quiet Fenestron tail rotor that helps manage noise impacts on park wildlife and visitors below.",
    visual: {
      engineCount: 1,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "skids",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "fenestron enclosed tail rotor",
        "panoramic cabin windows",
        "wide cabin for 7",
        "skid gear",
        "low-noise design",
      ],
    },
    aliases: ["H130", "EC130", "B4", "T2"],
  },
  {
    id: "airbus-h135",
    name: "Airbus H135",
    manufacturer: "Airbus Helicopters",
    type: "Helicopter",
    variant: "H135 T3 (formerly EC135)",
    firstFlight: "1994",
    inService: "1996",
    role: "Light Twin / EMS / Law Enforcement",
    country: "Germany/France",
    specs: {
      length: "39 ft 4 in (11.99 m)",
      maxSpeed: "178 mph (287 km/h)",
      range: "395 mi (635 km)",
      ceiling: "20,000 ft (6,096 m)",
      engines: "2× Pratt & Whitney Canada PW206B3 or Safran Arriel 2B1 turboshaft",
      crew: "1–2",
      capacity: "5–7 passengers",
    },
    description:
      "The Airbus H135 is a twin-engine light helicopter widely used for EMS (emergency medical service), law enforcement, police, and training. Its Fenestron tail rotor, bearingless main rotor, and full-authority digital engine control make it one of the most advanced light twins available.",
    funFact:
      "The H135 is the world's most widely used helicopter for EMS operations, with thousands flying medical missions daily across six continents — its combination of twin-engine safety, quiet Fenestron, and cabin access makes it ideal for landing in urban environments.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "skids",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "fenestron enclosed tail rotor",
        "bearingless main rotor",
        "twin engines",
        "skid gear",
        "wide flat-floor cabin",
      ],
    },
    aliases: ["H135", "EC135", "EC135 T3"],
  },
  {
    id: "airbus-h145",
    name: "Airbus H145",
    manufacturer: "Airbus Helicopters",
    type: "Helicopter",
    variant: "H145 D3 (formerly EC145)",
    firstFlight: "1999",
    inService: "2002",
    role: "Medium Twin / EMS / Utility",
    country: "Germany",
    specs: {
      length: "42 ft 8 in (13.03 m)",
      maxSpeed: "153 mph (246 km/h)",
      range: "431 mi (694 km)",
      ceiling: "20,000 ft (6,096 m)",
      engines: "2× Safran Arriel 2E turboshaft",
      crew: "1–2",
      capacity: "9 passengers",
    },
    description:
      "The Airbus H145 is a twin-engine medium helicopter combining the proven components of the BK 117 and EC135 families. The latest D3 variant introduced a five-blade rotor and advanced Fenestron tail rotor, making it one of the quietest helicopters in its class. Used by the US Army as the UH-72 Lakota.",
    funFact:
      "The H145 D3 variant introduced the first five-blade bearingless main rotor on a civil helicopter, which reduced noise and vibration so dramatically that passengers inside experience ride quality comparable to a limousine.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "skids",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "five-blade bearingless rotor (D3)",
        "fenestron tail rotor",
        "twin engines",
        "flat-floor cabin",
        "skid gear",
      ],
    },
    aliases: ["H145", "EC145", "BK 117 D3", "UH-72 Lakota (military)", "H145M"],
  },
  {
    id: "airbus-h160",
    name: "Airbus H160",
    manufacturer: "Airbus Helicopters",
    type: "Helicopter",
    variant: "H160",
    firstFlight: "2015",
    inService: "2021",
    role: "Medium Twin / Offshore / VIP / EMS",
    country: "France",
    specs: {
      length: "51 ft 1 in (15.57 m)",
      maxSpeed: "178 mph (287 km/h)",
      range: "542 mi (872 km)",
      ceiling: "20,000 ft (6,096 m)",
      engines: "2× Safran Arrano 1A turboshaft",
      crew: "1–2",
      capacity: "12 passengers",
    },
    description:
      "The Airbus H160 is a next-generation medium helicopter featuring a revolutionary Blue Edge rotor blade with curved tips that dramatically reduce noise. It also features an innovative Fenestron tail rotor canted at 12 degrees, biplane stabilizers, and advanced active vibration control.",
    funFact:
      "The H160's 'Blue Edge' rotor blades have a distinctive curved, scimitar-shaped tip that reduces blade-vortex interaction noise — the helicopter is so quiet that residents near heliports can barely hear it in approach.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Blue Edge curved-tip rotor blades",
        "canted fenestron tail rotor",
        "biplane horizontal stabilizers",
        "retractable landing gear",
        "innovative composite airframe",
      ],
    },
    aliases: ["H160", "Airbus H160"],
  },
  {
    id: "airbus-h175",
    name: "Airbus H175",
    manufacturer: "Airbus Helicopters",
    type: "Helicopter",
    variant: "H175",
    firstFlight: "2009",
    inService: "2014",
    role: "Super-Medium / Offshore / SAR",
    country: "France/China",
    specs: {
      length: "59 ft 1 in (18.02 m)",
      maxSpeed: "178 mph (287 km/h)",
      range: "504 mi (810 km)",
      ceiling: "20,000 ft (6,096 m)",
      engines: "2× Pratt & Whitney Canada PT6C-67E turboshaft",
      crew: "2",
      capacity: "16 passengers",
    },
    description:
      "The Airbus H175 is a super-medium helicopter developed in partnership between Airbus Helicopters and Chinese manufacturer Avicopter (AVIC). Positioned between the H155 and H225, it features a five-blade main rotor, Fenestron tail rotor, and is designed specifically for offshore oil and gas operations.",
    funFact:
      "The H175 is the result of the first major civil helicopter joint development program between a Western manufacturer (Airbus Helicopters) and a Chinese state enterprise (AVIC), signaling the increasing role of China in advanced aerospace manufacturing.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "five-blade composite main rotor",
        "fenestron tail rotor",
        "retractable landing gear",
        "wide offshore-configured cabin",
      ],
    },
    aliases: ["H175", "EC175", "Z-15 (Chinese designation)"],
  },
  {
    id: "airbus-h215-h225",
    name: "Airbus H215 / H225 Super Puma",
    manufacturer: "Airbus Helicopters",
    type: "Helicopter",
    variant: "H225M (EC725) / H215M (AS532)",
    firstFlight: "1978",
    inService: "1981",
    role: "Heavy Utility / Offshore / SAR",
    country: "France",
    specs: {
      length: "67 ft 4 in (20.53 m)",
      maxSpeed: "192 mph (309 km/h)",
      range: "857 mi (1,379 km)",
      ceiling: "15,090 ft (4,600 m)",
      engines: "2× Turbomeca Makila 2A1 turboshaft",
      crew: "2",
      capacity: "24 passengers",
    },
    description:
      "The H215/H225 Super Puma family is a range of heavy twin-turbine helicopters based on the original Aérospatiale SA 330 Puma. Used extensively for offshore oil and gas transport, SAR, and military assault. The military EC725/H225M Caracal serves as a special operations and combat SAR helicopter.",
    funFact:
      "The H225 Super Puma suffered a series of catastrophic gearbox failures in offshore operations that led to a temporary worldwide grounding in 2016 — leading to a complete redesign of the main gearbox and the most comprehensive helicopter safety review in offshore history.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "modern",
      distinguishingFeatures: [
        "four-blade composite main rotor",
        "retractable tricycle gear",
        "large cabin",
        "sponson fuel tanks",
        "in-flight refueling probe (military)",
      ],
    },
    aliases: ["Super Puma", "H225", "EC225", "H215", "AS332", "Caracal (military)", "EC725"],
  },
  {
    id: "aw139",
    name: "AW139",
    manufacturer: "Leonardo (AgustaWestland)",
    type: "Helicopter",
    variant: "AW139",
    firstFlight: "2001",
    inService: "2003",
    role: "Medium-Heavy / Offshore / SAR / VIP",
    country: "Italy",
    specs: {
      length: "56 ft 4 in (17.17 m)",
      maxSpeed: "193 mph (310 km/h)",
      range: "572 mi (920 km)",
      ceiling: "20,000 ft (6,096 m)",
      engines: "2× Pratt & Whitney Canada PT6C-67C turboshaft",
      crew: "2",
      capacity: "15 passengers",
    },
    description:
      "The AW139 is a large medium helicopter jointly developed by AgustaWestland (now Leonardo) and Bell Helicopter. It became one of the best-selling medium helicopters in the world, used extensively for offshore oil support, SAR, law enforcement, and VIP transport. It serves as the presidential helicopter of several nations.",
    funFact:
      "The AW139 was selected as the US presidential helicopter (as the VH-71 Kestrel) in 2005, but the US Navy cancelled the program in 2009 after costs ballooned to $13 billion for 28 aircraft — one of the most expensive helicopter procurement failures in US history.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "five-blade composite main rotor",
        "retractable tricycle gear",
        "wide cabin",
        "twin PT6 turboshaft engines",
        "modern glass cockpit",
      ],
    },
    aliases: ["AW139", "AgustaWestland AW139"],
  },
  {
    id: "aw169",
    name: "AW169",
    manufacturer: "Leonardo (AgustaWestland)",
    type: "Helicopter",
    variant: "AW169",
    firstFlight: "2012",
    inService: "2015",
    role: "Light-Medium Twin / EMS / Offshore",
    country: "Italy",
    specs: {
      length: "47 ft 4 in (14.42 m)",
      maxSpeed: "178 mph (287 km/h)",
      range: "497 mi (800 km)",
      ceiling: "20,000 ft (6,096 m)",
      engines: "2× Pratt & Whitney Canada PW210A turboshaft",
      crew: "1–2",
      capacity: "10 passengers",
    },
    description:
      "The AW169 is a new-generation light-medium twin helicopter designed for EMS, law enforcement, offshore, and corporate operations. It features a fully composite airframe, four-axis autopilot, active vibration control, and retractable landing gear for improved aerodynamic performance.",
    funFact:
      "The AW169 was the helicopter used in the fatal crash that killed Leicester City FC owner Vichai Srivaddhanaprabha in October 2018, following which helicopter tail rotor failure investigations were significantly enhanced across the industry.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "four-blade composite main rotor",
        "retractable tricycle gear",
        "all-composite airframe",
        "twin engines",
        "wide flat-floor cabin",
      ],
    },
    aliases: ["AW169"],
  },
  {
    id: "aw189",
    name: "AW189",
    manufacturer: "Leonardo (AgustaWestland)",
    type: "Helicopter",
    variant: "AW189",
    firstFlight: "2011",
    inService: "2014",
    role: "Super-Medium / Offshore / SAR",
    country: "Italy",
    specs: {
      length: "61 ft 8 in (18.79 m)",
      maxSpeed: "196 mph (316 km/h)",
      range: "869 mi (1,400 km)",
      ceiling: "20,000 ft (6,096 m)",
      engines: "2× General Electric CT7-2E1 turboshaft",
      crew: "2",
      capacity: "18 passengers",
    },
    description:
      "The AW189 is a super-medium twin helicopter designed primarily for offshore oil and gas operations and search and rescue. It features a five-blade composite rotor system, retractable landing gear, advanced avionics, and the largest cabin in its class, making it competitive with the Sikorsky S-92 and Airbus H225.",
    funFact:
      "The AW189 features a fully integrated Health and Usage Monitoring System (HUMS) that continuously monitors 2,500 aircraft parameters in real time, allowing maintenance teams to predict component failures before they occur — a major step forward in helicopter safety.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "five-blade composite main rotor",
        "retractable tricycle gear",
        "large offshore cabin",
        "twin GE turboshaft engines",
        "advanced HUMS system",
      ],
    },
    aliases: ["AW189"],
  },
  {
    id: "md-500",
    name: "MD 500",
    manufacturer: "MD Helicopters",
    type: "Helicopter",
    variant: "MD 500E",
    firstFlight: "1963",
    inService: "1968",
    role: "Light Utility / Scout",
    country: "USA",
    specs: {
      length: "30 ft 10 in (9.4 m)",
      maxSpeed: "175 mph (282 km/h)",
      range: "232 mi (373 km)",
      ceiling: "16,000 ft (4,877 m)",
      engines: "1× Allison 250-C20B turboshaft",
      crew: "1",
      capacity: "4 passengers",
    },
    description:
      "The MD 500 series is a family of light helicopters derived from the Hughes OH-6 Cayuse military scout helicopter, which won the US Army light observation helicopter competition in 1961. Known for its distinctive egg-shaped fuselage and outstanding agility, it serves military and civilian roles worldwide.",
    funFact:
      "The MD 500 is unofficially known as 'the Loach' from its military OH-6 variant name — a corruption of 'LOH' (Light Observation Helicopter) — and it famously flew lower, slower, and more dangerously close to enemy positions in Vietnam than almost any other aircraft.",
    visual: {
      engineCount: 1,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "skids",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "distinctive egg-shaped fuselage",
        "five-blade main rotor",
        "no tail fin — V-shaped tail",
        "skid gear",
        "very compact size",
      ],
    },
    aliases: ["MD 500", "Hughes 500", "OH-6 Cayuse", "Loach", "Defender"],
  },
  {
    id: "md-902-explorer",
    name: "MD 902 Explorer",
    manufacturer: "MD Helicopters",
    type: "Helicopter",
    variant: "MD 902",
    firstFlight: "1992",
    inService: "1994",
    role: "Light Twin / EMS / Law Enforcement",
    country: "USA",
    specs: {
      length: "38 ft 1 in (11.61 m)",
      maxSpeed: "155 mph (249 km/h)",
      range: "394 mi (634 km)",
      ceiling: "20,000 ft (6,096 m)",
      engines: "2× Pratt & Whitney Canada PW206E turboshaft",
      crew: "1",
      capacity: "7 passengers",
    },
    description:
      "The MD 902 Explorer is a twin-engine light helicopter featuring MD Helicopters' patented NOTAR (No Tail Rotor) system, which uses a pressurized air jet and circulation control to provide directional control instead of a conventional tail rotor. This makes it extremely quiet and safer around people on the ground.",
    funFact:
      "The MD 902's NOTAR system eliminates the tail rotor entirely — instead, pressurized air is blown through slots in the tail boom, using the Coanda effect to generate sideways thrust. This makes it one of the safest helicopters for operations near people since there is no spinning tail rotor.",
    visual: {
      engineCount: 2,
      engineType: "turboshaft",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "no-tail",
      landingGear: "skids",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "NOTAR — no tail rotor",
        "pressurized tail boom with exhaust slots",
        "five-blade main rotor",
        "twin engines",
        "very quiet operation",
      ],
    },
    aliases: ["MD 902", "MD Explorer", "NOTAR helicopter"],
  },
  {
    id: "schweizer-300",
    name: "Schweizer 300",
    manufacturer: "Schweizer Aircraft",
    type: "Helicopter",
    variant: "300C / 300CBi",
    firstFlight: "1956",
    inService: "1965",
    role: "Training / Agricultural",
    country: "USA",
    specs: {
      length: "30 ft 10 in (9.4 m)",
      maxSpeed: "100 mph (161 km/h)",
      range: "185 mi (298 km)",
      ceiling: "10,200 ft (3,109 m)",
      engines: "1× HIO-360-D1A piston or HIO-360-G1A",
      crew: "1",
      capacity: "2 passengers",
    },
    description:
      "The Schweizer 300 (formerly Hughes 300) is a three-seat piston training helicopter derived from the Hughes 269. It became one of the most widely used helicopter trainers in the world due to its forgiving flight characteristics, low cost, and simple maintenance. Also used extensively for agricultural spraying.",
    funFact:
      "The Schweizer 300C has an extremely forgiving flight envelope that makes it one of the best primary trainers ever built — its fully articulated rotor forgives many student errors that would be fatal in other helicopters, leading to its adoption by hundreds of flight schools worldwide.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "top-mounted",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "skids",
      sizeClass: "ultralight",
      era: "cold-war",
      distinguishingFeatures: [
        "open framework tail boom",
        "three-blade main rotor",
        "skid gear",
        "piston engine",
        "exposed tail rotor structure",
        "small bubble canopy",
      ],
    },
    aliases: ["Schweizer 300", "Hughes 300", "269C", "300C", "300CBi"],
  },
];
