import { AircraftEntry } from "./types";

export const militaryFighters: AircraftEntry[] = [
  // ============================================================
  // US FIGHTERS
  // ============================================================
  {
    id: "f-4-phantom-ii",
    name: "F-4 Phantom II",
    manufacturer: "McDonnell Douglas",
    type: "Fighter",
    firstFlight: "1958-05-27",
    inService: "1960",
    role: "Multirole Fighter / Interceptor",
    country: "USA",
    specs: {
      wingspan: "38 ft 5 in (11.7 m)",
      length: "63 ft (19.2 m)",
      maxSpeed: "Mach 2.23 (1,472 mph)",
      range: "1,615 mi (2,600 km)",
      ceiling: "60,000 ft (18,300 m)",
      engines: "2x General Electric J79-GE-17A turbojet",
      crew: "2",
    },
    description:
      "The F-4 Phantom II is a tandem two-seat, twin-engine, all-weather, long-range supersonic jet interceptor and fighter-bomber. It served as the primary air superiority fighter for the US Navy, Marine Corps, and Air Force during the Vietnam War era and was operated by 11 nations.",
    funFact:
      "The F-4 had no internal gun and relied entirely on missiles — early Vietnam losses prompted the US Navy to revive its fighter weapons school (Top Gun). The USAF added an internal gun pod and eventually redesigned later variants with a built-in M61 Vulcan.",
    visual: {
      engineCount: 2,
      engineType: "turbojet",
      enginePlacement: "twin engines buried in fuselage with side intakes",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "large",
      era: "cold-war",
      distinguishingFeatures: [
        "pronounced anhedral (drooped) outer wing panels",
        "upturned wingtips",
        "raised rear tandem cockpit",
        "large slab stabilators with pronounced anhedral",
        "twin exhaust nozzles with afterburner cans",
        "ventral fins beneath rear fuselage",
        "large bubble canopy over front seat",
        "long pointed nose with large radome",
      ],
    },
    aliases: ["Phantom", "Double Ugly", "Rhino", "Flying Anvil"],
  },
  {
    id: "f-5-tiger-ii",
    name: "F-5 Tiger II",
    manufacturer: "Northrop",
    type: "Fighter",
    variant: "F-5E/F",
    firstFlight: "1972-08-11",
    inService: "1974",
    role: "Light Fighter / Aggressor",
    country: "USA",
    specs: {
      wingspan: "26 ft 8 in (8.13 m)",
      length: "47 ft 4 in (14.45 m)",
      maxSpeed: "Mach 1.63 (1,075 mph)",
      range: "1,543 mi (2,483 km)",
      ceiling: "51,800 ft (15,790 m)",
      engines: "2x General Electric J85-GE-21B turbojet",
      crew: "1",
    },
    description:
      "The F-5 Tiger II is a lightweight, low-cost supersonic fighter developed for export and widely used as a US military aggressor aircraft in dissimilar air combat training. Over 3,800 were produced across all variants, serving more than 30 nations.",
    funFact:
      "The F-5's tight turn radius and small radar cross section made it an ideal adversary aircraft simulating Soviet fighters in US training programs — its performance envelope closely matched the MiG-21, making it the standard aggressor for decades.",
    visual: {
      engineCount: 2,
      engineType: "turbojet",
      enginePlacement: "twin engines in lower fuselage with paired cheek inlets",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "very compact, slim fuselage",
        "paired cheek air inlets flanking the nose on each side",
        "small squared wingtips with wingtip missile rails",
        "twin side-by-side engine nozzles at tail",
        "twin ventral fins",
        "streamlined low-drag profile",
        "small nose radome",
      ],
    },
    aliases: ["Tiger II", "Freedom Fighter (F-5A variant)"],
  },
  {
    id: "f-14-tomcat",
    name: "F-14 Tomcat",
    manufacturer: "Grumman",
    type: "Fighter",
    firstFlight: "1970-12-21",
    inService: "1974",
    role: "Carrier-based Air Superiority / Fleet Defense Interceptor",
    country: "USA",
    specs: {
      wingspan: "64 ft (19.5 m) spread / 38 ft (11.6 m) swept",
      length: "62 ft 8 in (19.1 m)",
      maxSpeed: "Mach 2.34 (1,544 mph)",
      range: "1,600 mi (2,575 km)",
      ceiling: "50,000 ft (15,240 m)",
      engines: "2x General Electric F110-GE-400 turbofan",
      crew: "2",
    },
    description:
      "The F-14 Tomcat was the US Navy's premier carrier-based fighter from the 1970s until retirement in 2006. Its variable-sweep wing, AWG-9 radar, and AIM-54 Phoenix missiles gave it unmatched fleet defense capability. It starred in the 1986 film Top Gun.",
    funFact:
      "The F-14's AWG-9 radar and AIM-54 Phoenix missiles could simultaneously track 24 targets and engage 6 at ranges exceeding 100 miles — a beyond-visual-range capability that remained unmatched for decades.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines in widely spaced nacelles beneath box fuselage",
      wingPosition: "variable",
      wingShape: "variable-sweep",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "large",
      era: "cold-war",
      distinguishingFeatures: [
        "variable-sweep wings sweeping from 20 to 68 degrees in flight",
        "twin widely spaced vertical tails canted slightly outward",
        "large box-like fuselage tunnel between engine nacelles",
        "prominent wing glove vanes at sweep pivot",
        "tandem two-seat cockpit with large bubble canopy",
        "chin-mounted IRST/TCS sensor pod",
        "distinctive flat underside fuselage",
        "automatic wing sweep controlled by CADC computer",
      ],
    },
    aliases: ["Tomcat", "Turkey (affectionate pilot nickname)"],
  },
  {
    id: "f-15-eagle",
    name: "F-15 Eagle",
    manufacturer: "McDonnell Douglas",
    type: "Fighter",
    firstFlight: "1972-07-27",
    inService: "1976",
    role: "Air Superiority Fighter",
    country: "USA",
    specs: {
      wingspan: "42 ft 10 in (13.05 m)",
      length: "63 ft 9 in (19.43 m)",
      maxSpeed: "Mach 2.5+ (1,650 mph)",
      range: "1,200 mi (1,930 km), ferry 3,450 mi",
      ceiling: "65,000 ft (20,000 m)",
      engines: "2x Pratt & Whitney F100-PW-220 turbofan",
      crew: "1",
    },
    description:
      "The F-15 Eagle is an all-weather tactical fighter designed to gain and maintain air superiority in aerial combat. Its undefeated air-to-air combat record — over 100 kills with zero losses — makes it one of the most successful fighters in aviation history.",
    funFact:
      "An Israeli F-15D once landed safely on one wing after a mid-air collision severed the right wing at the root during a 1983 training accident — the pilot didn't realize the wing was gone until he landed and looked out.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines in fuselage with large rectangular fixed inlets",
      wingPosition: "low",
      wingShape: "trapezoidal",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "large",
      era: "modern",
      distinguishingFeatures: [
        "large squared-off fixed air intakes on each fuselage side",
        "twin vertical tails",
        "very large trapezoidal wing",
        "raised avionics spine behind cockpit",
        "single-seat bubble canopy with excellent all-around visibility",
        "high thrust-to-weight ratio enabling vertical climbs",
        "no wing sweep pivot, fixed trapezoidal planform",
      ],
    },
    aliases: ["Eagle"],
  },
  {
    id: "f-15e-strike-eagle",
    name: "F-15E Strike Eagle",
    manufacturer: "McDonnell Douglas / Boeing",
    type: "Strike Fighter",
    variant: "F-15E",
    firstFlight: "1986-12-11",
    inService: "1989",
    role: "Multirole Strike Fighter",
    country: "USA",
    specs: {
      wingspan: "42 ft 10 in (13.05 m)",
      length: "63 ft 9 in (19.43 m)",
      maxSpeed: "Mach 2.5+ (1,650 mph)",
      range: "2,400 mi (3,860 km) with CFTs",
      ceiling: "60,000 ft (18,200 m)",
      engines: "2x Pratt & Whitney F100-PW-229 turbofan",
      crew: "2",
    },
    description:
      "The F-15E Strike Eagle is a dual-role fighter capable of air-to-air and precision air-to-ground missions in all weather, day or night. Its rear-seat WSO station and conformal fuel tanks (CFTs) give it range and weapons capacity surpassing many dedicated bombers.",
    funFact:
      "The F-15E can carry up to 23,000 lb of ordnance — more than a WWII-era B-17 Flying Fortress bomber — while retaining full air superiority capability with its own radar and missiles for self-defense.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines in fuselage with large rectangular fixed inlets",
      wingPosition: "low",
      wingShape: "trapezoidal",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "large",
      era: "modern",
      distinguishingFeatures: [
        "conformal fuel tanks (CFTs) integrated flush along each fuselage side",
        "two-seat tandem cockpit",
        "large squared-off fixed air intakes",
        "twin vertical tails",
        "LANTIRN or SNIPER targeting pods under intakes",
        "darker tactical gray paint scheme vs. air superiority Eagle",
        "denser weapons pylons on CFTs and wings",
      ],
    },
    aliases: ["Strike Eagle", "Mud Hen"],
  },
  {
    id: "f-16-fighting-falcon",
    name: "F-16 Fighting Falcon",
    manufacturer: "General Dynamics / Lockheed Martin",
    type: "Fighter",
    firstFlight: "1974-02-02",
    inService: "1978",
    role: "Multirole Fighter",
    country: "USA",
    specs: {
      wingspan: "32 ft 8 in (9.96 m)",
      length: "49 ft 5 in (15.06 m)",
      maxSpeed: "Mach 2.05 (1,353 mph)",
      range: "1,740 mi (2,800 km)",
      ceiling: "50,000 ft (15,240 m)",
      engines: "1x General Electric F110-GE-129 turbofan",
      crew: "1",
    },
    description:
      "The F-16 Fighting Falcon is a single-engine multirole combat aircraft that introduced relaxed static stability and fly-by-wire flight controls to production fighters. One of the most widely produced Western fighters with over 4,600 built for 25 air forces.",
    funFact:
      "The F-16's cockpit is reclined 30 degrees rearward and uses a side-stick controller — both firsts in production fighters — specifically to help the pilot withstand the 9g turns the aircraft can sustain, which would cause blackout in a conventional upright seat.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "single engine with large chin-mounted inlet",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "single large chin intake directly beneath the nose",
        "blended wing-body fuselage with prominent LERX strakes",
        "bubble canopy with no forward frame arch giving 360-degree visibility",
        "single engine with prominent afterburner nozzle",
        "smooth wing-body blending",
        "small ventral fins beneath tail",
        "side-mounted stick controller in reclined seat",
      ],
    },
    aliases: ["Viper", "Electric Jet", "Fighting Falcon"],
  },
  {
    id: "fa-18-hornet",
    name: "F/A-18 Hornet",
    manufacturer: "McDonnell Douglas",
    type: "Strike Fighter",
    firstFlight: "1978-11-18",
    inService: "1983",
    role: "Carrier-based Multirole Fighter/Attack",
    country: "USA",
    specs: {
      wingspan: "40 ft 4 in (12.31 m)",
      length: "56 ft (17.07 m)",
      maxSpeed: "Mach 1.8 (1,190 mph)",
      range: "1,089 mi (1,750 km)",
      ceiling: "50,000 ft (15,240 m)",
      engines: "2x General Electric F404-GE-402 turbofan",
      crew: "1",
    },
    description:
      "The F/A-18 Hornet is a twin-engine, supersonic, all-weather, carrier-capable multirole combat jet — the first aircraft designated both fighter and attack. It replaced multiple single-role aircraft in Navy and Marine Corps service and introduced digital fly-by-wire from day one.",
    funFact:
      "The F/A-18 was the first US tactical aircraft to use a fully integrated digital fly-by-wire system, digital mission computer, and multi-function cockpit displays as a complete package from initial production.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines with rounded rectangular cheek inlets",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "twin vertical tails canted outward at approximately 20 degrees",
        "large leading edge extensions (LEX) running from nose to wing",
        "folding wingtips for carrier storage",
        "trapezoidal wing with clipped tips",
        "rounded rectangular cheek inlets alongside fuselage",
        "distinctive LEX vortex strakes",
        "twin horizontal stabilators",
      ],
    },
    aliases: ["Hornet"],
  },
  {
    id: "fa-18ef-super-hornet",
    name: "F/A-18E/F Super Hornet",
    manufacturer: "Boeing",
    type: "Strike Fighter",
    variant: "F/A-18E (single-seat) / F/A-18F (two-seat)",
    firstFlight: "1995-11-29",
    inService: "1999",
    role: "Carrier-based Multirole Fighter/Attack",
    country: "USA",
    specs: {
      wingspan: "44 ft 9 in (13.62 m)",
      length: "60 ft 1 in (18.31 m)",
      maxSpeed: "Mach 1.8 (1,190 mph)",
      range: "1,275 mi (2,050 km)",
      ceiling: "50,000 ft (15,240 m)",
      engines: "2x General Electric F414-GE-400 turbofan",
      crew: "1 (E model) / 2 (F model)",
    },
    description:
      "The F/A-18E/F Super Hornet is approximately 20% larger than the original Hornet with greater range, payload, and survivability. It serves as the US Navy's primary strike fighter, replacing the F-14 Tomcat in the fleet defense role.",
    funFact:
      "Despite sharing a name with the Hornet, the Super Hornet shares only about 20% of its parts with the original — it is essentially a new aircraft, renamed for political reasons to smooth congressional approval of the program.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines with large square-edged rectangular inlets",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "large squared-off trapezoidal inlets (vs. rounded on classic Hornet)",
        "blockier squarer fuselage sections",
        "twin canted vertical tails",
        "enlarged wing with square-cut tips",
        "pronounced leading edge extensions (LEX)",
        "noticeably larger overall size than classic Hornet",
        "diamond-shaped inlet cross-section",
      ],
    },
    aliases: ["Super Hornet", "Rhino"],
  },
  {
    id: "ea-18g-growler",
    name: "EA-18G Growler",
    manufacturer: "Boeing",
    type: "Electronic Warfare",
    variant: "EA-18G",
    firstFlight: "2006-08-15",
    inService: "2009",
    role: "Carrier-based Electronic Attack",
    country: "USA",
    specs: {
      wingspan: "44 ft 9 in (13.62 m)",
      length: "60 ft 1 in (18.31 m)",
      maxSpeed: "Mach 1.8 (1,190 mph)",
      range: "1,275 mi (2,050 km)",
      ceiling: "50,000 ft (15,240 m)",
      engines: "2x General Electric F414-GE-400 turbofan",
      crew: "2",
    },
    description:
      "The EA-18G Growler is the electronic warfare variant of the F/A-18F Super Hornet, replacing the EA-6B Prowler. It provides airborne electronic attack, suppression of enemy air defenses, and radar/communications jamming from a carrier-capable platform.",
    funFact:
      "The Growler requires only 2 crew to do what the EA-6B Prowler needed 4 crew for — its automated systems and the ICAP III jamming suite compress the EW workload enough that one WSO can manage tasks that previously required three dedicated EWOs.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines with large rectangular inlets",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "AN/ALQ-218 electronic warfare receiver pods on each wingtip",
        "AN/ALQ-99 or NGJ jamming pods on wing pylons",
        "two-seat tandem cockpit",
        "ICAP III jamming system fairing on forward fuselage sides",
        "similar external silhouette to F/A-18F with EW pods replacing weapons",
        "distinctive bulbous wingtip ALQ pods",
      ],
    },
    aliases: ["Growler"],
  },
  {
    id: "f-22-raptor",
    name: "F-22 Raptor",
    manufacturer: "Lockheed Martin / Boeing",
    type: "Fighter",
    firstFlight: "1997-09-07",
    inService: "2005",
    role: "Air Superiority Stealth Fighter",
    country: "USA",
    specs: {
      wingspan: "44 ft 6 in (13.56 m)",
      length: "62 ft 1 in (18.92 m)",
      maxSpeed: "Mach 2.25 (1,500 mph); supercruise Mach 1.82",
      range: "1,600 mi (2,570 km)",
      ceiling: "65,000 ft (19,812 m)",
      engines: "2x Pratt & Whitney F119-PW-100 turbofan",
      crew: "1",
    },
    description:
      "The F-22 Raptor is a fifth-generation stealth tactical fighter combining low observability, supercruise, supermaneuverability, and advanced avionics. Considered the most capable air superiority fighter ever built, it has never been exported and production ended at 187 aircraft.",
    funFact:
      "The F-22 can supercruise — sustain supersonic flight without afterburner — at Mach 1.82, faster than many fighters fly with full afterburner, while its radar cross section is reportedly that of a marble-sized steel ball.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines with trapezoidal faceted fixed inlets",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "highly faceted stealth shaping throughout entire airframe",
        "trapezoidal fixed inlets with no moving ramps",
        "two-dimensional rectangular thrust-vectoring nozzles",
        "internal weapons bays (no external pylons for primary missions)",
        "twin canted vertical tails",
        "blended wing-body with smooth continuous curves",
        "frameless bubble canopy",
        "all-moving horizontal tails (tailerons)",
      ],
    },
    aliases: ["Raptor"],
  },
  {
    id: "f-35a",
    name: "F-35A Lightning II",
    manufacturer: "Lockheed Martin",
    type: "Fighter",
    variant: "F-35A (CTOL)",
    firstFlight: "2006-10-22",
    inService: "2015",
    role: "Multirole Stealth Fighter (Conventional Takeoff and Landing)",
    country: "USA",
    specs: {
      wingspan: "35 ft (10.7 m)",
      length: "51 ft 2 in (15.6 m)",
      maxSpeed: "Mach 1.6 (1,200 mph)",
      range: "1,380 mi (2,220 km)",
      ceiling: "50,000 ft (15,240 m)",
      engines: "1x Pratt & Whitney F135-PW-100 turbofan",
      crew: "1",
    },
    description:
      "The F-35A is the conventional takeoff and landing variant of the Lightning II for the USAF and allied air forces. It is the most produced variant and the only F-35 with an internal 25mm GAU-22/A cannon. It forms the core of many NATO air forces' fifth-generation capability.",
    funFact:
      "The F-35's distributed aperture system (DAS) places six infrared cameras around the aircraft so the pilot can literally see through the airframe in any direction — the helmet display projects what is below the aircraft onto the visor as the pilot looks down.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "single engine with DSI bump inlet under forward fuselage",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "diverterless supersonic inlet (DSI) with distinctive bump/bulge under nose",
        "single engine with round exhaust nozzle",
        "internal weapons bays in fuselage",
        "highly blended stealth airframe with no sharp discontinuities",
        "twin canted all-moving tails",
        "large frameless bubble canopy",
        "internal gun port on left upper fuselage (CTOL only)",
        "radar-absorbent material coating all surfaces",
      ],
    },
    aliases: ["Lightning II", "Joint Strike Fighter", "JSF"],
  },
  {
    id: "f-35b",
    name: "F-35B Lightning II",
    manufacturer: "Lockheed Martin",
    type: "Fighter",
    variant: "F-35B (STOVL)",
    firstFlight: "2008-06-11",
    inService: "2015",
    role: "Multirole Stealth Fighter (Short Takeoff / Vertical Landing)",
    country: "USA",
    specs: {
      wingspan: "35 ft (10.7 m)",
      length: "51 ft 2 in (15.6 m)",
      maxSpeed: "Mach 1.6 (1,200 mph)",
      range: "900 mi (1,445 km)",
      ceiling: "50,000 ft (15,240 m)",
      engines: "1x Pratt & Whitney F135-PW-600 turbofan + Rolls-Royce LiftSystem",
      crew: "1",
    },
    description:
      "The F-35B is the STOVL variant for the US Marine Corps and UK Royal Navy/Air Force. It features a shaft-driven Rolls-Royce lift fan behind the cockpit and a rotating rear nozzle for vertical flight, making it the only Western fighter capable of operating from amphibious assault ships.",
    funFact:
      "The F-35B's lift fan — driven by a driveshaft from the main engine — alone produces 20,000 lb of thrust straight downward, more thrust than many complete jet engines. Together with the main engine vectored aft, the system produces over 40,000 lb total for vertical flight.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "single engine with DSI bump inlet; lift fan behind cockpit",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "lift fan door directly behind cockpit (visible when open for VTOL)",
        "three-bearing swivel nozzle for vectored thrust at rear",
        "slightly wider fuselage than F-35A to accommodate lift system",
        "DSI bump inlet under nose",
        "twin canted all-moving tails",
        "roll post nozzles under air inlets for hover control",
        "no internal cannon (replaced by lift system components)",
      ],
    },
    aliases: ["Lightning II", "STOVL Variant"],
  },
  {
    id: "f-35c",
    name: "F-35C Lightning II",
    manufacturer: "Lockheed Martin",
    type: "Fighter",
    variant: "F-35C (CV)",
    firstFlight: "2010-06-06",
    inService: "2019",
    role: "Carrier-based Multirole Stealth Fighter",
    country: "USA",
    specs: {
      wingspan: "43 ft (13.1 m)",
      length: "51 ft 2 in (15.6 m)",
      maxSpeed: "Mach 1.6 (1,200 mph)",
      range: "1,200 mi (1,930 km)",
      ceiling: "50,000 ft (15,240 m)",
      engines: "1x Pratt & Whitney F135-PW-400 turbofan",
      crew: "1",
    },
    description:
      "The F-35C is the carrier variant for the US Navy with the largest wing of the three variants. Its folding outer wing panels, strengthened undercarriage, and larger wing area achieve the lower approach speeds required for carrier arrested landings.",
    funFact:
      "The F-35C has a wing nearly a third wider than the F-35A. The enlarged wing lowers approach speed to ~145 knots for safe arrested carrier landings — the same approach speed required of all US carrier aircraft regardless of weight.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "single engine with DSI bump inlet under forward fuselage",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "larger wings with rounded wingtips (folding outer sections)",
        "reinforced undercarriage visible as heavier main gear",
        "arresting hook under rear fuselage",
        "DSI bump inlet",
        "twin canted all-moving tails",
        "internal weapons bays",
        "larger overall wing area than F-35A or B",
      ],
    },
    aliases: ["Lightning II", "CV variant"],
  },
  {
    id: "f-86-sabre",
    name: "F-86 Sabre",
    manufacturer: "North American Aviation",
    type: "Fighter",
    firstFlight: "1947-10-01",
    inService: "1949",
    role: "Day Fighter / Interceptor",
    country: "USA",
    specs: {
      wingspan: "37 ft 1 in (11.3 m)",
      length: "37 ft 6 in (11.4 m)",
      maxSpeed: "Mach 0.9 (687 mph)",
      range: "1,525 mi (2,454 km)",
      ceiling: "49,600 ft (15,120 m)",
      engines: "1x General Electric J47-GE-27 turbojet",
      crew: "1",
    },
    description:
      "The F-86 Sabre was the USAF's first swept-wing jet fighter and the premier US fighter of the Korean War. It dueled the Soviet-built MiG-15 over Korea in history's first large-scale jet-versus-jet air combat — the battles shaped jet fighter doctrine for a generation.",
    funFact:
      "US Sabre pilots were credited with a roughly 10:1 kill ratio over MiG-15s in Korea. Modern declassified analysis puts the real ratio closer to 2:1 — both aircraft were evenly matched, but American pilots averaged far more flying hours.",
    visual: {
      engineCount: 1,
      engineType: "turbojet",
      enginePlacement: "single engine with circular nose intake",
      wingPosition: "mid",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "early-jet",
      distinguishingFeatures: [
        "distinctive circular nose intake opening",
        "35-degree swept wings",
        "all-flying horizontal stabilator",
        "six .50 caliber machine guns clustered in nose",
        "streamlined teardrop fuselage cross section",
        "single fin with swept vertical surface",
      ],
    },
    aliases: ["Sabre", "MiG Killer"],
  },
  {
    id: "f-100-super-sabre",
    name: "F-100 Super Sabre",
    manufacturer: "North American Aviation",
    type: "Fighter",
    firstFlight: "1953-05-25",
    inService: "1954",
    role: "Tactical Fighter-Bomber / Close Air Support",
    country: "USA",
    specs: {
      wingspan: "38 ft 9 in (11.81 m)",
      length: "47 ft 1 in (14.36 m)",
      maxSpeed: "Mach 1.3 (864 mph)",
      range: "1,500 mi (2,415 km)",
      ceiling: "50,000 ft (15,240 m)",
      engines: "1x Pratt & Whitney J57-P-21A turbojet",
      crew: "1",
    },
    description:
      "The F-100 Super Sabre was the world's first production fighter capable of supersonic level flight. It flew more combat sorties in Vietnam than the P-51 Mustang flew in all of World War II, primarily in the close air support role.",
    funFact:
      "Early F-100A variants had a dangerous yaw instability called the 'Sabre Dance' that caused several fatal accidents — the aircraft would enter an uncontrolled roll on approach. North American fixed it by increasing wing area and changing the fin.",
    visual: {
      engineCount: 1,
      engineType: "turbojet",
      enginePlacement: "single engine with large oval chin intake",
      wingPosition: "mid",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "large oval chin intake positioned under the cockpit",
        "highly swept 45-degree wings",
        "all-moving horizontal tail",
        "four 20mm M39 cannon in lower nose",
        "low-slung fuselage profile",
        "single fin slightly swept",
      ],
    },
    aliases: ["Super Sabre", "Hun (century fighter)"],
  },
  {
    id: "f-104-starfighter",
    name: "F-104 Starfighter",
    manufacturer: "Lockheed",
    type: "Fighter",
    firstFlight: "1954-02-28",
    inService: "1958",
    role: "Interceptor / Tactical Fighter",
    country: "USA",
    specs: {
      wingspan: "21 ft 11 in (6.68 m)",
      length: "54 ft 9 in (16.69 m)",
      maxSpeed: "Mach 2.2 (1,450 mph)",
      range: "1,550 mi (2,495 km)",
      ceiling: "58,000 ft (17,680 m)",
      engines: "1x General Electric J79-GE-19 turbojet",
      crew: "1",
    },
    description:
      "The F-104 Starfighter was an extreme-performance interceptor optimized for speed and altitude. Its tiny stub wings and needle fuselage produced a missile-like aircraft that was challenging to fly at low speed. It served widely with NATO and achieved Mach 2 comfortably.",
    funFact:
      "The F-104's wing leading edges were literally razor-sharp — ground crews required protective sleeves to avoid cuts when working near the wings. Its downward-ejecting seat in early versions was replaced after complaints it was useless at low altitude.",
    visual: {
      engineCount: 1,
      engineType: "turbojet",
      enginePlacement: "single engine with side cheek air intakes",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "t-tail",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "extremely thin stub wings with razor-sharp leading edges",
        "long needle-like fuselage resembling a missile",
        "T-tail with horizontal stabilizer on top of fin",
        "very short wingspan relative to fuselage length",
        "side-mounted air intakes with sharp lips",
        "prominent Mach cone inlet geometry",
      ],
    },
    aliases: ["Starfighter", "Missile with a Man in It", "Widowmaker"],
  },
  {
    id: "f-105-thunderchief",
    name: "F-105 Thunderchief",
    manufacturer: "Republic Aviation",
    type: "Strike Fighter",
    firstFlight: "1955-10-22",
    inService: "1958",
    role: "Supersonic Tactical Fighter-Bomber",
    country: "USA",
    specs: {
      wingspan: "34 ft 11 in (10.65 m)",
      length: "64 ft 3 in (19.58 m)",
      maxSpeed: "Mach 2.08 (1,372 mph)",
      range: "2,390 mi (3,846 km)",
      ceiling: "50,000 ft (15,240 m)",
      engines: "1x Pratt & Whitney J75-P-19W turbojet",
      crew: "1",
    },
    description:
      "The F-105 Thunderchief was a supersonic single-seat fighter-bomber that bore the greatest burden of early US air strikes over North Vietnam. It flew the most combat missions of any USAF aircraft in the war but suffered the highest combat loss rate.",
    funFact:
      "The F-105 was larger than the WWII B-29 Superfortress and could carry a heavier internal bomb load than most dedicated bombers of the Korean War era — yet it was designated a fighter because it had air-to-air capability.",
    visual: {
      engineCount: 1,
      engineType: "turbojet",
      enginePlacement: "single engine with distinctive area-ruled fuselage and chin intake",
      wingPosition: "mid",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "large",
      era: "cold-war",
      distinguishingFeatures: [
        "large area-ruled (Coke bottle) waist fuselage",
        "bulging fuselage housing internal bomb bay",
        "large swept wings",
        "chin intake with distinctive curved lip",
        "prominent dorsal air scoop on spine",
        "very large single engine exhaust",
      ],
    },
    aliases: ["Thud", "Thunderchief", "Ultra Hog"],
  },
  {
    id: "f-111-aardvark",
    name: "F-111 Aardvark",
    manufacturer: "General Dynamics",
    type: "Strike Fighter",
    firstFlight: "1964-12-21",
    inService: "1967",
    role: "Strategic and Tactical Strike Aircraft",
    country: "USA",
    specs: {
      wingspan: "63 ft (19.2 m) spread / 31 ft 11 in (9.74 m) swept",
      length: "73 ft 6 in (22.4 m)",
      maxSpeed: "Mach 2.5 (1,650 mph)",
      range: "3,210 mi (5,165 km)",
      ceiling: "60,000 ft (18,290 m)",
      engines: "2x Pratt & Whitney TF30-P-100 turbofan",
      crew: "2",
    },
    description:
      "The F-111 Aardvark was the world's first production aircraft with variable-sweep wings and the first to achieve sustained supersonic flight at treetop altitude. Its side-by-side seating and escape capsule made it unique among tactical jets.",
    funFact:
      "The F-111 crew does not eject in individual seats — the entire pressurized crew module separates from the aircraft as a single capsule, descends by parachute, and floats if it lands in water, providing much better survivability in low-level ejections.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines with rectangular cheek inlets on fuselage sides",
      wingPosition: "variable",
      wingShape: "variable-sweep",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "large",
      era: "cold-war",
      distinguishingFeatures: [
        "variable-sweep wings pivoting between spread and fully swept",
        "side-by-side two-seat cockpit (not tandem)",
        "long pointed needle nose",
        "two-dimensional rectangular air intakes on fuselage sides",
        "escape capsule replaces individual ejection seats",
        "large bomber-sized fuselage",
        "distinctive low-slung engine nacelles at rear",
      ],
    },
    aliases: ["Aardvark", "One-Eleven", "Flying Pig"],
  },
  {
    id: "f-117-nighthawk",
    name: "F-117 Nighthawk",
    manufacturer: "Lockheed (Skunk Works)",
    type: "Stealth Attack",
    firstFlight: "1981-06-18",
    inService: "1983",
    role: "Stealth Ground Attack / Precision Strike",
    country: "USA",
    specs: {
      wingspan: "43 ft 4 in (13.2 m)",
      length: "65 ft 11 in (20.1 m)",
      maxSpeed: "Mach 0.92 (617 mph)",
      range: "1,070 mi (1,720 km)",
      ceiling: "45,000 ft (13,716 m)",
      engines: "2x General Electric F404-GE-F1D2 turbofan",
      crew: "1",
    },
    description:
      "The F-117 Nighthawk was the world's first operational stealth aircraft, using flat faceted panels to scatter radar energy away from its source. Despite the fighter designation it had no air-to-air capability — it was a precision ground attack aircraft relying entirely on stealth for survival.",
    funFact:
      "The F-117 existed operationally for seven years before the US government acknowledged it publicly. It flew only at night during its early service life and pilots' families were told they flew F-4s and T-38s.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines buried in fuselage with grid-covered top inlets",
      wingPosition: "low",
      wingShape: "delta",
      tailType: "v-tail",
      landingGear: "tricycle",
      sizeClass: "large",
      era: "modern",
      distinguishingFeatures: [
        "entirely faceted flat-panel construction — no curved surfaces anywhere",
        "V-shaped butterfly tail",
        "saw-tooth edges on all panels and doors",
        "grid-covered inlets on top of fuselage to hide engine faces",
        "platypus-shaped exhaust slots to reduce infrared signature",
        "highly swept W-shaped leading edge delta wing",
        "flat black paint scheme",
        "internal weapons bay with no external stores",
      ],
    },
    aliases: ["Nighthawk", "Wobbly Goblin", "Black Jet"],
  },

  // ============================================================
  // US ATTACK AIRCRAFT
  // ============================================================
  {
    id: "a-10-thunderbolt-ii",
    name: "A-10 Thunderbolt II",
    manufacturer: "Fairchild Republic",
    type: "Attack",
    firstFlight: "1972-05-10",
    inService: "1977",
    role: "Close Air Support / Anti-Armor",
    country: "USA",
    specs: {
      wingspan: "57 ft 6 in (17.53 m)",
      length: "53 ft 4 in (16.26 m)",
      maxSpeed: "439 mph (707 km/h)",
      range: "800 mi (1,290 km) with combat load",
      ceiling: "45,000 ft (13,700 m)",
      engines: "2x General Electric TF34-GE-100A turbofan",
      crew: "1",
    },
    description:
      "The A-10 Thunderbolt II is a dedicated close air support aircraft built around the GAU-8/A Avenger 30mm rotary cannon. Its massive armor protection, redundant systems, and ability to fly on a single engine make it extraordinarily survivable over the modern battlefield.",
    funFact:
      "The entire A-10 was essentially designed around its GAU-8/A Avenger cannon — the gun is 19 ft long, weighs 4,029 lb, and fires 3,900 depleted-uranium rounds per minute. The recoil force is greater than the thrust of one of the aircraft's engines.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin turbofan pods mounted high on rear fuselage sides",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "massive 30mm GAU-8/A cannon barrel protruding from blunt nose",
        "twin turbofan engines in high-mounted rear fuselage pods",
        "straight wide-span wings with 11 hardpoints",
        "twin-boom tail with widely spaced vertical fins",
        "titanium 'bathtub' armor enclosure visible around cockpit",
        "large bubble canopy providing excellent forward and downward visibility",
        "straight leading edge wing",
      ],
    },
    aliases: ["Warthog", "Hog", "Tank Killer", "Flying Gun"],
  },
  {
    id: "a-4-skyhawk",
    name: "A-4 Skyhawk",
    manufacturer: "Douglas Aircraft",
    type: "Attack",
    firstFlight: "1954-06-22",
    inService: "1956",
    role: "Carrier-based Light Attack",
    country: "USA",
    specs: {
      wingspan: "27 ft 6 in (8.38 m)",
      length: "40 ft 3 in (12.22 m)",
      maxSpeed: "Mach 1.06 (673 mph)",
      range: "2,055 mi (3,307 km)",
      ceiling: "49,000 ft (14,935 m)",
      engines: "1x Pratt & Whitney J52-P-408 turbojet",
      crew: "1",
    },
    description:
      "The A-4 Skyhawk was a lightweight carrier-based attack aircraft designed by Ed Heinemann to be exactly half the Navy's specified weight limit. Its delta wing was compact enough to eliminate the need for folding wings for carrier storage, a remarkable achievement.",
    funFact:
      "When the Navy specified a 30,000 lb maximum weight, Ed Heinemann delivered an aircraft at 15,000 lb that outperformed heavier competitors. He reportedly told colleagues his goal was to design 'the smallest airplane that will do the job.'",
    visual: {
      engineCount: 1,
      engineType: "turbojet",
      enginePlacement: "single engine with circular nose intake",
      wingPosition: "low",
      wingShape: "delta",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "compact delta wing small enough to not require folding for carrier storage",
        "distinctive humped avionics bay behind cockpit",
        "circular nose intake",
        "four underwing and one centerline hardpoint",
        "hunchback silhouette from avionics fairing",
        "very small, agile overall size",
      ],
    },
    aliases: ["Skyhawk", "Scooter", "Heinemann's Hot Rod", "Bantam Bomber"],
  },
  {
    id: "a-6-intruder",
    name: "A-6 Intruder",
    manufacturer: "Grumman",
    type: "Attack",
    firstFlight: "1960-04-19",
    inService: "1963",
    role: "Carrier-based All-Weather Attack",
    country: "USA",
    specs: {
      wingspan: "53 ft (16.15 m)",
      length: "54 ft 7 in (16.69 m)",
      maxSpeed: "Mach 0.93 (644 mph)",
      range: "1,627 mi (2,618 km)",
      ceiling: "44,600 ft (13,595 m)",
      engines: "2x Pratt & Whitney J52-P-8B turbojet",
      crew: "2",
    },
    description:
      "The A-6 Intruder was the US Navy's all-weather carrier-based medium attack aircraft from Vietnam through the Gulf War. Its DIANE navigation and attack system enabled low-level precision strikes in darkness and bad weather that no other aircraft of its era could match.",
    funFact:
      "The A-6 Intruder was the first aircraft to use the DIANE (Digital Integrated Attack and Navigation Equipment) system — it could navigate at low altitude through valleys, avoid terrain, and release weapons with precision, completely automated, in 1963.",
    visual: {
      engineCount: 2,
      engineType: "turbojet",
      enginePlacement: "twin engines in fuselage with large cheek inlets",
      wingPosition: "mid",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "side-by-side two-seat cockpit (not tandem)",
        "blunt rounded nose housing navigation/attack radar",
        "large rounded fuselage with portly silhouette",
        "modest wing sweep angle",
        "folding wing tips for carrier storage",
        "five hardpoints for ordnance",
      ],
    },
    aliases: ["Intruder"],
  },
  {
    id: "a-7-corsair-ii",
    name: "A-7 Corsair II",
    manufacturer: "Vought",
    type: "Attack",
    firstFlight: "1965-09-27",
    inService: "1967",
    role: "Carrier-based Light Attack",
    country: "USA",
    specs: {
      wingspan: "38 ft 9 in (11.8 m)",
      length: "46 ft 1.5 in (14.06 m)",
      maxSpeed: "Mach 0.92 (698 mph)",
      range: "2,850 mi (4,590 km)",
      ceiling: "42,000 ft (12,800 m)",
      engines: "1x Allison TF41-A-2 turbofan",
      crew: "1",
    },
    description:
      "The A-7 Corsair II was a subsonic carrier-based light attack aircraft derived from the F-8 Crusader. It introduced the first head-up display (HUD) in US combat service and offered exceptional range and weapons payload for its class.",
    funFact:
      "The A-7 Corsair II was the first US aircraft to use a HUD (head-up display) in operational combat — a technology now standard on all fighters. This was in 1967, when most aircraft still relied on head-down instruments for weapon delivery.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "single engine with large oval chin intake",
      wingPosition: "mid",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "distinctive large oval chin intake",
        "squared wingtips",
        "blunt rounded nose",
        "shorter and stubbier than the F-8 Crusader it derived from",
        "eight hardpoints for heavy ordnance",
        "clean, simple fuselage lines",
      ],
    },
    aliases: ["Corsair II", "SLUF (Short Little Ugly Fella)"],
  },
  {
    id: "av-8b-harrier-ii",
    name: "AV-8B Harrier II",
    manufacturer: "McDonnell Douglas / British Aerospace",
    type: "Attack",
    firstFlight: "1981-11-05",
    inService: "1985",
    role: "V/STOL Close Air Support / Light Attack",
    country: "USA",
    specs: {
      wingspan: "30 ft 4 in (9.25 m)",
      length: "46 ft 4 in (14.12 m)",
      maxSpeed: "Mach 0.9 (662 mph)",
      range: "1,200 mi (1,900 km)",
      ceiling: "50,000 ft (15,240 m)",
      engines: "1x Rolls-Royce F402-RR-408 Pegasus turbofan",
      crew: "1",
    },
    description:
      "The AV-8B Harrier II is a second-generation V/STOL attack aircraft using vectored thrust from its Pegasus engine for vertical or short takeoffs and vertical landings. It operates from amphibious assault ships and forward air bases without runways.",
    funFact:
      "The Harrier can VIFF — Vector in Forward Flight — rotating its thrust nozzles in flight to execute deceleration maneuvers that cause pursuing aircraft to overshoot, a unique and disorienting capability in close combat.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "single Pegasus engine with four rotating vectoring nozzles",
      wingPosition: "high",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "tandem",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "four rotating vectored-thrust nozzles (two forward, two aft on each side)",
        "bicycle/tandem main landing gear with outrigger wheels at wingtips",
        "large single under-fuselage air intake",
        "bulging underfuselage strake fairings housing gun pods or ECM",
        "high-mounted swept wing",
        "small outrigger wingtip wheels clearly visible on the ground",
      ],
    },
    aliases: ["Harrier II", "Jump Jet"],
  },
  {
    id: "ac-130",
    name: "AC-130 Spectre/Ghostrider",
    manufacturer: "Lockheed / Boeing",
    type: "Gunship",
    variant: "AC-130U Spooky / AC-130J Ghostrider",
    firstFlight: "1966-06-16",
    inService: "1968",
    role: "Close Air Support Gunship",
    country: "USA",
    specs: {
      wingspan: "132 ft 7 in (40.4 m)",
      length: "97 ft 9 in (29.8 m)",
      maxSpeed: "300 mph (480 km/h)",
      range: "2,500 mi (4,022 km)",
      ceiling: "25,000 ft (7,620 m)",
      engines: "4x Allison T56-A-15 turboprop",
      crew: "13",
    },
    description:
      "The AC-130 is a heavily armed long-endurance ground attack gunship built on the C-130 Hercules airframe. Its side-firing weapons — including howitzers, Bofors cannon, and precision missiles — deliver continuous fire while the aircraft orbits a target in a left-hand pylon turn.",
    funFact:
      "The AC-130 orbits a target in a sustained left-hand turn, keeping all its side-mounted guns pointing continuously at a single fixed point on the ground — an orbiting fire solution that can sustain fire on a target for hours.",
    visual: {
      engineCount: 4,
      engineType: "turboprop",
      enginePlacement: "four turboprops on high-mounted straight wing",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "heavy",
      era: "modern",
      distinguishingFeatures: [
        "based on C-130 Hercules transport airframe",
        "multiple gun ports and muzzle openings along left (port) fuselage side",
        "105mm howitzer barrel visible protruding from left fuselage",
        "large sensor turrets under nose and mid-fuselage",
        "four turboprop engines on high-mounted straight wing",
        "large ramp/cargo door at rear",
        "extensive antenna fairings on fuselage",
      ],
    },
    aliases: ["Spectre", "Spooky", "Ghostrider", "Angel of Death"],
  },

  // ============================================================
  // RUSSIAN / SOVIET FIGHTERS
  // ============================================================
  {
    id: "mig-15",
    name: "MiG-15",
    manufacturer: "Mikoyan-Gurevich",
    type: "Fighter",
    natoReportingName: "Fagot",
    firstFlight: "1947-12-30",
    inService: "1949",
    role: "Fighter / Interceptor",
    country: "Soviet Union",
    specs: {
      wingspan: "33 ft 1 in (10.08 m)",
      length: "33 ft 2 in (10.1 m)",
      maxSpeed: "Mach 0.92 (668 mph)",
      range: "1,155 mi (1,860 km)",
      ceiling: "50,850 ft (15,500 m)",
      engines: "1x Klimov VK-1 turbojet",
      crew: "1",
    },
    description:
      "The MiG-15 was the Soviet Union's first swept-wing jet fighter and one of the most widely produced early jets. Its sudden appearance over Korea in November 1950 shocked UN forces and directly prompted the rushed deployment of the F-86 Sabre.",
    funFact:
      "The Soviet MiG-15's strong performance was partly because Stalin's government purchased two Rolls-Royce Nene centrifugal turbojets directly from Britain in 1947 — the British approved the commercial sale before realizing the Soviets would clone the engine.",
    visual: {
      engineCount: 1,
      engineType: "turbojet",
      enginePlacement: "single engine with large circular nose intake",
      wingPosition: "mid",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "early-jet",
      distinguishingFeatures: [
        "large circular nose intake",
        "35-degree swept wings and tail surfaces",
        "distinctive heavy cannon armament under nose (37mm + 23mm)",
        "short stubby compact fuselage",
        "prominent airbrakes on fuselage sides",
        "all-flying horizontal stabilizer",
      ],
    },
    aliases: ["Fagot"],
  },
  {
    id: "mig-17",
    name: "MiG-17",
    manufacturer: "Mikoyan-Gurevich",
    type: "Fighter",
    natoReportingName: "Fresco",
    firstFlight: "1950-01-14",
    inService: "1952",
    role: "Day Fighter",
    country: "Soviet Union",
    specs: {
      wingspan: "31 ft 7 in (9.63 m)",
      length: "36 ft 11 in (11.26 m)",
      maxSpeed: "Mach 1.03 (711 mph)",
      range: "913 mi (1,470 km)",
      ceiling: "54,460 ft (16,600 m)",
      engines: "1x Klimov VK-1F turbojet with afterburner",
      crew: "1",
    },
    description:
      "The MiG-17 was an evolved MiG-15 with greater wing sweep and an afterburner. Though considered obsolete by the Vietnam War era, its superb turn radius at low altitude made it extremely dangerous to American aircraft — it inflicted significant losses on F-105s and F-4s.",
    funFact:
      "In Vietnam, supersonic F-105 Thunderchiefs were shot down by MiG-17s that couldn't even reach Mach 1 — at low altitude the MiG-17 could out-turn any American aircraft, proving that speed was irrelevant in knife-fight close combat.",
    visual: {
      engineCount: 1,
      engineType: "turbojet",
      enginePlacement: "single engine with circular nose intake",
      wingPosition: "mid",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "early-jet",
      distinguishingFeatures: [
        "circular nose intake",
        "more sharply swept wings (45 degrees) than MiG-15",
        "three aerodynamic fences on each wing upper surface",
        "slightly longer fuselage than MiG-15",
        "afterburner with small variable nozzle",
        "cannon cluster under nose",
      ],
    },
    aliases: ["Fresco"],
  },
  {
    id: "mig-21",
    name: "MiG-21",
    manufacturer: "Mikoyan-Gurevich",
    type: "Fighter",
    natoReportingName: "Fishbed",
    firstFlight: "1956-02-14",
    inService: "1959",
    role: "Supersonic Day Fighter / Interceptor",
    country: "Soviet Union",
    specs: {
      wingspan: "23 ft 5 in (7.15 m)",
      length: "51 ft 8 in (15.76 m)",
      maxSpeed: "Mach 2.05 (1,351 mph)",
      range: "1,118 mi (1,800 km)",
      ceiling: "57,400 ft (17,500 m)",
      engines: "1x Tumansky R-25-300 turbojet",
      crew: "1",
    },
    description:
      "The MiG-21 is the most-produced supersonic jet aircraft in history with over 11,000 built across dozens of variants. Its simple, lightweight tailed-delta configuration proved highly adaptable, serving in over 60 countries and remaining in front-line service into the 2020s.",
    funFact:
      "More than 11,000 MiG-21s were produced — more than any other supersonic fighter ever built — and they have been operated by more than 60 nations. Indian Air Force MiG-21s were still shooting down Pakistani aircraft as recently as 2019.",
    visual: {
      engineCount: 1,
      engineType: "turbojet",
      enginePlacement: "single engine with nose inlet with adjustable centerbody cone",
      wingPosition: "mid",
      wingShape: "delta",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "nose intake with distinctive adjustable centerbody shock cone",
        "tailed delta wing (delta with separate horizontal tail)",
        "small compact delta wings",
        "tall single fin",
        "prominent spine-mounted avionics fairing",
        "small ventral fin beneath tail",
        "all-moving horizontal stabilizer",
      ],
    },
    aliases: ["Fishbed", "Balalaika", "Lead Sled"],
  },
  {
    id: "mig-23",
    name: "MiG-23",
    manufacturer: "Mikoyan",
    type: "Fighter",
    natoReportingName: "Flogger",
    firstFlight: "1967-04-10",
    inService: "1970",
    role: "Fighter / Ground Attack",
    country: "Soviet Union",
    specs: {
      wingspan: "45 ft 10 in (13.97 m) spread / 25 ft 6 in (7.78 m) swept",
      length: "55 ft 1 in (16.8 m)",
      maxSpeed: "Mach 2.35 (1,553 mph)",
      range: "1,150 mi (1,850 km)",
      ceiling: "59,000 ft (18,000 m)",
      engines: "1x Khachaturov R-35-300 turbojet",
      crew: "1",
    },
    description:
      "The MiG-23 was the Soviet Air Force's first variable-sweep wing fighter and introduced a look-down/shoot-down radar capability. It replaced the MiG-21 in front-line Soviet service and was widely exported to Warsaw Pact and client-state air forces.",
    funFact:
      "In 1989 a Belgian F-16 intercepted and shot down a MiG-23 over Belgium that had been flying on autopilot unmanned for over 900 km — the pilot had ejected over Poland after an engine problem and the aircraft flew on alone across Europe.",
    visual: {
      engineCount: 1,
      engineType: "turbojet",
      enginePlacement: "single engine with large fixed rectangular cheek inlets",
      wingPosition: "variable",
      wingShape: "variable-sweep",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "variable-sweep wings with three positions (16, 45, 72 degrees)",
        "large fixed rectangular cheek inlets with boundary layer splitter plates",
        "prominent dorsal spine fairing running aft from cockpit",
        "large single vertical tail",
        "ventral fins that fold to the sides on the ground",
        "R-60/R-23 missiles on fuselage pylons",
      ],
    },
    aliases: ["Flogger"],
  },
  {
    id: "mig-25",
    name: "MiG-25",
    manufacturer: "Mikoyan",
    type: "Fighter",
    natoReportingName: "Foxbat",
    firstFlight: "1964-09-06",
    inService: "1970",
    role: "High-Speed Interceptor / Reconnaissance",
    country: "Soviet Union",
    specs: {
      wingspan: "45 ft 9 in (13.95 m)",
      length: "78 ft 2 in (23.82 m)",
      maxSpeed: "Mach 3.2 (2,170 mph) at altitude",
      range: "1,075 mi (1,730 km)",
      ceiling: "67,900 ft (20,700 m)",
      engines: "2x Tumansky R-15B-300 turbojet",
      crew: "1",
    },
    description:
      "The MiG-25 Foxbat was designed to intercept the US B-70 Valkyrie and SR-71-class aircraft. Its extreme speed so alarmed the West that it accelerated F-15 development — though defector Viktor Belenko's 1976 landing in Japan revealed its true capabilities were more limited than feared.",
    funFact:
      "When pilot Viktor Belenko defected to Japan in a MiG-25 in 1976, Western analysts were stunned to discover it was built largely of stainless steel (not titanium as assumed) and used vacuum tube electronics — the latter actually immune to EMP.",
    visual: {
      engineCount: 2,
      engineType: "turbojet",
      enginePlacement: "twin engines with large rectangular side inlets",
      wingPosition: "high",
      wingShape: "swept",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "large",
      era: "cold-war",
      distinguishingFeatures: [
        "massive twin fixed rectangular air intakes",
        "twin vertical tails canted slightly outward",
        "very large overall size",
        "large trapezoidal wing",
        "distinctive twin-tail silhouette",
        "enormous nose housing powerful radar",
      ],
    },
    aliases: ["Foxbat"],
  },
  {
    id: "mig-29",
    name: "MiG-29",
    manufacturer: "Mikoyan",
    type: "Fighter",
    natoReportingName: "Fulcrum",
    firstFlight: "1977-10-06",
    inService: "1983",
    role: "Air Superiority Fighter",
    country: "Soviet Union / Russia",
    specs: {
      wingspan: "37 ft 3 in (11.36 m)",
      length: "56 ft 10 in (17.32 m)",
      maxSpeed: "Mach 2.25 (1,490 mph)",
      range: "930 mi (1,500 km)",
      ceiling: "59,100 ft (18,000 m)",
      engines: "2x Klimov RD-33 turbofan",
      crew: "1",
    },
    description:
      "The MiG-29 is a twin-engine tactical air superiority fighter designed to counter the F-16 and F/A-18. Its helmet-mounted sight and high off-boresight missiles gave Soviet pilots the ability to engage targets far off the aircraft's nose, years before Western equivalents.",
    funFact:
      "Soviet MiG-29 pilots had helmet-mounted sights enabling high off-boresight missile shots as far back as the 1980s — a capability Western pilots lacked until the JHMCS system arrived in the 2000s, representing a significant tactical advantage.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines in widely spaced underwing nacelles",
      wingPosition: "mid",
      wingShape: "swept",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "twin engines with inlets beneath each wing root",
        "prominent leading edge root extensions (LERX)",
        "auxiliary inlet louvers on top of LERX for ground operations (clog-proof intake)",
        "twin vertical tails",
        "wide underslung engine nacelle arrangement",
        "IRST sensor ball on starboard side forward of windshield",
      ],
    },
    aliases: ["Fulcrum"],
  },
  {
    id: "mig-31",
    name: "MiG-31",
    manufacturer: "Mikoyan",
    type: "Fighter",
    natoReportingName: "Foxhound",
    firstFlight: "1975-09-16",
    inService: "1981",
    role: "Long-range High-Speed Interceptor",
    country: "Soviet Union / Russia",
    specs: {
      wingspan: "44 ft 2 in (13.46 m)",
      length: "74 ft 5 in (22.69 m)",
      maxSpeed: "Mach 2.83 (1,860 mph)",
      range: "1,864 mi (3,000 km)",
      ceiling: "67,600 ft (20,600 m)",
      engines: "2x Soloviev D-30F6 turbofan",
      crew: "2",
    },
    description:
      "The MiG-31 is a long-range, high-speed interceptor derived from the MiG-25 with substantially improved avionics. It carried the world's first production phased-array airborne radar and can coordinate with three other MiG-31s to collectively cover a 900 km defensive front.",
    funFact:
      "The MiG-31 was the world's first production aircraft to fly with a phased-array radar — the Zaslon N007 could track 10 targets simultaneously and guide missiles against 4 of them at once, a first for any production aircraft.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines with large rectangular side inlets",
      wingPosition: "high",
      wingShape: "swept",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "large",
      era: "modern",
      distinguishingFeatures: [
        "two-seat tandem cockpit (vs. single-seat MiG-25)",
        "large rectangular fixed air inlets",
        "twin canted vertical tails",
        "large rounded nose radome housing phased-array radar",
        "oversized fuselage for fuel and mission systems",
        "more rounded nose vs. MiG-25's sharper profile",
      ],
    },
    aliases: ["Foxhound"],
  },
  {
    id: "su-27-flanker",
    name: "Su-27 Flanker",
    manufacturer: "Sukhoi",
    type: "Fighter",
    natoReportingName: "Flanker-B",
    firstFlight: "1977-05-20",
    inService: "1985",
    role: "Air Superiority Fighter",
    country: "Soviet Union / Russia",
    specs: {
      wingspan: "48 ft 3 in (14.7 m)",
      length: "71 ft 11 in (21.94 m)",
      maxSpeed: "Mach 2.35 (1,553 mph)",
      range: "2,193 mi (3,530 km)",
      ceiling: "62,500 ft (19,000 m)",
      engines: "2x Saturn AL-31F turbofan",
      crew: "1",
    },
    description:
      "The Su-27 Flanker is one of the most capable air superiority fighters ever designed, developed as a direct counter to the F-15 Eagle. Its supermaneuverable airframe demonstrated the famous Pugachev Cobra maneuver at the 1989 Paris Air Show, stunning Western observers.",
    funFact:
      "The Pugachev Cobra — pitching up to 120 degrees while maintaining forward momentum then recovering — demonstrated airframe agility that Western fighters couldn't match. Whether this has direct combat utility remains debated among pilots.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines in widely spaced underwing nacelles",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "large",
      era: "modern",
      distinguishingFeatures: [
        "smooth blended wing-body design with no sharp breaks",
        "twin widely spaced engine nacelles with gaps between them",
        "twin vertical tails",
        "prominent leading edge root extensions (LERX)",
        "underslung engine inlet arrangement beneath wing",
        "long graceful pointed nose",
        "IRST sensor ball offset to the right of centerline",
      ],
    },
    aliases: ["Flanker", "Flanker-B"],
  },
  {
    id: "su-30",
    name: "Su-30",
    manufacturer: "Sukhoi",
    type: "Strike Fighter",
    natoReportingName: "Flanker-C/H",
    firstFlight: "1989-12-31",
    inService: "1996",
    role: "Multirole Fighter / Strike",
    country: "Russia",
    specs: {
      wingspan: "48 ft 3 in (14.7 m)",
      length: "72 ft (21.94 m)",
      maxSpeed: "Mach 2.0 (1,320 mph)",
      range: "1,800 mi (2,900 km)",
      ceiling: "56,800 ft (17,300 m)",
      engines: "2x Saturn AL-31F turbofan",
      crew: "2",
    },
    description:
      "The Su-30 is a two-seat multirole derivative of the Su-27 developed for deep interdiction and complex multi-mission operations. Multiple heavily customized variants are operated by India, China, Malaysia, and other nations, several featuring thrust-vectoring engines and canards.",
    funFact:
      "India's Su-30MKI combines a Russian airframe and engines with Israeli electronic warfare systems, French radar components, and Indian avionics — a multinational integration project that makes it arguably the most capable Su-30 variant.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines in widely spaced underwing nacelles",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "large",
      era: "modern",
      distinguishingFeatures: [
        "two-seat tandem cockpit (vs. single-seat Su-27)",
        "canard foreplanes on Su-30MKI/MKM variants",
        "thrust-vectoring nozzles on some variants",
        "slightly longer nose for additional avionics",
        "twin vertical tails",
        "leading edge root extensions",
      ],
    },
    aliases: ["Flanker-C", "Flanker-H"],
  },
  {
    id: "su-33",
    name: "Su-33",
    manufacturer: "Sukhoi",
    type: "Fighter",
    natoReportingName: "Flanker-D",
    firstFlight: "1985-08-17",
    inService: "1995",
    role: "Carrier-based Air Defense Fighter",
    country: "Russia",
    specs: {
      wingspan: "48 ft 3 in (14.7 m) / folded 27 ft 10 in (8.5 m)",
      length: "69 ft 6 in (21.19 m)",
      maxSpeed: "Mach 2.17 (1,430 mph)",
      range: "1,864 mi (3,000 km)",
      ceiling: "57,400 ft (17,500 m)",
      engines: "2x Saturn AL-31F3 turbofan",
      crew: "1",
    },
    description:
      "The Su-33 is the carrier-based variant of the Su-27 developed for operations from the Admiral Kuznetsov aircraft carrier. It features folding wings, canard foreplanes, and a reinforced undercarriage for ski-jump launches and arrested landings.",
    funFact:
      "The Su-33 launches from Admiral Kuznetsov's ski-jump ramp using its own engine power rather than catapults — this limits its launch weight significantly compared to US catapult-launched aircraft, restricting its fuel and weapons load on each sortie.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines in widely spaced underwing nacelles",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "large",
      era: "modern",
      distinguishingFeatures: [
        "folding outer wing panels for carrier storage",
        "canard foreplanes for enhanced low-speed maneuverability",
        "reinforced landing gear legs for carrier arrested landings",
        "arresting hook under rear fuselage",
        "twin vertical tails",
        "wider wingspan when unfolded vs. Su-27",
      ],
    },
    aliases: ["Flanker-D", "Sea Flanker"],
  },
  {
    id: "su-35",
    name: "Su-35",
    manufacturer: "Sukhoi",
    type: "Fighter",
    natoReportingName: "Flanker-E",
    firstFlight: "2008-02-19",
    inService: "2014",
    role: "Air Superiority Multirole Fighter",
    country: "Russia",
    specs: {
      wingspan: "50 ft 2 in (15.3 m)",
      length: "72 ft 9 in (22.18 m)",
      maxSpeed: "Mach 2.25 (1,490 mph)",
      range: "2,200 mi (3,600 km)",
      ceiling: "59,100 ft (18,000 m)",
      engines: "2x Saturn AL-41F1S thrust-vectoring turbofan",
      crew: "1",
    },
    description:
      "The Su-35 is a heavily upgraded supermaneuverable multirole fighter featuring thrust-vectoring engines that enable controlled flight at near-zero airspeed. Designated 4++ generation, it bridges the gap between legacy 4th and 5th generation aircraft.",
    funFact:
      "The Su-35's thrust-vectoring nozzles can deflect up to 15 degrees in any plane, enabling post-stall maneuvers at near-zero airspeed that are physically impossible in conventional aircraft — the aircraft can point its nose in virtually any direction regardless of its flight path.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines with all-aspect thrust-vectoring nozzles",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "circular movable thrust-vectoring nozzles visible at rear",
        "no canards (unlike Su-30MKI)",
        "enlarged wing leading edge root extensions",
        "IRST sensor ball offset starboard ahead of windshield",
        "twin widely spaced vertical tails",
        "very clean wing with no fences",
      ],
    },
    aliases: ["Flanker-E", "Super Flanker"],
  },
  {
    id: "su-57-felon",
    name: "Su-57 Felon",
    manufacturer: "Sukhoi",
    type: "Fighter",
    natoReportingName: "Felon",
    firstFlight: "2010-01-29",
    inService: "2020",
    role: "Fifth-Generation Air Superiority Stealth Fighter",
    country: "Russia",
    specs: {
      wingspan: "46 ft 7 in (14.2 m)",
      length: "67 ft 1 in (20.46 m)",
      maxSpeed: "Mach 2.0 (1,320 mph); supercruise Mach 1.5",
      range: "2,175 mi (3,500 km)",
      ceiling: "65,600 ft (20,000 m)",
      engines: "2x Saturn AL-41F1 turbofan",
      crew: "1",
    },
    description:
      "The Su-57 Felon is Russia's first fifth-generation stealth multirole fighter, featuring a blended airframe, reduced radar signature, internal weapons bays, supercruise, and thrust vectoring. It represents Russia's answer to the F-22 and F-35.",
    funFact:
      "The Su-57 embeds sensors throughout its airframe rather than concentrating them in the nose — forming a distributed aperture system that gives the pilot spherical 360-degree situational awareness, similar in concept to the F-35's DAS.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines in widely spaced nacelles with thrust-vectoring nozzles",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "widely spaced twin engine bays with pronounced chines between them",
        "faceted stealth-shaped forward fuselage",
        "all-moving V-type canted twin tails",
        "two main internal weapons bays between nacelles",
        "broad chined nose with flat forward fuselage sides",
        "LERX blending into fuselage sides",
        "thrust-vectoring nozzles",
      ],
    },
    aliases: ["Felon", "T-50 (prototype)", "PAK FA"],
  },

  // ============================================================
  // EUROPEAN FIGHTERS
  // ============================================================
  {
    id: "eurofighter-typhoon",
    name: "Eurofighter Typhoon",
    manufacturer: "Eurofighter GmbH (BAE Systems / Airbus / Leonardo)",
    type: "Fighter",
    firstFlight: "1994-03-27",
    inService: "2003",
    role: "Multirole Fighter",
    country: "UK / Germany / Italy / Spain",
    specs: {
      wingspan: "35 ft 11 in (10.95 m)",
      length: "52 ft 4 in (15.96 m)",
      maxSpeed: "Mach 2.0 (1,321 mph)",
      range: "1,800 mi (2,900 km)",
      ceiling: "65,000 ft (19,812 m)",
      engines: "2x Eurojet EJ200 turbofan",
      crew: "1",
    },
    description:
      "The Eurofighter Typhoon is a twin-engine canard-delta multirole fighter operated by the four partner nations and several export customers. It is intentionally aerodynamically unstable for maximum agility, requiring fly-by-wire computers to fly at all.",
    funFact:
      "The Typhoon is so aerodynamically unstable that it is literally uncontrollable without its fly-by-wire computers — the digital flight control system makes thousands of corrective inputs per second, transforming instability into extraordinary maneuverability.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines with rectangular intakes under forward fuselage",
      wingPosition: "mid",
      wingShape: "delta",
      tailType: "no-tail",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "large delta wing with straight leading edge",
        "close-coupled canard foreplanes ahead of wing",
        "no horizontal tail (tailless delta configuration)",
        "twin rectangular chin intakes below cockpit",
        "single vertical fin",
        "prominent IRST sensor ball ahead of windshield on starboard side",
        "four underfuselage missile stations",
      ],
    },
    aliases: ["Typhoon", "Eurofighter"],
  },
  {
    id: "dassault-rafale",
    name: "Dassault Rafale",
    manufacturer: "Dassault Aviation",
    type: "Fighter",
    firstFlight: "1986-07-04",
    inService: "2001",
    role: "Omnirole Multirole Fighter",
    country: "France",
    specs: {
      wingspan: "35 ft 9 in (10.9 m)",
      length: "50 ft 2 in (15.30 m)",
      maxSpeed: "Mach 1.8 (1,185 mph)",
      range: "2,300 mi (3,700 km)",
      ceiling: "50,000 ft (15,235 m)",
      engines: "2x Snecma M88-2 turbofan",
      crew: "1 or 2",
    },
    description:
      "The Rafale is France's twin-engine canard-delta omnirole fighter serving both the French Air and Space Force and Navy. Its 'omnirole' designation reflects ability to simultaneously conduct multiple different missions within a single sortie.",
    funFact:
      "France walked out of the Eurofighter consortium to build the Rafale alone — widely criticized as costly nationalism at the time — but decades later the Rafale's export success and capabilities have vindicated the decision, with India, Egypt, Greece, and Qatar all ordering it.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines with semi-circular rectangular side inlets",
      wingPosition: "mid",
      wingShape: "delta",
      tailType: "no-tail",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "delta wing with close-coupled canard foreplanes",
        "no horizontal tail",
        "single vertical fin",
        "distinctive OSF (Optronique Secteur Frontal) IRST sensor under nose",
        "half-round intake lips on semi-circular inlets",
        "compact sleek fuselage",
        "four underfuselage and underbody missile stations",
      ],
    },
    aliases: ["Rafale"],
  },
  {
    id: "saab-jas-39-gripen",
    name: "Saab JAS 39 Gripen",
    manufacturer: "Saab",
    type: "Fighter",
    firstFlight: "1988-12-09",
    inService: "1997",
    role: "Multirole Fighter",
    country: "Sweden",
    specs: {
      wingspan: "27 ft 7 in (8.4 m)",
      length: "46 ft 3 in (14.1 m)",
      maxSpeed: "Mach 2.0 (1,320 mph)",
      range: "1,800 mi (2,900 km) with drop tanks",
      ceiling: "50,000 ft (15,240 m)",
      engines: "1x Volvo RM12 turbofan",
      crew: "1",
    },
    description:
      "The Gripen is a lightweight single-engine multirole fighter combining Scandinavian efficiency with modern combat capability. Designed for dispersed operations from road bases, it can be rearmed and refueled in under 10 minutes by a team of six conscript soldiers.",
    funFact:
      "Sweden designed the Gripen to operate from public highways — it was literally tested on Swedish rural roads, and the standard 10-minute turnaround requires only six personnel and no specialist ground equipment, enabling dispersal far from traditional air bases.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "single engine with large rectangular ventral inlet",
      wingPosition: "low",
      wingShape: "delta",
      tailType: "no-tail",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "small close-coupled canard-delta configuration",
        "no horizontal tail",
        "single vertical fin",
        "large rectangular ventral inlet",
        "very compact size relative to other modern fighters",
        "distinctive small agile proportions",
      ],
    },
    aliases: ["Gripen", "Griffin"],
  },
  {
    id: "panavia-tornado",
    name: "Panavia Tornado",
    manufacturer: "Panavia Aircraft GmbH (BAC / MBB / Aeritalia)",
    type: "Strike Fighter",
    variant: "IDS / ADV / ECR",
    firstFlight: "1974-08-14",
    inService: "1979",
    role: "Interdiction / Strike / Air Defense / Electronic Combat",
    country: "UK / Germany / Italy",
    specs: {
      wingspan: "45 ft 7 in (13.91 m) spread / 28 ft 2 in (8.60 m) swept",
      length: "54 ft 9 in (16.7 m)",
      maxSpeed: "Mach 2.2 (1,452 mph)",
      range: "870 mi (1,390 km) strike; ferry 2,420 mi",
      ceiling: "50,000 ft (15,240 m)",
      engines: "2x Turbo-Union RB199-34R turbofan",
      crew: "2",
    },
    description:
      "The Panavia Tornado is a variable-geometry twin-engine strike aircraft built by a UK/Germany/Italy consortium. Its IDS variant was optimized for ultra-low-level supersonic penetration of Soviet air defenses; its ADV variant was a dedicated long-range interceptor.",
    funFact:
      "The Tornado IDS was designed to fly at 200 ft altitude at 800 km/h in total darkness — its terrain-following radar could automatically maintain this height, weaving through valleys, allowing the crew to rest while the aircraft navigated electronically.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines with cheek inlets on fuselage sides",
      wingPosition: "variable",
      wingShape: "variable-sweep",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "variable-sweep wings with distinctive pivot fairings",
        "two-seat tandem cockpit",
        "thrust-reversers visible as buckets at engine exhausts",
        "compact fuselage relative to large swing-wing",
        "spine fairing housing systems",
        "underfuselage cannon (IDS variant)",
      ],
    },
    aliases: ["Tornado IDS", "Tornado ADV"],
  },
  {
    id: "dassault-mirage-2000",
    name: "Dassault Mirage 2000",
    manufacturer: "Dassault Aviation",
    type: "Fighter",
    firstFlight: "1978-03-10",
    inService: "1984",
    role: "Multirole Fighter / Interceptor",
    country: "France",
    specs: {
      wingspan: "29 ft 6 in (9.0 m)",
      length: "47 ft 2 in (14.36 m)",
      maxSpeed: "Mach 2.2 (1,453 mph)",
      range: "900 mi (1,450 km) internal fuel",
      ceiling: "59,000 ft (18,000 m)",
      engines: "1x Snecma M53-P2 turbofan",
      crew: "1",
    },
    description:
      "The Mirage 2000 revived the pure tailless delta configuration of the Mirage III for the fly-by-wire era. Modern digital flight controls make its inherently unstable delta layout safe and highly maneuverable. It has been exported to nine nations.",
    funFact:
      "Dassault deliberately chose the pure delta wing for the Mirage 2000 — rejecting swept and canard designs chosen by competitors — arguing that fly-by-wire computers could make the simple unstable delta safer and more maneuverable than complex wing designs.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "single engine with large underfuselage circular intake",
      wingPosition: "mid",
      wingShape: "delta",
      tailType: "no-tail",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "pure tailless delta wing with no canard",
        "no horizontal tail whatsoever",
        "single vertical fin",
        "large circular underfuselage intake with splitter plate",
        "very clean aerodynamic profile",
        "slender nose with small pilot probe",
      ],
    },
    aliases: ["Mirage 2000"],
  },
  {
    id: "dassault-mirage-iii",
    name: "Dassault Mirage III",
    manufacturer: "Dassault Aviation",
    type: "Fighter",
    firstFlight: "1956-11-17",
    inService: "1961",
    role: "Interceptor / Ground Attack",
    country: "France",
    specs: {
      wingspan: "27 ft 0 in (8.22 m)",
      length: "48 ft 5 in (15.03 m)",
      maxSpeed: "Mach 2.2 (1,453 mph)",
      range: "1,550 mi (2,500 km)",
      ceiling: "55,775 ft (17,000 m)",
      engines: "1x Snecma Atar 9C turbojet",
      crew: "1",
    },
    description:
      "The Mirage III became one of France's greatest military export successes, serving in over 20 countries. Israeli Mirage IIIs were decisive in the 1967 Six-Day War, and the design directly inspired the Israeli Kfir and South African Cheetah.",
    funFact:
      "Israeli Mirage IIIs destroyed virtually the entire Egyptian Air Force in 188 minutes during the preemptive strikes of June 5, 1967 — over 300 aircraft destroyed, most on the ground, in the opening hours of the Six-Day War.",
    visual: {
      engineCount: 1,
      engineType: "turbojet",
      enginePlacement: "single engine with conical nose intake with movable centerbody",
      wingPosition: "mid",
      wingShape: "delta",
      tailType: "no-tail",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "classic tailless delta wing",
        "conical nose intake with movable inlet centerbody (shock cone)",
        "single fin, no horizontal stabilizer",
        "clean simple aerodynamic form",
        "small ventral fin beneath fuselage",
        "RATO booster attachment points on fuselage (some variants)",
      ],
    },
    aliases: ["Mirage III", "Mirage IIIC", "Mirage IIIE"],
  },
  {
    id: "bae-harrier-gr7-gr9",
    name: "BAE Harrier GR7/GR9",
    manufacturer: "British Aerospace / Boeing",
    type: "Attack",
    variant: "GR7 / GR9",
    firstFlight: "1989-11-20",
    inService: "1990",
    role: "Ground Attack / Close Air Support (STOVL)",
    country: "United Kingdom",
    specs: {
      wingspan: "30 ft 4 in (9.25 m)",
      length: "46 ft 4 in (14.12 m)",
      maxSpeed: "Mach 0.9 (662 mph)",
      range: "2,015 mi (3,243 km) with drop tanks",
      ceiling: "50,000 ft (15,240 m)",
      engines: "1x Rolls-Royce Pegasus 107 turbofan",
      crew: "1",
    },
    description:
      "The Harrier GR7/GR9 is the RAF's night/all-weather capable V/STOL ground attack variant based on the AV-8B. The GR9 upgrade added Brimstone anti-armor missiles and improved targeting systems before the UK controversially retired the entire fleet in 2010.",
    funFact:
      "The UK retired all Harriers in 2010 as a cost-cutting measure, leaving the Royal Navy with no carrier-based fixed-wing aircraft for seven years — widely criticized as a strategic blunder by former military chiefs.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "single Pegasus engine with four vectoring nozzles",
      wingPosition: "high",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "tandem",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "four rotating thrust-vectoring nozzles",
        "high-mounted swept wing",
        "bicycle undercarriage with small outrigger wingtip wheels",
        "large under-fuselage chin intake",
        "FLIR sensor pod under nose",
        "UK-specific avionics blisters vs. US AV-8B",
      ],
    },
    aliases: ["Harrier GR7", "Harrier GR9"],
  },
  {
    id: "english-electric-lightning",
    name: "English Electric Lightning",
    manufacturer: "English Electric / BAC",
    type: "Fighter",
    firstFlight: "1954-08-04",
    inService: "1960",
    role: "All-Weather Interceptor",
    country: "United Kingdom",
    specs: {
      wingspan: "34 ft 10 in (10.61 m)",
      length: "55 ft 3 in (16.84 m)",
      maxSpeed: "Mach 2.0+ (1,500 mph)",
      range: "800 mi (1,290 km)",
      ceiling: "60,000 ft (18,300 m)",
      engines: "2x Rolls-Royce Avon 301R turbojet (stacked vertically in fuselage)",
      crew: "1",
    },
    description:
      "The English Electric Lightning was Britain's only entirely supersonic fighter, famous for its extraordinary climb rate and unique stacked-engine arrangement. Its two Avon engines are mounted vertically one above the other in the fuselage, an arrangement found in no other operational fighter.",
    funFact:
      "The Lightning could climb from brake release to 36,000 ft in under 3 minutes — faster than most missiles of its era. Its fuel consumption was so extreme that afterburner climbs left some variants with barely 20 minutes of usable fuel remaining.",
    visual: {
      engineCount: 2,
      engineType: "turbojet",
      enginePlacement: "twin engines stacked vertically in fuselage with large ventral intake",
      wingPosition: "mid",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "twin engines stacked one above the other in fuselage (unique configuration)",
        "large oval ventral belly intake",
        "highly swept 60-degree leading edge wings",
        "T-tail with horizontal stabilizer mounted atop fin",
        "overwing fuel tanks on some variants",
        "very wide fuselage diameter relative to wingspan",
        "distinctive nose probe",
      ],
    },
    aliases: ["Lightning"],
  },
  {
    id: "sepecat-jaguar",
    name: "SEPECAT Jaguar",
    manufacturer: "SEPECAT (BAC / Dassault)",
    type: "Strike Fighter",
    firstFlight: "1968-09-08",
    inService: "1973",
    role: "Tactical Strike / Ground Attack / Advanced Trainer",
    country: "UK / France",
    specs: {
      wingspan: "28 ft 6 in (8.69 m)",
      length: "55 ft 2.5 in (16.83 m)",
      maxSpeed: "Mach 1.6 (1,056 mph)",
      range: "875 mi (1,408 km)",
      ceiling: "46,000 ft (14,020 m)",
      engines: "2x Rolls-Royce / Turbomeca Adour Mk 104 turbofan",
      crew: "1",
    },
    description:
      "The Jaguar is a Franco-British supersonic ground attack aircraft developed jointly as a tactical strike and advanced trainer. It excelled at low-level high-speed penetration and served with the RAF, French Air Force, India, Oman, and Nigeria.",
    funFact:
      "India's Jaguars were so substantially upgraded with Israeli avionics and DARIN navigation/attack systems that they served as frontline aircraft until 2023 — fifty years after the Jaguar's first flight, still effective in the strike role.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines in fuselage with large oval underfuselage inlets",
      wingPosition: "mid",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "high-set cockpit providing good forward visibility",
        "pronounced anhedral (downward slant) on horizontal tail surfaces",
        "large oval intakes under each wing root",
        "tall slender single fin",
        "distinctive dorsal spine avionics fairing",
        "two 30mm ADEN cannon in fuselage sides",
      ],
    },
    aliases: ["Jaguar"],
  },

  // ============================================================
  // CHINESE FIGHTERS
  // ============================================================
  {
    id: "chengdu-j-10",
    name: "Chengdu J-10",
    manufacturer: "Chengdu Aircraft Corporation",
    type: "Fighter",
    natoReportingName: "Firebird",
    firstFlight: "1998-03-23",
    inService: "2003",
    role: "Multirole Fighter",
    country: "China",
    specs: {
      wingspan: "31 ft 2 in (9.5 m)",
      length: "49 ft 3 in (15.01 m)",
      maxSpeed: "Mach 2.0 (1,320 mph)",
      range: "1,243 mi (2,000 km)",
      ceiling: "59,055 ft (18,000 m)",
      engines: "1x Saturn AL-31FN or WS-10B turbofan",
      crew: "1",
    },
    description:
      "The J-10 is China's first domestically developed fourth-generation multirole fighter, featuring a canard-delta configuration. Developed partly with Israeli technical assistance following that nation's cancelled Lavi program, it replaced MiG-21 derivatives in PLAAF service.",
    funFact:
      "The J-10's development was significantly aided by Israeli technical assistance — Israel had developed the Lavi fighter incorporating F-16 technology before US pressure forced cancellation, and much of that design knowledge transferred to China in the 1990s.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "single engine with large rectangular chin inlet",
      wingPosition: "mid",
      wingShape: "delta",
      tailType: "no-tail",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "canard-delta configuration with no horizontal tail",
        "large rectangular chin inlet with splitter plate",
        "DSI inlet bump on J-10B/C variants",
        "single vertical tail",
        "close-coupled canard foreplanes",
        "resemblance to Israeli Lavi in overall layout",
      ],
    },
    aliases: ["Vigorous Dragon", "Firebird (NATO)"],
  },
  {
    id: "chengdu-j-20",
    name: "Chengdu J-20",
    manufacturer: "Chengdu Aircraft Corporation",
    type: "Fighter",
    natoReportingName: "Mighty Dragon",
    firstFlight: "2011-01-11",
    inService: "2017",
    role: "Fifth-Generation Stealth Air Superiority Fighter",
    country: "China",
    specs: {
      wingspan: "44 ft 7 in (13.6 m) estimated",
      length: "70 ft 10 in (21.6 m) estimated",
      maxSpeed: "Mach 2.0+ (estimated)",
      range: "1,553 mi (2,500 km) estimated",
      ceiling: "65,600 ft (20,000 m) estimated",
      engines: "2x WS-10C or WS-15 turbofan",
      crew: "1",
    },
    description:
      "The J-20 is China's first operational fifth-generation stealth fighter, larger than either the F-22 or F-35 and optimized for long-range penetration and BVR combat. It features internal weapons bays, canard-delta configuration, and chined nose for stealth.",
    funFact:
      "The J-20's large internal fuel capacity and long range are believed to be specifically optimized for anti-access missions against US carrier strike groups and the tanker aircraft that keep US fighters flying over the Pacific.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines with DSI bump inlets on fuselage cheeks",
      wingPosition: "mid",
      wingShape: "delta",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "canard foreplanes with no horizontal tail",
        "twin all-moving canted vertical tails",
        "large chined (faceted) nose for stealth",
        "DSI inlets with prominent bump on each fuselage side",
        "very long fuselage for internal weapons bays and fuel",
        "side-opening main weapons bays",
        "ventral fins under rear fuselage",
      ],
    },
    aliases: ["Mighty Dragon", "Weilong"],
  },
  {
    id: "shenyang-fc-31-j-35",
    name: "Shenyang FC-31 / J-35",
    manufacturer: "Shenyang Aircraft Corporation",
    type: "Fighter",
    variant: "FC-31 (export) / J-35 (PLANAF carrier)",
    firstFlight: "2012-10-31",
    inService: "2022",
    role: "Fifth-Generation Stealth Multirole Fighter",
    country: "China",
    specs: {
      wingspan: "37 ft 9 in (11.5 m) estimated",
      length: "55 ft 9 in (17.0 m) estimated",
      maxSpeed: "Mach 1.8+ estimated",
      range: "1,240 mi (2,000 km) estimated",
      ceiling: "52,500 ft (16,000 m) estimated",
      engines: "2x WS-13E turbofan",
      crew: "1",
    },
    description:
      "The FC-31/J-35 is China's second fifth-generation stealth fighter, smaller than the J-20 and designed for both export and carrier operations. The J-35 carrier variant entered service aboard China's Fujian carrier, giving China a credible carrier-based stealth capability.",
    funFact:
      "Western analysts noted striking similarities between the FC-31 and the F-35 after Chinese hackers were found to have stolen F-35 design data in 2009 — similarities in nose shape, intake geometry, and landing gear arrangement prompted detailed comparisons.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "twin engines with rectangular cheek inlets",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "twin-engine stealth layout",
        "rectangular inlets on fuselage cheeks",
        "twin canted vertical tails",
        "internal weapons bays",
        "folding wingtips on J-35 carrier variant",
        "arresting hook under rear fuselage (J-35)",
        "overall proportions resembling a blend of F-22 and F-35",
      ],
    },
    aliases: ["Gyrfalcon", "J-35", "FC-31"],
  },

  // ============================================================
  // OTHER NATIONS
  // ============================================================
  {
    id: "mitsubishi-f-2",
    name: "Mitsubishi F-2",
    manufacturer: "Mitsubishi Heavy Industries / Lockheed Martin",
    type: "Fighter",
    firstFlight: "1995-10-07",
    inService: "2000",
    role: "Multirole Fighter / Maritime Strike",
    country: "Japan",
    specs: {
      wingspan: "36 ft 5 in (11.13 m)",
      length: "51 ft 0 in (15.52 m)",
      maxSpeed: "Mach 2.0 (1,320 mph)",
      range: "834 mi (1,343 km)",
      ceiling: "59,055 ft (18,000 m)",
      engines: "1x General Electric F110-GE-129 turbofan",
      crew: "1",
    },
    description:
      "The F-2 is a multirole fighter jointly developed by Japan and the United States, based on but substantially larger than the F-16. It introduced one of the first production AESA (active electronically scanned array) radars and carries four ASM-2 anti-ship missiles for maritime strike.",
    funFact:
      "The F-2 was the first production fighter to carry an active phased-array (AESA) radar — Japan's J/APG-1 radar entered service before any American fighter had AESA, though its capabilities were initially limited compared to later systems.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "single engine with large chin inlet",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "enlarged cranked-delta wing notably wider than F-16",
        "AESA radar producing distinctive large nose radome",
        "JASDF hinomaru roundel markings",
        "four underwing hardpoints on enlarged wing",
        "single chin inlet like F-16 but with larger fuselage",
        "slightly longer fuselage than F-16",
      ],
    },
    aliases: ["Support Fighter", "FS-X"],
  },
  {
    id: "hal-tejas",
    name: "HAL Tejas",
    manufacturer: "Hindustan Aeronautics Limited",
    type: "Fighter",
    firstFlight: "2001-01-04",
    inService: "2016",
    role: "Light Multirole Fighter",
    country: "India",
    specs: {
      wingspan: "26 ft 0 in (8.2 m)",
      length: "43 ft 0 in (13.2 m)",
      maxSpeed: "Mach 1.8 (1,185 mph)",
      range: "1,850 mi (2,975 km) ferry",
      ceiling: "50,000 ft (15,240 m)",
      engines: "1x General Electric F404-GE-IN20 turbofan",
      crew: "1",
    },
    description:
      "The Tejas is India's first fully indigenous production combat aircraft, a lightweight tailless compound-delta fighter developed by HAL after three decades of effort. It features quadruplex fly-by-wire controls and an AESA radar in the Mk1A variant.",
    funFact:
      "India's Tejas program took over 30 years from inception to operational service — longer than almost any comparable aircraft in history — but the resulting aircraft can now be upgraded entirely without foreign permission, a major strategic goal for India.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "single engine with rectangular ventral inlet",
      wingPosition: "mid",
      wingShape: "delta",
      tailType: "no-tail",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "tailless compound delta wing",
        "no horizontal tail",
        "single vertical fin",
        "rectangular ventral inlet under fuselage",
        "blended wing-body with smooth transitions",
        "compact size relative to peers",
        "quadruplex fly-by-wire system",
      ],
    },
    aliases: ["Tejas", "Light Combat Aircraft", "LCA"],
  },
  {
    id: "iai-kfir",
    name: "IAI Kfir",
    manufacturer: "Israel Aerospace Industries",
    type: "Fighter",
    firstFlight: "1973-10-19",
    inService: "1975",
    role: "Multirole Fighter / Ground Attack",
    country: "Israel",
    specs: {
      wingspan: "26 ft 11 in (8.22 m)",
      length: "51 ft 4 in (15.65 m)",
      maxSpeed: "Mach 2.3 (1,516 mph)",
      range: "1,305 mi (2,100 km)",
      ceiling: "58,000 ft (17,680 m)",
      engines: "1x General Electric J79-J1E turbojet",
      crew: "1",
    },
    description:
      "The Kfir (Lion Cub) is an Israeli multirole fighter based on the Mirage 5 airframe but re-engined with the American J79 turbojet. Israel built it after France embargoed aircraft sales following the 1967 war, partly using clandestinely obtained Mirage blueprints.",
    funFact:
      "Israel built the Kfir by secretly obtaining the Mirage 5 technical drawings — a Swiss engineer working at Dassault passed plans to Israeli intelligence, and the entire development was classified. France protested vigorously when the Kfir was revealed.",
    visual: {
      engineCount: 1,
      engineType: "turbojet",
      enginePlacement: "single J79 engine with circular nose intake and wider rear fuselage",
      wingPosition: "mid",
      wingShape: "delta",
      tailType: "no-tail",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "Mirage III/5 delta airframe base with wider rear fuselage for J79 engine",
        "small close-coupled canard strakes just behind cockpit on C2/C7 variants",
        "J79 engine gives wider-diameter rear fuselage than original Mirage",
        "nose pitot boom",
        "pure tailless delta wing",
        "slightly blunter nose than Mirage III",
      ],
    },
    aliases: ["Kfir", "Lion Cub"],
  },
];
