import { AircraftEntry } from "./types";

export const militaryOther: AircraftEntry[] = [
  // ============================================================
  // BOMBERS
  // ============================================================
  {
    id: "b-52-stratofortress",
    name: "B-52 Stratofortress",
    manufacturer: "Boeing",
    type: "Strategic Bomber",
    firstFlight: "1952",
    inService: "1955",
    role: "Strategic Bomber",
    country: "USA",
    specs: {
      wingspan: "185 ft (56.4 m)",
      length: "159 ft 4 in (48.5 m)",
      maxSpeed: "650 mph (1,047 km/h)",
      range: "8,800 mi (14,162 km) unrefueled",
      ceiling: "50,000 ft (15,240 m)",
      engines: "8x Pratt & Whitney TF33-PW-103 turbofan",
      crew: "5",
    },
    description:
      "The B-52 Stratofortress is the longest-serving bomber in the US Air Force inventory, having first entered service in 1955. Its remarkable longevity stems from continuous upgrades that have kept it relevant despite being designed during the early Cold War. The aircraft is capable of delivering a wide range of conventional and nuclear weapons, and has served in every major US conflict since Vietnam.",
    funFact:
      "The B-52 has been in service so long that some pilots flying the aircraft today have grandfathers who also flew it — it is expected to remain operational until at least 2050, giving it a century of service.",
    visual: {
      engineCount: 8,
      engineType: "turbofan",
      enginePlacement: "Four twin-engine pods under swept wings",
      wingPosition: "high",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "cold-war",
      distinguishingFeatures: [
        "Eight engines in four underwing pods",
        "Drooping wingtips",
        "Distinctive bicycle-style landing gear",
        "Swept high-mounted wings",
      ],
    },
    aliases: ["BUFF (Big Ugly Fat Fellow)", "Stratofortress"],
  },
  {
    id: "b-1b-lancer",
    name: "B-1B Lancer",
    manufacturer: "Rockwell (now Boeing)",
    type: "Strategic Bomber",
    firstFlight: "1974",
    inService: "1986",
    role: "Strategic Bomber / Conventional Strike",
    country: "USA",
    specs: {
      wingspan: "137 ft (41.8 m) swept, 79 ft (24 m) extended",
      length: "146 ft (44.5 m)",
      maxSpeed: "Mach 1.25 (900+ mph)",
      range: "6,478 mi (10,400 km)",
      ceiling: "60,000 ft (18,288 m)",
      engines: "4x General Electric F101-GE-102 turbofan",
      crew: "4",
    },
    description:
      "The B-1B Lancer is a supersonic variable-sweep wing heavy bomber that replaced the B-52 in some roles while operating alongside it. Known as 'the Bone' by its crews, it features a distinctive variable-sweep wing design that allows it to fly at low altitude and high speed to penetrate enemy defenses. Originally designed as a nuclear delivery platform, it was converted to a conventional strike role in the 1990s.",
    funFact:
      "The B-1B's variable-sweep wings can be configured anywhere from 15 degrees (fully spread for takeoff and loitering) to 67.5 degrees (fully swept for high-speed flight), allowing it to be optimized for very different mission profiles.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Two pairs of engines under fuselage/wing roots in nacelles",
      wingPosition: "variable",
      wingShape: "variable-sweep",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "modern",
      distinguishingFeatures: [
        "Variable-sweep wings",
        "Blended fuselage/wing design",
        "Four engines in two nacelle pairs",
        "Pointed nose with pointed cockpit fairing",
      ],
    },
    aliases: ["The Bone", "Lancer"],
  },
  {
    id: "b-2-spirit",
    name: "B-2 Spirit",
    manufacturer: "Northrop Grumman",
    type: "Stealth Strategic Bomber",
    firstFlight: "1989",
    inService: "1997",
    role: "Strategic Stealth Bomber",
    country: "USA",
    specs: {
      wingspan: "172 ft (52.4 m)",
      length: "69 ft (21 m)",
      maxSpeed: "Mach 0.95 (630 mph / 1,010 km/h)",
      range: "6,000 mi (9,600 km) without refueling",
      ceiling: "50,000 ft (15,152 m)",
      engines: "4x General Electric F118-GE-100 turbofan",
      crew: "2",
    },
    description:
      "The B-2 Spirit is a stealth strategic bomber that employs a flying wing design to achieve an extremely low radar cross-section. Only 21 were built, making it the most expensive aircraft ever produced at approximately $2.1 billion per airframe. Its flying wing shape eliminates conventional tail surfaces, reducing radar returns dramatically. The aircraft can carry both conventional and thermonuclear weapons.",
    funFact:
      "The B-2 requires climate-controlled hangars because temperature and humidity changes can affect its radar-absorbing material coating. A single maintenance inspection can take as long as 124 man-hours per flight hour.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Four engines buried within the flying wing",
      wingPosition: "mid",
      wingShape: "swept",
      tailType: "no-tail",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "modern",
      distinguishingFeatures: [
        "Pure flying wing design with no tail surfaces",
        "W-shaped trailing edge",
        "Extremely flat profile",
        "All-wing planform",
        "Hidden engine inlets",
      ],
    },
    aliases: ["Spirit", "Stealth Bomber"],
  },
  {
    id: "b-21-raider",
    name: "B-21 Raider",
    manufacturer: "Northrop Grumman",
    type: "Stealth Strategic Bomber",
    firstFlight: "2023",
    inService: "2026 (projected)",
    role: "Strategic Stealth Bomber",
    country: "USA",
    specs: {
      wingspan: "~140 ft (estimated)",
      length: "~68 ft (estimated)",
      maxSpeed: "Classified (estimated subsonic)",
      range: "Classified (intercontinental capable)",
      ceiling: "Classified",
      engines: "2x turbofan (type classified)",
      crew: "2 (optionally unmanned capable)",
    },
    description:
      "The B-21 Raider is the United States Air Force's next-generation stealth strategic bomber, designed to replace both the B-1B Lancer and B-52 Stratofortress over time. It shares its flying wing lineage with the B-2 Spirit but incorporates dramatically improved stealth technology, open-mission systems architecture, and the ability to operate optionally unmanned. The Raider is named in honor of the Doolittle Raiders.",
    funFact:
      "The B-21 is designed from the outset to be upgradeable through software rather than hardware modifications, a concept called 'open architecture' that allows new weapons and sensor systems to be integrated quickly without expensive structural changes.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Two engines buried within the flying wing body",
      wingPosition: "mid",
      wingShape: "swept",
      tailType: "no-tail",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "Flying wing design similar to B-2 but smaller",
        "Highly refined stealth shaping",
        "Smooth continuous wing planform",
        "No vertical tail surfaces",
      ],
    },
    aliases: ["Raider"],
  },
  {
    id: "avro-vulcan",
    name: "Avro Vulcan",
    manufacturer: "Avro (Hawker Siddeley)",
    type: "Strategic Bomber",
    variant: "B.2",
    firstFlight: "1952",
    inService: "1956–1984",
    role: "Strategic Nuclear Bomber",
    country: "UK",
    specs: {
      wingspan: "111 ft (33.8 m)",
      length: "99 ft 11 in (30.4 m)",
      maxSpeed: "Mach 0.98 (645 mph / 1,038 km/h)",
      range: "4,600 mi (7,400 km)",
      ceiling: "55,000 ft (16,764 m)",
      engines: "4x Bristol Olympus 301 turbojet",
      crew: "5",
    },
    description:
      "The Avro Vulcan was one of the UK's V-bombers, forming the backbone of Britain's airborne nuclear deterrent during the Cold War. Its distinctive delta wing gave it an unusual appearance for the era and provided excellent high-altitude performance. The Vulcan gained lasting fame during the 1982 Falklands War with Operation Black Buck — the longest-distance bombing raids in history at the time.",
    funFact:
      "During the Falklands War, each Black Buck mission required 11 Victor tanker aircraft to get a single Vulcan to the target at Stanley Airfield and back — a feat of aerial refueling coordination never attempted before or since.",
    visual: {
      engineCount: 4,
      engineType: "turbojet",
      enginePlacement: "Four engines buried in the delta wing roots",
      wingPosition: "low",
      wingShape: "delta",
      tailType: "no-tail",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "cold-war",
      distinguishingFeatures: [
        "Large ogival delta wing",
        "No horizontal tail surfaces",
        "Engines buried in wing roots",
        "Distinctive triangular planform",
      ],
    },
    aliases: ["V-Bomber"],
  },
  {
    id: "tu-95-bear",
    name: "Tupolev Tu-95 Bear",
    manufacturer: "Tupolev",
    type: "Strategic Bomber / Maritime Patrol",
    natoReportingName: "Bear",
    firstFlight: "1952",
    inService: "1956",
    role: "Strategic Bomber / Maritime Patrol",
    country: "Russia",
    specs: {
      wingspan: "164 ft 11 in (50.3 m)",
      length: "151 ft 6 in (46.2 m)",
      maxSpeed: "575 mph (925 km/h)",
      range: "9,400 mi (15,000 km)",
      ceiling: "45,000 ft (13,716 m)",
      engines: "4x Kuznetsov NK-12 turboprop",
      crew: "6–7",
    },
    description:
      "The Tupolev Tu-95 Bear is a large strategic bomber and maritime patrol aircraft that remains the only turboprop-powered bomber in operational service today. Its four massive contra-rotating propeller assemblies produce a distinctive sound loud enough to be heard on submarine sonar. The Bear has been continuously upgraded since its introduction and serves in various variants including missile carrier, electronic intelligence, and maritime patrol roles.",
    funFact:
      "The Tu-95's contra-rotating propellers turn in opposite directions on the same shaft, which eliminates torque effects and makes it the fastest propeller-driven aircraft ever built. It is so loud that NATO submarines can reportedly hear it on their passive sonar.",
    visual: {
      engineCount: 4,
      engineType: "turboprop",
      enginePlacement: "Four engines mounted on swept wings, each with contra-rotating props",
      wingPosition: "mid",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "cold-war",
      distinguishingFeatures: [
        "Four massive contra-rotating propeller engines",
        "Swept wings with large engine nacelles",
        "Tail gunner position",
        "Very long fuselage",
      ],
    },
    aliases: ["Bear", "Tu-95MS"],
  },
  {
    id: "tu-160-blackjack",
    name: "Tupolev Tu-160 Blackjack",
    manufacturer: "Tupolev",
    type: "Strategic Bomber",
    natoReportingName: "Blackjack",
    firstFlight: "1981",
    inService: "1987",
    role: "Strategic Bomber",
    country: "Russia",
    specs: {
      wingspan: "182 ft 9 in (55.7 m) spread, 109 ft 11 in (33.5 m) swept",
      length: "177 ft 6 in (54.1 m)",
      maxSpeed: "Mach 2.05 (1,380 mph / 2,220 km/h)",
      range: "7,643 mi (12,300 km)",
      ceiling: "52,000 ft (15,850 m)",
      engines: "4x Kuznetsov NK-32 turbofan",
      crew: "4",
    },
    description:
      "The Tupolev Tu-160 Blackjack is the world's largest and heaviest combat aircraft, as well as the fastest bomber currently in service. A variable-sweep wing supersonic strategic bomber, it was designed to penetrate NATO air defenses at high speed and low altitude. Despite resembling the American B-1B externally, it was developed independently and differs significantly in design philosophy. Russia has resumed production of upgraded Tu-160M variants.",
    funFact:
      "The Tu-160 is painted white — earning it the Russian nickname 'White Swan' — not for aesthetics but because white reflects thermal radiation during a nuclear blast, providing marginal protection to the aircraft and crew.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Four engines in two underwing nacelle pairs",
      wingPosition: "variable",
      wingShape: "variable-sweep",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "super-heavy",
      era: "modern",
      distinguishingFeatures: [
        "Variable-sweep wings",
        "White paint scheme",
        "Very large fuselage",
        "Four engines in paired nacelles",
        "Distinctive blended wing-body",
      ],
    },
    aliases: ["White Swan", "Blackjack"],
  },
  {
    id: "handley-page-victor",
    name: "Handley Page Victor",
    manufacturer: "Handley Page",
    type: "Strategic Bomber / Tanker",
    variant: "B.2 / K.2",
    firstFlight: "1952",
    inService: "1958–1993",
    role: "Strategic Bomber / Aerial Refueling Tanker",
    country: "UK",
    specs: {
      wingspan: "120 ft (36.6 m)",
      length: "114 ft 11 in (35.0 m)",
      maxSpeed: "Mach 0.92 (640 mph / 1,030 km/h)",
      range: "4,600 mi (7,400 km)",
      ceiling: "56,000 ft (17,069 m)",
      engines: "4x Rolls-Royce Conway 201 turbofan",
      crew: "5",
    },
    description:
      "The Handley Page Victor was the last of Britain's three V-bombers to enter service, distinguished by its crescent-shaped wings and T-tail configuration. After its nuclear strike role was replaced by Polaris submarines in the 1960s, the Victor was converted to the tanker role and served the RAF for decades more. Victor tankers played a crucial role in the Falklands War supporting Vulcan Black Buck raids.",
    funFact:
      "The Victor's unusual crescent wing was designed to sweep progressively from root to tip — the root is swept more than the tip — which ensured that shock waves formed uniformly across the wing at high transonic speeds, preventing dangerous pitch changes.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Four engines buried in the crescent wing roots",
      wingPosition: "high",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "cold-war",
      distinguishingFeatures: [
        "Crescent-shaped swept wings",
        "T-tail configuration",
        "Engines buried in wing roots",
        "High-mounted wings with compound sweep",
      ],
    },
    aliases: ["V-Bomber"],
  },

  // ============================================================
  // TRANSPORTS
  // ============================================================
  {
    id: "c-130-hercules",
    name: "C-130 Hercules",
    manufacturer: "Lockheed (now Lockheed Martin)",
    type: "Military Transport",
    firstFlight: "1954",
    inService: "1956",
    role: "Tactical Airlift / Multi-role Transport",
    country: "USA",
    specs: {
      wingspan: "132 ft 7 in (40.4 m)",
      length: "97 ft 9 in (29.8 m)",
      maxSpeed: "366 mph (589 km/h)",
      range: "2,356 mi (3,791 km) with max payload",
      ceiling: "28,000 ft (8,534 m)",
      engines: "4x Allison T56-A-15 turboprop",
      crew: "5",
      capacity: "92 troops or 64 paratroopers or 74 litter patients",
    },
    description:
      "The C-130 Hercules is one of the most versatile and long-lived military transport aircraft ever built. Its high-mounted wings, turboprop engines, and rear-loading ramp allow it to operate from unprepared dirt strips while carrying heavy cargo. More than 70 variants have been produced for over 60 nations, serving roles from gunships to weather reconnaissance, aerial firefighting, and coast guard patrol.",
    funFact:
      "A C-130 once landed and took off from the deck of the USS Forrestal aircraft carrier in 1963 during tests — carrying no arresting gear, no catapult, and no tail hook. It remains the largest aircraft ever to land on a carrier.",
    visual: {
      engineCount: 4,
      engineType: "turboprop",
      enginePlacement: "Four turboprops mounted on high-mounted straight wings",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "cold-war",
      distinguishingFeatures: [
        "High-mounted straight wings",
        "Four turboprop engines",
        "Rear loading ramp",
        "Upswept rear fuselage",
        "Rounded nose with cockpit greenhouse windows",
      ],
    },
    aliases: ["Herc", "Hercules", "Herk"],
  },
  {
    id: "c-130j-super-hercules",
    name: "C-130J Super Hercules",
    manufacturer: "Lockheed Martin",
    type: "Military Transport",
    firstFlight: "1996",
    inService: "1999",
    role: "Tactical Airlift / Multi-role Transport",
    country: "USA",
    specs: {
      wingspan: "132 ft 7 in (40.4 m)",
      length: "97 ft 9 in (29.8 m) or 112 ft 9 in (34.4 m) stretched",
      maxSpeed: "417 mph (671 km/h)",
      range: "3,107 mi (5,000 km)",
      ceiling: "28,000 ft (8,534 m)",
      engines: "4x Rolls-Royce AE 2100D3 turboprop",
      crew: "3",
      capacity: "92 troops or 74 litter patients",
    },
    description:
      "The C-130J Super Hercules is a thoroughly modernized Hercules featuring new Rolls-Royce AE 2100 turboprops driving six-blade composite propellers, a digital glass cockpit, and modern avionics that reduce crew from five to three. Despite sharing the classic Hercules silhouette, the J-model shares less than 20% of parts with earlier variants. It is the current production standard and serves dozens of air forces worldwide.",
    funFact:
      "Despite the 'J' suffix implying an incremental upgrade, the C-130J is so different from earlier Hercules variants that pilots need a completely separate type rating — they cannot simply upgrade from a C-130E or H checkout.",
    visual: {
      engineCount: 4,
      engineType: "turboprop",
      enginePlacement: "Four turboprops with six-blade props on high-mounted wings",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "Six-blade composite propellers",
        "High-mounted straight wings",
        "Rear loading ramp",
        "Glass cockpit visible through greenhouse windows",
      ],
    },
    aliases: ["Super Herc", "J-model"],
  },
  {
    id: "c-17-globemaster-iii",
    name: "C-17 Globemaster III",
    manufacturer: "McDonnell Douglas / Boeing",
    type: "Strategic / Tactical Transport",
    firstFlight: "1991",
    inService: "1993",
    role: "Strategic and Tactical Airlift",
    country: "USA",
    specs: {
      wingspan: "169 ft 10 in (51.8 m)",
      length: "174 ft (53.0 m)",
      maxSpeed: "Mach 0.77 (515 mph / 830 km/h)",
      range: "2,785 mi (4,482 km) with 160,000 lb payload",
      ceiling: "45,000 ft (13,716 m)",
      engines: "4x Pratt & Whitney F117-PW-100 turbofan",
      crew: "3",
      capacity: "77,519 kg payload or 102 paratroopers",
    },
    description:
      "The C-17 Globemaster III combines the strategic range of a large jet transport with the tactical ability to land on short, austere airstrips. Its externally blown flap system allows steep approaches to short runways while carrying maximum loads. The aircraft can also back up under its own power, a capability called 'reverse thrust' parking that allows operation from small ramps. Production ended in 2015 with 279 built.",
    funFact:
      "The C-17 can perform a 'combat offload' — releasing palletized cargo by driving pallets off the back ramp while rolling down a runway at low speed — delivering supplies to airfields too dangerous to stop on.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Four high-bypass turbofans on straight high wings",
      wingPosition: "high",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "modern",
      distinguishingFeatures: [
        "T-tail configuration",
        "Four turbofans on high-mounted swept wings",
        "Rear loading ramp",
        "Winglets on wingtips",
        "Very large cargo door",
      ],
    },
    aliases: ["Globemaster", "C-17"],
  },
  {
    id: "c-5-galaxy",
    name: "C-5 Galaxy",
    manufacturer: "Lockheed (now Lockheed Martin)",
    type: "Strategic Heavy Transport",
    variant: "C-5M Super Galaxy",
    firstFlight: "1968",
    inService: "1969",
    role: "Strategic Heavy Airlift",
    country: "USA",
    specs: {
      wingspan: "222 ft 9 in (67.9 m)",
      length: "247 ft 1 in (75.3 m)",
      maxSpeed: "Mach 0.79 (518 mph / 833 km/h)",
      range: "5,524 mi (8,889 km) with 120,000 lb payload",
      ceiling: "35,700 ft (10,880 m)",
      engines: "4x General Electric CF6-80C2 turbofan (C-5M)",
      crew: "7",
      capacity: "129,000 kg payload / 270 troops",
    },
    description:
      "The C-5 Galaxy is one of the largest military aircraft in the world, capable of carrying 270 troops or oversized cargo including main battle tanks and helicopters. It features both front- and rear-loading doors, allowing drive-through loading of vehicles. The C-5M Super Galaxy upgrade replaced the original TF39 engines with far more efficient CF6-80C2 turbofans and added modern avionics, extending the fleet's service life to 2040.",
    funFact:
      "The C-5 can carry the equivalent weight of six fully loaded school buses, and its cargo floor can accommodate two M1 Abrams main battle tanks, three UH-60 Black Hawk helicopters, or a complete disassembled Space Shuttle main engine.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Four large turbofans in underwing pods on high-mounted wings",
      wingPosition: "high",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "super-heavy",
      era: "cold-war",
      distinguishingFeatures: [
        "Enormous size",
        "T-tail",
        "Front and rear cargo doors",
        "High-mounted swept wings",
        "Four large underwing engine pods",
      ],
    },
    aliases: ["Galaxy", "FRED (Fantastic Ridiculous Economic Disaster)"],
  },
  {
    id: "c-141-starlifter",
    name: "C-141 Starlifter",
    manufacturer: "Lockheed",
    type: "Strategic Transport",
    variant: "C-141B",
    firstFlight: "1963",
    inService: "1965–2006",
    role: "Strategic Airlift",
    country: "USA",
    specs: {
      wingspan: "159 ft 11 in (48.7 m)",
      length: "168 ft 3 in (51.3 m)",
      maxSpeed: "Mach 0.775 (512 mph / 824 km/h)",
      range: "4,080 mi (6,570 km) with full payload",
      ceiling: "41,600 ft (12,680 m)",
      engines: "4x Pratt & Whitney TF33-P-7 turbofan",
      crew: "4–5",
      capacity: "90 troops or 62,774 kg payload",
    },
    description:
      "The C-141 Starlifter was the US Air Force's first dedicated jet strategic airlifter, entering service in 1965. It bridged the gap between piston-engine transports and the later C-5 Galaxy, providing a genuine intercontinental airlift capability. The fleet was stretched in the 1970s by inserting a 23-foot fuselage plug, effectively creating 90 new aircraft from 270 existing airframes. It was retired in 2006, replaced by the C-17.",
    funFact:
      "The C-141 was so consistently and heavily used during the Vietnam War that it became known as 'The Hanoi Taxi' — a specific aircraft (serial 66-0177) that carried the first American POWs home from Hanoi in 1973 is preserved at the National Museum of the US Air Force.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Four turbofans in underwing pods on swept high-mounted wings",
      wingPosition: "high",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "cold-war",
      distinguishingFeatures: [
        "T-tail",
        "High-mounted swept wings",
        "Four underwing engine pods",
        "Upswept rear fuselage with rear ramp",
      ],
    },
    aliases: ["Starlifter", "Hanoi Taxi"],
  },
  {
    id: "c-2-greyhound",
    name: "C-2 Greyhound",
    manufacturer: "Grumman",
    type: "Carrier Onboard Delivery",
    firstFlight: "1964",
    inService: "1966",
    role: "Carrier Onboard Delivery (COD)",
    country: "USA",
    specs: {
      wingspan: "80 ft 7 in (24.6 m)",
      length: "57 ft 7 in (17.6 m)",
      maxSpeed: "352 mph (567 km/h)",
      range: "1,495 mi (2,400 km)",
      ceiling: "30,000 ft (9,144 m)",
      engines: "2x Allison T56-A-425 turboprop",
      crew: "4",
      capacity: "26 passengers or 4,536 kg cargo",
    },
    description:
      "The C-2 Greyhound is a carrier onboard delivery aircraft derived from the E-2 Hawkeye airframe, sharing its wings and powerplant but featuring a completely different wide fuselage designed for cargo and passenger transport. It operates from aircraft carriers to deliver mail, spare parts, and personnel, performing arrested landings and catapult-assisted takeoffs — demanding feats for a transport aircraft. The CMV-22B Osprey is gradually replacing it.",
    funFact:
      "The C-2 Greyhound can fold its wings and fit within an aircraft carrier elevator, allowing it to be stowed below deck. Cargo inside can weigh up to 10,000 lbs, and it must decelerate from ~130 mph to zero in about two seconds on carrier landing.",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "Two turboprops on high-mounted wings",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "twin",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "Twin tail fins",
        "High-mounted folding wings",
        "Wide fuselage for cargo",
        "Rear loading ramp",
        "Carrier-capable with tailhook",
      ],
    },
    aliases: ["Greyhound", "COD"],
  },
  {
    id: "airbus-a400m",
    name: "Airbus A400M Atlas",
    manufacturer: "Airbus Defence and Space",
    type: "Military Transport",
    firstFlight: "2009",
    inService: "2013",
    role: "Tactical / Strategic Airlift",
    country: "International (EU)",
    specs: {
      wingspan: "139 ft 1 in (42.4 m)",
      length: "148 ft 3 in (45.1 m)",
      maxSpeed: "485 mph (780 km/h)",
      range: "5,466 mi (8,710 km) ferry range",
      ceiling: "37,073 ft (11,300 m)",
      engines: "4x Europrop TP400-D6 turboprop",
      crew: "2–3",
      capacity: "37,000 kg payload / 116 fully equipped troops",
    },
    description:
      "The Airbus A400M Atlas bridges the gap between tactical airlifters like the C-130 and strategic heavylifters like the C-17. Powered by four powerful turboprop engines driving eight-bladed scimitar propellers, it can cruise at jet-like speeds while retaining the ability to land on unprepared strips. Built by a consortium of European nations, it serves France, Germany, Spain, Turkey, the UK, and others. The TP400 engine is the most powerful turboprop engine in the Western world.",
    funFact:
      "The A400M's TP400 engines rotate in opposite directions — the two engines on the left wing spin clockwise and the two on the right spin counterclockwise — which eliminates asymmetric torque and improves handling during single-engine operations.",
    visual: {
      engineCount: 4,
      engineType: "turboprop",
      enginePlacement: "Four turboprops with eight-bladed scimitar propellers on high-mounted wings",
      wingPosition: "high",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "Eight-bladed scimitar propellers",
        "Four large turboprop engines",
        "Swept high-mounted wings",
        "Rear loading ramp",
        "Distinctive nose shape",
      ],
    },
    aliases: ["Atlas"],
  },
  {
    id: "kawasaki-c-2",
    name: "Kawasaki C-2",
    manufacturer: "Kawasaki Aerospace",
    type: "Military Transport",
    firstFlight: "2010",
    inService: "2016",
    role: "Strategic / Tactical Airlift",
    country: "Japan",
    specs: {
      wingspan: "144 ft 4 in (44.0 m)",
      length: "143 ft 8 in (43.9 m)",
      maxSpeed: "536 mph (862 km/h)",
      range: "5,405 mi (8,900 km) ferry range",
      ceiling: "43,000 ft (13,100 m)",
      engines: "2x General Electric CF6-80C2K1F turbofan",
      crew: "3",
      capacity: "36,000 kg payload",
    },
    description:
      "The Kawasaki C-2 is Japan's indigenously developed medium-heavy military transport aircraft, designed to replace the aging Kawasaki C-1. Powered by two turbofan engines, it is substantially larger and faster than its predecessor, with transoceanic range capability. The Japan Air Self-Defense Force operates the aircraft primarily for strategic airlift, disaster relief, and humanitarian operations. Its development reflects Japan's push for greater defense industry self-sufficiency.",
    funFact:
      "The Kawasaki C-2 is one of only a few military transports to use two large high-bypass turbofan engines rather than four turboprops or turbofans, giving it jet-airliner-like cruise performance while maintaining tactical transport capabilities.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Two turbofans in underwing pods on high-mounted wings",
      wingPosition: "high",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "Two large turbofan engines",
        "High-mounted swept wings",
        "Rear loading ramp",
        "Upswept rear fuselage",
      ],
    },
    aliases: ["C-2"],
  },
  {
    id: "embraer-c-390",
    name: "Embraer C-390 Millennium",
    manufacturer: "Embraer",
    type: "Military Transport",
    firstFlight: "2015",
    inService: "2019",
    role: "Tactical / Medium Airlift",
    country: "Brazil",
    specs: {
      wingspan: "111 ft 7 in (34.0 m)",
      length: "105 ft 8 in (32.2 m)",
      maxSpeed: "561 mph (903 km/h)",
      range: "3,417 mi (5,500 km) with 23,000 kg",
      ceiling: "36,000 ft (11,000 m)",
      engines: "2x CFM International CFM56-5C turbofan",
      crew: "2",
      capacity: "23,600 kg payload / 64 paratroopers",
    },
    description:
      "The Embraer C-390 Millennium is a modern jet-powered military transport designed as a C-130 replacement, offering superior speed and payload while retaining tactical short-field capability. Developed by Brazilian manufacturer Embraer with international partners, it is the largest aircraft ever designed and built in Latin America. The KC-390 tanker variant adds aerial refueling capability, extending its military utility significantly.",
    funFact:
      "The C-390 uses the same CFM56 engine family found on many commercial airliners like the Boeing 737 and Airbus A320, which simplifies maintenance and logistics for air forces that also operate commercial aircraft powered by the same engine.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Two turbofans under low-mounted swept wings",
      wingPosition: "high",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "Jet-powered tactical transport",
        "Two underwing turbofan engines",
        "Rear loading ramp",
        "High-mounted wings",
      ],
    },
    aliases: ["KC-390", "C-390"],
  },

  // ============================================================
  // TANKERS
  // ============================================================
  {
    id: "kc-135-stratotanker",
    name: "KC-135 Stratotanker",
    manufacturer: "Boeing",
    type: "Aerial Refueling Tanker",
    firstFlight: "1956",
    inService: "1957",
    role: "Aerial Refueling / Strategic Transport",
    country: "USA",
    specs: {
      wingspan: "130 ft 10 in (39.9 m)",
      length: "136 ft 3 in (41.5 m)",
      maxSpeed: "580 mph (933 km/h)",
      range: "11,015 mi (17,731 km) as transport",
      ceiling: "50,000 ft (15,240 m)",
      engines: "4x CFM International CFM56-2 turbofan (R model)",
      crew: "3–4",
      capacity: "90,719 kg fuel transfer",
    },
    description:
      "The KC-135 Stratotanker has served as the primary aerial refueling aircraft of the US Air Force since 1957, sharing its basic design with the Boeing 707. The aircraft uses the flying boom method of fuel transfer, with a boom operator lying prone in the rear of the aircraft to guide the boom into the receiver's receptacle. Re-engined KC-135R variants replaced early J57 turbojets with fuel-efficient CFM56 turbofans, dramatically reducing fuel burn.",
    funFact:
      "The KC-135 transfers fuel through a rigid flying boom at rates of up to 1,000 gallons per minute — that means it can offload the equivalent of a typical car's full fuel tank in about 0.9 seconds while both aircraft fly in close formation at 400 mph.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Four turbofans in underwing pods on swept wings",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "cold-war",
      distinguishingFeatures: [
        "Distinctive flying boom extending from the tail",
        "Four underwing engine pods",
        "Swept wings",
        "Narrow fuselage similar to 707",
      ],
    },
    aliases: ["Stratotanker", "KC-135R"],
  },
  {
    id: "kc-46-pegasus",
    name: "KC-46 Pegasus",
    manufacturer: "Boeing",
    type: "Aerial Refueling Tanker",
    firstFlight: "2015",
    inService: "2019",
    role: "Aerial Refueling / Strategic Transport",
    country: "USA",
    specs: {
      wingspan: "157 ft 8 in (48.1 m)",
      length: "165 ft 6 in (50.5 m)",
      maxSpeed: "Mach 0.86 (585 mph / 940 km/h)",
      range: "11,830 mi (19,000 km) ferry range",
      ceiling: "43,100 ft (13,100 m)",
      engines: "2x Pratt & Whitney PW4062 turbofan",
      crew: "3",
      capacity: "212,299 lb fuel offload",
    },
    description:
      "The KC-46 Pegasus is the US Air Force's newest aerial tanker, derived from the Boeing 767-200ER commercial airliner. It can refuel aircraft using either the flying boom or drogue-and-basket system, making it compatible with US Navy and allied aircraft that use the probe-and-drogue method. The KC-46 features a remote vision system that allows the boom operator to guide refueling via cameras rather than lying prone in the tail.",
    funFact:
      "The KC-46's Remote Vision System — cameras that display refueling on screens for the boom operator — was plagued by depth perception problems for years after introduction, causing numerous boom strikes. Boeing spent years fixing the camera and display system as part of an ongoing contract dispute with the Air Force.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Two large turbofans under swept wings",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "Flying boom and drogue refueling capability",
        "767 airliner-derived fuselage",
        "Two large underwing engines",
        "Refueling pod visible under wings",
      ],
    },
    aliases: ["Pegasus"],
  },
  {
    id: "kc-10-extender",
    name: "KC-10 Extender",
    manufacturer: "McDonnell Douglas",
    type: "Aerial Refueling Tanker / Transport",
    firstFlight: "1980",
    inService: "1981",
    role: "Aerial Refueling / Strategic Airlift",
    country: "USA",
    specs: {
      wingspan: "165 ft 4 in (50.4 m)",
      length: "181 ft 7 in (55.4 m)",
      maxSpeed: "Mach 0.82 (610 mph / 982 km/h)",
      range: "11,500 mi (18,500 km) unrefueled",
      ceiling: "42,000 ft (12,802 m)",
      engines: "3x General Electric CF6-50C2 turbofan",
      crew: "4",
      capacity: "161,480 kg fuel transfer",
    },
    description:
      "The KC-10 Extender is a large aerial refueling tanker and strategic transport derived from the DC-10 widebody airliner. It is capable of both boom and drogue-and-basket refueling, and can itself be refueled in flight, dramatically extending deployment range. The KC-10 can simultaneously carry cargo and passengers while performing the tanker mission. It was primarily used during Desert Storm and other major operations before being retired in 2024.",
    funFact:
      "The KC-10 can carry enough fuel to refuel a full squadron of F-15 fighters to ferry them across the Atlantic nonstop — and it can do this while also carrying 75 passengers and their baggage in cargo pallets, effectively acting as both a tanker and airliner simultaneously.",
    visual: {
      engineCount: 3,
      engineType: "turbofan",
      enginePlacement: "Two turbofans under wings, one in tail root",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "modern",
      distinguishingFeatures: [
        "Three engines (two underwing, one in tail)",
        "Wide DC-10 fuselage",
        "Flying boom under tail",
        "Hose-and-drogue pods under wings",
      ],
    },
    aliases: ["Extender"],
  },
  {
    id: "airbus-a330-mrtt",
    name: "Airbus A330 MRTT",
    manufacturer: "Airbus Defence and Space",
    type: "Aerial Refueling Tanker / Transport",
    firstFlight: "2007",
    inService: "2011",
    role: "Aerial Refueling / Strategic Airlift",
    country: "International (EU)",
    specs: {
      wingspan: "197 ft 10 in (60.3 m)",
      length: "193 ft 7 in (59.0 m)",
      maxSpeed: "Mach 0.86 (567 mph / 913 km/h)",
      range: "8,500 mi (13,678 km) ferry range",
      ceiling: "40,000 ft (12,191 m)",
      engines: "2x Rolls-Royce Trent 772 turbofan",
      crew: "3",
      capacity: "111,000 kg fuel transfer",
    },
    description:
      "The Airbus A330 Multi Role Tanker Transport (MRTT) is derived from the Airbus A330-200 widebody airliner. It features a fly-by-wire aerial refueling boom system called the Advanced Refueling Boom System (ARBS), controlled by an automated refueling operator station, and can also refuel probe-equipped aircraft via hose-and-drogue pods under each wing. It is operated by the air forces of Australia, France, Saudi Arabia, South Korea, Singapore, Spain, the UK (as the Voyager), and the UAE.",
    funFact:
      "The A330 MRTT's automated refueling boom can detect a receiver aircraft's receptacle and engage autonomously — a world first for a production tanker. The system reduces boom operator workload dramatically and enables refueling of stealthy aircraft with non-standard approaches.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Two large turbofans under swept wings",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "contemporary",
      distinguishingFeatures: [
        "Wide A330 airliner fuselage",
        "Refueling boom under tail",
        "Wing-mounted hose-and-drogue pods",
        "Two large turbofan engines",
      ],
    },
    aliases: ["Voyager (UK)", "MRTT", "A330 MRTT"],
  },

  // ============================================================
  // PATROL / SURVEILLANCE
  // ============================================================
  {
    id: "p-3-orion",
    name: "P-3 Orion",
    manufacturer: "Lockheed",
    type: "Maritime Patrol Aircraft",
    firstFlight: "1959",
    inService: "1962",
    role: "Maritime Patrol / Anti-Submarine Warfare",
    country: "USA",
    specs: {
      wingspan: "100 ft 6 in (30.6 m)",
      length: "116 ft 10 in (35.6 m)",
      maxSpeed: "473 mph (761 km/h)",
      range: "4,398 mi (7,079 km)",
      ceiling: "28,300 ft (8,626 m)",
      engines: "4x Allison T56-A-14 turboprop",
      crew: "11",
    },
    description:
      "The P-3 Orion is a land-based maritime patrol and anti-submarine aircraft derived from the Lockheed L-188 Electra commercial turboprop airliner. It has served as the primary American and allied maritime patrol platform since the 1960s, hunting submarines with sonobuoys, magnetic anomaly detectors, and torpedoes. While largely replaced by the P-8 Poseidon in US Navy service, P-3s continue in service with many allied nations.",
    funFact:
      "The P-3's distinctive 'stinger' tail extension houses a Magnetic Anomaly Detector (MAD) boom, which can sense the tiny distortion in Earth's magnetic field caused by a submarine's steel hull — even when the sub is hundreds of feet below the surface.",
    visual: {
      engineCount: 4,
      engineType: "turboprop",
      enginePlacement: "Four turboprops on low-mounted straight wings",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "cold-war",
      distinguishingFeatures: [
        "MAD boom extending from tail",
        "Weapons bay under fuselage",
        "Four turboprop engines",
        "Low straight wings with large engine nacelles",
      ],
    },
    aliases: ["Orion"],
  },
  {
    id: "p-8-poseidon",
    name: "P-8 Poseidon",
    manufacturer: "Boeing",
    type: "Maritime Patrol Aircraft",
    firstFlight: "2009",
    inService: "2013",
    role: "Maritime Patrol / Anti-Submarine Warfare",
    country: "USA",
    specs: {
      wingspan: "123 ft 6 in (37.6 m)",
      length: "129 ft 6 in (39.5 m)",
      maxSpeed: "Mach 0.82 (575 mph / 925 km/h)",
      range: "4,585 mi (7,378 km)",
      ceiling: "41,000 ft (12,496 m)",
      engines: "2x CFM International CFM56-7B turbofan",
      crew: "9",
    },
    description:
      "The P-8 Poseidon is the US Navy's replacement for the P-3 Orion, derived from the Boeing 737-800ERX commercial airliner. It offers higher speed, altitude, and range than the P-3, along with significantly improved sensor systems and a modern digital mission system. Armed with torpedoes, Harpoon missiles, and depth charges, it can hunt submarines across vast ocean areas. It has been exported widely to India, Australia, Norway, the UK, and others.",
    funFact:
      "Unlike the P-3, the P-8 does not have a Magnetic Anomaly Detector because it operates at higher altitudes where MAD is ineffective. Instead, it relies entirely on sonobuoys and other sensors, deploying them in large patterns to localize submarines over wide areas.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Two turbofans under swept wings",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "737-derived fuselage",
        "Distinctive weapons bay",
        "No MAD tail boom",
        "Winglets on swept wings",
        "Two underwing turbofans",
      ],
    },
    aliases: ["Poseidon"],
  },
  {
    id: "e-3-sentry",
    name: "E-3 Sentry AWACS",
    manufacturer: "Boeing",
    type: "Airborne Warning and Control System",
    firstFlight: "1972",
    inService: "1977",
    role: "Airborne Early Warning and Control",
    country: "USA",
    specs: {
      wingspan: "145 ft 9 in (44.4 m)",
      length: "152 ft 11 in (46.6 m)",
      maxSpeed: "530 mph (853 km/h)",
      range: "5,000 mi (8,046 km)",
      ceiling: "29,000 ft (8,839 m)",
      engines: "4x CFM International CFM56-2 turbofan",
      crew: "4 flight + 13–19 mission specialists",
    },
    description:
      "The E-3 Sentry is an airborne warning and control system (AWACS) aircraft built on the Boeing 707-320 airframe. Its most distinctive feature is the large rotating radar dome (rotodome) mounted above the fuselage, which houses an AN/APY-1 or APY-2 surveillance radar that can track airborne and surface targets at ranges exceeding 250 miles. The E-3 serves as an airborne command center, directing friendly fighter aircraft during combat operations.",
    funFact:
      "The E-3's rotodome rotates at 6 rpm during normal operations and at 0.25 rpm during standby to ensure the bearings do not develop flat spots. The dome is 30 feet in diameter but only 6 feet thick, shaped like a flying saucer.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Four turbofans in underwing pods on swept wings",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "modern",
      distinguishingFeatures: [
        "Large circular rotating radar rotodome above fuselage",
        "707-derived fuselage",
        "Four underwing engine pods",
        "Distinctive radar dome on twin struts",
      ],
    },
    aliases: ["AWACS", "Sentry"],
  },
  {
    id: "e-2-hawkeye",
    name: "E-2 Hawkeye",
    manufacturer: "Grumman (now Northrop Grumman)",
    type: "Carrier-Based Early Warning",
    variant: "E-2D Advanced Hawkeye",
    firstFlight: "1960",
    inService: "1964",
    role: "Airborne Early Warning / Battle Management",
    country: "USA",
    specs: {
      wingspan: "80 ft 7 in (24.6 m)",
      length: "57 ft 8 in (17.6 m)",
      maxSpeed: "374 mph (602 km/h)",
      range: "1,394 mi (2,246 km)",
      ceiling: "34,700 ft (10,576 m)",
      engines: "2x Rolls-Royce T56-A-427A turboprop",
      crew: "5",
    },
    description:
      "The E-2 Hawkeye is a carrier-based tactical airborne early warning aircraft operated by the US Navy and several allied navies. Its distinctive rotating disc-shaped rotodome contains a radar capable of tracking hundreds of targets simultaneously. The latest E-2D Advanced Hawkeye variant incorporates an entirely new radar with 360-degree simultaneous scanning, aerial refueling capability, and advanced data links. It is often called the 'eyes of the fleet.'",
    funFact:
      "The E-2 has four vertical tail fins instead of a single fin — this arrangement was chosen to reduce the aircraft's height so it can fit on aircraft carrier elevators and in below-deck hangar bays while still providing adequate directional control.",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "Two turboprops on high-mounted wings",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "h-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "Large rotating circular rotodome above fuselage",
        "Four vertical tail fins",
        "Carrier-capable with tailhook",
        "High-mounted folding wings",
      ],
    },
    aliases: ["Hawkeye", "Eyes of the Fleet"],
  },
  {
    id: "e-7-wedgetail",
    name: "E-7A Wedgetail",
    manufacturer: "Boeing / Northrop Grumman",
    type: "Airborne Early Warning and Control",
    firstFlight: "2004",
    inService: "2009",
    role: "Airborne Early Warning / Battle Management",
    country: "Australia",
    specs: {
      wingspan: "124 ft (37.8 m)",
      length: "159 ft 2 in (48.5 m)",
      maxSpeed: "Mach 0.86 (583 mph / 938 km/h)",
      range: "6,200 mi (10,000 km)",
      ceiling: "41,000 ft (12,500 m)",
      engines: "2x CFM International CFM56-7B turbofan",
      crew: "6 flight + mission crew",
    },
    description:
      "The E-7A Wedgetail is an airborne early warning and control aircraft operated by the Royal Australian Air Force, based on the Boeing 737-700 airframe. Rather than a rotating rotodome, the Wedgetail uses a fixed Multi-Role Electronically Scanned Array (MESA) radar mounted on a dorsal spine, providing simultaneous 360-degree surveillance coverage without mechanical rotation. The UK selected the E-7 to replace its E-3 Sentry fleet.",
    funFact:
      "Unlike the E-3 Sentry whose radar dome must physically rotate to scan, the Wedgetail's MESA radar has no moving parts — its active electronically scanned array can switch beam direction electronically in microseconds, scanning the entire sky hundreds of times per second.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Two turbofans under swept wings",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "Fixed dorsal MESA radar spine (not rotating)",
        "737-derived fuselage",
        "Two CFM56 turbofan engines",
        "Distinctive elongated top spine",
      ],
    },
    aliases: ["Wedgetail", "E-7"],
  },
  {
    id: "rc-135-rivet-joint",
    name: "RC-135 Rivet Joint",
    manufacturer: "Boeing / L3Harris",
    type: "Reconnaissance / SIGINT",
    firstFlight: "1964",
    inService: "1964",
    role: "Signals Intelligence / Reconnaissance",
    country: "USA",
    specs: {
      wingspan: "130 ft 10 in (39.9 m)",
      length: "136 ft 3 in (41.5 m)",
      maxSpeed: "580 mph (930 km/h)",
      range: "6,350 mi (10,220 km)",
      ceiling: "50,000 ft (15,240 m)",
      engines: "4x CFM International CFM56-2 turbofan",
      crew: "3 flight + 27 mission specialists",
    },
    description:
      "The RC-135V/W Rivet Joint is a strategic signals intelligence (SIGINT) collection aircraft based on the KC-135 Stratotanker airframe. Operated by the 55th Wing at Offutt Air Force Base, it is crammed with electronic intelligence gathering equipment that can intercept, identify, and geolocate radio frequency emissions across a broad spectrum. It has been continuously upgraded since the 1960s and is operated by the US Air Force, RAF, and Australian Air Force.",
    funFact:
      "The RC-135 Rivet Joint's fuselage is so densely packed with electronic equipment that the mission specialists sit in what is basically an electronic cave with no windows — and the sheer heat generated by all the electronics requires a dedicated cooling system as powerful as that of a small building.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Four turbofans in underwing pods on swept wings",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "modern",
      distinguishingFeatures: [
        "Multiple antenna fairings covering fuselage",
        "Distinctive cheek fairings on nose",
        "KC-135 derived airframe",
        "Various blade antennas along fuselage",
      ],
    },
    aliases: ["Rivet Joint", "RC-135"],
  },
  {
    id: "ep-3-aries",
    name: "EP-3 Aries II",
    manufacturer: "Lockheed / Boeing",
    type: "Reconnaissance / SIGINT",
    firstFlight: "1969",
    inService: "1969",
    role: "Signals Intelligence / Reconnaissance",
    country: "USA",
    specs: {
      wingspan: "100 ft 6 in (30.6 m)",
      length: "116 ft 10 in (35.6 m)",
      maxSpeed: "411 mph (661 km/h)",
      range: "3,000 mi (4,800 km)",
      ceiling: "28,300 ft (8,626 m)",
      engines: "4x Allison T56-A-14 turboprop",
      crew: "24",
    },
    description:
      "The EP-3E Aries II is a signals intelligence (SIGINT) reconnaissance variant of the P-3 Orion maritime patrol aircraft, operated by the US Navy's Fleet Air Reconnaissance Squadrons. Stuffed with electronic intelligence collection equipment, it monitors electronic emissions including radar, communications, and telemetry signals. The aircraft gained international attention in 2001 when an EP-3E was forced to land at a Chinese military base on Hainan Island after a midair collision with a Chinese fighter jet.",
    funFact:
      "When the Hainan Island EP-3 was forced to land in China in 2001, the 24-member crew spent 11 days destroying sensitive equipment and code material aboard the aircraft before the Chinese gained access. The aircraft was eventually returned disassembled — in crates.",
    visual: {
      engineCount: 4,
      engineType: "turboprop",
      enginePlacement: "Four turboprops on low straight wings",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "cold-war",
      distinguishingFeatures: [
        "P-3 airframe with numerous antenna fairings",
        "Canoe-shaped radome under fuselage",
        "Multiple blade antennas",
        "No MAD boom (unlike P-3)",
      ],
    },
    aliases: ["Aries II", "EP-3"],
  },

  // ============================================================
  // TRAINERS
  // ============================================================
  {
    id: "t-6-texan-ii",
    name: "T-6 Texan II",
    manufacturer: "Beechcraft (Textron Aviation)",
    type: "Military Trainer",
    firstFlight: "1992",
    inService: "2001",
    role: "Primary Flight Trainer",
    country: "USA",
    specs: {
      wingspan: "33 ft 5 in (10.2 m)",
      length: "33 ft 4 in (10.2 m)",
      maxSpeed: "316 mph (509 km/h)",
      range: "900 mi (1,448 km)",
      ceiling: "31,000 ft (9,449 m)",
      engines: "1x Pratt & Whitney Canada PT6A-68 turboprop",
      crew: "2",
    },
    description:
      "The T-6 Texan II is the primary trainer for US Air Force and Navy student pilots, as well as many allied air forces. Derived from the Pilatus PC-9, it replaced the T-37 Tweet in US service. The tandem-seat turboprop provides new pilots with an introduction to high-performance aircraft systems and instrument flying before they progress to jet trainers. Over 1,000 have been built and it serves in more than 20 countries.",
    funFact:
      "Despite its name honoring the famous WWII-era T-6 Texan trainer, the T-6 Texan II is descended from a Swiss design (Pilatus PC-9) rather than the original Texan. Beechcraft won the US Joint Primary Aircraft Training System competition by adapting the PC-9 design to American requirements.",
    visual: {
      engineCount: 1,
      engineType: "turboprop",
      enginePlacement: "Single turboprop in nose",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "Single turboprop nose engine",
        "Tandem cockpit with bubble canopy",
        "Low straight wings",
        "Retractable tricycle gear",
      ],
    },
    aliases: ["Texan II", "T-6A"],
  },
  {
    id: "t-38-talon",
    name: "T-38 Talon",
    manufacturer: "Northrop",
    type: "Jet Trainer",
    firstFlight: "1959",
    inService: "1961",
    role: "Advanced Jet Trainer / Companion Trainer",
    country: "USA",
    specs: {
      wingspan: "25 ft 3 in (7.7 m)",
      length: "46 ft 4 in (14.1 m)",
      maxSpeed: "Mach 1.08 (820 mph / 1,320 km/h)",
      range: "1,093 mi (1,759 km)",
      ceiling: "55,000 ft (16,764 m)",
      engines: "2x General Electric J85-GE-5 turbojet",
      crew: "2",
    },
    description:
      "The T-38 Talon is a supersonic twin-engine jet trainer that has been the standard advanced trainer for US Air Force pilots since 1961, making it the world's first supersonic trainer. It shares its basic design with the F-5 Freedom Fighter family. The slender, lightweight design gives it excellent performance with modest engine power. NASA uses T-38s extensively as companion trainers and proficiency aircraft for astronauts. Despite its age, it remains in service pending T-7A Red Hawk introduction.",
    funFact:
      "The T-38 has trained virtually every active duty US Air Force pilot since the 1960s and continues in service despite being designed over 65 years ago. NASA astronauts fly T-38s to maintain proficiency and use them for formation flying practice during space shuttle approach simulations.",
    visual: {
      engineCount: 2,
      engineType: "turbojet",
      enginePlacement: "Two turbojets side-by-side in the fuselage",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "Very slender fuselage",
        "Two engines side-by-side in the rear fuselage",
        "Tandem cockpit",
        "Small swept wings",
        "Supersonic capable",
      ],
    },
    aliases: ["Talon"],
  },
  {
    id: "t-45-goshawk",
    name: "T-45 Goshawk",
    manufacturer: "McDonnell Douglas / Boeing",
    type: "Carrier-Capable Jet Trainer",
    firstFlight: "1988",
    inService: "1991",
    role: "Advanced Jet Trainer / Carrier Landing Trainer",
    country: "USA",
    specs: {
      wingspan: "30 ft 9 in (9.4 m)",
      length: "39 ft 4 in (11.9 m)",
      maxSpeed: "625 mph (1,006 km/h)",
      range: "1,150 mi (1,850 km)",
      ceiling: "42,500 ft (12,954 m)",
      engines: "1x Rolls-Royce F405-RR-401 turbofan",
      crew: "2",
    },
    description:
      "The T-45 Goshawk is a carrier-capable advanced jet trainer derived from the BAE Systems Hawk, modified significantly for US Navy carrier operations including a strengthened airframe, arresting hook, carrier-compatible landing gear, and single-engine operation. It trains US Navy and Marine Corps pilots for carrier operations, taking them from initial jet training through carrier qualification. The aircraft is headquartered at Kingsville, Texas and Meridian, Mississippi.",
    funFact:
      "The T-45 was so extensively modified from the BAE Hawk that it shares fewer than 20% of its parts with the original aircraft. The carrier-capable landing gear alone required a complete redesign of the wing root and forward fuselage structure.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "Single turbofan in the rear fuselage",
      wingPosition: "mid",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "Single-engine swept wing trainer",
        "Tandem cockpit",
        "Carrier-capable with arresting hook",
        "Air intake on top of fuselage behind cockpit",
      ],
    },
    aliases: ["Goshawk"],
  },
  {
    id: "t-7a-red-hawk",
    name: "T-7A Red Hawk",
    manufacturer: "Boeing / Saab",
    type: "Advanced Jet Trainer",
    firstFlight: "2016",
    inService: "2024 (projected IOC)",
    role: "Advanced Jet Trainer",
    country: "USA",
    specs: {
      wingspan: "30 ft 9 in (9.4 m)",
      length: "46 ft (14.0 m)",
      maxSpeed: "Mach 1.3 (1,000 mph / 1,609 km/h) (estimated)",
      range: "1,050 mi (1,690 km) estimated",
      ceiling: "50,000+ ft estimated",
      engines: "1x General Electric F404-GE-103 turbofan",
      crew: "2",
    },
    description:
      "The T-7A Red Hawk is the US Air Force's next-generation advanced jet trainer, designed to replace the aging T-38 Talon. Developed jointly by Boeing and Saab, it was designed entirely in 3D using digital engineering tools, reducing design and manufacturing time dramatically. The name honors the Tuskegee Airmen, whose P-40s and P-51 Mustangs bore distinctive red tail markings. The digital-native design allows reconfigurable cockpits to simulate various aircraft.",
    funFact:
      "The T-7A Red Hawk was designed using entirely digital tools — no physical mockups were built during development. Boeing used advanced 3D design and simulation software to go from concept to first flight in just three years, a compressed schedule enabled by eliminating traditional physical prototyping steps.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "Single turbofan in the rear fuselage",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "Advanced tandem-seat design",
        "Single engine supersonic trainer",
        "Low swept wings",
        "Modern glass cockpit",
        "Distinctive twin ventral fins",
      ],
    },
    aliases: ["Red Hawk"],
  },
  {
    id: "bae-hawk",
    name: "BAE Systems Hawk",
    manufacturer: "BAE Systems (originally Hawker Siddeley)",
    type: "Jet Trainer / Light Combat",
    variant: "Hawk T.1 / Hawk 200",
    firstFlight: "1974",
    inService: "1976",
    role: "Advanced Jet Trainer / Light Attack",
    country: "UK",
    specs: {
      wingspan: "30 ft 10 in (9.4 m)",
      length: "39 ft 4 in (12.0 m)",
      maxSpeed: "622 mph (1,000 km/h)",
      range: "1,400 mi (2,253 km)",
      ceiling: "44,500 ft (13,565 m)",
      engines: "1x Rolls-Royce Turbomeca Adour Mk.151 turbofan",
      crew: "2",
    },
    description:
      "The BAE Hawk is a highly successful British jet trainer that has served as the basis for the Red Arrows aerobatic display team's aircraft and inspired numerous export variants. Used by over 20 air forces worldwide, it serves in the advanced training and light combat roles. The Hawk's combination of performance, economy, and reliability has made it a benchmark in trainer design. The single-seat Hawk 200 combat variant adds weapons capability for export customers.",
    funFact:
      "The Red Arrows — the RAF aerobatic display team — have flown the Hawk since 1979, performing incredibly close formation maneuvers in their red-painted Hawks at airshows worldwide. The team practices formations within 6 feet of each other while flying at 400 mph.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "Single turbofan in the rear fuselage with dorsal intake",
      wingPosition: "mid",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "Single engine with dorsal intake behind cockpit",
        "Tandem cockpit",
        "Elegant swept wing design",
        "Clean aerodynamic lines",
      ],
    },
    aliases: ["Hawk"],
  },
  {
    id: "alpha-jet",
    name: "Alpha Jet",
    manufacturer: "Dassault-Breguet / Dornier",
    type: "Jet Trainer / Light Attack",
    firstFlight: "1973",
    inService: "1978",
    role: "Advanced Jet Trainer / Light Attack",
    country: "France/Germany",
    specs: {
      wingspan: "29 ft 11 in (9.1 m)",
      length: "40 ft 3 in (12.3 m)",
      maxSpeed: "621 mph (1,000 km/h)",
      range: "1,528 mi (2,459 km)",
      ceiling: "48,000 ft (14,629 m)",
      engines: "2x SNECMA/Turbomeca Larzac 04-C6 turbofan",
      crew: "2",
    },
    description:
      "The Alpha Jet is a Franco-German twin-engine jet trainer and light attack aircraft developed jointly by Dassault-Breguet and Dornier to meet requirements of both the French Air Force (trainer role) and the German Luftwaffe (light attack role). Despite serving in different primary roles for its two home nations, the same basic airframe satisfied both requirements. It has been exported widely in Africa, the Middle East, and Asia.",
    funFact:
      "The Alpha Jet serves as the mount for the French Patrouille de France aerobatic display team, which has flown the aircraft since 1981. The team is one of the oldest military aerobatic teams in the world, tracing its history to 1931.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Two turbofans in underwing pods close to the fuselage",
      wingPosition: "high",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "High-mounted swept wings",
        "Two engines in fuselage-side nacelles",
        "Tandem cockpit",
        "Shoulder wing configuration",
      ],
    },
    aliases: ["Alpha Jet E", "Alpha Jet A"],
  },
  {
    id: "aero-l-39-albatros",
    name: "Aero L-39 Albatros",
    manufacturer: "Aero Vodochody",
    type: "Jet Trainer",
    firstFlight: "1968",
    inService: "1971",
    role: "Advanced Jet Trainer / Light Attack",
    country: "Czechoslovakia (now Czech Republic)",
    specs: {
      wingspan: "31 ft (9.5 m)",
      length: "39 ft 9 in (12.1 m)",
      maxSpeed: "444 mph (715 km/h)",
      range: "695 mi (1,119 km)",
      ceiling: "37,729 ft (11,500 m)",
      engines: "1x Progress AI-25TL turbofan",
      crew: "2",
    },
    description:
      "The Aero L-39 Albatros was the standard jet trainer of Warsaw Pact air forces during the Cold War, replacing the L-29 Delfin. Developed in Czechoslovakia and widely exported to Soviet-aligned nations, over 2,900 were built, making it one of the most-produced jet trainers in history. After the Cold War, surplus L-39s flooded the civilian warbird market, and they are now popular with private owners and aerobatic teams worldwide including the Breitling Jet Team.",
    funFact:
      "The L-39 is so inexpensive to purchase and operate that civilian buyers have snapped up hundreds of ex-military airframes. Today more L-39s are flown privately than by military operators, and they are popular attractions at airshows, often performing precision aerobatics at a fraction of the cost of Western jet aircraft.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "Single turbofan in the fuselage with two lateral air intakes",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "Single engine with twin side air intakes",
        "Tandem cockpit with bubble canopy",
        "Low swept wings",
        "Clean Soviet-era design lines",
      ],
    },
    aliases: ["Albatros", "L-39"],
  },
  {
    id: "pilatus-pc-21",
    name: "Pilatus PC-21",
    manufacturer: "Pilatus Aircraft",
    type: "Military Trainer",
    firstFlight: "2002",
    inService: "2008",
    role: "Advanced Turboprop Trainer",
    country: "Switzerland",
    specs: {
      wingspan: "29 ft 2 in (8.9 m)",
      length: "36 ft 8 in (11.2 m)",
      maxSpeed: "370 mph (593 km/h)",
      range: "1,333 mi (2,146 km)",
      ceiling: "38,000 ft (11,582 m)",
      engines: "1x Pratt & Whitney Canada PT6A-68B turboprop",
      crew: "2",
    },
    description:
      "The Pilatus PC-21 is a high-performance turboprop trainer designed to bridge the gap between primary trainers and advanced jet trainers, providing a more cost-effective training solution. Its advanced avionics — including a glass cockpit, head-up display, and mission computers — simulate the environment of modern combat aircraft, allowing pilot training for jet operations without the fuel costs of actual jets. It serves the air forces of Switzerland, Australia, Singapore, Saudi Arabia, and others.",
    funFact:
      "The PC-21 is powered by a turboprop but its cockpit is designed to mimic a jet fighter's environment so closely that several air forces have eliminated their dedicated jet trainers entirely, saving significant operating costs while still producing jet-qualified pilots.",
    visual: {
      engineCount: 1,
      engineType: "turboprop",
      enginePlacement: "Single turboprop in nose",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "Sleek low-wing design",
        "Single nose turboprop",
        "Tandem bubble canopy",
        "Aggressive aerodynamic styling for a turboprop",
      ],
    },
    aliases: ["PC-21"],
  },
  {
    id: "pilatus-pc-7",
    name: "Pilatus PC-7 Turbo Trainer",
    manufacturer: "Pilatus Aircraft",
    type: "Military Trainer",
    firstFlight: "1978",
    inService: "1978",
    role: "Basic / Primary Trainer",
    country: "Switzerland",
    specs: {
      wingspan: "33 ft 5 in (10.2 m)",
      length: "31 ft 11 in (9.7 m)",
      maxSpeed: "269 mph (432 km/h)",
      range: "884 mi (1,422 km)",
      ceiling: "33,000 ft (10,058 m)",
      engines: "1x Pratt & Whitney Canada PT6A-25C turboprop",
      crew: "2",
    },
    description:
      "The Pilatus PC-7 Turbo Trainer is a basic military turboprop trainer that has become one of the most popular trainer aircraft in the world, serving over 20 air forces across all continents. It offers a step up from piston trainers while being less complex and costly than the PC-9 and PC-21. The PC-7 provides an excellent introduction to turboprop handling and high-performance flight characteristics, suitable for screening and primary military flight training.",
    funFact:
      "The PC-7 has been in continuous production since 1978 with relatively minor changes — a testament to the soundness of its original design. The Swiss Patrouille Suisse aerobatic team used PC-7s until switching to F-5 Tigers, and several other national aerobatic teams have flown the aircraft.",
    visual: {
      engineCount: 1,
      engineType: "turboprop",
      enginePlacement: "Single turboprop in nose",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "Single nose turboprop",
        "Low straight wings",
        "Tandem cockpit",
        "Clean, simple lines",
      ],
    },
    aliases: ["PC-7", "Turbo Trainer"],
  },
  {
    id: "embraer-super-tucano",
    name: "Embraer EMB 314 Super Tucano",
    manufacturer: "Embraer",
    type: "Turboprop Trainer / Light Attack",
    firstFlight: "1999",
    inService: "2003",
    role: "Light Attack / COIN / Trainer",
    country: "Brazil",
    specs: {
      wingspan: "36 ft 6 in (11.1 m)",
      length: "37 ft (11.3 m)",
      maxSpeed: "367 mph (590 km/h)",
      range: "1,636 mi (2,634 km)",
      ceiling: "35,000 ft (10,668 m)",
      engines: "1x Pratt & Whitney Canada PT6A-68C turboprop",
      crew: "2",
    },
    description:
      "The Embraer EMB 314 Super Tucano is a turboprop light attack, counterinsurgency, and trainer aircraft widely used for jungle warfare and close air support. Its pressurized cockpit, advanced avionics, and rugged design allow operations from short unpaved strips in demanding environments. The USAF selected a version of the Super Tucano (as the A-29) for the Afghan Air Force. It is in service with over 15 air forces, particularly in Latin America and Africa.",
    funFact:
      "The Super Tucano was specifically designed to operate in the Amazon rainforest environment, where it has been used extensively by the Brazilian Air Force in narcotrafficking interdiction. It has intercepted and forced down suspected drug-running aircraft over the jungle — a mission that requires low-speed loitering ability that jet aircraft cannot provide.",
    visual: {
      engineCount: 1,
      engineType: "turboprop",
      enginePlacement: "Single turboprop in nose",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "Single nose turboprop",
        "Tandem cockpit",
        "Low straight wings with hardpoints",
        "Armored cockpit for combat operations",
      ],
    },
    aliases: ["Super Tucano", "A-29 Super Tucano"],
  },
  {
    id: "beechcraft-t-34-mentor",
    name: "Beechcraft T-34 Mentor",
    manufacturer: "Beechcraft",
    type: "Military Trainer",
    variant: "T-34C Turbo Mentor",
    firstFlight: "1948",
    inService: "1953",
    role: "Primary / Basic Flight Trainer",
    country: "USA",
    specs: {
      wingspan: "33 ft 4 in (10.2 m)",
      length: "28 ft 8 in (8.7 m)",
      maxSpeed: "246 mph (396 km/h)",
      range: "748 mi (1,204 km)",
      ceiling: "30,000 ft (9,144 m)",
      engines: "1x Pratt & Whitney Canada PT6A-25 turboprop (T-34C)",
      crew: "2",
    },
    description:
      "The Beechcraft T-34 Mentor was derived from the Bonanza civilian aircraft and served as the primary trainer for US Air Force and Navy pilots from the 1950s through the 1990s. The T-34C Turbo Mentor variant replaced the original piston engine with a turboprop, significantly improving performance and reliability. The aircraft was retired from US Navy service in 1993 but continues to serve with many foreign air forces.",
    funFact:
      "The T-34 was designed by Walter Beech in just 90 days after the military issued its trainer requirement, and the prototype was built in approximately 100 days — an extraordinarily fast development timeline for any aircraft.",
    visual: {
      engineCount: 1,
      engineType: "turboprop",
      enginePlacement: "Single turboprop in nose",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "Single engine low-wing monoplane",
        "Tandem cockpit",
        "Bonanza-derived design",
        "Clean trainer silhouette",
      ],
    },
    aliases: ["Mentor", "Turbo Mentor"],
  },

  // ============================================================
  // RUSSIAN / HEAVY TRANSPORTS
  // ============================================================
  {
    id: "an-124-ruslan",
    name: "Antonov An-124 Ruslan",
    manufacturer: "Antonov",
    type: "Strategic Heavy Transport",
    natoReportingName: "Condor",
    firstFlight: "1982",
    inService: "1986",
    role: "Strategic Heavy Airlift",
    country: "Ukraine/Russia",
    specs: {
      wingspan: "240 ft 5 in (73.3 m)",
      length: "226 ft 8 in (69.1 m)",
      maxSpeed: "537 mph (865 km/h)",
      range: "3,200 mi (5,150 km) with max payload",
      ceiling: "39,400 ft (12,010 m)",
      engines: "4x ZMKB Progress D-18T turbofan",
      crew: "6",
      capacity: "150,000 kg payload",
    },
    description:
      "The Antonov An-124 Ruslan is one of the world's largest military transport aircraft and the second-largest cargo aircraft ever produced (after the An-225). Capable of carrying 150 metric tons, it can transport oversized military hardware including tanks, helicopters, and self-propelled artillery. Both military and commercial variants are operated, and the An-124 became a vital commercial heavy-lift aircraft for oversized cargo worldwide.",
    funFact:
      "The An-124 has a unique double-bubble cross-section fuselage — the upper deck houses the crew and passenger compartment while the massive lower deck is the cargo hold. The floor can be lowered hydraulically to allow direct loading from the ground without ramps.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Four turbofans in underwing pods on swept high-mounted wings",
      wingPosition: "high",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "super-heavy",
      era: "modern",
      distinguishingFeatures: [
        "Enormous fuselage with drooped nose for front loading",
        "Four large turbofan engines",
        "High-mounted swept wings",
        "Rear loading ramp",
        "Complex 24-wheel landing gear bogies",
      ],
    },
    aliases: ["Ruslan", "Condor"],
  },
  {
    id: "an-225-mriya",
    name: "Antonov An-225 Mriya",
    manufacturer: "Antonov",
    type: "Strategic Super-Heavy Transport",
    natoReportingName: "Cossack",
    firstFlight: "1988",
    inService: "1989",
    role: "Strategic Super-Heavy Airlift",
    country: "Ukraine",
    specs: {
      wingspan: "290 ft (88.4 m)",
      length: "275 ft 7 in (84.0 m)",
      maxSpeed: "528 mph (850 km/h)",
      range: "2,796 mi (4,500 km) with max payload",
      ceiling: "40,026 ft (12,200 m)",
      engines: "6x ZMKB Progress D-18T turbofan",
      crew: "6",
      capacity: "250,000 kg payload",
    },
    description:
      "The Antonov An-225 Mriya (meaning 'Dream' in Ukrainian) was the world's largest and heaviest aircraft ever built, with a maximum takeoff weight of 640 metric tons. Originally designed to carry the Soviet Buran space shuttle on its back, it was the only aircraft of its type ever built. After the Soviet collapse, it operated commercially hauling outsized cargo worldwide. The sole completed An-225 was destroyed at Hostomel Airport near Kyiv during the Russian invasion of Ukraine in February 2022.",
    funFact:
      "The An-225 holds 240 world records for cargo aircraft performance, including carrying the world's heaviest single cargo item (a 190-metric-ton generator) and the world's longest aircraft payload (a 42-meter wind turbine blade). Its destruction in 2022 marked the end of the largest aircraft ever to fly.",
    visual: {
      engineCount: 6,
      engineType: "turbofan",
      enginePlacement: "Six turbofans in underwing pods on swept high-mounted wings",
      wingPosition: "high",
      wingShape: "swept",
      tailType: "twin",
      landingGear: "retractable",
      sizeClass: "super-heavy",
      era: "modern",
      distinguishingFeatures: [
        "Six engines (largest number of any airlift aircraft)",
        "Twin vertical tail fins",
        "Enormous fuselage",
        "High-mounted swept wings",
        "32-wheel main landing gear",
      ],
    },
    aliases: ["Mriya", "Dream", "Cossack"],
  },
  {
    id: "il-76",
    name: "Ilyushin Il-76",
    manufacturer: "Ilyushin",
    type: "Military / Commercial Transport",
    natoReportingName: "Candid",
    firstFlight: "1971",
    inService: "1974",
    role: "Strategic Airlift / Multi-role Transport",
    country: "Russia",
    specs: {
      wingspan: "165 ft 8 in (50.5 m)",
      length: "152 ft 10 in (46.6 m)",
      maxSpeed: "528 mph (850 km/h)",
      range: "3,107 mi (5,000 km) with max payload",
      ceiling: "39,370 ft (12,000 m)",
      engines: "4x Aviadvigatel PS-90A-76 turbofan (Il-76MD-90A)",
      crew: "5",
      capacity: "50,000 kg payload",
    },
    description:
      "The Ilyushin Il-76 is the Soviet Union's answer to the C-141 Starlifter and has served as Russia's primary military jet transport since the 1970s. Designed for rough-field operations in Siberia and Central Asia, it features high-mounted wings, large turbofans, and a distinctive tail gunner position. The Il-76 has been exported widely and operates in both military and commercial roles across the former Soviet sphere and beyond. The modernized Il-76MD-90A features new PS-90 engines and glass cockpit.",
    funFact:
      "The Il-76 was one of the few jet transports designed from the outset to operate from unpaved strips — its landing gear is designed to spread the aircraft's weight across 20 wheels on a four-bogie main gear arrangement, allowing it to land on frozen tundra, gravel, and grass strips.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Four turbofans in underwing pods on swept high-mounted wings",
      wingPosition: "high",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "cold-war",
      distinguishingFeatures: [
        "High-mounted swept wings with four engines",
        "Distinctive glazed navigator nose",
        "Rear tail gunner turret",
        "Upswept rear fuselage with ramp",
      ],
    },
    aliases: ["Candid", "Il-76MD"],
  },

  // ============================================================
  // UAVs
  // ============================================================
  {
    id: "mq-9-reaper",
    name: "MQ-9 Reaper",
    manufacturer: "General Atomics Aeronautical Systems",
    type: "Unmanned Combat Aerial Vehicle",
    firstFlight: "2001",
    inService: "2007",
    role: "UCAV / ISR",
    country: "USA",
    specs: {
      wingspan: "66 ft (20.1 m)",
      length: "36 ft (11 m)",
      maxSpeed: "300 mph (482 km/h)",
      range: "1,150 mi (1,850 km)",
      ceiling: "50,000 ft (15,240 m)",
      engines: "1x Honeywell TPE331-10GD turboprop",
      crew: "0 (remote crew of 2)",
    },
    description:
      "The MQ-9 Reaper is a remotely piloted UCAV developed for long-endurance surveillance and strike missions. An evolution of the MQ-1 Predator with greatly increased payload and speed, the Reaper can carry Hellfire missiles, GBU-12 Paveway II laser-guided bombs, and JDAM precision munitions. It has been the primary armed drone in US service since 2007 and has been used extensively in Afghanistan, Iraq, Syria, and counterterrorism operations worldwide.",
    funFact:
      "The MQ-9 Reaper can stay airborne for over 14 hours with a full weapons load, and its crew — sitting in a ground control station sometimes thousands of miles away — can hand off 'control' of the aircraft between shifts, allowing the Reaper to effectively fly indefinitely through crew rotation.",
    visual: {
      engineCount: 1,
      engineType: "turboprop",
      enginePlacement: "Single pusher turboprop at the tail",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "v-tail",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Pusher propeller at the rear",
        "Inverted V-tail",
        "Long straight wings",
        "Sensor turret under nose",
        "Weapons pylons under wings",
      ],
    },
    aliases: ["Reaper", "Predator B"],
  },
  {
    id: "mq-1-predator",
    name: "MQ-1 Predator",
    manufacturer: "General Atomics Aeronautical Systems",
    type: "Unmanned Aerial Vehicle",
    firstFlight: "1994",
    inService: "1995–2018 (USAF)",
    role: "ISR / Light Strike",
    country: "USA",
    specs: {
      wingspan: "55 ft (16.8 m)",
      length: "27 ft (8.2 m)",
      maxSpeed: "135 mph (217 km/h)",
      range: "675 mi (1,086 km)",
      ceiling: "25,000 ft (7,620 m)",
      engines: "1x Rotax 914F piston engine",
      crew: "0 (remote crew)",
    },
    description:
      "The MQ-1 Predator was the US Air Force's first widely deployed UCAV, transitioning from a pure ISR platform to an armed system when modified to carry AGM-114 Hellfire missiles. It pioneered the concept of persistent strike — loitering over a target for hours before engaging with precision weapons. The Predator fundamentally changed modern warfare and counterterrorism operations, demonstrating that unmanned aircraft could conduct lethal strikes with minimal risk to US personnel.",
    funFact:
      "The MQ-1 Predator was originally designed only for reconnaissance — no one planned to arm it. The decision to add Hellfire missiles came after 9/11 when the military realized the Predator had been watching Osama bin Laden but had no weapon to engage him. The armed conversion was completed in months.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single pusher piston engine at the tail",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "v-tail",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "Pusher propeller at the rear",
        "Inverted V-tail",
        "Long narrow straight wings",
        "Sensor ball under nose",
        "Slender fuselage",
      ],
    },
    aliases: ["Predator"],
  },
  {
    id: "rq-4-global-hawk",
    name: "RQ-4 Global Hawk",
    manufacturer: "Northrop Grumman",
    type: "High-Altitude Long-Endurance UAV",
    firstFlight: "1998",
    inService: "2001",
    role: "Strategic Reconnaissance / ISR",
    country: "USA",
    specs: {
      wingspan: "130 ft 9 in (39.9 m)",
      length: "47 ft 6 in (14.5 m)",
      maxSpeed: "391 mph (629 km/h)",
      range: "14,154 mi (22,780 km)",
      ceiling: "60,000 ft (18,288 m)",
      engines: "1x Rolls-Royce AE 3007H turbofan",
      crew: "0 (remote crew)",
    },
    description:
      "The RQ-4 Global Hawk is a high-altitude long-endurance unmanned aerial vehicle designed to provide persistent wide-area surveillance. With a wingspan larger than a Boeing 737, it can survey an area the size of Illinois in a single 24-hour sortie using its integrated sensor suite of electro-optical, infrared, and synthetic aperture radar sensors. The Global Hawk effectively performs the strategic reconnaissance mission previously flown by the U-2, though both continue to serve.",
    funFact:
      "The RQ-4 Global Hawk can fly for more than 32 hours continuously, covering 40,000 nautical miles of territory in a single sortie while returning imagery and intelligence data in real time via satellite link. Its wingspan of 130 feet is wider than a Boeing 737.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "Single turbofan mounted on top of the fuselage behind the payload bay",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "Extremely long straight wings",
        "Bulbous nose housing sensor payload",
        "Single engine mounted atop rear fuselage",
        "No weapons pylons",
      ],
    },
    aliases: ["Global Hawk"],
  },
  {
    id: "rq-170-sentinel",
    name: "RQ-170 Sentinel",
    manufacturer: "Lockheed Martin Skunk Works",
    type: "Stealth Reconnaissance UAV",
    firstFlight: "2007 (estimated)",
    inService: "2009 (estimated)",
    role: "Stealth Reconnaissance / ISR",
    country: "USA",
    specs: {
      wingspan: "~65 ft (estimated)",
      length: "~14 ft (estimated)",
      maxSpeed: "Classified",
      range: "Classified",
      ceiling: "50,000 ft (estimated)",
      engines: "1x turbofan (type classified)",
      crew: "0 (remote crew)",
    },
    description:
      "The RQ-170 Sentinel is a stealthy flying wing UAV developed by Lockheed Martin Skunk Works for CIA and US Air Force operations. Its existence was confirmed only after an example crashed and was recovered largely intact by Iran in 2011. The Sentinel is believed to have performed surveillance over Pakistan before and during the Operation Neptune Spear raid that killed Osama bin Laden, providing real-time video to the White House.",
    funFact:
      "The RQ-170 that crashed in Iran in 2011 was apparently spoofed — Iran claims it used GPS jamming and spoofing to convince the aircraft's autopilot that it was landing at its home base while actually guided to a landing in Iran. The US denied this, but the aircraft was recovered nearly intact, suggesting a controlled landing rather than a crash.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "Single turbofan buried in the flying wing body",
      wingPosition: "mid",
      wingShape: "swept",
      tailType: "no-tail",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Flying wing design",
        "No tail surfaces",
        "Smooth stealthy contours",
        "Single buried engine",
      ],
    },
    aliases: ["Sentinel", "Beast of Kandahar"],
  },
  {
    id: "mq-25-stingray",
    name: "MQ-25 Stingray",
    manufacturer: "Boeing",
    type: "Carrier-Based Unmanned Tanker",
    firstFlight: "2019",
    inService: "2025 (projected)",
    role: "Carrier-Based Aerial Refueling",
    country: "USA",
    specs: {
      wingspan: "~75 ft (estimated)",
      length: "~51 ft (estimated)",
      maxSpeed: "Classified (subsonic)",
      range: "Classified",
      ceiling: "Classified",
      engines: "1x Rolls-Royce AE 3007N turbofan",
      crew: "0 (remotely piloted)",
    },
    description:
      "The MQ-25 Stingray is the US Navy's first operational unmanned combat aircraft, designed primarily as a carrier-based aerial refueling tanker to extend the range of carrier air wings. It will be the first unmanned aircraft to operate from a carrier at sea routinely. By taking over the tanking mission from manned F/A-18s, the MQ-25 will free up strike fighters for combat missions. It represents a major milestone in unmanned naval aviation.",
    funFact:
      "In 2021, the MQ-25 became the first unmanned aircraft to refuel another aircraft in flight when it successfully passed fuel to an F/A-18 Super Hornet during test operations. This marked a historic milestone in naval aviation history.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "Single turbofan buried within the fuselage",
      wingPosition: "mid",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Flying wing-like blended body",
        "Carrier-capable with tailhook",
        "Refueling pod on centerline",
        "No vertical tail",
      ],
    },
    aliases: ["Stingray"],
  },
  {
    id: "bayraktar-tb2",
    name: "Bayraktar TB2",
    manufacturer: "Baykar",
    type: "Tactical UAV / UCAV",
    firstFlight: "2014",
    inService: "2016",
    role: "Tactical Reconnaissance / Light Strike",
    country: "Turkey",
    specs: {
      wingspan: "39 ft 4 in (12.0 m)",
      length: "21 ft (6.5 m)",
      maxSpeed: "138 mph (222 km/h)",
      range: "186 mi (300 km) (comms range)",
      ceiling: "27,030 ft (8,240 m)",
      engines: "1x Rotax 912 piston engine",
      crew: "0 (remote crew)",
    },
    description:
      "The Bayraktar TB2 is a Turkish-built medium-altitude long-endurance UCAV that gained worldwide attention through its effectiveness in conflicts in Libya, Nagorno-Karabakh, and Ukraine. Armed with laser-guided smart micro munitions (MAM-L, MAM-C), it demonstrated that relatively inexpensive armed drones could neutralize conventional military forces including tanks, air defense systems, and logistics vehicles. The TB2's combat success drove demand from dozens of nations.",
    funFact:
      "In the 2020 Nagorno-Karabakh conflict, Azerbaijani TB2 drones destroyed hundreds of Armenian armored vehicles, artillery pieces, and air defense systems in just 44 days, fundamentally altering the conflict's outcome. The drone cost less than $5 million per unit — less than a single advanced anti-aircraft missile system it was sent to destroy.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single pusher piston engine at the tail",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "twin-boom",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "Pusher propeller configuration",
        "Twin tail booms with horizontal stabilizer",
        "Long straight wings",
        "Inverted gull wing center section",
        "Sensor ball under nose",
      ],
    },
    aliases: ["TB2", "Bayraktar"],
  },
  {
    id: "ga-avenger",
    name: "General Atomics Avenger",
    manufacturer: "General Atomics Aeronautical Systems",
    type: "Stealth UCAV",
    firstFlight: "2009",
    inService: "2011 (limited)",
    role: "Stealth Strike / ISR",
    country: "USA",
    specs: {
      wingspan: "66 ft (20.1 m)",
      length: "44 ft (13.4 m)",
      maxSpeed: "460 mph (740 km/h)",
      range: "1,800 mi (2,897 km)",
      ceiling: "50,000 ft (15,240 m)",
      engines: "1x Pratt & Whitney PW545B turbofan",
      crew: "0 (remote crew)",
    },
    description:
      "The General Atomics Avenger (formerly Predator C) is a jet-powered, stealthy UCAV designed to operate in contested airspace where propeller-driven systems like the MQ-9 Reaper would be vulnerable. Its smooth fuselage and S-shaped engine inlet reduce radar cross-section, and its turbofan engine enables dash speeds comparable to manned combat aircraft. The Avenger has been evaluated for various ISR and strike missions but has not yet achieved full production orders.",
    funFact:
      "The Avenger's S-shaped engine inlet is a key stealth feature — the curved duct prevents radar waves from reaching the highly reflective turbine blades inside the engine, which would otherwise be a major radar return. This same technique is used on the B-2 Spirit and F-22 Raptor.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "Single turbofan with dorsal S-duct inlet",
      wingPosition: "mid",
      wingShape: "swept",
      tailType: "v-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Stealthy smooth fuselage contours",
        "Dorsal engine intake",
        "V-tail configuration",
        "Internal weapons bay",
        "Jet-powered unlike most UCAVs",
      ],
    },
    aliases: ["Predator C", "Avenger"],
  },
];
