import { AircraftEntry } from "./types";

export const specialAircraft: AircraftEntry[] = [
  // ============================================================
  // RECONNAISSANCE
  // ============================================================
  {
    id: "sr-71-blackbird",
    name: "SR-71 Blackbird",
    manufacturer: "Lockheed Skunk Works",
    type: "Strategic Reconnaissance",
    firstFlight: "1964",
    inService: "1966–1998",
    role: "Strategic Reconnaissance",
    country: "USA",
    specs: {
      wingspan: "55 ft 7 in (16.9 m)",
      length: "107 ft 5 in (32.7 m)",
      maxSpeed: "Mach 3.3+ (2,200+ mph / 3,540 km/h)",
      range: "3,200 mi (5,150 km) unrefueled",
      ceiling: "85,000 ft (25,908 m)",
      engines: "2x Pratt & Whitney J58 continuous bleed turbojet/ramjet",
      crew: "2",
    },
    description:
      "The SR-71 Blackbird is the fastest air-breathing aircraft ever built, capable of sustained flight above Mach 3.2 at altitudes exceeding 85,000 feet. Developed by Lockheed's Skunk Works under the direction of Clarence 'Kelly' Johnson, it served as the US Air Force's primary strategic reconnaissance platform from 1966 to 1998. The aircraft's titanium construction and radical design were decades ahead of contemporary technology. In its 32-year service life, not a single SR-71 was ever shot down.",
    funFact:
      "The SR-71 flew so fast that its airframe heated to over 900°F (480°C) from aerodynamic friction. The aircraft was designed with gaps in its titanium panels on the ground — they only sealed properly after thermal expansion at cruise speeds. This meant fuel would drip from the aircraft when parked, requiring a quick takeoff to refuel airborne.",
    visual: {
      engineCount: 2,
      engineType: "turbojet",
      enginePlacement: "Two J58 engines in large nacelles blended into the wing",
      wingPosition: "low",
      wingShape: "delta",
      tailType: "twin",
      landingGear: "retractable",
      sizeClass: "large",
      era: "cold-war",
      distinguishingFeatures: [
        "All-black titanium construction",
        "Chine-shaped forebody blending into delta wing",
        "Two massive engine nacelles with shock cones",
        "Twin canted outboard rudders",
        "Extremely long thin fuselage",
      ],
    },
    aliases: ["Blackbird", "Habu", "SR-71A"],
  },
  {
    id: "u-2-dragon-lady",
    name: "U-2 Dragon Lady",
    manufacturer: "Lockheed Skunk Works",
    type: "High-Altitude Reconnaissance",
    firstFlight: "1955",
    inService: "1957",
    role: "Strategic Reconnaissance / ISR",
    country: "USA",
    specs: {
      wingspan: "103 ft (31.4 m)",
      length: "62 ft 9 in (19.1 m)",
      maxSpeed: "500 mph (805 km/h)",
      range: "7,000 mi (11,265 km)",
      ceiling: "80,000 ft (24,384 m)",
      engines: "1x General Electric F118-GE-101 turbofan",
      crew: "1",
    },
    description:
      "The U-2 Dragon Lady is a single-engine, ultra-high-altitude reconnaissance aircraft that has been in continuous service since 1957 — one of the longest operational careers of any aircraft. Flying at over 70,000 feet, it collects imagery, SIGINT, and MASINT intelligence above most weather and beyond the reach of most surface-to-air missiles. Despite advances in satellite and drone technology, the U-2 remains in service because it can carry large sensor payloads to extreme altitudes on short notice.",
    funFact:
      "Piloting the U-2 is extraordinarily demanding: pilots must wear a full pressure suit (similar to a spacesuit) because at 70,000 feet, the cabin altitude is equivalent to 29,000 feet even with pressurization. Landing is also notoriously difficult — the aircraft has tandem bicycle-style gear and extremely long glider-like wings that must be stalled precisely onto the runway.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "Single turbofan in the fuselage",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "tandem",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "Extremely long glider-like straight wings",
        "Bicycle (tandem) landing gear",
        "Very narrow fuselage",
        "Single engine",
        "Designed-in fragility for weight savings",
      ],
    },
    aliases: ["Dragon Lady", "U-2S"],
  },
  {
    id: "lockheed-tr-1",
    name: "Lockheed TR-1",
    manufacturer: "Lockheed Skunk Works",
    type: "High-Altitude Tactical Reconnaissance",
    firstFlight: "1981",
    inService: "1981–1997",
    role: "Tactical Battlefield Reconnaissance",
    country: "USA",
    specs: {
      wingspan: "103 ft (31.4 m)",
      length: "63 ft (19.2 m)",
      maxSpeed: "475 mph (764 km/h)",
      range: "3,000 mi (4,828 km)",
      ceiling: "90,000 ft (27,432 m)",
      engines: "1x Pratt & Whitney J75-P-13B turbojet",
      crew: "1",
    },
    description:
      "The TR-1 was an advanced tactical reconnaissance variant of the U-2, developed for battlefield surveillance over Europe. Equipped with the ASARS-2 radar and Precision Location Strike System (PLSS), it could track Warsaw Pact ground forces and direct NATO strike aircraft to mobile targets. The TR-1 was eventually redesignated as U-2R/S aircraft and retired from the separate TR-1 designation in the 1990s. Its sensor systems pioneered many reconnaissance technologies still in use today.",
    funFact:
      "The TR-1 was designed during the Cold War with a specific mission: to map the entire Warsaw Pact order of battle in Central Europe within hours of a conflict breaking out. It carried synthetic aperture radar that could see through clouds, enabling real-time battlefield intelligence in the notoriously overcast European theater.",
    visual: {
      engineCount: 1,
      engineType: "turbojet",
      enginePlacement: "Single turbojet in the fuselage",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "tandem",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "Very long straight wings similar to U-2",
        "Bicycle tandem landing gear",
        "Large sensor pods under wings",
        "Narrow fuselage",
      ],
    },
    aliases: ["TR-1A", "U-2R"],
  },
  {
    id: "rf-4-phantom",
    name: "RF-4 Phantom II",
    manufacturer: "McDonnell Douglas",
    type: "Tactical Reconnaissance",
    variant: "RF-4C / RF-4E",
    firstFlight: "1964",
    inService: "1964–1995",
    role: "Tactical Photo / Electronic Reconnaissance",
    country: "USA",
    specs: {
      wingspan: "38 ft 5 in (11.7 m)",
      length: "62 ft 11 in (19.2 m)",
      maxSpeed: "Mach 2.23 (1,473 mph / 2,370 km/h)",
      range: "1,750 mi (2,817 km)",
      ceiling: "59,600 ft (18,166 m)",
      engines: "2x General Electric J79-GE-17 turbojet",
      crew: "2",
    },
    description:
      "The RF-4 Phantom II was a dedicated reconnaissance variant of the famous F-4 Phantom fighter, replacing its guns and weapons systems with sophisticated camera and electronic sensor packages. The elongated nose housed multiple cameras, infrared linescanners, and electronic intelligence sensors. It served the US Air Force, Navy, and many allied nations throughout the Cold War. Despite being unarmed, it relied on its speed — Mach 2+ — to evade interceptors over enemy territory.",
    funFact:
      "The RF-4C could photograph a 1-mile-wide strip of terrain while flying at Mach 1.2 at low level, creating a photographic mosaic of enemy defenses so detailed that intelligence analysts could identify individual vehicles. Pilots flew these missions unarmed, relying entirely on speed to survive.",
    visual: {
      engineCount: 2,
      engineType: "turbojet",
      enginePlacement: "Two turbojets side-by-side in the fuselage",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "Extended camera nose (longer than standard F-4)",
        "No weapons pylons",
        "Drooped outer wing leading edges",
        "Anhedral horizontal tail",
        "Camera windows in nose",
      ],
    },
    aliases: ["Photo Phantom", "RF-4C"],
  },

  // ============================================================
  // EXPERIMENTAL
  // ============================================================
  {
    id: "bell-x-1",
    name: "Bell X-1",
    manufacturer: "Bell Aircraft Corporation",
    type: "Experimental / Research",
    firstFlight: "1946",
    inService: "1946–1958",
    role: "Transonic / Supersonic Research",
    country: "USA",
    specs: {
      wingspan: "28 ft (8.5 m)",
      length: "30 ft 11 in (9.4 m)",
      maxSpeed: "Mach 1.45 (957 mph / 1,541 km/h)",
      range: "N/A (air-launched)",
      ceiling: "71,902 ft (21,916 m)",
      engines: "1x Reaction Motors XLR-11 rocket engine",
      crew: "1",
    },
    description:
      "The Bell X-1 was the first aircraft to exceed the speed of sound in level flight, achieving this milestone on October 14, 1947, with Chuck Yeager at the controls. The orange, bullet-shaped aircraft was air-launched from a B-29 mother ship to conserve rocket fuel for the supersonic dash. Its thin straight wings and rocket power helped it overcome the 'sound barrier' — the deadly transonic buffeting that had killed test pilots before it. The X-1 program established the foundation for all subsequent supersonic aircraft development.",
    funFact:
      "Chuck Yeager flew the Bell X-1 through the sound barrier with two broken ribs, suffered the night before when he fell off a horse. Not wanting to be grounded, he told only his buddy Jack Ridley, who improvised a broom handle so Yeager could close the X-1's hatch with one arm.",
    visual: {
      engineCount: 1,
      engineType: "turbojet",
      enginePlacement: "Single rocket engine in the tail",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "early-jet",
      distinguishingFeatures: [
        "Bullet-shaped orange fuselage",
        "Thin straight wings",
        "Air-launched from B-29",
        "Rocket powered",
        "No air intakes (rocket engine)",
      ],
    },
    aliases: ["Glamorous Glennis", "X-1"],
  },
  {
    id: "north-american-x-15",
    name: "North American X-15",
    manufacturer: "North American Aviation",
    type: "Experimental / Hypersonic Research",
    firstFlight: "1959",
    inService: "1959–1968",
    role: "Hypersonic Research / Space Boundary Exploration",
    country: "USA",
    specs: {
      wingspan: "22 ft 4 in (6.8 m)",
      length: "50 ft 9 in (15.5 m)",
      maxSpeed: "Mach 6.72 (4,520 mph / 7,274 km/h)",
      range: "N/A (air-launched)",
      ceiling: "354,200 ft (107,960 m)",
      engines: "1x Thiokol XLR99 rocket engine",
      crew: "1",
    },
    description:
      "The North American X-15 remains the fastest and highest-flying winged aircraft ever built, reaching Mach 6.72 and altitudes exceeding 100 km (the Kármán line, the boundary of space) in its research program. Twelve test pilots flew the X-15, eight of whom qualified as astronauts by crossing the 50-mile (80 km) altitude threshold. The program generated critical data on hypersonic flight, reentry, and aerodynamic heating that informed the Mercury, Gemini, and Apollo programs.",
    funFact:
      "The X-15's outer skin reached temperatures of 1,200°F (648°C) during high-speed flights, requiring a special ablative coating. Neil Armstrong was one of the X-15 pilots before becoming an astronaut — he flew it seven times and used data from those flights in designing the Lunar Landing Research Vehicle.",
    visual: {
      engineCount: 1,
      engineType: "turbojet",
      enginePlacement: "Single large rocket engine in the tail",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "cruciform",
      landingGear: "skids",
      sizeClass: "medium",
      era: "cold-war",
      distinguishingFeatures: [
        "Distinctive wedge-shaped fuselage cross-section",
        "Very small straight wings",
        "Large ventral fin below fuselage",
        "Skid landing gear (belly landing)",
        "Visible reaction control thruster ports",
      ],
    },
    aliases: ["X-15"],
  },
  {
    id: "grumman-x-29",
    name: "Grumman X-29",
    manufacturer: "Grumman",
    type: "Experimental / Technology Demonstrator",
    firstFlight: "1984",
    inService: "1984–1992",
    role: "Forward-Swept Wing Research",
    country: "USA",
    specs: {
      wingspan: "27 ft 2 in (8.3 m)",
      length: "53 ft 11 in (16.4 m)",
      maxSpeed: "Mach 1.6 (1,056 mph / 1,700 km/h)",
      range: "N/A (research)",
      ceiling: "50,000 ft (15,240 m)",
      engines: "1x General Electric F404-GE-400 turbofan",
      crew: "1",
    },
    description:
      "The Grumman X-29 was an experimental technology demonstrator featuring forward-swept wings — a configuration that is aerodynamically unstable and was previously considered impractical for high-speed aircraft. Advanced composite materials and a digital fly-by-wire control system making 40 corrections per second enabled the radical design to fly. The X-29 demonstrated superior maneuverability at high angles of attack, though the aerodynamic benefits were ultimately not deemed worth the design complexity for production aircraft.",
    funFact:
      "The X-29's forward-swept wings are so aerodynamically unstable that without the fly-by-wire computer making continuous corrections at 40 times per second, the aircraft would tumble out of control within milliseconds. No human pilot could manually fly it — the computer is always in the loop.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "Single turbofan in the fuselage",
      wingPosition: "mid",
      wingShape: "forward-swept",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "Dramatic forward-swept wings",
        "Canard foreplanes",
        "Single engine intake below nose",
        "Unusual wing sweep direction",
      ],
    },
    aliases: ["X-29"],
  },
  {
    id: "boeing-x-32",
    name: "Boeing X-32",
    manufacturer: "Boeing",
    type: "Experimental / JSFX Technology Demonstrator",
    firstFlight: "2000",
    inService: "2000–2001",
    role: "Joint Strike Fighter Concept Demonstrator",
    country: "USA",
    specs: {
      wingspan: "36 ft (11 m)",
      length: "45 ft (13.7 m)",
      maxSpeed: "Mach 1.6+ (estimated)",
      range: "N/A (demonstrator)",
      ceiling: "Classified",
      engines: "1x Pratt & Whitney F119-SE611 turbofan",
      crew: "1",
    },
    description:
      "The Boeing X-32 was Boeing's competitor against the Lockheed Martin X-35 in the Joint Strike Fighter competition. Distinguished by its massive single air intake and delta wing, the X-32B variant demonstrated short takeoff and vertical landing capability using a direct-lift system that channeled engine thrust through a large forward duct. Despite meeting most JSF requirements, Boeing lost the competition to the X-35, which became the F-35 Lightning II.",
    funFact:
      "The X-32 was immediately nicknamed 'Monica' by Pentagon insiders because of its unusually large lip-shaped intake — a physical characteristic that became a source of unflattering comparisons. Its ungainly appearance is thought to have contributed to negative perceptions during the competitive evaluation.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "Single turbofan with massive chin intake",
      wingPosition: "mid",
      wingShape: "delta",
      tailType: "no-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Enormous single chin intake",
        "Delta wing with no horizontal tail",
        "Distinctive lip-shaped air intake",
        "Single engine",
      ],
    },
    aliases: ["X-32", "Monica"],
  },
  {
    id: "lockheed-martin-x-35",
    name: "Lockheed Martin X-35",
    manufacturer: "Lockheed Martin",
    type: "Experimental / JSF Technology Demonstrator",
    firstFlight: "2000",
    inService: "2000–2001",
    role: "Joint Strike Fighter Concept Demonstrator",
    country: "USA",
    specs: {
      wingspan: "35 ft (10.7 m)",
      length: "51 ft 5 in (15.7 m)",
      maxSpeed: "Mach 1.6+",
      range: "N/A (demonstrator)",
      ceiling: "Classified",
      engines: "1x Pratt & Whitney F119-SE611 turbofan",
      crew: "1",
    },
    description:
      "The Lockheed Martin X-35 was the concept demonstrator for what became the F-35 Lightning II after winning the Joint Strike Fighter competition. The X-35B demonstrated short takeoff and vertical landing using a revolutionary shaft-driven lift fan — a large fan in the aircraft's center driven mechanically from the main engine. This system proved both effective and low-risk compared to Boeing's X-32 alternative, convincing evaluators that the Lockheed design was the safer production choice.",
    funFact:
      "During the JSF competition fly-off, the X-35B performed a maneuver no aircraft had previously demonstrated: a short takeoff, supersonic dash, and then a vertical landing — all in a single flight. This was called 'Mission X' and it conclusively demonstrated the viability of the shaft-driven lift fan concept.",
    visual: {
      engineCount: 1,
      engineType: "turbofan",
      enginePlacement: "Single turbofan with DSI intake on fuselage side",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "contemporary",
      distinguishingFeatures: [
        "Diverterless supersonic intake",
        "Trapezoidal wing",
        "Lift fan door visible on top of fuselage",
        "Twin canted vertical tails",
      ],
    },
    aliases: ["X-35", "JSF demonstrator"],
  },
  {
    id: "nasa-x-43",
    name: "NASA X-43 Hyper-X",
    manufacturer: "MicroCraft Inc. / Boeing",
    type: "Experimental / Hypersonic Research",
    firstFlight: "2001",
    inService: "2001–2004",
    role: "Scramjet Hypersonic Research",
    country: "USA",
    specs: {
      wingspan: "5 ft (1.5 m)",
      length: "12 ft (3.7 m)",
      maxSpeed: "Mach 9.8 (7,365 mph / 11,850 km/h)",
      range: "N/A (expendable)",
      ceiling: "110,000 ft (33,528 m)",
      engines: "1x hydrogen-fueled scramjet",
      crew: "0 (unmanned)",
    },
    description:
      "The NASA X-43 Hyper-X is the fastest air-breathing aircraft in history, reaching Mach 9.8 during its final test flight in November 2004. It demonstrated that a scramjet (supersonic combustion ramjet) engine could sustain powered hypersonic flight, burning hydrogen fuel in a supersonic airstream. The X-43 was air-launched from a B-52 attached to a Pegasus rocket booster that accelerated it to scramjet ignition speed. Each flight lasted only about 10 seconds of powered scramjet operation before the vehicle impacted the Pacific Ocean.",
    funFact:
      "At Mach 9.8, the X-43 traveled approximately 1 mile every 0.55 seconds — fast enough to fly from New York to Los Angeles in under 12 minutes. The scramjet engine operated for just 10 seconds but validated decades of theoretical research on air-breathing hypersonic propulsion.",
    visual: {
      engineCount: 1,
      engineType: "turbojet",
      enginePlacement: "Scramjet integrated into the vehicle undersurface",
      wingPosition: "low",
      wingShape: "delta",
      tailType: "no-tail",
      landingGear: "skids",
      sizeClass: "ultralight",
      era: "contemporary",
      distinguishingFeatures: [
        "Flat lifting body shape",
        "Scramjet exhaust visible under the tail",
        "Integrated forebody inlet",
        "Tiny research vehicle",
      ],
    },
    aliases: ["Hyper-X", "X-43A"],
  },
  {
    id: "bell-x-5",
    name: "Bell X-5",
    manufacturer: "Bell Aircraft Corporation",
    type: "Experimental / Variable-Sweep Research",
    firstFlight: "1951",
    inService: "1951–1958",
    role: "Variable-Sweep Wing Research",
    country: "USA",
    specs: {
      wingspan: "33 ft 6 in (10.2 m) minimum, 20 ft 9 in (6.3 m) maximum",
      length: "38 ft (11.6 m)",
      maxSpeed: "716 mph (1,152 km/h)",
      range: "N/A (research)",
      ceiling: "50,700 ft (15,454 m)",
      engines: "1x Allison J35-A-17A turbojet",
      crew: "1",
    },
    description:
      "The Bell X-5 was the first aircraft capable of varying its wing sweep angle in flight, pioneering the variable-sweep wing concept later used in the F-111, F-14 Tomcat, B-1B Lancer, and Tornado. Inspired by the captured German Messerschmitt P.1101 (which had to be adjusted on the ground), the X-5 could change sweep from 20 to 60 degrees in flight. The research data it generated proved essential to the development of variable-geometry combat aircraft.",
    funFact:
      "The Bell X-5 was based on a captured German wartime research aircraft — the Messerschmitt P.1101, which had been found unfinished at a Bavarian mountain factory in 1945. Bell bought the incomplete German design, studied it, and created an American version that could actually change sweep in the air (the German original required ground adjustment).",
    visual: {
      engineCount: 1,
      engineType: "turbojet",
      enginePlacement: "Single turbojet in the fuselage with a chin intake",
      wingPosition: "mid",
      wingShape: "variable-sweep",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "early-jet",
      distinguishingFeatures: [
        "Variable-sweep wings with pivot visible at wing root",
        "Single chin intake",
        "T-type horizontal tail",
        "Small research aircraft",
      ],
    },
    aliases: ["X-5"],
  },

  // ============================================================
  // UNIQUE / SPECIAL PURPOSE
  // ============================================================
  {
    id: "space-shuttle-orbiter",
    name: "Space Shuttle Orbiter",
    manufacturer: "Rockwell International",
    type: "Spaceplane / Reusable Launch Vehicle",
    variant: "OV-105 (Endeavour)",
    firstFlight: "1977 (ALT) / 1981 (orbital)",
    inService: "1981–2011",
    role: "Crewed Orbital Spaceflight",
    country: "USA",
    specs: {
      wingspan: "78 ft 1 in (23.8 m)",
      length: "122 ft 5 in (37.2 m)",
      maxSpeed: "Mach 25 (17,500 mph / 28,163 km/h) orbital velocity",
      range: "Orbital",
      ceiling: "Orbital (>200 mi / 322 km)",
      engines: "3x Space Shuttle Main Engine (SSME) + 2x OMS pods",
      crew: "2–7",
    },
    description:
      "The Space Shuttle Orbiter was NASA's reusable crewed spacecraft that served as the centerpiece of the Space Shuttle system from 1981 to 2011. Five orbiters flew operational missions: Columbia, Challenger, Discovery, Atlantis, and Endeavour. During reentry, the orbiter flew as a glider — with no engine power — relying entirely on its delta wing shape and thermal protection system tiles to survive the extreme heat of reentry before landing on a runway. It remains the only crewed vehicle to fly as both a spacecraft and a conventional aircraft.",
    funFact:
      "The Space Shuttle had the worst glide ratio of any winged vehicle in history — about 1:1 at subsonic speeds, compared to 15:1 for a typical airliner. Astronauts described it as 'flying a brick.' The commander had one and only one chance to land; there was no go-around capability because it had no engines during final approach.",
    visual: {
      engineCount: 3,
      engineType: "turbofan",
      enginePlacement: "Three main engines in the tail, two OMS pods on tail sides",
      wingPosition: "low",
      wingShape: "delta",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "heavy",
      era: "modern",
      distinguishingFeatures: [
        "Distinctive delta wing with double-delta shape",
        "Thermal protection tiles covering fuselage",
        "Three main engine bells in tail",
        "Two OMS engine pods flanking vertical tail",
        "Large cargo bay doors on top of fuselage",
      ],
    },
    aliases: ["Shuttle Orbiter", "Columbia", "Challenger", "Discovery", "Atlantis", "Endeavour"],
  },
  {
    id: "white-knight-two",
    name: "Scaled Composites White Knight Two",
    manufacturer: "Scaled Composites",
    type: "Launch Aircraft / Mothership",
    firstFlight: "2008",
    inService: "2008",
    role: "Carrier Aircraft for SpaceShipTwo",
    country: "USA",
    specs: {
      wingspan: "140 ft (42.7 m)",
      length: "78 ft (23.8 m)",
      maxSpeed: "280 mph (450 km/h)",
      range: "N/A (return to base mission)",
      ceiling: "52,000 ft (15,850 m)",
      engines: "4x Pratt & Whitney Canada PW308A turbofan",
      crew: "2",
      capacity: "SpaceShipTwo vehicle + 2–4 additional crew",
    },
    description:
      "White Knight Two (VMS Eve) is the carrier aircraft developed by Scaled Composites to launch SpaceShipTwo at high altitude, giving the suborbital spaceplane the altitude and energy needed for its rocket engine burn. The aircraft features a distinctive twin-fuselage design, with SpaceShipTwo suspended between the two fuselages. Its composite construction and high-aspect-ratio wing give it excellent high-altitude performance. White Knight Two is named 'VMS Eve' after Richard Branson's mother.",
    funFact:
      "White Knight Two's cabin is pressurized to a flight altitude of 12,000 feet, allowing the SpaceShipTwo's astronaut passengers to experience a preview of the conditions they will encounter during their spaceflight — without the need to wear pressure suits for the carrier phase.",
    visual: {
      engineCount: 4,
      engineType: "turbofan",
      enginePlacement: "Two turbofans on each wing, one on each side of each fuselage",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "twin-boom",
      landingGear: "tricycle",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "Twin fuselage design",
        "SpaceShipTwo carried between fuselages",
        "High-aspect-ratio straight wings",
        "Twin tail booms with stabilizers",
        "Four turbofan engines",
      ],
    },
    aliases: ["VMS Eve", "WhiteKnightTwo"],
  },
  {
    id: "spaceshiptwo",
    name: "SpaceShipTwo",
    manufacturer: "Scaled Composites / The Spaceship Company",
    type: "Suborbital Spaceplane",
    variant: "VSS Unity",
    firstFlight: "2010",
    inService: "2010",
    role: "Commercial Suborbital Spaceflight",
    country: "USA",
    specs: {
      wingspan: "27 ft (8.2 m)",
      length: "60 ft (18.3 m)",
      maxSpeed: "Mach 3 (2,300 mph / 3,700 km/h) during boost",
      range: "N/A (suborbital)",
      ceiling: "282,000 ft (86 km) (VSS Unity)",
      engines: "1x RocketMotorTwo hybrid rocket",
      crew: "2 pilots + 6 passengers",
    },
    description:
      "SpaceShipTwo is Virgin Galactic's commercial suborbital spaceplane, designed to carry six paying passengers to the edge of space and back on a 90-minute flight experience. Air-launched from White Knight Two, it fires its hybrid rocket motor to climb to approximately 50–88 miles altitude, providing minutes of weightlessness and views of the black sky of space and the curvature of the Earth. It uses a novel 'feathering' reentry system — the tail rotates upward to create drag and stability during descent.",
    funFact:
      "SpaceShipTwo's 'feathering' reentry system, where the tail rotates 65 degrees upward to create a shuttlecock-like descent, is designed to be self-stabilizing in all conditions — unlike the Space Shuttle, which required precise pilot input during reentry. The system makes the spacecraft nearly impossible to lose control of during descent.",
    visual: {
      engineCount: 1,
      engineType: "turbojet",
      enginePlacement: "Single hybrid rocket motor in the tail",
      wingPosition: "mid",
      wingShape: "swept",
      tailType: "twin",
      landingGear: "retractable",
      sizeClass: "light",
      era: "contemporary",
      distinguishingFeatures: [
        "Feathering tail reentry system",
        "Two vertical tail fins",
        "Hybrid rocket motor",
        "Large windows for passenger views",
        "Air-launched from mothership",
      ],
    },
    aliases: ["VSS Unity", "SpaceShipTwo", "SS2"],
  },
  {
    id: "scaled-composites-voyager",
    name: "Scaled Composites Voyager",
    manufacturer: "Scaled Composites",
    type: "Long-Range Research Aircraft",
    firstFlight: "1984",
    inService: "1986 (record flight)",
    role: "Around-the-World Nonstop Unrefueled Flight",
    country: "USA",
    specs: {
      wingspan: "110 ft 8 in (33.8 m)",
      length: "29 ft (8.9 m)",
      maxSpeed: "196 mph (315 km/h)",
      range: "26,366 mi (42,432 km) nonstop unrefueled",
      ceiling: "20,000 ft (6,096 m)",
      engines: "2x Teledyne Continental motors (front push and rear pull)",
      crew: "2",
    },
    description:
      "The Scaled Composites Voyager is the aircraft in which Dick Rutan and Jeana Yeager completed the first nonstop, unrefueled circumnavigation of the Earth in December 1986. The entire aircraft was essentially a flying fuel tank, with fuel making up 72% of its takeoff weight. Designed by Burt Rutan for his brother Dick, Voyager required every ounce of ingenuity to achieve the range needed — its canard twin-boom design and composite construction saved every possible pound of structural weight.",
    funFact:
      "When Voyager took off for its record flight, its wingtips were so heavily loaded with fuel that they dragged on the runway. Dick Rutan had a ground crew member break off each drooping wingtip section as the aircraft gained speed — the wingtips were sacrificial and intentionally designed to break off at takeoff.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "One pusher in the rear, one puller in the front of the fuselage pod",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "twin-boom",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "Twin outrigger boom fuselages",
        "Tandem engine arrangement (one front, one rear)",
        "Extremely high aspect ratio straight wings",
        "Central crew pod",
        "Distinctive canard-boom configuration",
      ],
    },
    aliases: ["Voyager"],
  },
  {
    id: "rutan-long-ez",
    name: "Rutan Long-EZ",
    manufacturer: "Rutan Aircraft Factory (homebuilt)",
    type: "Long-Range Homebuilt",
    firstFlight: "1979",
    inService: "1980",
    role: "Long-Range Personal Aircraft / Homebuilt",
    country: "USA",
    specs: {
      wingspan: "26 ft 10 in (8.2 m)",
      length: "16 ft 9 in (5.1 m)",
      maxSpeed: "193 mph (311 km/h)",
      range: "2,010 mi (3,234 km)",
      ceiling: "25,700 ft (7,833 m)",
      engines: "1x Lycoming O-235 piston",
      crew: "2",
    },
    description:
      "The Rutan Long-EZ is a highly popular homebuilt aircraft designed by Burt Rutan as a longer-range development of the VariEze. Its canard pusher configuration, composite construction, and exceptional efficiency give it remarkable range — over 2,000 miles — from a small engine. More than 700 Long-EZs were built by amateur constructors from plans, making it one of the most successful homebuilt designs in history. The design inspired a generation of canard composite aircraft.",
    funFact:
      "The Long-EZ is inherently stall/spin resistant because its canard is designed to stall before the main wing — when the nose pitches up too far, the canard stalls and drops the nose automatically before the main wing can enter a full stall. This passive safety feature has saved many pilots' lives.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single pusher piston engine at the rear",
      wingPosition: "mid",
      wingShape: "swept",
      tailType: "no-tail",
      landingGear: "tricycle",
      sizeClass: "ultralight",
      era: "modern",
      distinguishingFeatures: [
        "Canard foreplanes instead of horizontal tail",
        "Pusher propeller at the rear",
        "Swept main wing with winglets",
        "No conventional tail",
        "Tandem seating in low-profile composite fuselage",
      ],
    },
    aliases: ["Long-EZ"],
  },
  {
    id: "burt-rutan-varieze",
    name: "Rutan VariEze",
    manufacturer: "Rutan Aircraft Factory (homebuilt)",
    type: "Homebuilt / Experimental",
    firstFlight: "1975",
    inService: "1976",
    role: "Personal / Experimental Aircraft",
    country: "USA",
    specs: {
      wingspan: "22 ft 2 in (6.8 m)",
      length: "14 ft 7 in (4.5 m)",
      maxSpeed: "215 mph (346 km/h)",
      range: "1,100 mi (1,770 km)",
      ceiling: "25,000 ft (7,620 m)",
      engines: "1x Continental O-200 piston",
      crew: "2",
    },
    description:
      "The Rutan VariEze (pronounced 'Very Easy') was Burt Rutan's breakthrough homebuilt design that pioneered the use of glass-fiber composite construction and the canard pusher configuration for amateur-built aircraft. Introduced at the 1975 Oshkosh EAA Convention, it triggered a revolution in homebuilt aircraft design. Its exceptional performance, efficiency, and distinctive appearance inspired thousands of builders and dozens of derivative designs, including the Long-EZ and Cozy series.",
    funFact:
      "When Rutan unveiled the VariEze at the 1975 EAA Oshkosh Fly-In, he reportedly created such a sensation that aircraft kit manufacturers saw immediate drops in their orders — homebuilders were determined to build their own VariEze instead. The design showed that amateur builders could create aircraft far more sophisticated than anything available as a kit.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single pusher piston at the rear",
      wingPosition: "mid",
      wingShape: "swept",
      tailType: "no-tail",
      landingGear: "tricycle",
      sizeClass: "ultralight",
      era: "modern",
      distinguishingFeatures: [
        "Canard pusher configuration",
        "Retractable main gear under fuselage",
        "Fixed nosewheel that retracts in flight (optional)",
        "Winglets on swept main wing",
        "Very compact design",
      ],
    },
    aliases: ["VariEze", "Vari-Eze"],
  },
  {
    id: "concorde",
    name: "Concorde",
    manufacturer: "Aérospatiale / BAC",
    type: "Supersonic Transport",
    firstFlight: "1969",
    inService: "1976–2003",
    role: "Supersonic Passenger Transport",
    country: "France/UK",
    specs: {
      wingspan: "83 ft 8 in (25.6 m)",
      length: "202 ft 3 in (61.66 m)",
      maxSpeed: "Mach 2.04 (1,354 mph / 2,179 km/h)",
      range: "3,900 mi (6,276 km)",
      ceiling: "60,000 ft (18,288 m)",
      engines: "4x Rolls-Royce/SNECMA Olympus 593 turbojet",
      crew: "3",
      capacity: "92–128 passengers",
    },
    description:
      "Concorde was the world's first successful supersonic commercial airliner, operated by Air France and British Airways between 1976 and 2003. Flying at Mach 2 at 60,000 feet, it could cross the Atlantic in under 3.5 hours — half the time of subsonic jets. Only 20 were built (14 commercial) and the aircraft never achieved economic viability at scale. Operations ended following the tragic 2000 Air France crash and declining passenger demand after 9/11. Concorde remains an icon of technological ambition.",
    funFact:
      "Concorde's airframe stretched by up to 10 inches (25 cm) during supersonic cruise due to aerodynamic heating expanding the aluminum and steel structure. A small gap would open between the cockpit wall and the instrument panel that engineers used to store their uniform caps — the only place warm enough to keep them from wrinkling.",
    visual: {
      engineCount: 4,
      engineType: "turbojet",
      enginePlacement: "Four turbojets grouped in two under-wing nacelle pairs",
      wingPosition: "low",
      wingShape: "delta",
      tailType: "no-tail",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "modern",
      distinguishingFeatures: [
        "Distinctive ogival delta wing (droop leading edge)",
        "Drooping nose visor for pilot visibility on landing",
        "No horizontal tail surfaces",
        "Four engine nacelles under delta wing",
        "Extremely long slender fuselage",
      ],
    },
    aliases: ["SST", "Concorde SST"],
  },
  {
    id: "solar-impulse",
    name: "Solar Impulse 2",
    manufacturer: "Solar Impulse",
    type: "Solar-Powered Research Aircraft",
    firstFlight: "2014",
    inService: "2015–2016",
    role: "Solar-Powered Circumnavigation",
    country: "Switzerland",
    specs: {
      wingspan: "236 ft (72 m)",
      length: "94 ft (28.9 m)",
      maxSpeed: "90 mph (144 km/h)",
      range: "Unlimited (solar)",
      ceiling: "28,000 ft (8,534 m)",
      engines: "4x electric motors (17.4 kW each)",
      crew: "1",
    },
    description:
      "Solar Impulse 2 is a solar-powered aircraft designed to fly around the world using only energy from the sun. Piloted alternately by Bertrand Piccard and André Borschberg, it completed the first solar-powered circumnavigation of the Earth in 2016. With a wingspan wider than a Boeing 747 but weighing less than a family car, Solar Impulse 2 carries 17,248 solar cells that charge lithium batteries to sustain flight through the night. Its record flight from Japan to Hawaii lasted 117 hours 52 minutes nonstop.",
    funFact:
      "Solar Impulse 2's wingspan of 72 meters is wider than a Boeing 747, but it weighs only 2,300 kg — about the same as a large car. Its four electric motors produce a combined 70 horsepower, roughly equivalent to a small motorcycle engine, yet it can climb to 28,000 feet and cruise indefinitely on sunshine alone.",
    visual: {
      engineCount: 4,
      engineType: "electric",
      enginePlacement: "Four electric motors with pusher propellers on long straight wings",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "Enormous aspect-ratio straight wings covered in solar cells",
        "Four nacelles with electric motors and propellers",
        "Very slender fuselage pod",
        "Single-seat cockpit",
        "Carbon fiber construction",
      ],
    },
    aliases: ["Si2", "Solar Impulse"],
  },

  // ============================================================
  // AEROBATIC
  // ============================================================
  {
    id: "extra-300",
    name: "Extra 300",
    manufacturer: "Extra Aircraft",
    type: "Aerobatic Aircraft",
    variant: "Extra 330SC",
    firstFlight: "1988",
    inService: "1988",
    role: "Unlimited Aerobatics / Competition",
    country: "Germany",
    specs: {
      wingspan: "26 ft 3 in (8.0 m)",
      length: "23 ft 1 in (7.1 m)",
      maxSpeed: "245 mph (395 km/h)",
      range: "497 mi (800 km)",
      ceiling: "16,400 ft (5,000 m)",
      engines: "1x Lycoming AEIO-540-L1B5 piston",
      crew: "1–2",
    },
    description:
      "The Extra 300 is one of the world's premier unlimited aerobatic aircraft, designed by Walter Extra and used by many world aerobatic champions. Its carbon fiber construction and symmetric airfoil allow equal performance both upright and inverted, while its powerful Lycoming engine provides a thrust-to-weight ratio near 1:1. The Extra 300 series is the mount of choice for many air race, airshow, and competition aerobatic performers worldwide.",
    funFact:
      "The Extra 300 is stressed to +/-10G — meaning it can withstand forces ten times the weight of gravity in both positive and negative directions. In competition aerobatics, pilots routinely pull 8-9G during snaps and spins, subjecting themselves to forces that would cause most people to black out.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single inverted piston engine in nose",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "taildragger",
      sizeClass: "ultralight",
      era: "modern",
      distinguishingFeatures: [
        "Mid-wing monoplane",
        "Large bubble canopy",
        "Taildragger gear",
        "Large aerobatic rudder",
        "Sleek composite fuselage",
      ],
    },
    aliases: ["Extra 300L", "Extra 330", "Extra"],
  },
  {
    id: "pitts-special-s2",
    name: "Pitts Special S-2",
    manufacturer: "Pitts Aerobatics (Aviat Aircraft)",
    type: "Aerobatic Biplane",
    firstFlight: "1944",
    inService: "1944",
    role: "Aerobatics / Competition",
    country: "USA",
    specs: {
      wingspan: "20 ft (6.1 m)",
      length: "17 ft 9 in (5.4 m)",
      maxSpeed: "194 mph (312 km/h)",
      range: "248 mi (399 km)",
      ceiling: "19,700 ft (6,004 m)",
      engines: "1x Lycoming AEIO-360-A1E piston",
      crew: "2",
    },
    description:
      "The Pitts Special is a legendary aerobatic biplane that dominated competition aerobatics from the 1960s through the 1980s. Designed by Curtis Pitts in 1944, its short fuselage, low weight, and large control surfaces give it an extraordinarily high roll rate — up to 420 degrees per second in some variants. The Pitts has been flown to world aerobatic championships more times than any other aircraft and remains one of the best-handling aerobatic biplanes ever designed.",
    funFact:
      "The Pitts Special has the fastest roll rate of any production aircraft — approximately 420 degrees per second in the single-seat S-1S. At this rate, it completes a full 360-degree roll in less than one second, so fast that spectators at airshows often see only a blur.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single inverted inline engine in nose",
      wingPosition: "biplane",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "taildragger",
      sizeClass: "ultralight",
      era: "modern",
      distinguishingFeatures: [
        "Biplane configuration with symmetrical wings",
        "Very short fuselage",
        "Taildragger landing gear",
        "Open or enclosed tandem cockpit",
        "Large aerobatic control surfaces",
      ],
    },
    aliases: ["Pitts Special", "S-2B"],
  },
  {
    id: "edge-540",
    name: "Zivko Edge 540",
    manufacturer: "Zivko Aeronautics",
    type: "Aerobatic Aircraft",
    firstFlight: "1993",
    inService: "1993",
    role: "Unlimited Aerobatics / Air Racing",
    country: "USA",
    specs: {
      wingspan: "24 ft 4 in (7.4 m)",
      length: "19 ft 4 in (5.9 m)",
      maxSpeed: "275 mph (442 km/h)",
      range: "395 mi (636 km)",
      ceiling: "16,000 ft (4,877 m)",
      engines: "1x Lycoming AEIO-540 piston",
      crew: "1",
    },
    description:
      "The Zivko Edge 540 is a high-performance aerobatic aircraft widely used in the Red Bull Air Race World Championship and unlimited aerobatics competition. Its carbon composite construction and Lycoming engine combination gives it an exceptional thrust-to-weight ratio, while its symmetric airfoil enables equal performance inverted and upright. The Edge 540 has been flown to multiple Red Bull Air Race championships and is considered one of the most responsive aerobatic aircraft ever designed.",
    funFact:
      "In the Red Bull Air Race, Edge 540 pilots navigate a pylons course pulling up to 10G while flying at speeds up to 230 mph just a few feet off the ground. The aircraft's carbon fiber structure is so precisely balanced that mechanics weigh paint before applying it to ensure equal coats don't upset the aircraft's center of gravity.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single inverted piston in nose",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "taildragger",
      sizeClass: "ultralight",
      era: "contemporary",
      distinguishingFeatures: [
        "Very low profile composite fuselage",
        "Mid-wing with large symmetric airfoil",
        "Large taildragger gear",
        "Single open or enclosed cockpit",
        "Racing livery",
      ],
    },
    aliases: ["Edge 540", "Zivko 540"],
  },
  {
    id: "sukhoi-su-26",
    name: "Sukhoi Su-26",
    manufacturer: "Sukhoi",
    type: "Aerobatic Aircraft",
    firstFlight: "1984",
    inService: "1984",
    role: "Unlimited Aerobatics / Competition",
    country: "Russia",
    specs: {
      wingspan: "25 ft 1 in (7.8 m)",
      length: "22 ft 3 in (6.8 m)",
      maxSpeed: "292 mph (470 km/h)",
      range: "435 mi (700 km)",
      ceiling: "20,000 ft (6,096 m)",
      engines: "1x Vedeneev M-14P radial piston",
      crew: "1",
    },
    description:
      "The Sukhoi Su-26 was the Soviet Union's answer to Western aerobatic dominance, a purpose-built unlimited aerobatic monoplane that broke Western dominance at the World Aerobatic Championships when it debuted in 1984. Powered by a radial engine derived from agricultural and sport aircraft motors, it combined high power with excellent handling. Soviet pilots flying the Su-26 swept the World Championships in 1984 and the design sparked a new generation of Russian aerobatic aircraft including the Su-29 and Su-31.",
    funFact:
      "When the Su-26 appeared at the 1984 World Aerobatic Championships, Western competitors were so shocked by its performance and maneuverability that several immediately inquired about purchasing one. Its debut ended a decade of Western dominance in international aerobatics.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single radial engine in the nose",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "taildragger",
      sizeClass: "ultralight",
      era: "modern",
      distinguishingFeatures: [
        "Radial engine with distinctive cowling",
        "Mid-wing monoplane",
        "Taildragger configuration",
        "Large cockpit canopy",
        "Russian aerobatic aircraft styling",
      ],
    },
    aliases: ["Su-26M", "Su-26"],
  },

  // ============================================================
  // FLYING BOATS
  // ============================================================
  {
    id: "grumman-goose",
    name: "Grumman G-21 Goose",
    manufacturer: "Grumman",
    type: "Amphibious Flying Boat",
    firstFlight: "1937",
    inService: "1938",
    role: "Utility Transport / Amphibious Operations",
    country: "USA",
    specs: {
      wingspan: "49 ft (14.9 m)",
      length: "38 ft 6 in (11.7 m)",
      maxSpeed: "201 mph (323 km/h)",
      range: "640 mi (1,030 km)",
      ceiling: "21,300 ft (6,492 m)",
      engines: "2x Pratt & Whitney R-985 Wasp Junior piston",
      crew: "2",
      capacity: "6 passengers",
    },
    description:
      "The Grumman G-21 Goose is a classic prewar amphibious aircraft that served the US military extensively during World War II in utility and air-sea rescue roles. Its rugged construction and amphibious capability — retractable wheels plus a hull for water landings — made it ideal for remote operations and island-hopping campaigns. Postwar, many Gooses served in Alaska, the Caribbean, and other remote areas as bush transport and charter aircraft, some still flying today.",
    funFact:
      "The Grumman Goose has been in continuous commercial service for over 85 years — not by one operator but by a succession of small charter and bush operators who have kept individual examples flying in Alaska, the Bahamas, and British Columbia. Its amphibious capability makes it irreplaceable in regions without runways.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "Two radial engines on high-mounted parasol wing",
      wingPosition: "parasol",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "pre-wwii",
      distinguishingFeatures: [
        "Boat hull fuselage for water landing",
        "Two radial engines on parasol wing",
        "Retractable wheeled gear for land operations",
        "Wing-tip floats",
        "Classic art-deco aluminum construction",
      ],
    },
    aliases: ["Goose", "G-21"],
  },
  {
    id: "grumman-albatross",
    name: "Grumman HU-16 Albatross",
    manufacturer: "Grumman",
    type: "Amphibious Search and Rescue",
    firstFlight: "1947",
    inService: "1949–1983",
    role: "Search and Rescue / Maritime Patrol",
    country: "USA",
    specs: {
      wingspan: "96 ft 8 in (29.5 m)",
      length: "61 ft 3 in (18.7 m)",
      maxSpeed: "236 mph (380 km/h)",
      range: "2,850 mi (4,587 km)",
      ceiling: "21,500 ft (6,553 m)",
      engines: "2x Wright R-1820-76A Cyclone piston",
      crew: "5–6",
      capacity: "22 passengers or 12 stretcher patients",
    },
    description:
      "The Grumman HU-16 Albatross was the primary search and rescue aircraft of the US Air Force and Navy from the early 1950s through the 1970s, capable of landing on the open ocean to rescue downed pilots and shipwreck survivors. Its large hull and robust construction allowed water operations in swells up to 4–6 feet. The Albatross rescued hundreds of downed aviators during the Korean and Vietnam Wars, and served the coast guards and navies of many nations.",
    funFact:
      "The Albatross could land in open-ocean swells that would destroy most aircraft, thanks to its deep V-hull design and watertight construction. USAF crews would regularly land in 6-foot seas and higher during wartime rescues, accepting significant risk to themselves to save downed pilots.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "Two radial engines on high-mounted straight wings",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "early-jet",
      distinguishingFeatures: [
        "Deep boat hull fuselage",
        "Two large radial engines on high wings",
        "Retractable tricycle gear",
        "Wing-tip floats",
        "Distinctive large keel under hull",
      ],
    },
    aliases: ["Albatross", "HU-16"],
  },
  {
    id: "martin-mars",
    name: "Martin JRM Mars",
    manufacturer: "Glenn L. Martin Company",
    type: "Heavy Flying Boat",
    firstFlight: "1942",
    inService: "1945–2015 (as water bomber)",
    role: "Heavy Transport / Aerial Firefighting",
    country: "USA",
    specs: {
      wingspan: "200 ft (61 m)",
      length: "120 ft 3 in (36.7 m)",
      maxSpeed: "221 mph (356 km/h)",
      range: "4,945 mi (7,958 km)",
      ceiling: "14,600 ft (4,450 m)",
      engines: "4x Wright R-3350 Duplex Cyclone radial piston",
      crew: "7",
      capacity: "133 troops / 27,000 gallons of water (tanker variant)",
    },
    description:
      "The Martin Mars was one of the largest flying boats ever built, originally designed as a US Navy heavy transport. Only seven were completed; five saw naval service. Postwar, four were acquired by Canadian forestry operators and converted to aerial water bombers — the largest piston-engine water bombers ever built. Operating as the Hawaii Mars and Philippine Mars, they scooped up to 27,276 liters of water from lakes in 27 seconds while skimming the surface at 75 mph, then dropped it on forest fires. The last was retired in 2015.",
    funFact:
      "The Martin Mars water bomber could scoop 27,000 liters (7,200 gallons) of water from a lake in a single 27-second run at 75 mph — enough to fill 450 standard bathtubs. In one fire season it could protect an area the size of a small city. Firefighters considered it irreplaceable, and efforts to preserve one flying aircraft continue.",
    visual: {
      engineCount: 4,
      engineType: "piston",
      enginePlacement: "Four large radial engines on high-mounted straight wings",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "super-heavy",
      era: "wwii",
      distinguishingFeatures: [
        "Enormous boat hull",
        "Four large radial engines on high wing",
        "No wheeled landing gear (water operations only)",
        "Wing-tip floats",
        "Massive water-bomber belly probes",
      ],
    },
    aliases: ["Hawaii Mars", "Philippine Mars"],
  },
  {
    id: "beriev-be-200",
    name: "Beriev Be-200 Altair",
    manufacturer: "Beriev Aircraft Company",
    type: "Jet-Powered Amphibious Aircraft",
    firstFlight: "1998",
    inService: "2003",
    role: "Aerial Firefighting / SAR / Maritime Patrol",
    country: "Russia",
    specs: {
      wingspan: "106 ft 11 in (32.6 m)",
      length: "102 ft (31.4 m)",
      maxSpeed: "466 mph (750 km/h)",
      range: "2,237 mi (3,600 km)",
      ceiling: "26,247 ft (8,000 m)",
      engines: "2x Progress D-436TP turbofan",
      crew: "2",
      capacity: "12,000 liters water / 72 passengers (passenger variant)",
    },
    description:
      "The Beriev Be-200 Altair is the world's only jet-powered amphibious aircraft in series production, designed primarily for aerial firefighting but also used for search and rescue and maritime patrol. Unlike piston or turboprop water bombers, its turbofan engines give it speed and range comparable to regional airliners. The Be-200 can scoop 12 tonnes of water in 14 seconds while skimming a water body at 150 mph, then deliver it to a fire in minutes. It has fought fires in Russia, Europe, and the Middle East.",
    funFact:
      "The Be-200 is the fastest amphibious aircraft in operational service — its jet engines allow it to fly ferry legs between water sources and fires at airline-like speeds, then transition to a low-level water-scooping run in minutes. This speed advantage means it can make far more drops per hour than slower turboprop water bombers.",
    visual: {
      engineCount: 2,
      engineType: "turbofan",
      enginePlacement: "Two turbofans mounted high on the fuselage above the wing",
      wingPosition: "high",
      wingShape: "swept",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "large",
      era: "contemporary",
      distinguishingFeatures: [
        "Jet engines mounted high above wings to avoid water spray",
        "Boat hull with water scoops",
        "T-tail",
        "Retractable wheeled gear for land operations",
        "High-mounted swept wings",
      ],
    },
    aliases: ["Altair", "Be-200"],
  },
  {
    id: "canadair-cl-415",
    name: "Bombardier (Canadair) CL-415 SuperScooper",
    manufacturer: "Canadair / Bombardier",
    type: "Aerial Firefighting Amphibian",
    variant: "CL-415 / DHC-515",
    firstFlight: "1993",
    inService: "1994",
    role: "Aerial Firefighting",
    country: "Canada",
    specs: {
      wingspan: "93 ft 11 in (28.6 m)",
      length: "65 ft (19.8 m)",
      maxSpeed: "234 mph (376 km/h)",
      range: "1,445 mi (2,326 km)",
      ceiling: "15,000 ft (4,572 m)",
      engines: "2x Pratt & Whitney Canada PW123AF turboprop",
      crew: "2",
      capacity: "6,137 liters water",
    },
    description:
      "The Canadair CL-415 SuperScooper is the world's most widely used purpose-built aerial firefighting aircraft, combining an amphibious hull with turboprop engines optimized for scooping water from lakes and reservoirs. In 12 seconds at 145 mph, it scoops 6,137 liters of water while skimming the surface. It is operated by the firefighting agencies of France, Spain, Greece, Italy, Croatia, Canada, and others. De Havilland Canada has resumed production as the DHC-515 Firefighter to meet growing demand amid climate-driven wildfire increases.",
    funFact:
      "The CL-415 can drop its full water load in exactly 1 second — 6,137 liters of water hitting a fire zone in a single pulse creates a mist cloud with tremendous cooling and smothering effect. The timing and pattern of the drop is optimized to maximize fire suppression, not to make the biggest splash.",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "Two turboprops on high-mounted straight wings",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "t-tail",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "modern",
      distinguishingFeatures: [
        "High-mounted straight wings",
        "T-tail",
        "Boat hull with water scoops",
        "Retractable wheeled gear",
        "Distinctive red and yellow firefighting colors (typical)",
      ],
    },
    aliases: ["SuperScooper", "CL-215", "CL-415", "DHC-515"],
  },
  {
    id: "icon-a5",
    name: "ICON A5",
    manufacturer: "ICON Aircraft",
    type: "Light Sport Amphibian",
    firstFlight: "2008",
    inService: "2015",
    role: "Recreational / Light Sport Flying",
    country: "USA",
    specs: {
      wingspan: "34 ft (10.4 m)",
      length: "23 ft (7.1 m)",
      maxSpeed: "105 mph (169 km/h)",
      range: "427 mi (687 km)",
      ceiling: "15,000 ft (4,572 m)",
      engines: "1x Rotax 912 iS piston",
      crew: "2",
    },
    description:
      "The ICON A5 is a light sport amphibious aircraft designed to make flying more accessible and fun, targeted at the recreational aviation market. Its folding wings allow storage in a standard marina slip or garage, and its amphibious capability opens water takeoff and landing to a new generation of pilots. The A5 is noted for its exceptional spin resistance, achieved through a combination of carefully designed wing geometry and stall characteristics, making it one of the safest light aircraft for novice pilots.",
    funFact:
      "The ICON A5 was designed from the outset with 'fun' as a primary engineering requirement — unusual for any aircraft program. The development team used game design principles to make the aircraft intuitive and engaging, resulting in controls and avionics specifically optimized for pleasure rather than maximum performance or utility.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single pusher piston on a boom above the fuselage",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "twin-boom",
      landingGear: "retractable",
      sizeClass: "ultralight",
      era: "contemporary",
      distinguishingFeatures: [
        "Sleek sport boat hull",
        "Pusher propeller above the tail boom",
        "Folding wings",
        "Twin tail booms",
        "Retractable gear for land operations",
      ],
    },
    aliases: ["A5", "ICON A5"],
  },
  {
    id: "dornier-seastar",
    name: "Dornier Seastar",
    manufacturer: "Dornier Seawings",
    type: "Amphibious Light Transport",
    variant: "CD2",
    firstFlight: "1984",
    inService: "1990s",
    role: "Utility Amphibious Transport / Charter",
    country: "Germany",
    specs: {
      wingspan: "52 ft 6 in (16.0 m)",
      length: "41 ft (12.5 m)",
      maxSpeed: "220 mph (354 km/h)",
      range: "1,055 mi (1,698 km)",
      ceiling: "16,000 ft (4,877 m)",
      engines: "2x Pratt & Whitney Canada PT6A-135A turboprop",
      crew: "2",
      capacity: "9 passengers",
    },
    description:
      "The Dornier Seastar is a modern amphibious utility aircraft derived from the Dornier Do 24 and Dornier Wal lineage, designed for charter operations in areas with water access and limited runway infrastructure. Its composite construction and twin-turboprop arrangement in a push-pull configuration above the fuselage keep the engines well clear of water spray during water operations. Small numbers operate in resort areas, island chains, and coastal regions worldwide.",
    funFact:
      "The Dornier Seastar's distinctive push-pull tandem engine configuration — two engines mounted one behind the other on a pylon above the wing — traces its lineage back to the famous Dornier flying boats of the 1920s, including the legendary Wal (Whale) that made the first transatlantic flights.",
    visual: {
      engineCount: 2,
      engineType: "turboprop",
      enginePlacement: "Two turboprops in push-pull tandem on a pylon above the high wing",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "modern",
      distinguishingFeatures: [
        "Push-pull tandem engine arrangement on a dorsal pylon",
        "High-mounted straight wings",
        "Sponsons on fuselage sides instead of wingtip floats",
        "Composite construction",
        "Boat hull",
      ],
    },
    aliases: ["Seastar", "Dornier CD2"],
  },
];
