import { AircraftEntry } from "./types";

export const warbirdBombers: AircraftEntry[] = [
  // ============================================================
  // WWII BOMBERS / ATTACK
  // ============================================================
  {
    id: "b-17-flying-fortress",
    name: "B-17 Flying Fortress",
    manufacturer: "Boeing",
    type: "Heavy Bomber",
    variant: "G",
    firstFlight: "1935-07-28",
    inService: "1938",
    role: "Strategic heavy bomber",
    country: "USA",
    specs: {
      wingspan: "103 ft 9 in",
      length: "74 ft 4 in",
      maxSpeed: "287 mph",
      range: "2,000 mi",
      ceiling: "35,600 ft",
      engines: "4× Wright R-1820-97 Cyclone (1,200 hp each)",
      crew: "10",
    },
    description:
      "The B-17 Flying Fortress was the backbone of the USAAF daylight strategic bombing campaign over Europe. Renowned for its ability to absorb tremendous battle damage and still return home, it became one of the most iconic aircraft of World War II. The G-model introduced the distinctive chin turret to counter head-on fighter attacks.",
    funFact:
      "A B-17 named 'All American' flew back to base with its entire tail section nearly sheared off after a mid-air collision with a Bf 109 — the aircraft was so structurally sound it held together for the 90-minute flight home.",
    visual: {
      engineCount: 4,
      engineType: "piston",
      enginePlacement: "Four radial engines equally spaced along low-mounted straight wings",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "wwii",
      distinguishingFeatures: [
        "chin turret (G model)",
        "ball turret under fuselage",
        "waist gun windows",
        "four radial engines",
        "natural metal or olive drab finish",
        "tall single tail fin",
      ],
    },
    aliases: ["Flying Fortress", "B-17G", "Fort"],
  },
  {
    id: "b-24-liberator",
    name: "B-24 Liberator",
    manufacturer: "Consolidated Aircraft",
    type: "Heavy Bomber",
    firstFlight: "1939-12-29",
    inService: "1941",
    role: "Strategic heavy bomber",
    country: "USA",
    specs: {
      wingspan: "110 ft",
      length: "67 ft 8 in",
      maxSpeed: "290 mph",
      range: "2,100 mi",
      ceiling: "28,000 ft",
      engines: "4× Pratt & Whitney R-1830-65 Twin Wasp (1,200 hp each)",
      crew: "10",
    },
    description:
      "The B-24 Liberator was actually produced in greater numbers than any other American aircraft in history during WWII. With its distinctive Davis high-aspect-ratio wing and twin tail, it served in every theater of the war. Its long range made it especially valuable for anti-submarine patrols and long missions to targets in Romania and the Pacific.",
    funFact:
      "The B-24 was built in more variants and served in more different roles than any other WWII bomber — from heavy bomber to maritime patrol, tanker, transport, and photo reconnaissance.",
    visual: {
      engineCount: 4,
      engineType: "piston",
      enginePlacement: "Four radial engines along high-aspect-ratio shoulder-mounted straight wing",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "twin",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "wwii",
      distinguishingFeatures: [
        "twin tail fins",
        "deep slab-sided fuselage",
        "Davis high-aspect-ratio wing",
        "ball turret under nose",
        "tricycle gear (some variants)",
        "four radial engines",
      ],
    },
    aliases: ["Liberator", "The Boxcar", "B-24J"],
  },
  {
    id: "b-25-mitchell",
    name: "B-25 Mitchell",
    manufacturer: "North American Aviation",
    type: "Medium Bomber",
    firstFlight: "1940-08-19",
    inService: "1941",
    role: "Medium bomber / attack aircraft",
    country: "USA",
    specs: {
      wingspan: "67 ft 7 in",
      length: "52 ft 11 in",
      maxSpeed: "284 mph",
      range: "1,350 mi",
      ceiling: "24,200 ft",
      engines: "2× Wright R-2600-92 Double Cyclone (1,700 hp each)",
      crew: "5–6",
    },
    description:
      "The B-25 Mitchell was the most widely used American medium bomber of WWII, famous for the Doolittle Raid on Tokyo in April 1942. It served in every theater of the war and was prized for its versatility. The H-model was even fitted with a 75mm cannon in the nose for anti-shipping work in the Pacific.",
    funFact:
      "The B-25 is the only aircraft named after a specific person — Brigadier General Billy Mitchell, the outspoken advocate of air power who was court-martialed for his beliefs.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "Two radial engines on mid-mounted shoulder wings",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "twin",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "wwii",
      distinguishingFeatures: [
        "twin tail fins",
        "greenhouse nose (early) or solid gun nose (H/J)",
        "shoulder-mounted gull-dihedral wing",
        "two radial engines",
        "tricycle landing gear",
      ],
    },
    aliases: ["Mitchell", "B-25J", "Billy Mitchell bomber"],
  },
  {
    id: "b-26-marauder",
    name: "B-26 Marauder",
    manufacturer: "Glenn L. Martin Company",
    type: "Medium Bomber",
    firstFlight: "1940-11-25",
    inService: "1941",
    role: "Medium bomber",
    country: "USA",
    specs: {
      wingspan: "71 ft",
      length: "58 ft 3 in",
      maxSpeed: "287 mph",
      range: "1,100 mi",
      ceiling: "21,000 ft",
      engines: "2× Pratt & Whitney R-2800-43 Double Wasp (1,920 hp each)",
      crew: "7",
    },
    description:
      "The B-26 Marauder earned the nickname 'Widow Maker' early in its service life due to a high accident rate from its high wing loading and demanding handling. However, once crews were properly trained, it became one of the most accurate medium bombers of the war, eventually achieving the lowest loss rate of any WWII US bomber.",
    funFact:
      "Despite its early reputation as the 'Widow Maker,' by the end of the war the B-26 had the lowest combat loss rate of any US aircraft in the European Theater — just 0.5% per mission.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "Two large radial engines on mid-mounted straight wings",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "wwii",
      distinguishingFeatures: [
        "torpedo-shaped fuselage",
        "short stubby wings",
        "very large propellers",
        "two large radial engines",
        "single conventional tail",
        "distinctive cylindrical fuselage",
      ],
    },
    aliases: ["Marauder", "Widow Maker", "Flying Prostitute"],
  },
  {
    id: "b-29-superfortress",
    name: "B-29 Superfortress",
    manufacturer: "Boeing",
    type: "Very Heavy Bomber",
    firstFlight: "1942-09-21",
    inService: "1944",
    role: "Strategic very heavy bomber",
    country: "USA",
    specs: {
      wingspan: "141 ft 3 in",
      length: "99 ft",
      maxSpeed: "357 mph",
      range: "3,250 mi",
      ceiling: "31,850 ft",
      engines: "4× Wright R-3350-23 Duplex-Cyclone (2,200 hp each)",
      crew: "11",
    },
    description:
      "The B-29 Superfortress was the most technologically advanced bomber of WWII, featuring pressurized crew compartments, remote-controlled gun turrets, and a central fire-control system. It conducted the firebombing campaigns against Japan and delivered the two atomic bombs that ended the Pacific War. It represented a quantum leap over previous bomber designs.",
    funFact:
      "The B-29 program cost more than the Manhattan Project — approximately $3 billion (about $44 billion in 2024 dollars) versus $2 billion for the atomic bomb development.",
    visual: {
      engineCount: 4,
      engineType: "piston",
      enginePlacement: "Four large radial engines equally spaced on long low-mounted straight wings",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "wwii",
      distinguishingFeatures: [
        "elongated streamlined fuselage",
        "large bubble-canopy cockpit",
        "remote gun blisters along fuselage sides",
        "very long straight wings",
        "four large radial engines",
        "single tall fin",
        "pressurized crew tunnel between fore and aft sections",
      ],
    },
    aliases: ["Superfortress", "B-san", "The Superbomber"],
  },
  {
    id: "a-20-havoc",
    name: "A-20 Havoc",
    manufacturer: "Douglas Aircraft Company",
    type: "Light Bomber / Attack",
    variant: "G",
    firstFlight: "1938-10-26",
    inService: "1940",
    role: "Light bomber, attack aircraft, night fighter",
    country: "USA",
    specs: {
      wingspan: "61 ft 4 in",
      length: "48 ft",
      maxSpeed: "339 mph",
      range: "1,025 mi",
      ceiling: "25,000 ft",
      engines: "2× Wright R-2600-23 Double Cyclone (1,600 hp each)",
      crew: "3",
    },
    description:
      "The A-20 Havoc was a versatile twin-engine light bomber and attack aircraft that served with the USAAF, RAF (as the Boston and Havoc), and Soviet Air Forces during WWII. Its speed and agility made it effective for low-level attack missions, and it was also used extensively as a night fighter early in the war.",
    funFact:
      "The Soviet Union received over 3,000 A-20s through Lend-Lease, making it one of the most important Allied aircraft on the Eastern Front — Soviet pilots nicknamed it 'Bostonik' (little Boston).",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "Two radial engines on shoulder-mounted straight wings",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "wwii",
      distinguishingFeatures: [
        "glazed bombardier nose",
        "two radial engines",
        "sleek streamlined fuselage",
        "shoulder-mounted wings",
        "tricycle landing gear",
        "solid nose (attack variants)",
      ],
    },
    aliases: ["Havoc", "Boston", "DB-7"],
  },
  {
    id: "a-26-invader",
    name: "A-26 Invader",
    manufacturer: "Douglas Aircraft Company",
    type: "Attack / Light Bomber",
    firstFlight: "1942-07-10",
    inService: "1944",
    role: "Attack bomber",
    country: "USA",
    specs: {
      wingspan: "70 ft",
      length: "50 ft",
      maxSpeed: "355 mph",
      range: "1,400 mi",
      ceiling: "22,100 ft",
      engines: "2× Pratt & Whitney R-2800-79 Double Wasp (2,000 hp each)",
      crew: "3",
    },
    description:
      "The A-26 Invader entered service late in WWII and went on to serve in Korea and Vietnam, making it one of the longest-serving combat aircraft in US history. The B-26B variant with the solid eight-gun nose was devastatingly effective for strafing attacks, while the glass-nose variant carried a bombardier.",
    funFact:
      "The A-26 Invader holds the distinction of being the only American aircraft to see combat in WWII, Korea, and Vietnam — a span of nearly 30 years of active combat service.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "Two large radial engines on low-mounted straight wings",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "wwii",
      distinguishingFeatures: [
        "solid eight-gun nose (B model) or glazed nose (A model)",
        "two large radial engines",
        "low-mounted straight wings",
        "sleek streamlined fuselage",
        "tricycle landing gear",
        "gun turret on top of fuselage",
      ],
    },
    aliases: ["Invader", "B-26 Invader", "On Mark Marksman"],
  },
  {
    id: "sbd-dauntless",
    name: "SBD Dauntless",
    manufacturer: "Douglas Aircraft Company",
    type: "Dive Bomber",
    firstFlight: "1935",
    inService: "1940",
    role: "Carrier-based scout and dive bomber",
    country: "USA",
    specs: {
      wingspan: "41 ft 6 in",
      length: "33 ft",
      maxSpeed: "255 mph",
      range: "1,115 mi",
      ceiling: "25,530 ft",
      engines: "1× Wright R-1820-60 Cyclone (1,000 hp)",
      crew: "2",
    },
    description:
      "The SBD Dauntless dive bomber was the most important US naval aircraft of the early Pacific War. It sank more Japanese shipping than any other Allied aircraft and was the decisive weapon at Midway, where SBDs sank four Japanese fleet carriers in a single day, turning the tide of the Pacific War.",
    funFact:
      "At the Battle of Midway, SBD Dauntlesses sank four Japanese fleet carriers — Akagi, Kaga, Soryu, and Hiryu — in a single day, achieving what no other naval engagement had ever accomplished.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single radial engine in nose",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "wwii",
      distinguishingFeatures: [
        "perforated dive flaps on trailing edge",
        "single radial engine",
        "low-mounted straight wings",
        "rear gunner position",
        "bomb crutch under fuselage",
        "greenhouse cockpit canopy",
      ],
    },
    aliases: ["Dauntless", "Slow But Deadly", "SBD"],
  },
  {
    id: "tbf-avenger",
    name: "TBF/TBM Avenger",
    manufacturer: "Grumman / General Motors",
    type: "Torpedo Bomber",
    firstFlight: "1941-08-07",
    inService: "1942",
    role: "Carrier-based torpedo bomber",
    country: "USA",
    specs: {
      wingspan: "54 ft 2 in",
      length: "40 ft",
      maxSpeed: "275 mph",
      range: "1,000 mi",
      ceiling: "30,100 ft",
      engines: "1× Wright R-2600-20 Double Cyclone (1,900 hp)",
      crew: "3",
    },
    description:
      "The TBF Avenger was the standard US Navy torpedo bomber from 1942 onwards. Its cavernous internal weapons bay could carry a full-size torpedo, bombs, or depth charges. It served with distinction throughout the Pacific and was also used extensively for anti-submarine patrol. Notable as the aircraft type in which future President George H.W. Bush was shot down.",
    funFact:
      "Future US President George H.W. Bush was piloting an Avenger when it was shot down over the Pacific in 1944. He was the only one of his three-man crew to survive.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single large radial engine in nose",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "wwii",
      distinguishingFeatures: [
        "very large bulbous fuselage for torpedo bay",
        "greenhouse canopy over three crew",
        "single large radial engine",
        "folding wings for carrier storage",
        "rear-facing turret",
        "ventral gun position",
      ],
    },
    aliases: ["Avenger", "TBM", "Turkey"],
  },
  {
    id: "avro-lancaster",
    name: "Avro Lancaster",
    manufacturer: "Avro",
    type: "Heavy Bomber",
    firstFlight: "1941-01-09",
    inService: "1942",
    role: "Strategic heavy bomber",
    country: "United Kingdom",
    specs: {
      wingspan: "102 ft",
      length: "69 ft 6 in",
      maxSpeed: "282 mph",
      range: "2,530 mi",
      ceiling: "24,500 ft",
      engines: "4× Rolls-Royce Merlin XX (1,280 hp each)",
      crew: "7",
    },
    description:
      "The Avro Lancaster was the primary heavy bomber of RAF Bomber Command's night offensive against Germany. With its massive bomb bay capable of carrying the 22,000-lb Grand Slam earthquake bomb, it was also used for precision attacks including the famous Dambusters raid. It dropped more bombs than any other Allied aircraft in the European Theater.",
    funFact:
      "The Lancaster's bomb bay was so large it could carry the 22,000-lb Grand Slam bomb — the largest non-nuclear bomb of WWII — which could penetrate deep underground before exploding to create an 'earthquake' effect.",
    visual: {
      engineCount: 4,
      engineType: "piston",
      enginePlacement: "Four inline liquid-cooled engines equally spaced on mid-mounted straight wings",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "twin",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "wwii",
      distinguishingFeatures: [
        "twin oval tail fins",
        "four Merlin inline engines",
        "long straight mid-mounted wings",
        "prominent dorsal turret",
        "tail turret with four guns",
        "very deep fuselage bomb bay",
      ],
    },
    aliases: ["Lanc", "Lancaster bomber", "The Lanc"],
  },
  {
    id: "de-havilland-mosquito",
    name: "de Havilland Mosquito",
    manufacturer: "de Havilland",
    type: "Multi-role Combat Aircraft",
    variant: "B Mk IV",
    firstFlight: "1940-11-25",
    inService: "1941",
    role: "Bomber, night fighter, photo reconnaissance, pathfinder",
    country: "United Kingdom",
    specs: {
      wingspan: "54 ft 2 in",
      length: "44 ft 6 in",
      maxSpeed: "415 mph",
      range: "1,860 mi",
      ceiling: "36,000 ft",
      engines: "2× Rolls-Royce Merlin 25 (1,620 hp each)",
      crew: "2",
    },
    description:
      "The de Havilland Mosquito was a revolutionary aircraft built primarily of wood, allowing mass production without straining strategic metal supplies. So fast it could outrun most German fighters, it excelled in every role it was assigned — precision bombing, night fighting, pathfinding, and photo reconnaissance. It was one of the most versatile aircraft of the entire war.",
    funFact:
      "The Mosquito was built almost entirely of wood (spruce, balsa, and birwood plywood), yet it was faster than contemporary all-metal fighters. Its wooden construction also made it difficult to detect on early radar systems.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "Two Merlin inline engines on shoulder-mounted straight wings",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "wwii",
      distinguishingFeatures: [
        "wooden construction",
        "streamlined teardrop fuselage",
        "two Merlin inline engines",
        "mid-mounted straight wings",
        "distinctive pointed nose",
        "bubble canopy",
        "tricycle landing gear",
      ],
    },
    aliases: ["Mossie", "The Wooden Wonder", "The Termite's Dream"],
  },
  {
    id: "junkers-ju-87-stuka",
    name: "Junkers Ju 87 Stuka",
    manufacturer: "Junkers",
    type: "Dive Bomber",
    variant: "B-2",
    firstFlight: "1935-09-17",
    inService: "1936",
    role: "Dive bomber, close air support",
    country: "Germany",
    specs: {
      wingspan: "45 ft 3 in",
      length: "37 ft 9 in",
      maxSpeed: "238 mph",
      range: "373 mi",
      ceiling: "23,915 ft",
      engines: "1× Junkers Jumo 211Da (1,200 hp)",
      crew: "2",
    },
    description:
      "The Junkers Ju 87 Stuka dive bomber became a symbol of Blitzkrieg warfare, using its Jericho Trumpet wind-driven sirens to create a terrifying screaming sound during dives. It was devastatingly effective when air superiority was assured, but highly vulnerable to fighters. Hans-Ulrich Rudel flew over 2,530 combat missions in the Stuka, making him the most decorated German serviceman of the war.",
    funFact:
      "The Stuka's 'Jericho Trumpet' sirens were not weapons — they were wind-driven propellers attached to the landing gear legs specifically to create a terrifying shriek during dive attacks to demoralize troops on the ground.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single inline engine in nose",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "light",
      era: "wwii",
      distinguishingFeatures: [
        "inverted gull wings",
        "fixed spatted undercarriage with wheel fairings",
        "Jericho Trumpet sirens on landing gear",
        "single inline engine",
        "large bomb crutch under fuselage",
        "greenhouse canopy",
        "prominent chin radiator",
      ],
    },
    aliases: ["Stuka", "Ju 87", "Jericho Trumpet"],
  },
  {
    id: "junkers-ju-88",
    name: "Junkers Ju 88",
    manufacturer: "Junkers",
    type: "Medium Bomber / Multi-role",
    firstFlight: "1936-12-21",
    inService: "1939",
    role: "Medium bomber, dive bomber, night fighter, torpedo bomber",
    country: "Germany",
    specs: {
      wingspan: "65 ft 10 in",
      length: "47 ft 3 in",
      maxSpeed: "292 mph",
      range: "1,696 mi",
      ceiling: "26,900 ft",
      engines: "2× Junkers Jumo 211J (1,340 hp each)",
      crew: "4",
    },
    description:
      "The Junkers Ju 88 was arguably the most versatile German aircraft of WWII, serving as a medium bomber, dive bomber, torpedo bomber, night fighter, day fighter, and reconnaissance aircraft. It equipped more Luftwaffe units than any other aircraft and proved adaptable to virtually every combat role the Germans required.",
    funFact:
      "The Ju 88 was used in 'Mistel' (mistletoe) composite aircraft formations, where an unmanned Ju 88 packed with explosives was attached below a fighter aircraft and guided toward targets before being released.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "Two inline engines on mid-mounted straight wings",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "wwii",
      distinguishingFeatures: [
        "glazed beetle-eye nose",
        "two inline engines",
        "dive brakes under wings",
        "narrow fuselage",
        "prominent gondola under nose",
        "two-spar wing",
      ],
    },
    aliases: ["Ju 88", "The Maid of All Work"],
  },
  {
    id: "heinkel-he-111",
    name: "Heinkel He 111",
    manufacturer: "Heinkel",
    type: "Medium Bomber",
    variant: "H-6",
    firstFlight: "1935-02-24",
    inService: "1936",
    role: "Medium bomber",
    country: "Germany",
    specs: {
      wingspan: "74 ft 2 in",
      length: "53 ft 9 in",
      maxSpeed: "252 mph",
      range: "1,212 mi",
      ceiling: "21,980 ft",
      engines: "2× Junkers Jumo 211F-2 (1,300 hp each)",
      crew: "5",
    },
    description:
      "The Heinkel He 111 was the primary German medium bomber of WWII, initially disguised as a civilian transport. Its distinctive elliptical wings and fully glazed asymmetric 'greenhouse' nose are instantly recognizable. It was the main bomber during the Battle of Britain and the London Blitz but became obsolete as Allied fighters improved.",
    funFact:
      "The He 111 was initially developed in secret as a 'high-speed commercial transport' for Lufthansa to circumvent the Treaty of Versailles restrictions on German military aircraft.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "Two inline engines on distinctive elliptical mid-mounted wings",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "wwii",
      distinguishingFeatures: [
        "distinctive elliptical wings",
        "fully glazed offset greenhouse nose",
        "two inline engines",
        "asymmetric cockpit canopy",
        "ventral gondola",
        "step in the nose glazing",
      ],
    },
    aliases: ["He 111", "Schnurbart (Moustache)"],
  },
  {
    id: "short-sunderland",
    name: "Short Sunderland",
    manufacturer: "Short Brothers",
    type: "Maritime Patrol Flying Boat",
    firstFlight: "1937-10-16",
    inService: "1938",
    role: "Maritime patrol, anti-submarine, long-range transport",
    country: "United Kingdom",
    specs: {
      wingspan: "112 ft 9 in",
      length: "85 ft 4 in",
      maxSpeed: "213 mph",
      range: "2,900 mi",
      ceiling: "17,900 ft",
      engines: "4× Bristol Pegasus XVIII (1,065 hp each)",
      crew: "13",
    },
    description:
      "The Short Sunderland was a large four-engine flying boat developed from the Short Empire civil flying boat. It was one of the most capable Allied maritime patrol aircraft of WWII, carrying depth charges, bombs, and extensive defensive armament. German submariners dubbed it the 'Flying Porcupine' for its heavy defensive firepower.",
    funFact:
      "German U-boat crews nicknamed the Sunderland the 'Flying Porcupine' because it bristled with so many defensive guns — up to 18 machine guns in various positions — that attacking it was extremely dangerous.",
    visual: {
      engineCount: 4,
      engineType: "piston",
      enginePlacement: "Four radial engines on high-mounted parasol-style wings above the flying boat hull",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "heavy",
      era: "wwii",
      distinguishingFeatures: [
        "flying boat hull",
        "sponsons for water stability",
        "four radial engines on high-mounted wings",
        "two-deck interior",
        "retractable bow gun turret",
        "tail turret",
        "large single vertical tail fin",
      ],
    },
    aliases: ["Flying Porcupine", "Sunderland"],
  },
  {
    id: "fairey-swordfish",
    name: "Fairey Swordfish",
    manufacturer: "Fairey Aviation Company",
    type: "Torpedo Bomber / Biplane",
    variant: "Mk I",
    firstFlight: "1934-04-17",
    inService: "1936",
    role: "Torpedo bomber, anti-submarine, mine-laying",
    country: "United Kingdom",
    specs: {
      wingspan: "45 ft 6 in",
      length: "35 ft 8 in",
      maxSpeed: "138 mph",
      range: "546 mi",
      ceiling: "10,700 ft",
      engines: "1× Bristol Pegasus XXX (750 hp)",
      crew: "3",
    },
    description:
      "The Fairey Swordfish was already obsolete when WWII began, yet it outlasted the aircraft meant to replace it and achieved remarkable combat successes. It crippled the Italian fleet at Taranto, damaged the Bismarck's steering, and sank numerous U-boats. Its slow speed and fabric construction actually made it resistant to early radar-fused shells, as they couldn't trigger fast enough.",
    funFact:
      "The Swordfish's slow speed of 138 mph was actually an advantage when attacking the German battleship Bismarck — the ship's antiaircraft guns couldn't track it slowly enough, and several torpedoes hit their mark, damaging her steering.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single radial engine in nose of biplane",
      wingPosition: "biplane",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "light",
      era: "wwii",
      distinguishingFeatures: [
        "biplane configuration",
        "open cockpit (early models)",
        "fixed spatted undercarriage",
        "torpedo or bomb under fuselage",
        "fabric-covered structure",
        "large single radial engine",
        "interplane struts and bracing wires",
      ],
    },
    aliases: ["Stringbag", "Swordfish"],
  },
  {
    id: "pby-catalina",
    name: "PBY Catalina",
    manufacturer: "Consolidated Aircraft",
    type: "Maritime Patrol Flying Boat / Amphibian",
    firstFlight: "1935-03-28",
    inService: "1936",
    role: "Maritime patrol, search and rescue, anti-submarine, torpedo bomber",
    country: "USA",
    specs: {
      wingspan: "104 ft",
      length: "63 ft 10 in",
      maxSpeed: "196 mph",
      range: "2,520 mi",
      ceiling: "13,000 ft",
      engines: "2× Pratt & Whitney R-1830-92 Twin Wasp (1,200 hp each)",
      crew: "8–9",
    },
    description:
      "The PBY Catalina was the most widely used patrol flying boat of WWII and one of the most successful military flying boats ever built. With its distinctive parasol wing mounted atop a pylon above the hull, it excelled at long-range maritime patrol and search-and-rescue missions. It spotted the Japanese fleet at Midway and participated in the first US torpedo attacks of the Pacific War.",
    funFact:
      "A PBY Catalina was the aircraft that spotted the Japanese fleet heading toward Midway on June 3, 1942, giving the US Navy the critical warning that allowed them to prepare their ambush.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "Two radial engines mounted side-by-side on a pylon above the parasol wing",
      wingPosition: "parasol",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "wwii",
      distinguishingFeatures: [
        "parasol wing mounted on pylon above fuselage",
        "two engines side-by-side in tandem nacelle on wing",
        "flying boat / amphibian hull",
        "distinctive blister gun positions on sides",
        "retractable wingtip floats",
        "large twin tail",
        "bow gun position",
      ],
    },
    aliases: ["Catalina", "Cat", "Black Cat", "Dumbo"],
  },
  {
    id: "mitsubishi-g4m-betty",
    name: "Mitsubishi G4M Betty",
    manufacturer: "Mitsubishi",
    type: "Medium Bomber",
    firstFlight: "1939-10-23",
    inService: "1941",
    role: "Land-based medium bomber, torpedo bomber",
    country: "Japan",
    specs: {
      wingspan: "82 ft",
      length: "65 ft 7 in",
      maxSpeed: "272 mph",
      range: "3,749 mi",
      ceiling: "29,365 ft",
      engines: "2× Mitsubishi MK4A Kasei 11 (1,530 hp each)",
      crew: "7",
    },
    description:
      "The Mitsubishi G4M was Japan's primary land-based naval bomber throughout WWII. Designed for extreme range, it sacrificed armor and self-sealing fuel tanks, making it extremely vulnerable to combat damage — American pilots nicknamed it the 'Flying Lighter' because it caught fire so easily. Despite this, it sank HMS Prince of Wales and HMS Repulse in 1941.",
    funFact:
      "American pilots called the G4M the 'Flying Lighter' or 'One-Shot Lighter' because its unprotected fuel tanks caught fire so readily. The crew even nicknamed it 'the Flying Cigar' for the same reason.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "Two radial engines on mid-mounted straight wings",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "wwii",
      distinguishingFeatures: [
        "distinctive oval fuselage cross-section",
        "large blister gun positions",
        "two radial engines",
        "rounded nose with glazing",
        "tail gun position",
        "very clean aerodynamic lines",
      ],
    },
    aliases: ["Betty", "Flying Lighter", "Flying Cigar"],
  },
  {
    id: "aichi-d3a-val",
    name: "Aichi D3A Val",
    manufacturer: "Aichi",
    type: "Carrier Dive Bomber",
    firstFlight: "1938",
    inService: "1940",
    role: "Carrier-based dive bomber",
    country: "Japan",
    specs: {
      wingspan: "47 ft 2 in",
      length: "33 ft 5 in",
      maxSpeed: "242 mph",
      range: "915 mi",
      ceiling: "30,050 ft",
      engines: "1× Mitsubishi Kinsei 44 (1,000 hp)",
      crew: "2",
    },
    description:
      "The Aichi D3A Val was the Imperial Japanese Navy's primary carrier-based dive bomber at the start of WWII. It participated in the attack on Pearl Harbor and sank more Allied warships than any other Axis aircraft. Though already being replaced by 1944, it remained in service throughout the war and was used extensively in kamikaze attacks.",
    funFact:
      "The D3A Val sank more Allied naval vessels than any other Axis aircraft in the war, including the cruisers HMS Cornwall and HMS Dorsetshire, which it sank in less than 20 minutes.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single radial engine in nose",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "light",
      era: "wwii",
      distinguishingFeatures: [
        "fixed spatted undercarriage",
        "elliptical wings",
        "dive brakes under wings",
        "single radial engine",
        "rounded fuselage",
        "rear gunner position",
        "bomb crutch under fuselage",
      ],
    },
    aliases: ["Val", "D3A", "Type 99 Carrier Bomber"],
  },
  {
    id: "nakajima-b5n-kate",
    name: "Nakajima B5N Kate",
    manufacturer: "Nakajima",
    type: "Torpedo Bomber",
    firstFlight: "1937",
    inService: "1938",
    role: "Carrier-based torpedo and level bomber",
    country: "Japan",
    specs: {
      wingspan: "50 ft 11 in",
      length: "33 ft 10 in",
      maxSpeed: "235 mph",
      range: "1,237 mi",
      ceiling: "27,100 ft",
      engines: "1× Nakajima NK1B Sakae 11 (970 hp)",
      crew: "3",
    },
    description:
      "The Nakajima B5N Kate was the most capable torpedo bomber in the world when it entered service, featuring an advanced retractable undercarriage and internal weapons bay at a time when most contemporaries still had fixed gear and external bomb loads. Kate torpedo bombers delivered the fatal blows to Pearl Harbor's battleships and sank USS Lexington, Yorktown, Wasp, and Hornet.",
    funFact:
      "B5N Kates delivered the torpedo hits that sank more US aircraft carriers than any other weapon in history — they were responsible for the mortal damage to USS Lexington, Yorktown, Wasp, and Hornet.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single radial engine in nose",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "wwii",
      distinguishingFeatures: [
        "clean low-wing monoplane",
        "retractable undercarriage",
        "three-seat open cockpit arrangement",
        "single radial engine",
        "torpedo or bomb under fuselage",
        "folding wings for carrier storage",
      ],
    },
    aliases: ["Kate", "B5N", "Type 97 Carrier Attack Bomber"],
  },
  {
    id: "ilyushin-il-2-sturmovik",
    name: "Ilyushin Il-2 Sturmovik",
    manufacturer: "Ilyushin",
    type: "Ground Attack / Assault Aircraft",
    firstFlight: "1939-10-02",
    inService: "1941",
    role: "Ground attack, close air support, anti-tank",
    country: "USSR",
    specs: {
      wingspan: "47 ft 11 in",
      length: "38 ft 3 in",
      maxSpeed: "257 mph",
      range: "497 mi",
      ceiling: "19,685 ft",
      engines: "1× Mikulin AM-38F (1,720 hp)",
      crew: "2",
    },
    description:
      "The Ilyushin Il-2 Sturmovik was the most produced military aircraft in history, with over 36,000 built. Stalin famously declared it 'as necessary to the Red Army as air and bread.' Featuring a heavily armored 'bathtub' protecting the crew and engine, it was devastatingly effective against German tanks and infantry, earning the nickname 'The Flying Tank' from Soviet troops and 'Black Death' from the Germans.",
    funFact:
      "The Il-2 was produced in greater numbers than any other military aircraft in history — over 36,000 were built. When production slowed, Stalin sent an angry telegram to the factory directors: 'The Red Army needs the Il-2 like it needs air and bread.'",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single inline engine in nose",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "wwii",
      distinguishingFeatures: [
        "armored bathtub enclosing engine and crew",
        "large single inline engine",
        "low-mounted straight wings",
        "rear gunner position (two-seat version)",
        "underwing rocket rails",
        "distinctive hump over armored cockpit",
        "very sturdy angular appearance",
      ],
    },
    aliases: ["Sturmovik", "Flying Tank", "Black Death", "Ilyusha"],
  },
  {
    id: "petlyakov-pe-2",
    name: "Petlyakov Pe-2",
    manufacturer: "Petlyakov",
    type: "Dive Bomber / Fast Bomber",
    firstFlight: "1939-12-22",
    inService: "1941",
    role: "Dive bomber, tactical bomber, reconnaissance",
    country: "USSR",
    specs: {
      wingspan: "56 ft 3 in",
      length: "41 ft 7 in",
      maxSpeed: "360 mph",
      range: "932 mi",
      ceiling: "28,870 ft",
      engines: "2× Klimov VK-105PF (1,260 hp each)",
      crew: "3",
    },
    description:
      "The Petlyakov Pe-2 was the Soviet Union's most important tactical bomber of WWII. Originally designed as a high-altitude twin-engine fighter, it was redesigned as a dive bomber after the outbreak of war. Fast enough to outrun many Luftwaffe fighters, it became the standard Soviet light bomber and served in massive numbers throughout the Eastern Front.",
    funFact:
      "The Pe-2 was designed by Vladimir Petlyakov while he was imprisoned in a Soviet design 'sharashka' — a secret research facility for imprisoned engineers. His early release depended on completing the aircraft.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "Two inline engines on twin-boom or conventional mid-mounted wings",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "twin",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "wwii",
      distinguishingFeatures: [
        "twin tail fins",
        "twin inline engines",
        "distinctive stepped cockpit",
        "ventral gondola",
        "dive brakes",
        "streamlined Soviet design aesthetic",
      ],
    },
    aliases: ["Pe-2", "Peshka (little pawn)"],
  },

  // ============================================================
  // VINTAGE TRANSPORT
  // ============================================================
  {
    id: "douglas-dc3-c47",
    name: "Douglas DC-3 / C-47 Skytrain",
    manufacturer: "Douglas Aircraft Company",
    type: "Transport / Airliner",
    variant: "C-47A",
    firstFlight: "1935-12-17",
    inService: "1936",
    role: "Transport, airliner, paratroop carrier, medical evacuation",
    country: "USA",
    specs: {
      wingspan: "95 ft",
      length: "64 ft 5 in",
      maxSpeed: "224 mph",
      range: "1,513 mi",
      ceiling: "26,400 ft",
      engines: "2× Pratt & Whitney R-1830-90C Twin Wasp (1,200 hp each)",
      crew: "3–4",
      capacity: "28 passengers or 6,000 lb cargo",
    },
    description:
      "The Douglas DC-3/C-47 is arguably the most significant transport aircraft ever built. It transformed air travel, made airlines profitable, and its military version — the C-47 Skytrain — dropped paratroopers on D-Day, Arnhem, and across every theater of WWII. Eisenhower named it one of the decisive weapons of the war. Hundreds remain airworthy today, 90 years after first flight.",
    funFact:
      "General Eisenhower named the C-47 one of the four weapons most decisive to Allied victory in WWII (alongside the bazooka, jeep, and atomic bomb). More than 10,000 were built, and hundreds still fly today.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "Two radial engines on low-mounted tapered wings",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "taildragger",
      sizeClass: "medium",
      era: "wwii",
      distinguishingFeatures: [
        "taildragger configuration",
        "two radial engines on low-mounted wings",
        "distinctive rounded fuselage",
        "large cargo door (C-47)",
        "swept vertical tail",
        "oval cabin windows",
        "graceful tapered wings",
      ],
    },
    aliases: ["Gooney Bird", "Dakota", "Skytrain", "Skytrooper", "Spooky (AC-47)"],
  },
  {
    id: "lockheed-constellation",
    name: "Lockheed Constellation / C-121",
    manufacturer: "Lockheed",
    type: "Airliner / Transport",
    variant: "L-749",
    firstFlight: "1943-01-09",
    inService: "1944",
    role: "Long-range airliner, military transport, airborne early warning",
    country: "USA",
    specs: {
      wingspan: "123 ft",
      length: "116 ft 2 in",
      maxSpeed: "377 mph",
      range: "5,400 mi",
      ceiling: "24,000 ft",
      engines: "4× Wright R-3350-DA3 Turbo Compound (3,400 hp each)",
      crew: "5",
      capacity: "81–109 passengers",
    },
    description:
      "The Lockheed Constellation, known affectionately as the 'Connie,' is widely considered the most beautiful airliner ever built. Its distinctive triple-tail and dolphin-shaped fuselage (required to clear the tail's field of view) set it apart from every other aircraft. It was the premier intercontinental airliner of the late 1940s and 1950s before jets made piston airliners obsolete.",
    funFact:
      "Howard Hughes, who helped design the Constellation as a TWA specification, flew the prototype from Burbank to Washington D.C. in 6 hours 57 minutes — a transcontinental record at the time.",
    visual: {
      engineCount: 4,
      engineType: "piston",
      enginePlacement: "Four large radial engines equally spaced along low-mounted wings",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "triple",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "early-jet",
      distinguishingFeatures: [
        "distinctive triple tail fins",
        "dolphin-shaped curved fuselage",
        "four large radial engines",
        "graceful upward curve of fuselage",
        "elegant streamlined nose",
        "circular cabin windows",
        "low-mounted tapered wings",
      ],
    },
    aliases: ["Connie", "Triple Tail", "The Most Beautiful Airliner"],
  },
  {
    id: "douglas-dc4-c54",
    name: "Douglas DC-4 / C-54 Skymaster",
    manufacturer: "Douglas Aircraft Company",
    type: "Airliner / Transport",
    firstFlight: "1942-02-14",
    inService: "1942",
    role: "Long-range transport, airliner",
    country: "USA",
    specs: {
      wingspan: "117 ft 6 in",
      length: "93 ft 11 in",
      maxSpeed: "275 mph",
      range: "4,250 mi",
      ceiling: "22,300 ft",
      engines: "4× Pratt & Whitney R-2000-7 Twin Wasp (1,350 hp each)",
      crew: "4",
      capacity: "44–86 passengers",
    },
    description:
      "The Douglas DC-4/C-54 Skymaster was the first truly practical four-engine American airliner, introducing the tricycle undercarriage that became standard for all subsequent airliners. As the C-54 Skymaster, it was the primary long-range transport of the USAAF and saw extensive service in WWII and during the Berlin Airlift.",
    funFact:
      "President Franklin D. Roosevelt used a heavily modified C-54 called 'Sacred Cow' as the first dedicated presidential aircraft, featuring a special elevator to accommodate his wheelchair.",
    visual: {
      engineCount: 4,
      engineType: "piston",
      enginePlacement: "Four radial engines equally spaced on low-mounted straight wings",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "wwii",
      distinguishingFeatures: [
        "four radial engines on low-mounted wings",
        "tricycle landing gear",
        "unpressurized round fuselage",
        "single large vertical tail",
        "clean uncluttered lines",
        "circular porthole-style windows",
      ],
    },
    aliases: ["Skymaster", "DC-4", "C-54"],
  },
  {
    id: "douglas-dc6",
    name: "Douglas DC-6",
    manufacturer: "Douglas Aircraft Company",
    type: "Airliner / Transport",
    firstFlight: "1946-02-15",
    inService: "1947",
    role: "Long-range airliner, cargo transport",
    country: "USA",
    specs: {
      wingspan: "117 ft 6 in",
      length: "100 ft 7 in",
      maxSpeed: "360 mph",
      range: "3,860 mi",
      ceiling: "25,000 ft",
      engines: "4× Pratt & Whitney R-2800-CB17 Double Wasp (2,400 hp each)",
      crew: "4",
      capacity: "52–102 passengers",
    },
    description:
      "The Douglas DC-6 was a pressurized, longer-range development of the DC-4, entering service in 1947 to compete with Lockheed's Constellation. It was one of the most reliable and successful piston airliners ever built, serving major airlines worldwide and remaining in cargo service to this day in some remote locations.",
    funFact:
      "The DC-6 remains in active commercial service in parts of Alaska and remote regions, more than 75 years after its first flight — a testament to its rugged construction and reliability.",
    visual: {
      engineCount: 4,
      engineType: "piston",
      enginePlacement: "Four radial engines equally spaced on low-mounted wings",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "early-jet",
      distinguishingFeatures: [
        "four large radial engines",
        "pressurized round fuselage",
        "low-mounted tapered wings",
        "single large vertical tail",
        "tricycle landing gear",
        "rectangular cabin windows",
      ],
    },
    aliases: ["DC-6", "DC-6B"],
  },
  {
    id: "douglas-dc7",
    name: "Douglas DC-7",
    manufacturer: "Douglas Aircraft Company",
    type: "Airliner",
    variant: "DC-7C Seven Seas",
    firstFlight: "1953-05-18",
    inService: "1953",
    role: "Long-range intercontinental airliner",
    country: "USA",
    specs: {
      wingspan: "127 ft 6 in",
      length: "112 ft 3 in",
      maxSpeed: "406 mph",
      range: "5,635 mi",
      ceiling: "25,000 ft",
      engines: "4× Wright R-3350-EA1 Turbo Compound (3,400 hp each)",
      crew: "4",
      capacity: "60–105 passengers",
    },
    description:
      "The Douglas DC-7C 'Seven Seas' was the ultimate expression of the piston-engined airliner, the first to offer truly non-stop transatlantic service in both directions. It represented the pinnacle of Douglas's piston transport line, but arrived just as the jet age was beginning. Its complex Wright Turbo-Compound engines were notoriously difficult to maintain.",
    funFact:
      "The DC-7C Seven Seas was the first aircraft capable of non-stop westbound transatlantic service against prevailing headwinds — but it was rendered obsolete within a year by the Boeing 707 jet.",
    visual: {
      engineCount: 4,
      engineType: "piston",
      enginePlacement: "Four large turbo-compound engines on low-mounted tapered wings",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "heavy",
      era: "early-jet",
      distinguishingFeatures: [
        "four large turbo-compound engines",
        "slightly taller fin than DC-6",
        "low-mounted tapered wings",
        "pressurized fuselage",
        "tricycle landing gear",
        "larger overall than DC-6",
      ],
    },
    aliases: ["DC-7C", "Seven Seas", "The Last Connie Fighter"],
  },
  {
    id: "curtiss-c46-commando",
    name: "Curtiss C-46 Commando",
    manufacturer: "Curtiss-Wright",
    type: "Military Transport",
    firstFlight: "1940-03-26",
    inService: "1942",
    role: "Military cargo and troop transport",
    country: "USA",
    specs: {
      wingspan: "108 ft 1 in",
      length: "76 ft 4 in",
      maxSpeed: "269 mph",
      range: "1,200 mi",
      ceiling: "27,600 ft",
      engines: "2× Pratt & Whitney R-2800-51 Double Wasp (2,000 hp each)",
      crew: "4",
      capacity: "40 troops or 10,000 lb cargo",
    },
    description:
      "The Curtiss C-46 Commando was the largest twin-engine transport aircraft of WWII and was particularly important for flying supplies 'over the Hump' — the Himalayas — from India to China. Its powerful engines and pressurized fuselage made it better suited than the C-47 for the extreme altitudes required on this route.",
    funFact:
      "The C-46 flew the legendary 'Hump' route over the Himalayas between India and China, operating at altitudes up to 25,000 feet without pressurization in some cases, earning its pilots the informal 'Hump Pilot' distinction.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "Two large radial engines on low-mounted straight wings",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "wwii",
      distinguishingFeatures: [
        "distinctive figure-8 or double-bubble fuselage cross-section",
        "two very large radial engines",
        "low-mounted straight wings",
        "large single vertical tail",
        "tricycle landing gear",
        "large cargo door on left side",
      ],
    },
    aliases: ["Commando", "The Whale", "Plumber's Nightmare"],
  },
  {
    id: "ford-trimotor",
    name: "Ford Trimotor",
    manufacturer: "Ford Motor Company",
    type: "Airliner / Transport",
    variant: "4-AT",
    firstFlight: "1926-06-11",
    inService: "1926",
    role: "Passenger airliner, utility transport",
    country: "USA",
    specs: {
      wingspan: "74 ft",
      length: "49 ft 10 in",
      maxSpeed: "130 mph",
      range: "570 mi",
      ceiling: "16,500 ft",
      engines: "3× Pratt & Whitney Wasp (450 hp each)",
      crew: "2",
      capacity: "11–13 passengers",
    },
    description:
      "The Ford Trimotor, nicknamed the 'Tin Goose,' was America's first successful all-metal airliner and the aircraft that began scheduled air service across the United States. Its corrugated duralumin skin was innovative for its time, and its three-engine layout was considered the safest configuration available, giving passengers confidence to fly for the first time.",
    funFact:
      "A Ford Trimotor was the first aircraft to fly over the South Pole, flown by Richard Byrd and pilot Bernt Balchen on November 28–29, 1929.",
    visual: {
      engineCount: 3,
      engineType: "piston",
      enginePlacement: "One radial engine in the nose plus one radial engine on each wing",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "medium",
      era: "pre-wwii",
      distinguishingFeatures: [
        "corrugated duralumin skin",
        "three radial engines (one nose, one each wing)",
        "high-mounted straight wings",
        "fixed tailwheel gear",
        "distinctive boxy corrugated fuselage",
        "round cabin windows",
        "wing engine nacelles below wing",
      ],
    },
    aliases: ["Tin Goose", "Tin Lizzie of the Air", "The Trimotor"],
  },
  {
    id: "junkers-ju-52",
    name: "Junkers Ju 52/3m",
    manufacturer: "Junkers",
    type: "Airliner / Military Transport",
    firstFlight: "1932-04-07",
    inService: "1932",
    role: "Passenger airliner, military transport, paratroop carrier",
    country: "Germany",
    specs: {
      wingspan: "95 ft 10 in",
      length: "62 ft",
      maxSpeed: "178 mph",
      range: "808 mi",
      ceiling: "18,040 ft",
      engines: "3× BMW 132T-2 (830 hp each)",
      crew: "3",
      capacity: "17 passengers or 18 paratroopers",
    },
    description:
      "The Junkers Ju 52 was Germany's workhorse transport aircraft of the 1930s and WWII, serving as an airliner for Lufthansa and the primary transport and paratroop carrier of the Luftwaffe. Like the Ford Trimotor, it featured corrugated duralumin skin and a three-engine layout. It participated in every major German airborne operation including Crete and the Eastern Front.",
    funFact:
      "The Ju 52 was so beloved in Germany that it was nicknamed 'Tante Ju' (Aunt Ju) and 'Iron Annie' — it served with Lufthansa into the 1950s and continued flying in some countries well into the 1980s.",
    visual: {
      engineCount: 3,
      engineType: "piston",
      enginePlacement: "One radial engine in nose plus one on each wing",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "medium",
      era: "pre-wwii",
      distinguishingFeatures: [
        "corrugated duralumin skin",
        "three radial engines",
        "low-mounted straight wings",
        "fixed tailwheel undercarriage",
        "distinctive angular corrugated fuselage",
        "large single vertical tail",
        "wing-mounted engine nacelles",
      ],
    },
    aliases: ["Tante Ju", "Iron Annie", "Auntie Ju"],
  },
  {
    id: "boeing-314-clipper",
    name: "Boeing 314 Clipper",
    manufacturer: "Boeing",
    type: "Flying Boat Airliner",
    firstFlight: "1938-06-07",
    inService: "1939",
    role: "Transatlantic and transpacific passenger flying boat",
    country: "USA",
    specs: {
      wingspan: "152 ft",
      length: "106 ft",
      maxSpeed: "199 mph",
      range: "3,685 mi",
      ceiling: "13,400 ft",
      engines: "4× Wright GR-2600 Double Cyclone (1,600 hp each)",
      crew: "10",
      capacity: "68–74 passengers (day), 36 in berths (night)",
    },
    description:
      "The Boeing 314 Clipper was the largest, most luxurious flying boat ever built for commercial service, offering sleeping berths, a dining room, and lounge areas for passengers crossing the Atlantic and Pacific. Pan American's 'Clippers' were the only way to fly transoceanic routes in the late 1930s. During WWII, they were commandeered to transport VIPs including Winston Churchill and President Roosevelt.",
    funFact:
      "The Boeing 314 had a dressing room, separate men's and women's bathrooms, a dining lounge, and sleeping berths — it was essentially a flying ocean liner. A one-way ticket from New York to Southampton cost $375 (over $7,000 today).",
    visual: {
      engineCount: 4,
      engineType: "piston",
      enginePlacement: "Four radial engines on parasol-style shoulder-mounted wings",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "heavy",
      era: "pre-wwii",
      distinguishingFeatures: [
        "massive flying boat hull",
        "large sponsons for water stability",
        "four large radial engines on high-mounted wings",
        "double-deck interior",
        "wide slab-sided fuselage",
        "large single vertical tail",
        "retractable wing wingtip floats",
      ],
    },
    aliases: ["Clipper", "Pan Am Clipper", "Flying Boat"],
  },
  {
    id: "hughes-h4-hercules",
    name: "Hughes H-4 Hercules",
    manufacturer: "Hughes Aircraft",
    type: "Flying Boat",
    firstFlight: "1947-11-02",
    inService: "Never entered service",
    role: "Heavy transport flying boat",
    country: "USA",
    specs: {
      wingspan: "319 ft 11 in",
      length: "218 ft 8 in",
      maxSpeed: "250 mph",
      range: "3,000 mi",
      ceiling: "20,900 ft",
      engines: "8× Pratt & Whitney R-4360 Wasp Major (3,000 hp each)",
      crew: "3",
      capacity: "750 troops or 150,000 lb cargo",
    },
    description:
      "The Hughes H-4 Hercules, nicknamed the 'Spruce Goose' (a name Howard Hughes despised), remains the largest flying boat and largest wooden aircraft ever built. Constructed primarily of birch (not spruce) due to WWII wartime restrictions on aluminum, it flew only once — a one-mile low-altitude hop over Long Beach Harbor in November 1947. It now resides in the Evergreen Aviation Museum in Oregon.",
    funFact:
      "Howard Hughes hated the nickname 'Spruce Goose' — the aircraft is actually built primarily of birch, not spruce. Hughes reportedly stormed out of a congressional hearing when a senator used the nickname.",
    visual: {
      engineCount: 8,
      engineType: "piston",
      enginePlacement: "Eight massive radial engines equally spaced along high-mounted straight wings",
      wingPosition: "high",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "fixed",
      sizeClass: "super-heavy",
      era: "wwii",
      distinguishingFeatures: [
        "eight massive radial engines",
        "enormous flying boat hull",
        "longest wingspan of any aircraft ever built",
        "wooden birch laminate construction",
        "massive single vertical tail",
        "large sponsons for water stability",
        "high-mounted straight wing",
        "distinctive overlapping propeller arcs",
      ],
    },
    aliases: ["Spruce Goose", "Flying Lumberyard", "H-4 Hercules"],
  },
  {
    id: "antonov-an-2",
    name: "Antonov An-2",
    manufacturer: "Antonov",
    type: "Utility Biplane",
    firstFlight: "1947-08-31",
    inService: "1948",
    role: "Agricultural, utility, parachute training, cargo",
    country: "USSR",
    specs: {
      wingspan: "59 ft 8 in (upper), 46 ft 9 in (lower)",
      length: "41 ft 9 in",
      maxSpeed: "160 mph",
      range: "560 mi",
      ceiling: "14,760 ft",
      engines: "1× Shvetsov ASh-62IR (1,000 hp)",
      crew: "1–2",
      capacity: "12 passengers or 2,800 lb cargo",
    },
    description:
      "The Antonov An-2 is the world's largest single-engine biplane still in production (in China as the Shijiazhuang Y-5). It holds the world record as the only aircraft type to remain in production for over 70 years. The An-2's remarkable short-field performance — it can fly as slowly as 30 mph and can even fly backwards in a strong headwind — makes it ideal for remote bush operations.",
    funFact:
      "The An-2 has no stall speed listed in its flight manual. The manual states: 'If the engine quits in instrument conditions, the pilot should reduce power to idle, maintain level attitude, and the aircraft will descend at about 5 mph below stall.' It simply mushed rather than stalled.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single large radial engine in nose of upper wing biplane",
      wingPosition: "biplane",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "taildragger",
      sizeClass: "light",
      era: "cold-war",
      distinguishingFeatures: [
        "biplane with unequal span wings",
        "single large radial engine",
        "taildragger configuration",
        "fabric-covered control surfaces",
        "large enclosed cockpit",
        "round cabin windows",
        "very short take-off run",
        "upper wing wider than lower",
      ],
    },
    aliases: ["Annushka", "Annie", "Colt (NATO)", "Kukuruznik (Corn Cutter)", "Y-5"],
  },

  // ============================================================
  // PRE-WWII / TRAINERS / WWI ERA
  // ============================================================
  {
    id: "wright-flyer",
    name: "Wright Flyer",
    manufacturer: "Wright Brothers",
    type: "Experimental Aircraft",
    firstFlight: "1903-12-17",
    inService: "1903",
    role: "First powered heavier-than-air aircraft",
    country: "USA",
    specs: {
      wingspan: "40 ft 4 in",
      length: "21 ft 1 in",
      maxSpeed: "30 mph",
      range: "0.02 mi (longest flight)",
      ceiling: "10 ft",
      engines: "1× Wright custom inline 4-cylinder (12 hp)",
      crew: "1",
    },
    description:
      "The Wright Flyer made the first successful powered, sustained, and controlled heavier-than-air flight on December 17, 1903 at Kitty Hawk, North Carolina. Orville Wright piloted the first flight of 12 seconds covering 120 feet. The fourth and final flight of the day, piloted by Wilbur, covered 852 feet in 59 seconds. The aircraft was damaged by wind later that day and never flew again.",
    funFact:
      "The Wright Flyer's total flight time on December 17, 1903 — all four flights combined — was less than 2 minutes. The longest single flight covered 852 feet, shorter than the wingspan of a modern Boeing 747.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single inline engine mounted between wings driving two pusher propellers via chains",
      wingPosition: "biplane",
      wingShape: "straight",
      tailType: "no-tail",
      landingGear: "skids",
      sizeClass: "ultralight",
      era: "pre-wwii",
      distinguishingFeatures: [
        "canard foreplane",
        "biplane configuration",
        "twin pusher propellers",
        "chain drive from engine to propellers",
        "wooden skid landing gear",
        "no enclosure for pilot",
        "wire-braced wing warping control",
        "hip cradle for lateral control",
      ],
    },
    aliases: ["Kitty Hawk Flyer", "1903 Flyer"],
  },
  {
    id: "sopwith-camel",
    name: "Sopwith Camel",
    manufacturer: "Sopwith Aviation Company",
    type: "Fighter",
    variant: "F.1",
    firstFlight: "1916-12-22",
    inService: "1917",
    role: "Single-seat fighter",
    country: "United Kingdom",
    specs: {
      wingspan: "28 ft",
      length: "18 ft 9 in",
      maxSpeed: "115 mph",
      range: "300 mi",
      ceiling: "19,000 ft",
      engines: "1× Clerget 9B rotary (130 hp)",
      crew: "1",
    },
    description:
      "The Sopwith Camel was the most successful Allied fighter of WWI, credited with shooting down 1,294 enemy aircraft — more than any other Allied aircraft. Its name came from the hump-shaped fairing over the twin Vickers guns. The rotary engine's gyroscopic effect made it extremely agile in a right turn but dangerous to inexperienced pilots, who were often killed in accidents.",
    funFact:
      "The Sopwith Camel killed more of its own pilots than the enemy did during training — its rotary engine's powerful gyroscopic torque made it so responsive to right turns that novice pilots frequently crashed. Expert pilots exploited this to make the Camel nearly impossible to follow in combat.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single rotary engine in nose",
      wingPosition: "biplane",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "taildragger",
      sizeClass: "ultralight",
      era: "pre-wwii",
      distinguishingFeatures: [
        "biplane with equal-span wings",
        "distinctive hump fairing over twin Vickers guns",
        "rotary engine with cowling",
        "short nose due to compact rotary",
        "wire-braced wings",
        "open cockpit",
        "rounded fuselage",
      ],
    },
    aliases: ["Camel", "The Hump", "F.1 Camel"],
  },
  {
    id: "fokker-dr1",
    name: "Fokker Dr.I",
    manufacturer: "Fokker Flugzeugwerke",
      type: "Fighter",
    firstFlight: "1917-06-05",
    inService: "1917",
    role: "Single-seat triplane fighter",
    country: "Germany",
    specs: {
      wingspan: "23 ft 7 in",
      length: "18 ft 11 in",
      maxSpeed: "115 mph",
      range: "185 mi",
      ceiling: "20,000 ft",
      engines: "1× Oberursel Ur.II rotary (110 hp)",
      crew: "1",
    },
    description:
      "The Fokker Dr.I triplane is the most famous WWI aircraft due to its association with Manfred von Richthofen, the Red Baron, who flew a red-painted version when he scored his last 19 victories. The triplane configuration gave exceptional maneuverability and climb rate but poor top speed. It was in service only briefly before being replaced by the superior Fokker D.VII.",
    funFact:
      "The Red Baron, Manfred von Richthofen, achieved his final 19 victories in the Fokker Dr.I — he was shot down and killed on April 21, 1918, but it is still debated whether he was killed by ground fire or by Canadian ace Roy Brown.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single rotary engine in nose of triplane",
      wingPosition: "biplane",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "taildragger",
      sizeClass: "ultralight",
      era: "pre-wwii",
      distinguishingFeatures: [
        "triplane configuration (three wings)",
        "no wing bracing wires (cantilevered wings)",
        "single rotary engine",
        "small wingspan",
        "twin Spandau machine guns",
        "open cockpit",
        "distinctive tailskid",
        "angular rudder shape",
      ],
    },
    aliases: ["Dreidecker", "Dr.I Triplane", "Red Baron's plane"],
  },
  {
    id: "spad-s-xiii",
    name: "SPAD S.XIII",
    manufacturer: "Société Pour L'Aviation et ses Dérivés (SPAD)",
    type: "Fighter",
    firstFlight: "1917-04-04",
    inService: "1917",
    role: "Single-seat biplane fighter",
    country: "France",
    specs: {
      wingspan: "26 ft 4 in",
      length: "20 ft 8 in",
      maxSpeed: "138 mph",
      range: "186 mi",
      ceiling: "21,800 ft",
      engines: "1× Hispano-Suiza 8Ca inline (235 hp)",
      crew: "1",
    },
    description:
      "The SPAD S.XIII was the premier Allied fighter of 1917-1918, combining high speed and structural strength with excellent diving ability. Unlike the rotary-engined Nieuports and Camels, the SPAD's inline engine gave it a higher top speed and the ability to dive steeply without risk of overspeeding. It was flown by Eddie Rickenbacker and many of the war's top Allied aces.",
    funFact:
      "Eddie Rickenbacker, America's top ace with 26 victories, flew the SPAD S.XIII. He kept his aircraft so well maintained that he once dove a SPAD from 22,000 feet — well beyond its certified limits — to escape German fighters.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single inline engine in nose",
      wingPosition: "biplane",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "taildragger",
      sizeClass: "ultralight",
      era: "pre-wwii",
      distinguishingFeatures: [
        "biplane with unequal span wings",
        "inline liquid-cooled engine",
        "distinctive radiator on nose",
        "twin Vickers machine guns",
        "open cockpit",
        "wire-braced wings",
        "squarish fuselage cross-section",
      ],
    },
    aliases: ["SPAD XIII", "Spad fighter"],
  },
  {
    id: "de-havilland-dh82-tiger-moth",
    name: "de Havilland DH.82 Tiger Moth",
    manufacturer: "de Havilland",
    type: "Trainer Biplane",
    firstFlight: "1931-10-26",
    inService: "1932",
    role: "Primary trainer, aerobatic trainer",
    country: "United Kingdom",
    specs: {
      wingspan: "29 ft 4 in",
      length: "23 ft 11 in",
      maxSpeed: "109 mph",
      range: "302 mi",
      ceiling: "13,600 ft",
      engines: "1× de Havilland Gipsy Major (130 hp)",
      crew: "2",
    },
    description:
      "The de Havilland Tiger Moth was the primary trainer of the Royal Air Force from 1932 and trained the majority of Commonwealth pilots during WWII under the Empire Air Training Scheme. Simple, forgiving, and aerobatic, it produced tens of thousands of pilots. It remains one of the most common vintage aircraft flying today and is used for aerobatic displays and pleasure flying.",
    funFact:
      "Over 8,800 Tiger Moths were built, and they trained more than 50,000 Commonwealth pilots during WWII. Hundreds are still flying today, nearly 90 years after their introduction.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single inverted inline engine in nose",
      wingPosition: "biplane",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "taildragger",
      sizeClass: "ultralight",
      era: "pre-wwii",
      distinguishingFeatures: [
        "biplane with staggered wings",
        "open tandem cockpits",
        "inverted inline engine",
        "swept upper wing leading edge",
        "distinctive interplane struts",
        "light fabric-covered structure",
        "tailskid undercarriage",
      ],
    },
    aliases: ["Tiger Moth", "DH.82", "Tiggie"],
  },
  {
    id: "boeing-stearman-pt17",
    name: "Boeing Stearman PT-17 Kaydet",
    manufacturer: "Stearman / Boeing",
    type: "Trainer Biplane",
    firstFlight: "1934",
    inService: "1936",
    role: "Primary flight trainer",
    country: "USA",
    specs: {
      wingspan: "32 ft 2 in",
      length: "24 ft 3 in",
      maxSpeed: "124 mph",
      range: "505 mi",
      ceiling: "11,200 ft",
      engines: "1× Continental R-670-5 radial (220 hp)",
      crew: "2",
    },
    description:
      "The Boeing Stearman Kaydet was the primary trainer of the US Army Air Corps and Navy from the late 1930s through WWII. Over 10,000 were built, and virtually every American military pilot of WWII had their first flight training in a Stearman. The colorful yellow and blue aircraft became so iconic they are simply called 'the Stearman' by warbird enthusiasts.",
    funFact:
      "Nearly every American military aviator who flew in WWII — from fighter pilots to bomber crews — first soloed in a Stearman PT-17. Today, thousands of Stearmans perform at airshows doing wing-walking and aerobatics.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single radial engine in nose of biplane",
      wingPosition: "biplane",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "taildragger",
      sizeClass: "ultralight",
      era: "pre-wwii",
      distinguishingFeatures: [
        "equal-span biplane wings",
        "single radial engine with exposed cylinders",
        "open tandem cockpits",
        "colorful yellow and blue paint scheme",
        "fixed spatted undercarriage",
        "N-shaped interplane struts",
        "fabric-covered fuselage and wings",
      ],
    },
    aliases: ["Stearman", "Kaydet", "Yellow Peril", "PT-17"],
  },
  {
    id: "north-american-t6-texan",
    name: "North American T-6 Texan",
    manufacturer: "North American Aviation",
    type: "Advanced Trainer",
    variant: "T-6G",
    firstFlight: "1935-04-01",
    inService: "1938",
    role: "Advanced pilot trainer",
    country: "USA",
    specs: {
      wingspan: "42 ft",
      length: "29 ft 6 in",
      maxSpeed: "208 mph",
      range: "870 mi",
      ceiling: "24,200 ft",
      engines: "1× Pratt & Whitney R-1340-AN-1 Wasp (600 hp)",
      crew: "2",
    },
    description:
      "The North American T-6 Texan was the standard advanced trainer for Allied pilots during WWII, used by the United States, Britain (as the Harvard), Canada, and many other nations. It bridged the gap between primary trainers like the Stearman and front-line combat aircraft, introducing student pilots to retractable gear, variable-pitch propellers, and high-performance flying.",
    funFact:
      "The T-6 Texan's distinctive whistling sound — produced by the grooves in its propeller — made it easily recognizable in the air. It was so widely used that it trained pilots who went on to fly virtually every major combat aircraft of WWII.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "Single large radial engine in nose",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "wwii",
      distinguishingFeatures: [
        "single large radial engine",
        "tandem enclosed cockpit under long greenhouse canopy",
        "low-mounted wings",
        "retractable taildragger gear",
        "distinctive round engine cowling",
        "grooved propeller creating whistling sound",
        "aluminum monocoque construction",
      ],
    },
    aliases: ["Texan", "Harvard (RAF/RCAF)", "SNJ (Navy)", "T-6"],
  },
];
