import { AircraftEntry } from "./types";

export const warbirdFighters: AircraftEntry[] = [
  {
    id: "p51-mustang",
    name: "P-51 Mustang",
    manufacturer: "North American Aviation",
    type: "Fighter",
    variant: "P-51D",
    firstFlight: "1940-10-26",
    inService: "1942",
    role: "Long-range escort fighter / air superiority",
    country: "USA",
    specs: {
      wingspan: "37 ft 0 in (11.28 m)",
      length: "32 ft 3 in (9.83 m)",
      maxSpeed: "437 mph (703 km/h)",
      range: "1,650 mi (2,655 km) with drop tanks",
      ceiling: "41,900 ft (12,800 m)",
      engines: "1× Packard V-1650-7 (Merlin) V-12, 1,490 hp",
      crew: "1",
    },
    description:
      "The P-51 Mustang is widely regarded as the finest American fighter of World War II. Originally designed to a British specification in just 117 days, it transformed into a war-winner once fitted with the Rolls-Royce Merlin engine. Its laminar-flow wing gave it exceptional range and speed, allowing it to escort bombers deep into Germany — a capability no other Allied fighter could match. The Mustang turned the tide of the daylight bombing campaign over Europe.",
    funFact:
      "The P-51's fuselage was designed so quickly that North American's chief designer Edgar Schmued reportedly completed the initial layout in just 24 hours.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted inline V-12",
      wingPosition: "low",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "wwii",
      distinguishingFeatures: [
        "distinctive teardrop bubble canopy on D model",
        "scoop-style ventral radiator intake under fuselage",
        "clean elliptical-trapezoidal laminar-flow wing",
        "razorback fuselage spine on early models",
        "Malcolm hood or bubble canopy",
      ],
    },
    aliases: ["Mustang", "Pony", "Spam Can", "P-51D"],
  },
  {
    id: "p47-thunderbolt",
    name: "P-47 Thunderbolt",
    manufacturer: "Republic Aviation",
    type: "Fighter / Fighter-bomber",
    variant: "P-47D",
    firstFlight: "1941-05-06",
    inService: "1942",
    role: "Air superiority fighter / ground attack",
    country: "USA",
    specs: {
      wingspan: "40 ft 9 in (12.43 m)",
      length: "36 ft 1 in (11.0 m)",
      maxSpeed: "426 mph (686 km/h)",
      range: "800 mi (1,290 km) with drop tanks",
      ceiling: "42,000 ft (12,800 m)",
      engines: "1× Pratt & Whitney R-2800-59 Double Wasp radial, 2,535 hp",
      crew: "1",
    },
    description:
      "The P-47 Thunderbolt was the heaviest and largest single-engine, single-seat fighter of World War II. Nicknamed 'The Jug' for its portly shape, it was powered by the massive Pratt & Whitney R-2800 Double Wasp radial engine and proved extraordinarily rugged. It excelled as both an air superiority fighter at high altitude and a devastating ground attack aircraft, capable of absorbing enormous battle damage and still returning home.",
    funFact:
      "The P-47 was so large and heavy that Luftwaffe pilots who first encountered it assumed it must be a twin-engine aircraft. One pilot reportedly radioed in a report of 'two-engine Thunderbolts.'",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted radial",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "wwii",
      distinguishingFeatures: [
        "very large barrel-shaped fuselage housing R-2800 radial",
        "broad chord elliptical wings",
        "bubble canopy on late D and M models",
        "razorback spine on early production",
        "four .50-cal machine guns per wing",
        "turbo-supercharger hump behind cockpit",
      ],
    },
    aliases: ["Jug", "Thunderbolt", "T-Bolt", "Republic Thunderbolt"],
  },
  {
    id: "p38-lightning",
    name: "P-38 Lightning",
    manufacturer: "Lockheed Corporation",
    type: "Heavy fighter / interceptor",
    variant: "P-38L",
    firstFlight: "1939-01-27",
    inService: "1941",
    role: "Long-range escort / interceptor / photo reconnaissance",
    country: "USA",
    specs: {
      wingspan: "52 ft 0 in (15.85 m)",
      length: "37 ft 10 in (11.53 m)",
      maxSpeed: "414 mph (667 km/h)",
      range: "1,300 mi (2,092 km)",
      ceiling: "44,000 ft (13,400 m)",
      engines: "2× Allison V-1710-111/113 V-12, 1,600 hp each",
      crew: "1",
    },
    description:
      "The P-38 Lightning was America's only twin-engine, twin-boom fighter to see widespread service in World War II. Its distinctive silhouette — a central nacelle housing the cockpit flanked by two engine booms connected by a tail — made it instantly recognizable. It served in every theater of the war and became the most successful American ace aircraft in the Pacific, where its range was invaluable. Ace Richard Bong scored all 40 of his kills in a P-38.",
    funFact:
      "The P-38 was responsible for the most consequential fighter intercept of the war — on April 18, 1943, sixteen P-38s flew a 600-mile round trip to ambush and shoot down the transport carrying Admiral Isoroku Yamamoto, Japan's commander-in-chief.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "twin booms, one engine per boom",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "twin-boom",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "wwii",
      distinguishingFeatures: [
        "twin-boom configuration with central nacelle",
        "counter-rotating propellers eliminating torque",
        "distinctive twin tail fins connecting booms",
        "nose-mounted cannon and machine guns concentrated at center",
        "turbosuperchargers mounted atop each boom",
      ],
    },
    aliases: ["Lightning", "Fork-tailed Devil", "Two-tailed Monster"],
  },
  {
    id: "p40-warhawk",
    name: "P-40 Warhawk",
    manufacturer: "Curtiss-Wright",
    type: "Fighter / ground attack",
    variant: "P-40N Warhawk",
    firstFlight: "1938-10-14",
    inService: "1940",
    role: "Air superiority fighter / close air support",
    country: "USA",
    specs: {
      wingspan: "37 ft 4 in (11.38 m)",
      length: "33 ft 4 in (10.16 m)",
      maxSpeed: "378 mph (608 km/h)",
      range: "750 mi (1,207 km)",
      ceiling: "38,000 ft (11,600 m)",
      engines: "1× Allison V-1710-81 V-12, 1,360 hp",
      crew: "1",
    },
    description:
      "The P-40 Warhawk was one of the most important American fighters at the outbreak of World War II, serving in North Africa, China, and the Pacific. Though outclassed at high altitude by German and Japanese opponents, it was fast at low and medium altitudes, rugged, and effective when flown with appropriate tactics. The Flying Tigers of the American Volunteer Group in China made the P-40 famous with its shark-mouth nose art.",
    funFact:
      "The iconic shark-mouth nose art on Flying Tiger P-40s was inspired by a photograph of a RAF No. 112 Squadron Tomahawk in North Africa. AVG pilots adopted it enthusiastically, and it became one of the most recognized aircraft markings of World War II.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted inline V-12",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "wwii",
      distinguishingFeatures: [
        "large chin radiator inlet giving shark-like nose",
        "long pointed nose from inline engine",
        "three exhaust stacks per side on fuselage",
        "straight leading edge wing",
        "shark mouth nose art on Flying Tiger examples",
      ],
    },
    aliases: ["Warhawk", "Tomahawk", "Kittyhawk", "Flying Tiger"],
  },
  {
    id: "f4u-corsair",
    name: "F4U Corsair",
    manufacturer: "Chance Vought",
    type: "Carrier-based fighter",
    variant: "F4U-1D",
    firstFlight: "1940-05-29",
    inService: "1943",
    role: "Fleet defense fighter / close air support",
    country: "USA",
    specs: {
      wingspan: "41 ft 0 in (12.5 m)",
      length: "33 ft 4 in (10.16 m)",
      maxSpeed: "446 mph (718 km/h)",
      range: "1,015 mi (1,634 km)",
      ceiling: "36,900 ft (11,247 m)",
      engines: "1× Pratt & Whitney R-2800-18W Double Wasp radial, 2,250 hp",
      crew: "1",
    },
    description:
      "The F4U Corsair was built around the most powerful aircraft engine available in 1938 — the Pratt & Whitney R-2800 Double Wasp — requiring a large-diameter three-bladed propeller that necessitated the iconic inverted gull wing to provide adequate ground clearance. Initially rejected by the Navy for carrier operations due to visibility and bounce landing issues, it became the most capable carrier fighter of the Pacific war and served into the Korean War.",
    funFact:
      "Japanese pilots nicknamed the Corsair 'Whistling Death' because of the distinctive sound its wing-root air intakes made at high speed. Its kill ratio of 11:1 against Japanese aircraft remains one of the highest of World War II.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted radial",
      wingPosition: "low",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "wwii",
      distinguishingFeatures: [
        "inverted gull wing — most distinctive feature",
        "very large four-blade propeller",
        "oil cooler intake scoops in wing leading edges",
        "long nose obscuring forward visibility on ground",
        "rounded wingtips that fold upward for carrier storage",
        "birdcage canopy on early variants, bubble on later",
      ],
    },
    aliases: ["Corsair", "Whistling Death", "Ensign Eliminator", "U-Bird"],
  },
  {
    id: "f6f-hellcat",
    name: "F6F Hellcat",
    manufacturer: "Grumman Aircraft Engineering",
    type: "Carrier-based fighter",
    variant: "F6F-5",
    firstFlight: "1942-06-26",
    inService: "1943",
    role: "Fleet air defense / carrier escort fighter",
    country: "USA",
    specs: {
      wingspan: "42 ft 10 in (13.06 m)",
      length: "33 ft 7 in (10.24 m)",
      maxSpeed: "380 mph (612 km/h)",
      range: "945 mi (1,521 km)",
      ceiling: "37,300 ft (11,370 m)",
      engines: "1× Pratt & Whitney R-2800-10W Double Wasp radial, 2,000 hp",
      crew: "1",
    },
    description:
      "The F6F Hellcat was designed specifically to defeat the Mitsubishi Zero, incorporating lessons learned from early Pacific combat. Grumman's engineers produced a larger, tougher, more heavily armed aircraft that overwhelmed Japanese fighters with pilot armor, self-sealing tanks, and six .50-caliber machine guns. It became the dominant carrier fighter of the Pacific war, accounting for 5,163 of the 6,477 enemy aircraft destroyed by Navy pilots — a 19:1 kill ratio.",
    funFact:
      "Grumman designed and built the Hellcat in only 18 months from concept to first flight, an extraordinary feat for such a complex aircraft. The company's reputation for fast, rugged aircraft earned it the nickname 'Grumman Iron Works.'",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted radial",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "wwii",
      distinguishingFeatures: [
        "large squarish fuselage with pronounced humped spine",
        "wide-track undercarriage folding inward for carrier stowage",
        "wide chord wings folding upward",
        "massive R-2800 radial cowling",
        "six .50-cal guns, three per wing",
        "pronounced chin oil cooler",
      ],
    },
    aliases: ["Hellcat", "Grumman Cat", "Iron Works Fighter"],
  },
  {
    id: "p39-airacobra",
    name: "P-39 Airacobra",
    manufacturer: "Bell Aircraft Corporation",
    type: "Fighter",
    variant: "P-39Q",
    firstFlight: "1938-04-06",
    inService: "1941",
    role: "Air superiority fighter / ground attack",
    country: "USA",
    specs: {
      wingspan: "34 ft 0 in (10.36 m)",
      length: "30 ft 2 in (9.19 m)",
      maxSpeed: "385 mph (620 km/h)",
      range: "650 mi (1,046 km)",
      ceiling: "35,000 ft (10,700 m)",
      engines: "1× Allison V-1710-85 V-12, 1,200 hp",
      crew: "1",
    },
    description:
      "The P-39 Airacobra was a revolutionary design for its time, placing the Allison V-1710 engine behind the pilot in a mid-fuselage position, with an extended driveshaft running forward to the nose-mounted propeller. This allowed a 37mm cannon to fire through the propeller hub. Though largely ineffective in US and British service at altitude due to the lack of a supercharger, the Soviets received nearly 5,000 and used them brilliantly in low-altitude ground attack and dogfighting.",
    funFact:
      "Soviet ace Alexander Pokryshkin, the second-highest Allied ace of the war with 59 confirmed kills, flew the P-39 Airacobra for most of his career. He reportedly preferred it over Soviet-built fighters and became a master of the 'Cobra' maneuver.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "mid-fuselage behind cockpit, driveshaft to nose",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "wwii",
      distinguishingFeatures: [
        "automobile-style car door entry on each side",
        "engine mounted behind pilot — unique mid-engine layout",
        "tricycle landing gear — unusual for WWII fighters",
        "37mm cannon firing through propeller hub",
        "relatively clean nose without large radial cowling",
      ],
    },
    aliases: ["Airacobra", "Cobra", "P-39"],
  },
  {
    id: "p61-black-widow",
    name: "P-61 Black Widow",
    manufacturer: "Northrop Corporation",
    type: "Night fighter",
    variant: "P-61B",
    firstFlight: "1942-05-26",
    inService: "1944",
    role: "Night fighter / intruder",
    country: "USA",
    specs: {
      wingspan: "66 ft 0 in (20.12 m)",
      length: "49 ft 7 in (15.11 m)",
      maxSpeed: "366 mph (589 km/h)",
      range: "1,350 mi (2,172 km)",
      ceiling: "33,100 ft (10,090 m)",
      engines: "2× Pratt & Whitney R-2800-65 Double Wasp radial, 2,250 hp each",
      crew: "3",
    },
    description:
      "The P-61 Black Widow was the first American aircraft designed from the outset as a radar-equipped night fighter. It incorporated the SCR-720 AI (airborne intercept) radar in its distinctive nose pod, and the twin-boom layout — similar to the P-38 — provided a stable platform for the radar operator and gunner positions. Though large and not especially fast, it was effective in the night intercept role and served in both Pacific and European theaters.",
    funFact:
      "A P-61 scored one of the last aerial victories of World War II. On August 14, 1945 — the very night Japan announced its surrender — a P-61 named 'Lady in the Dark' shot down a Japanese aircraft, making it one of the final kills of the entire war.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "twin booms, one radial engine per boom",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "twin-boom",
      landingGear: "retractable",
      sizeClass: "large",
      era: "wwii",
      distinguishingFeatures: [
        "twin-boom layout with central nacelle, similar to P-38 but much larger",
        "SCR-720 radar nose radome",
        "dorsal four-.50-cal barbette turret",
        "twin vertical tails connecting booms",
        "three-crew layout: pilot, radar operator, gunner",
        "jet-black overall finish for night operations",
      ],
    },
    aliases: ["Black Widow", "Lady in the Dark"],
  },
  {
    id: "f4f-wildcat",
    name: "F4F Wildcat",
    manufacturer: "Grumman Aircraft Engineering",
    type: "Carrier-based fighter",
    variant: "F4F-4",
    firstFlight: "1937-09-02",
    inService: "1940",
    role: "Fleet air defense fighter",
    country: "USA",
    specs: {
      wingspan: "38 ft 0 in (11.58 m)",
      length: "28 ft 9 in (8.76 m)",
      maxSpeed: "318 mph (512 km/h)",
      range: "845 mi (1,360 km)",
      ceiling: "34,900 ft (10,600 m)",
      engines: "1× Pratt & Whitney R-1830-86 Twin Wasp radial, 1,200 hp",
      crew: "1",
    },
    description:
      "The F4F Wildcat was the primary US Navy carrier fighter at the outbreak of World War II and bore the brunt of early Pacific air combat despite being outclassed by the Japanese Zero in climb rate, maneuverability, and range. American pilots survived by developing the Thach Weave — a defensive tactic — and by exploiting the Wildcat's superior firepower, armor, and self-sealing tanks. It served until replaced by the Hellcat in 1943.",
    funFact:
      "The Wildcat used a manually cranked landing gear — the pilot had to turn a hand crank 29 times to fully retract the wheels. Forgetting to crank could result in a wheels-up landing, and more than a few pilots lost count during combat maneuvering.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted radial",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "wwii",
      distinguishingFeatures: [
        "squared-off wingtips",
        "narrow-track landing gear retracting into fuselage sides",
        "stubby, barrel-shaped fuselage",
        "prominent radial engine cowling",
        "small cockpit with framed canopy",
        "distinctive upward-folding sto-wing panels",
      ],
    },
    aliases: ["Wildcat", "Martlet (British designation)", "F4F"],
  },
  {
    id: "f8f-bearcat",
    name: "F8F Bearcat",
    manufacturer: "Grumman Aircraft Engineering",
    type: "Carrier-based fighter",
    variant: "F8F-1",
    firstFlight: "1944-08-21",
    inService: "1945",
    role: "Fleet air defense interceptor",
    country: "USA",
    specs: {
      wingspan: "35 ft 10 in (10.92 m)",
      length: "28 ft 3 in (8.61 m)",
      maxSpeed: "421 mph (678 km/h)",
      range: "865 mi (1,392 km)",
      ceiling: "38,700 ft (11,796 m)",
      engines: "1× Pratt & Whitney R-2800-34W Double Wasp radial, 2,100 hp",
      crew: "1",
    },
    description:
      "The F8F Bearcat was Grumman's attempt to build the smallest, lightest airframe possible around the powerful R-2800 Double Wasp engine. The result was a compact, powerful fighter with an exceptional rate of climb — at 4,800 ft/min it was the fastest-climbing piston fighter in US Navy service. Arriving too late for World War II combat, it served postwar and was exported to France, where it saw extensive combat in Indochina.",
    funFact:
      "A modified Bearcat named 'Rare Bear' held the piston-engine aircraft speed record of 528 mph (850 km/h) set in 1989, demonstrating just how potent the basic design was. It remains a dominant force in unlimited class air racing.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted radial",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "wwii",
      distinguishingFeatures: [
        "very compact fuselage barely larger than the engine cowling",
        "bubble canopy giving excellent visibility",
        "wide-track undercarriage",
        "small overall size — the smallest Grumman carrier fighter",
        "pronounced engine bulge behind cowling",
        "clipped rounded wingtips",
      ],
    },
    aliases: ["Bearcat", "Grumman Bear"],
  },
  {
    id: "spitfire",
    name: "Supermarine Spitfire",
    manufacturer: "Supermarine (Vickers-Armstrong)",
    type: "Fighter / interceptor",
    variant: "Spitfire Mk IX",
    firstFlight: "1936-03-05",
    inService: "1938",
    role: "Air superiority fighter / interceptor",
    country: "United Kingdom",
    specs: {
      wingspan: "36 ft 10 in (11.23 m)",
      length: "31 ft 0 in (9.46 m)",
      maxSpeed: "408 mph (657 km/h)",
      range: "434 mi (698 km)",
      ceiling: "43,000 ft (13,100 m)",
      engines: "1× Rolls-Royce Merlin 61/63/66/70 V-12, 1,565 hp",
      crew: "1",
    },
    description:
      "The Supermarine Spitfire is Britain's most iconic fighter aircraft and one of the most aesthetically beautiful aircraft ever built. Designer R.J. Mitchell's elliptical wing gave it exceptional lift and high-speed performance, while the Rolls-Royce Merlin engine provided the power. It served from the first day of World War II to the last, continually updated through dozens of marks. It was the only British fighter in continuous production throughout the entire war.",
    funFact:
      "The Spitfire's elliptical wing was extremely difficult and expensive to manufacture — each wing required 25,000 rivets and involved complex curved surfaces. Production was so challenging that alternative straight-wing variants were seriously considered to speed output.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted inline V-12",
      wingPosition: "low",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "wwii",
      distinguishingFeatures: [
        "unmistakable elliptical wings with rounded tips",
        "slim elegant fuselage with inline Merlin engine",
        "small rounded tail surfaces",
        "narrow undercarriage retracting outward",
        "distinctive chin radiator and oil cooler asymmetric layout",
        "rounded cockpit greenhouse transitioning to rounded spine",
      ],
    },
    aliases: ["Spitfire", "Spit", "The Spit"],
  },
  {
    id: "hawker-hurricane",
    name: "Hawker Hurricane",
    manufacturer: "Hawker Aircraft",
    type: "Fighter",
    variant: "Hurricane Mk IIc",
    firstFlight: "1935-11-06",
    inService: "1937",
    role: "Air superiority fighter / ground attack",
    country: "United Kingdom",
    specs: {
      wingspan: "40 ft 0 in (12.19 m)",
      length: "32 ft 3 in (9.82 m)",
      maxSpeed: "340 mph (547 km/h)",
      range: "460 mi (740 km)",
      ceiling: "35,600 ft (10,850 m)",
      engines: "1× Rolls-Royce Merlin XX V-12, 1,280 hp",
      crew: "1",
    },
    description:
      "The Hawker Hurricane was the first monoplane fighter to enter RAF service and the most numerous British fighter during the Battle of Britain — accounting for more German aircraft destroyed than all other defenses combined. Though less glamorous than the Spitfire, the Hurricane was more rugged, easier to repair in the field, and more stable as a gun platform. Its fabric-covered fuselage could be repaired with doped canvas; damaged Spitfires often had to be rebuilt from scratch.",
    funFact:
      "During the Battle of Britain, Hurricanes outnumbered Spitfires by almost 2:1 and shot down more German aircraft than all other British defenses — aircraft, guns, and ships — combined. Yet the Spitfire received far more of the public glory.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted inline V-12",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "wwii",
      distinguishingFeatures: [
        "thick curved wing without elliptical refinement of Spitfire",
        "fabric-covered fuselage aft of cockpit on early models",
        "prominent humped fuselage forward of cockpit",
        "framed greenhouse cockpit canopy",
        "wide-track undercarriage retracting inward",
        "more angular, workmanlike appearance than Spitfire",
      ],
    },
    aliases: ["Hurricane", "Hurri"],
  },
  {
    id: "hawker-typhoon",
    name: "Hawker Typhoon",
    manufacturer: "Hawker Aircraft",
    type: "Fighter-bomber",
    variant: "Typhoon Mk IB",
    firstFlight: "1940-02-24",
    inService: "1942",
    role: "Ground attack / low-level fighter-bomber",
    country: "United Kingdom",
    specs: {
      wingspan: "41 ft 7 in (12.67 m)",
      length: "31 ft 11 in (9.73 m)",
      maxSpeed: "412 mph (663 km/h)",
      range: "510 mi (821 km)",
      ceiling: "35,200 ft (10,730 m)",
      engines: "1× Napier Sabre IIA H-24, 2,180 hp",
      crew: "1",
    },
    description:
      "The Hawker Typhoon was originally intended as a Spitfire replacement but proved disappointing as a high-altitude fighter due to the troubled Napier Sabre engine. However, it found its true calling as a low-level ground attack aircraft, armed with eight rockets and two 1,000-lb bombs. During the Normandy campaign it was devastatingly effective against German armor and vehicles, becoming the primary Allied ground attack aircraft in Northwest Europe.",
    funFact:
      "Early Typhoons had a serious structural problem — the tail could literally break off in high-speed dives due to elevator flutter. This killed several pilots before the cause was identified and corrected with a modified elevator balance and strengthened tail joint.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted H-24 inline",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "wwii",
      distinguishingFeatures: [
        "very thick wing section — visibly chunkier than Spitfire",
        "large square radiator chin intake",
        "car door cockpit entry on early production",
        "prominent exhaust stacks along lower cowl sides",
        "large four-blade propeller for Sabre engine",
        "rocket rails under wings on late production",
      ],
    },
    aliases: ["Typhoon", "Tiffy", "Tiffie"],
  },
  {
    id: "hawker-tempest",
    name: "Hawker Tempest",
    manufacturer: "Hawker Aircraft",
    type: "Fighter / fighter-bomber",
    variant: "Tempest Mk V",
    firstFlight: "1942-09-02",
    inService: "1944",
    role: "Air superiority fighter / V-1 interceptor",
    country: "United Kingdom",
    specs: {
      wingspan: "41 ft 0 in (12.50 m)",
      length: "33 ft 8 in (10.26 m)",
      maxSpeed: "435 mph (700 km/h)",
      range: "740 mi (1,191 km)",
      ceiling: "36,500 ft (11,125 m)",
      engines: "1× Napier Sabre IIA/IIB/IIC H-24, 2,180 hp",
      crew: "1",
    },
    description:
      "The Hawker Tempest was developed to address the Typhoon's weaknesses at altitude by incorporating a thinner laminar-flow wing. The result was one of the fastest propeller-driven aircraft of the war at low and medium altitudes. It excelled in the air superiority role and became the most effective Allied interceptor against the V-1 flying bomb — its speed allowed it to catch the fast-flying weapons that eluded most other Allied fighters.",
    funFact:
      "Tempest pilots developed a technique for destroying V-1 flying bombs without risking explosion — they would fly alongside, slide their wingtip under the V-1's wing, and flip it over. This disrupted the gyroscope and sent it into the ground without triggering the warhead.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted H-24 inline",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "wwii",
      distinguishingFeatures: [
        "thinner elliptical wing compared to Typhoon",
        "larger tail surfaces than Typhoon",
        "chin radiator similar to but cleaner than Typhoon",
        "four 20mm Hispano cannons in wings",
        "bubble canopy on most production variants",
        "slightly longer nose than Typhoon",
      ],
    },
    aliases: ["Tempest", "Tempest V"],
  },
  {
    id: "bristol-beaufighter",
    name: "Bristol Beaufighter",
    manufacturer: "Bristol Aeroplane Company",
    type: "Heavy fighter / strike aircraft",
    variant: "Beaufighter TF Mk X",
    firstFlight: "1939-07-17",
    inService: "1940",
    role: "Night fighter / anti-shipping strike / torpedo bomber",
    country: "United Kingdom",
    specs: {
      wingspan: "57 ft 10 in (17.63 m)",
      length: "41 ft 8 in (12.7 m)",
      maxSpeed: "320 mph (515 km/h)",
      range: "1,470 mi (2,366 km)",
      ceiling: "26,500 ft (8,077 m)",
      engines: "2× Bristol Hercules XVII radial, 1,770 hp each",
      crew: "2",
    },
    description:
      "The Bristol Beaufighter was a powerful, adaptable twin-engine heavy fighter that served in multiple roles throughout the war. Originally designed as a night fighter using radar to intercept German bombers, it proved effective in anti-shipping strikes in the Mediterranean and torpedo attacks against Japanese shipping in the Pacific. Its heavy armament — four 20mm cannons and six machine guns — made it a devastating attack aircraft.",
    funFact:
      "Japanese crews called the Beaufighter 'Whispering Death' because its twin sleeve-valve Hercules radials were much quieter than typical air-cooled radials, allowing it to approach targets without the usual engine warning noise.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "wing-mounted radials",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "large",
      era: "wwii",
      distinguishingFeatures: [
        "large barrel-shaped fuselage",
        "two powerful Bristol Hercules radials",
        "prominent nose housing radar on night fighter variants",
        "four 20mm cannon in belly",
        "observer/gunner position with rearward-firing gun",
        "torpedo shackle under fuselage on TF variants",
      ],
    },
    aliases: ["Beaufighter", "Beau", "Whispering Death"],
  },
  {
    id: "gloster-meteor",
    name: "Gloster Meteor",
    manufacturer: "Gloster Aircraft Company",
    type: "Jet fighter",
    variant: "Meteor F Mk III",
    firstFlight: "1943-03-05",
    inService: "1944",
    role: "Air superiority jet fighter / V-1 interceptor",
    country: "United Kingdom",
    specs: {
      wingspan: "43 ft 0 in (13.11 m)",
      length: "41 ft 3 in (12.57 m)",
      maxSpeed: "493 mph (793 km/h)",
      range: "1,000 mi (1,610 km)",
      ceiling: "44,000 ft (13,400 m)",
      engines: "2× Rolls-Royce Welland/Derwent turbojet, 1,700 lbf each",
      crew: "1",
    },
    description:
      "The Gloster Meteor was the only Allied jet aircraft to see operational service in World War II and the first jet aircraft of the RAF. Powered by two centrifugal-flow turbojet engines mounted in its wings, it was faster than any piston fighter of the era. It entered service just in time to intercept V-1 flying bombs over southern England in 1944. The Meteor never encountered the German Me 262 in aerial combat during the war.",
    funFact:
      "Because the Allies feared their jet technology falling into enemy hands if a Meteor was shot down, the aircraft was initially restricted to operations over England and the English Channel only, and was not permitted to fly over occupied Europe for months after entering service.",
    visual: {
      engineCount: 2,
      engineType: "turbojet",
      enginePlacement: "wing-mounted nacelles midspan",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "wwii",
      distinguishingFeatures: [
        "twin jet nacelles mounted mid-wing",
        "straight wing configuration, not swept",
        "conventional tail design",
        "no propellers — pure jet aircraft",
        "four 20mm Hispano cannons in nose",
        "greenhouse-style framed canopy on early variants",
      ],
    },
    aliases: ["Meteor", "Meatbox"],
  },
  {
    id: "bf109",
    name: "Messerschmitt Bf 109",
    manufacturer: "Bayerische Flugzeugwerke / Messerschmitt AG",
    type: "Fighter",
    variant: "Bf 109G-6",
    firstFlight: "1935-05-28",
    inService: "1937",
    role: "Air superiority fighter / interceptor",
    country: "Germany",
    specs: {
      wingspan: "32 ft 6 in (9.92 m)",
      length: "29 ft 7 in (9.02 m)",
      maxSpeed: "386 mph (621 km/h)",
      range: "620 mi (998 km)",
      ceiling: "39,370 ft (12,000 m)",
      engines: "1× Daimler-Benz DB 605A inverted V-12, 1,475 hp",
      crew: "1",
    },
    description:
      "The Messerschmitt Bf 109 was the backbone of the Luftwaffe fighter arm throughout World War II and one of the most produced fighter aircraft in history — over 33,000 were built. Its inverted V-12 engine allowed a cannon to fire through the propeller shaft, giving it a powerful nose-mounted armament. The top aces of all time flew the Bf 109 — Erich Hartmann's 352 kills, the highest confirmed total of any pilot in history, were all achieved in the 109.",
    funFact:
      "The Bf 109's narrow undercarriage, which angled outward and retracted inward, caused more accidents than enemy action. Pilots had to maintain precise control during takeoff and landing to prevent ground loops. Approximately 1,500 Bf 109s were lost in landing accidents throughout the war.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted inverted V-12",
      wingPosition: "low",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "wwii",
      distinguishingFeatures: [
        "narrow-track undercarriage creating very pigeon-toed stance",
        "angular squared-off wingtips",
        "prominent cowl bulges over supercharger and gun troughs",
        "small angular tail",
        "frameless canopy with rear armor plate on later variants",
        "leading-edge slats visible when extended",
      ],
    },
    aliases: ["Bf 109", "Me 109", "Emil (E)", "Friedrich (F)", "Gustav (G)", "109"],
  },
  {
    id: "fw190",
    name: "Focke-Wulf Fw 190",
    manufacturer: "Focke-Wulf Flugzeugbau",
    type: "Fighter / ground attack",
    variant: "Fw 190A-8",
    firstFlight: "1939-06-01",
    inService: "1941",
    role: "Air superiority fighter / ground attack",
    country: "Germany",
    specs: {
      wingspan: "34 ft 5 in (10.50 m)",
      length: "29 ft 0 in (8.84 m)",
      maxSpeed: "408 mph (656 km/h)",
      range: "500 mi (805 km)",
      ceiling: "37,400 ft (11,400 m)",
      engines: "1× BMW 801D-2 radial, 1,700 hp",
      crew: "1",
    },
    description:
      "The Focke-Wulf Fw 190 shocked the RAF when it appeared over the English Channel in 1941, outclassing the contemporary Spitfire Mk V in almost every parameter. Its wide-track undercarriage made it much easier to handle on the ground than the Bf 109, and it could carry heavier armament. The radial-engined Fw 190A was followed by the high-altitude Fw 190D with a Junkers Jumo inline engine, which was widely considered the best piston fighter in Luftwaffe service.",
    funFact:
      "When RAF test pilot Jeffrey Quill and others first encountered the Fw 190 in combat in 1941, the RAF was so alarmed by its superiority that it launched Operation Airthief — a plan to steal a Fw 190 intact, eventually succeeding when a confused German pilot accidentally landed at an RAF base in 1942.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted radial (BMW 801) or inline (190D)",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "wwii",
      distinguishingFeatures: [
        "wide-track undercarriage retracting inward",
        "large BMW 801 radial cowling with annular radiator",
        "bubble-style framed canopy",
        "clean elliptical wingtips",
        "prominent wing root cannon fairings",
        "long pointed nose on Dora (D-9) variant with Jumo inline",
      ],
    },
    aliases: ["Fw 190", "Würger (Butcher Bird)", "Dora (D-9)", "Anton (A series)"],
  },
  {
    id: "me262",
    name: "Messerschmitt Me 262",
    manufacturer: "Messerschmitt AG",
    type: "Jet fighter / bomber",
    variant: "Me 262A-1a Schwalbe",
    firstFlight: "1942-07-18",
    inService: "1944",
    role: "Jet interceptor / ground attack",
    country: "Germany",
    specs: {
      wingspan: "41 ft 0 in (12.51 m)",
      length: "34 ft 9 in (10.60 m)",
      maxSpeed: "559 mph (900 km/h)",
      range: "652 mi (1,050 km)",
      ceiling: "37,565 ft (11,450 m)",
      engines: "2× Junkers Jumo 004B turbojet, 1,984 lbf each",
      crew: "1",
    },
    description:
      "The Messerschmitt Me 262 was the world's first operational jet-powered fighter aircraft, entering service with the Luftwaffe in 1944. It was significantly faster than any Allied piston-engine fighter and carried a devastating armament of four 30mm MK 108 cannon. Despite its technological superiority, it arrived too late and in too few numbers to change the course of the war, hampered by engine reliability problems, pilot shortages, and Adolf Hitler's insistence on using it as a bomber.",
    funFact:
      "Adolf Hitler's insistence on using the Me 262 as a 'Blitzbomber' instead of a fighter is often cited as having delayed its operational introduction. In reality, fighter development was already underway before Hitler's intervention, and engine reliability and fuel shortages were bigger limiting factors.",
    visual: {
      engineCount: 2,
      engineType: "turbojet",
      enginePlacement: "underwing nacelles below swept wings",
      wingPosition: "low",
      wingShape: "swept",
      tailType: "conventional",
      landingGear: "tricycle",
      sizeClass: "medium",
      era: "wwii",
      distinguishingFeatures: [
        "swept wings — the first swept-wing combat aircraft",
        "two Junkers Jumo 004 turbojet pods under wings",
        "nosecone housing four 30mm cannon",
        "tricycle undercarriage unusual for German aircraft",
        "sleek fuselage with no propeller",
        "glazed greenhouse-style canopy",
      ],
    },
    aliases: ["Me 262", "Schwalbe (Swallow)", "Sturmvogel (Stormbird)", "262"],
  },
  {
    id: "bf110",
    name: "Messerschmitt Bf 110",
    manufacturer: "Bayerische Flugzeugwerke / Messerschmitt AG",
    type: "Heavy fighter / destroyer",
    variant: "Bf 110G-4",
    firstFlight: "1936-05-12",
    inService: "1939",
    role: "Heavy fighter / night fighter / Zerstörer",
    country: "Germany",
    specs: {
      wingspan: "53 ft 5 in (16.27 m)",
      length: "41 ft 7 in (12.65 m)",
      maxSpeed: "342 mph (550 km/h)",
      range: "1,305 mi (2,100 km)",
      ceiling: "35,760 ft (10,900 m)",
      engines: "2× Daimler-Benz DB 601A inverted V-12, 1,175 hp each",
      crew: "2",
    },
    description:
      "The Messerschmitt Bf 110 was designed as a long-range escort fighter and 'destroyer' (Zerstörer) capable of clearing the skies ahead of German bombers. It performed well in early campaigns against weak opposition but proved disastrously vulnerable during the Battle of Britain when it encountered single-engine Hurricanes and Spitfires. It found success as a night fighter equipped with radar, ultimately accounting for more RAF bomber kills than any other Luftwaffe night fighter.",
    funFact:
      "During the Battle of Britain, Bf 110s were themselves so badly mauled by RAF fighters that they required Bf 109 escorts — the escorts of the bombers needed escorting themselves. Hermann Göring reportedly flew into a rage when his Zerstörer force asked for fighter protection.",
    visual: {
      engineCount: 2,
      engineType: "piston",
      enginePlacement: "wing-mounted inline V-12 engines",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "twin",
      landingGear: "retractable",
      sizeClass: "large",
      era: "wwii",
      distinguishingFeatures: [
        "twin Daimler-Benz inline engines mounted on mid wing",
        "twin tail fins on single fuselage",
        "glazed nose greenhouse for cannon",
        "rear-facing gunner position in tandem cockpit",
        "Lichtenstein radar aerials on nose of night fighter G-4",
        "elongated fuselage with twin tail",
      ],
    },
    aliases: ["Bf 110", "Me 110", "Zerstörer", "Twin-engine Messerschmitt"],
  },
  {
    id: "fw-ta152",
    name: "Focke-Wulf Ta 152",
    manufacturer: "Focke-Wulf Flugzeugbau",
    type: "High-altitude fighter",
    variant: "Ta 152H-1",
    firstFlight: "1944-09-12",
    inService: "1945",
    role: "High-altitude interceptor",
    country: "Germany",
    specs: {
      wingspan: "47 ft 7 in (14.50 m)",
      length: "35 ft 5 in (10.80 m)",
      maxSpeed: "472 mph (760 km/h)",
      range: "745 mi (1,200 km)",
      ceiling: "48,556 ft (14,800 m)",
      engines: "1× Junkers Jumo 213E inverted V-12 with MW-50, 2,250 hp",
      crew: "1",
    },
    description:
      "The Focke-Wulf Ta 152 was Kurt Tank's ultimate development of the Fw 190 lineage, optimized for extreme high-altitude operations with a pressurized cockpit and an extended, long-span wing. The Ta 152H could reach altitudes where no Allied fighter could effectively operate. It arrived far too late to influence the war, with only about 150 built, but demonstrated extraordinary performance — Kurt Tank himself reportedly escaped pursuing Allied fighters by pushing the throttle forward and simply pulling away.",
    funFact:
      "Kurt Tank, the designer, personally flew the Ta 152H in combat and was reportedly bounced by Allied fighters. He activated the MW-50 methanol-water injection boost and GM-1 nitrous oxide system simultaneously, and the resulting speed increase left the pursuing aircraft so far behind that they gave up the chase.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted inline V-12",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "medium",
      era: "wwii",
      distinguishingFeatures: [
        "noticeably longer wingspan than standard Fw 190",
        "elongated fuselage compared to Fw 190A",
        "pointed spinner on Jumo 213 inline engine",
        "pressurized cockpit bubble",
        "lengthened and widened chord wing",
        "slim inline engine profile versus radial Fw 190A",
      ],
    },
    aliases: ["Ta 152", "Ta 152H", "Tank 152"],
  },
  {
    id: "he162",
    name: "Heinkel He 162",
    manufacturer: "Ernst Heinkel Flugzeugwerke",
    type: "Jet fighter",
    variant: "He 162A-2 Salamander",
    firstFlight: "1944-12-06",
    inService: "1945",
    role: "Emergency jet interceptor",
    country: "Germany",
    specs: {
      wingspan: "23 ft 7 in (7.20 m)",
      length: "29 ft 8 in (9.05 m)",
      maxSpeed: "522 mph (840 km/h)",
      range: "606 mi (975 km)",
      ceiling: "39,400 ft (12,000 m)",
      engines: "1× BMW 003E-1 turbojet, 1,764 lbf",
      crew: "1",
    },
    description:
      "The Heinkel He 162 Salamander was an emergency jet fighter designed and built at astonishing speed — from concept approval to first flight in just 90 days. Constructed largely of wood due to aluminum shortages, it mounted a single BMW 003 turbojet atop the fuselage behind the cockpit. Intended to be flown by minimally trained Hitler Youth pilots, it was actually far too demanding for novices. Only about 130 saw operational service before the war's end.",
    funFact:
      "The He 162 was designed and built in 90 days, going from initial design approval on September 8, 1944 to first flight on December 6, 1944 — a pace that has never been matched for a jet combat aircraft before or since. The prototype crashed on its third flight due to bonding failures in the wooden construction.",
    visual: {
      engineCount: 1,
      engineType: "turbojet",
      enginePlacement: "dorsal-mounted atop fuselage behind cockpit",
      wingPosition: "mid",
      wingShape: "straight",
      tailType: "twin",
      landingGear: "tricycle",
      sizeClass: "light",
      era: "wwii",
      distinguishingFeatures: [
        "jet engine mounted on TOP of fuselage — highly distinctive",
        "twin tail fins angled outward on tailplane",
        "wooden wings and tail components",
        "very small and compact overall",
        "no propeller — pure jet",
        "butterfly-type anhedral wingtips on some variants",
      ],
    },
    aliases: ["He 162", "Salamander", "Volksjäger (People's Fighter)", "Spatz (Sparrow)"],
  },
  {
    id: "a6m-zero",
    name: "Mitsubishi A6M Zero",
    manufacturer: "Mitsubishi Aircraft",
    type: "Carrier-based fighter",
    variant: "A6M5",
    firstFlight: "1939-04-01",
    inService: "1940",
    role: "Fleet air defense / carrier escort fighter",
    country: "Japan",
    specs: {
      wingspan: "36 ft 1 in (11.00 m)",
      length: "29 ft 11 in (9.06 m)",
      maxSpeed: "351 mph (565 km/h)",
      range: "1,118 mi (1,800 km)",
      ceiling: "38,520 ft (11,740 m)",
      engines: "1× Nakajima NK1C Sakae-12 radial, 950 hp",
      crew: "1",
    },
    description:
      "The Mitsubishi A6M Zero was the world's finest carrier-based fighter when introduced and dominated the Pacific skies in the first year of World War II. It achieved extraordinary range and maneuverability by sacrificing everything else — it had no pilot armor, no self-sealing fuel tanks, and was structurally light to the point of fragility. Allied pilots learned never to dogfight a Zero at low speeds and instead developed hit-and-run tactics that exploited the Zero's poor high-speed control and structural limits.",
    funFact:
      "An intact Zero discovered in the Aleutian Islands in 1942 was repaired and extensively flight-tested by the US Navy. The technical intelligence gained — particularly the Zero's loss of control at high speeds — allowed American pilots to develop tactics that dramatically improved their combat survival rates.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted radial",
      wingPosition: "low",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "wwii",
      distinguishingFeatures: [
        "distinctive round wingtips with blunt square cut on A6M5",
        "large greenhouse cockpit with rounded canopy frames",
        "smooth slim fuselage with minimal protrusions",
        "relatively small radial cowling",
        "prominent fixed wing root fillets",
        "long landing gear legs for propeller clearance",
      ],
    },
    aliases: ["Zero", "Zeke", "Rei-sen", "A6M", "Mitsubishi Zero"],
  },
  {
    id: "ki84-hayate",
    name: "Nakajima Ki-84 Hayate",
    manufacturer: "Nakajima Aircraft Company",
    type: "Fighter",
    variant: "Ki-84-I Ko",
    firstFlight: "1943-03-09",
    inService: "1944",
    role: "Air superiority fighter / interceptor",
    country: "Japan",
    specs: {
      wingspan: "36 ft 10 in (11.24 m)",
      length: "32 ft 6 in (9.92 m)",
      maxSpeed: "392 mph (631 km/h)",
      range: "1,025 mi (1,650 km)",
      ceiling: "34,450 ft (10,500 m)",
      engines: "1× Nakajima Ha-45-21 Homare radial, 1,990 hp",
      crew: "1",
    },
    description:
      "The Nakajima Ki-84 Hayate (Gale) was arguably Japan's finest fighter of World War II. Unlike earlier Japanese designs, it incorporated pilot armor and self-sealing fuel tanks without sacrificing performance, and its powerful Homare engine made it fast enough to challenge any Allied fighter. In service it proved capable of countering both P-47s and P-51s at all altitudes. However, poor fuel quality, inadequate maintenance materials, and poorly trained pilots late in the war prevented it from achieving its potential.",
    funFact:
      "American test pilots who flew captured Ki-84s after the war were impressed, rating it comparable or superior to the P-51D in several performance parameters. When properly fueled with high-octane American aviation gasoline, the Ki-84's Homare engine produced significantly more power than Japanese fuel allowed.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted radial",
      wingPosition: "low",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "wwii",
      distinguishingFeatures: [
        "clean rounded fuselage with small radial cowling",
        "bubble canopy providing good pilot visibility",
        "four-blade propeller on Homare engine",
        "slightly squared wingtips",
        "clean cowl with minimal protrusions",
        "relatively narrow undercarriage",
      ],
    },
    aliases: ["Ki-84", "Hayate", "Frank (Allied code name)"],
  },
  {
    id: "ki61-hien",
    name: "Kawasaki Ki-61 Hien",
    manufacturer: "Kawasaki Aircraft Industries",
    type: "Fighter",
    variant: "Ki-61-II Kai",
    firstFlight: "1941-12-03",
    inService: "1943",
    role: "Air superiority fighter / high-altitude interceptor",
    country: "Japan",
    specs: {
      wingspan: "39 ft 4 in (12.00 m)",
      length: "29 ft 4 in (8.94 m)",
      maxSpeed: "379 mph (610 km/h)",
      range: "684 mi (1,100 km)",
      ceiling: "36,090 ft (11,000 m)",
      engines: "1× Kawasaki Ha-40 (licensed DB 601A) inverted V-12, 1,175 hp",
      crew: "1",
    },
    description:
      "The Kawasaki Ki-61 Hien (Swallow) was unique among Japanese fighters of the war — it was the only one powered by a liquid-cooled inline engine rather than a radial. Based on a licensed Daimler-Benz DB 601 V-12, it produced a distinctly European-looking fighter that Allied pilots initially mistook for a Bf 109 or Macchi C.202. Its performance at altitude was generally better than Zero-type aircraft, and it proved effective against B-29 bombers raiding Japan in 1944-45.",
    funFact:
      "Allied intelligence was so confused by the Ki-61's appearance that early identification guides labeled it 'Tony' and speculated it might actually be an Italian-built Macchi or a license-built German fighter. It was the only Japanese fighter they could not immediately identify as a new Japanese design.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted inline V-12",
      wingPosition: "low",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "wwii",
      distinguishingFeatures: [
        "inline engine giving European appearance unlike most Japanese fighters",
        "slim pointed nose without radial cowling",
        "chin radiator bath similar to Bf 109/Spitfire",
        "clean fuselage profile from inline powerplant",
        "somewhat resembles German or Italian designs",
        "slightly rounded Japanese-style canopy",
      ],
    },
    aliases: ["Ki-61", "Hien", "Tony (Allied code name)"],
  },
  {
    id: "yak3",
    name: "Yakovlev Yak-3",
    manufacturer: "Yakovlev Design Bureau",
    type: "Fighter",
    variant: "Yak-3",
    firstFlight: "1943-02-28",
    inService: "1944",
    role: "Air superiority fighter / low-altitude combatant",
    country: "Soviet Union",
    specs: {
      wingspan: "30 ft 2 in (9.20 m)",
      length: "27 ft 10 in (8.49 m)",
      maxSpeed: "407 mph (655 km/h)",
      range: "560 mi (900 km)",
      ceiling: "35,450 ft (10,800 m)",
      engines: "1× Klimov VK-105PF-2 V-12, 1,300 hp",
      crew: "1",
    },
    description:
      "The Yakovlev Yak-3 was one of the finest dogfighters of World War II within its optimum altitude band below 13,000 feet. Extremely light, simple, and maneuverable, it could outmaneuver any German fighter at low to medium altitude. The Luftwaffe issued formal orders to its pilots to avoid combat with Yak-3s below 5,000 meters — a remarkable testament to its capabilities. It was the mount of choice for the Normandie-Niemen regiment of French volunteer pilots fighting in the USSR.",
    funFact:
      "The Luftwaffe issued a formal written order to its pilots: 'Avoid combat with Yak fighters having no air intake beneath the nose at altitudes below 5000m.' This referred to the Yak-3, distinguishing it from the earlier Yak-1 and Yak-7. Such an explicit order to avoid an opponent is extremely rare in military aviation history.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted inline V-12",
      wingPosition: "low",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "wwii",
      distinguishingFeatures: [
        "very small and compact — among the smallest WWII fighters",
        "absence of underwing radiator scoop distinguishes Yak-3 from Yak-1",
        "radiator moved to under-nose chin position on Yak-3",
        "clean simple wooden wing construction",
        "rounded Soviet canopy style",
        "short nose relative to fuselage length",
      ],
    },
    aliases: ["Yak-3", "Yakovlev 3"],
  },
  {
    id: "la5-lavochkin",
    name: "Lavochkin La-5",
    manufacturer: "Lavochkin Design Bureau",
    type: "Fighter",
    variant: "La-5FN",
    firstFlight: "1942-03-21",
    inService: "1942",
    role: "Air superiority fighter / low-altitude combatant",
    country: "Soviet Union",
    specs: {
      wingspan: "32 ft 2 in (9.80 m)",
      length: "28 ft 5 in (8.67 m)",
      maxSpeed: "403 mph (648 km/h)",
      range: "475 mi (765 km)",
      ceiling: "36,089 ft (11,000 m)",
      engines: "1× Shvetsov ASh-82FN air-cooled radial, 1,850 hp",
      crew: "1",
    },
    description:
      "The Lavochkin La-5 was a transformative Soviet fighter, replacing the inline LaGG-3 engine with a powerful Shvetsov radial to create an aircraft that could finally match the Bf 109F and G on equal terms. The La-5FN (FN = Forsirovannyy Neposredstvennogo, direct fuel injection) was particularly capable and played a key role in the Battle of Kursk in 1943. Ivan Kozhedub, the top Allied ace of the war with 64 kills, scored many of his victories in the La-5 and its successor, the La-7.",
    funFact:
      "Ivan Kozhedub flew the La-5 and La-7 to achieve 64 confirmed aerial kills — the highest total of any Allied pilot in the war. On two occasions late in the war, he also engaged and shot down American P-51 Mustangs whose pilots apparently mistook his La-7 for a German aircraft and attacked first.",
    visual: {
      engineCount: 1,
      engineType: "piston",
      enginePlacement: "nose-mounted radial",
      wingPosition: "mid",
      wingShape: "trapezoidal",
      tailType: "conventional",
      landingGear: "retractable",
      sizeClass: "light",
      era: "wwii",
      distinguishingFeatures: [
        "large Shvetsov radial cowling with prominent air intake slots",
        "round cowling with Soviet star markings",
        "rounded Soviet-style canopy",
        "two cowl-mounted ShVAK cannons firing through propeller arc",
        "relatively wide fuselage from radial engine",
        "slightly blunt nose profile compared to inline-engined Soviet fighters",
      ],
    },
    aliases: ["La-5", "La-5FN", "Lavochkin 5"],
  },
];
